# PWKD Option 2 — Prune ResNet50 Directly

Implements **Pruning While Knowledge Distillation** (Wang et al., 2025) using:
- **Teacher**: frozen pretrained ResNet50 (RadImageNet weights)
- **Student**: a deep copy of the *same* pretrained ResNet50, fine-tuned
  with PWKD simultaneously pruning and distilling

This is a same-architecture setup, closely analogous to the paper's
EDSR-32-256 → EDSR-16-64 setup but keeping the architecture fixed and
instead driving channels to zero through the differentiable sparsity penalty.
The wavelet channel-projection step is skipped (teacher/student channels match).

Starting from pretrained weights means the student begins at the teacher's
F1 level (~0.49) and PWKD nudges it toward a smaller, slightly lower-F1 model —
a much more favourable trade-off than training from scratch.

Produces 5 compressed models at pruning ratios [10%, 25%, 50%, 70%, 90%],
saved to `trained_models/pwkd_self_r50_<ratio>/` and uploaded to HuggingFace.

**Run all cells top to bottom. Requires GPU.**

In [1]:
import os, copy, subprocess
import torch

target = 'CS6423_knowledge_distillation_project'
if not os.getcwd().endswith(target):
    import sys
    os.chdir(os.path.join(os.getcwd(), target))
    if os.getcwd() not in sys.path:
        sys.path.insert(0, os.getcwd())

print(f'Working dir: {os.getcwd()}')
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device: {device}')

subprocess.run(['pip', 'install', 'PyWavelets', '--quiet'], check=True)

Working dir: /home/cor10/CS6423_knowledge_distillation_project
Device: cuda

CompletedProcess(args=['pip', 'install', 'PyWavelets', '--quiet'], returncode=0)

In [2]:
import pandas as pd
from modules.dataset_prepper import datasetPrepper

data_prep = datasetPrepper(
    dataframe_path='data/labels.csv',
    image_dir='data/test_images',
).prepare(compute_class_weights=True)

NUM_CLASSES = len(data_prep.class_names)
print(f'Classes: {NUM_CLASSES}')
print(f'Train batches: {len(data_prep.train_loader)} | Val batches: {len(data_prep.val_loader)}')

Classes: 61
Train batches: 249 | Val batches: 50

In [3]:
from modules.imagenet_loader import ImagenetLoader
from modules.evaluate_model import ModelEvaluator

loader = ImagenetLoader()

# Load pretrained ResNet50 — this serves as both the frozen teacher
# and the starting point for each student deep copy
resnet50_pretrained = loader.load_radimagenet_resnet50(
    weights_path='trained_models/resnet50_baseline_gpu_new/resnet50_baseline_gpu_new.pth',
    load_type='load'
)
resnet50_pretrained = resnet50_pretrained.to(device)

evaluator = ModelEvaluator(
    data_loader=data_prep.val_loader,
    class_names=data_prep.class_names,
    device=str(device),
)

baseline_metrics = evaluator.evaluate_single(resnet50_pretrained, 'ResNet50_baseline')
BASELINE_PARAMS  = baseline_metrics['total_parameters']
print(f'ResNet50 baseline F1:    {baseline_metrics["f1_macro"]:.4f}')
print(f'ResNet50 baseline params: {BASELINE_PARAMS:,}')

Warming up ResNet50_baseline...
Running inference...
ResNet50 baseline F1:    0.4867
ResNet50 baseline params: 23,633,021

## Same-architecture note

Because teacher and student are both ResNet50, their channel counts match at
every stage. The MVRM projection step (`teacher_proj`) becomes an identity
operation — `PWKDLoss` handles this automatically when `teacher_channels ==
student_channels`.

| Stage   | ResNet50 teacher | ResNet50 student |
|---------|-----------------|------------------|
| layer2  | 512             | 512              |
| layer3  | 1024            | 1024             |
| layer4  | 2048            | 2048             |

In [4]:
import torch.nn as nn
import copy
from modules.model_trainer import modelTrainer
from modules.evaluate_model import ModelEvaluator
from pwkd.pwkd import PWKDLoss, make_aux_fn, finalise_student

RESNET50_CHANNELS = {'layer2': 512, 'layer3': 1024, 'layer4': 2048}

PRUNING_RATIOS = [0, 0.05, 0.10, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.50, 0.70, 0.90]
NUM_EPOCHS     = 10
KD_TEMP        = 4.0
LAM            = 0.2
SPARSE_WEIGHT  = 5e-4
learn_rate     = 1e-4

evaluator = ModelEvaluator(
    data_loader=data_prep.val_loader,
    class_names=data_prep.class_names,
    device=str(device),
)

teacher = copy.deepcopy(resnet50_pretrained).eval()
for p in teacher.parameters():
    p.requires_grad = False

pwkd_metrics = []

print(f'ResNet50 baseline F1:    {baseline_metrics["f1_macro"]:.4f}')
print(f'ResNet50 baseline params: {BASELINE_PARAMS:,}')


for ratio in PRUNING_RATIOS:
    label = f'pwkd_self_r50_r{int(ratio * 100)}'
    print(f'\n{"="*60}')
    print(f'  PWKD Option 2 (ResNet50) — pruning ratio {ratio:.0%}')
    print(f'{"="*60}')

    student = copy.deepcopy(resnet50_pretrained).to(device)
    for p in student.parameters():
        p.requires_grad = True
        
        # reset teacher each experiment
    teacher_copy = copy.deepcopy(teacher).to(device)
    teacher_copy.eval()

    pwkd_loss = PWKDLoss(
        student          = student,
        teacher          = teacher_copy,
        pruning_ratio    = ratio,
        teacher_channels = RESNET50_CHANNELS,
        student_channels = RESNET50_CHANNELS,
        class_weights    = data_prep.class_weights.to(device)
                           if data_prep.class_weights is not None else None,
        lam              = LAM,
        kd_temp          = KD_TEMP,
        sparse_weight    = 0 if ratio == 0 else SPARSE_WEIGHT,
    ).to(device)

    
    trainer = modelTrainer(
        model      = student,
        data_prep  = data_prep,
        device     = device,
        # learn_rate = 2e-4,
        learn_rate = learn_rate,
        num_epochs = NUM_EPOCHS,
        model_name = label,
    )
    trainer.loss_fn   = pwkd_loss
    # trainer.optimizer = torch.optim.AdamW(
    #     params = student.parameters()
    #         if ratio == 0
    #     else
    #         list(student.parameters()) + list(pwkd_loss.parameters()),
    #     lr=learn_rate, weight_decay=1e-4,
    # )
    trainer.optimizer = torch.optim.AdamW(
        list(student.parameters()) + list(pwkd_loss.parameters()),
        lr=5e-5 if ratio == 0 else learn_rate,
        weight_decay=1e-4,
    )
    trainer.create_classnum_to_label_map(data_prep.class_names)
    trainer.train_all(save_as_object=True, aux_forward_fn=make_aux_fn(teacher_copy), pwkd=True)
    
    # Reload best checkpoint before finalising
    best_ckpt = os.path.join('trained_models', label, f'{label}_full.pth')
    student = torch.load(best_ckpt, map_location=device, weights_only=False)['model']
    student = student.to(device)

    student = finalise_student(student, pwkd_loss, data_prep.train_loader, device)

    import os
    save_dir = os.path.join('trained_models', label)
    os.makedirs(save_dir, exist_ok=True)
    torch.save({'model': student, 'epoch': NUM_EPOCHS},
               os.path.join(save_dir, f'{label}_full.pth'))
    print(f'Saved → {save_dir}/{label}_full.pth')

    student.eval()
    metrics = evaluator.evaluate_single(student, label)

    pwkd_metrics.append({
        'Pruning Ratio':      f'{int(ratio*100)}%',
        'Size Reduction (%)': round((BASELINE_PARAMS - metrics['total_parameters'])
                                    / BASELINE_PARAMS * 100, 2),
        'F1 Score':           round(metrics['f1_macro'],     4),
        'Size (MB)':          round(metrics['model_size_mb'], 1),
        'Latency (ms)':       round(metrics['avg_latency_ms'], 2),
    })
    print(f'  ratio: {ratio:.0%} | F1: {metrics["f1_macro"]:.4f} | '
          f'params: {metrics["total_parameters"]:,} | '
          f'latency: {metrics["avg_latency_ms"]:.2f}ms')

summary_df = pd.DataFrame(pwkd_metrics).set_index('Pruning Ratio')
print('\nPWKD Option 2 (ResNet50) — Results')
display(summary_df)

ResNet50 baseline F1:    0.4867
ResNet50 baseline params: 23,633,021

============================================================
  PWKD Option 2 (ResNet50) — pruning ratio 0%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:51<00:00,  4.84batch/s, loss=0.87]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.63batch/s]

Epoch 1/10
Train Loss: 0.6459 | Train F1: 0.7135
Val Loss: 1.3241 | Val F1: 0.4775
Epoch Time: 54.67s

Epoch 2/10: 100%|██████████| 249/249 [00:51<00:00,  4.87batch/s, loss=0.408]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.65batch/s]

Epoch 2/10
Train Loss: 0.4232 | Train F1: 0.7835
Val Loss: 1.2859 | Val F1: 0.4730
Epoch Time: 54.38s

Epoch 3/10: 100%|██████████| 249/249 [00:51<00:00,  4.87batch/s, loss=0.416]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.58batch/s]

Epoch 3/10
Train Loss: 0.3517 | Train F1: 0.8094
Val Loss: 1.2831 | Val F1: 0.4769
Epoch Time: 54.33s

Epoch 4/10: 100%|██████████| 249/249 [00:51<00:00,  4.87batch/s, loss=0.699]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.54batch/s]

Epoch 4/10
Train Loss: 0.3261 | Train F1: 0.8273
Val Loss: 1.2977 | Val F1: 0.4750
Epoch Time: 54.35s

Epoch 5/10: 100%|██████████| 249/249 [00:51<00:00,  4.87batch/s, loss=0.393]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.61batch/s]

Epoch 5/10
Train Loss: 0.2992 | Train F1: 0.8424
Val Loss: 1.2631 | Val F1: 0.4952
Epoch Time: 54.30s

Epoch 6/10: 100%|██████████| 249/249 [00:51<00:00,  4.87batch/s, loss=0.464]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.55batch/s]

Epoch 6/10
Train Loss: 0.2905 | Train F1: 0.8492
Val Loss: 1.2795 | Val F1: 0.4789
Epoch Time: 54.36s

Epoch 7/10: 100%|██████████| 249/249 [00:51<00:00,  4.87batch/s, loss=0.353]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.58batch/s]

Epoch 7/10
Train Loss: 0.2689 | Train F1: 0.8544
Val Loss: 1.3004 | Val F1: 0.4801
Epoch Time: 54.32s

Epoch 8/10: 100%|██████████| 249/249 [00:51<00:00,  4.87batch/s, loss=0.405]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.59batch/s]

Epoch 8/10
Train Loss: 0.2679 | Train F1: 0.8598
Val Loss: 1.3541 | Val F1: 0.4569
Epoch Time: 54.37s

Epoch 9/10: 100%|██████████| 249/249 [00:51<00:00,  4.88batch/s, loss=0.345]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.60batch/s]

Epoch 9/10
Train Loss: 0.2695 | Train F1: 0.8617
Val Loss: 1.3198 | Val F1: 0.4789
Epoch Time: 54.28s

Epoch 10/10: 100%|██████████| 249/249 [00:51<00:00,  4.88batch/s, loss=0.267]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.56batch/s]

Epoch 10/10
Train Loss: 0.2469 | Train F1: 0.8704
Val Loss: 1.2391 | Val F1: 0.4744
Epoch Time: 54.29s

Finalised: 0/3776 conv1 channels zeroed (0.0%)
Saved → trained_models/pwkd_self_r50_r0/pwkd_self_r50_r0_full.pth

Warming up pwkd_self_r50_r0...
Running inference...
  ratio: 0% | F1: 0.4952 | params: 23,633,021 | latency: 1.12ms

============================================================
  PWKD Option 2 (ResNet50) — pruning ratio 5%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [01:19<00:00,  3.12batch/s, loss=0.722]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.59batch/s]

Epoch 1/10
Train Loss: 0.8174 | Train F1: 0.6607
Val Loss: 1.4761 | Val F1: 0.4298
Epoch Time: 83.00s

Epoch 2/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.927]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.56batch/s]

Epoch 2/10
Train Loss: 0.4801 | Train F1: 0.7601
Val Loss: 1.5018 | Val F1: 0.4297
Epoch Time: 82.48s

Epoch 3/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.326]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.46batch/s]

Epoch 3/10
Train Loss: 0.4152 | Train F1: 0.7876
Val Loss: 1.4563 | Val F1: 0.4601
Epoch Time: 82.56s

Epoch 4/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.411]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.44batch/s]

Epoch 4/10
Train Loss: 0.3506 | Train F1: 0.8132
Val Loss: 1.5203 | Val F1: 0.4249
Epoch Time: 82.70s

Epoch 5/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.47]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.55batch/s]

Epoch 5/10
Train Loss: 0.3198 | Train F1: 0.8228
Val Loss: 1.3764 | Val F1: 0.4808
Epoch Time: 82.61s

Epoch 6/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.55]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.54batch/s]

Epoch 6/10
Train Loss: 0.3448 | Train F1: 0.8320
Val Loss: 1.5221 | Val F1: 0.4414
Epoch Time: 82.58s

Epoch 7/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.477]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.50batch/s]

Epoch 7/10
Train Loss: 0.3500 | Train F1: 0.8216
Val Loss: 1.4926 | Val F1: 0.4185
Epoch Time: 82.73s

Epoch 8/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.363]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.53batch/s]

Epoch 8/10
Train Loss: 0.3232 | Train F1: 0.8347
Val Loss: 1.4006 | Val F1: 0.4524
Epoch Time: 82.52s

Epoch 9/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.439]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.57batch/s]

Epoch 9/10
Train Loss: 0.2973 | Train F1: 0.8506
Val Loss: 1.4857 | Val F1: 0.4407
Epoch Time: 82.44s

Epoch 10/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.359]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.40batch/s]

Epoch 10/10
Train Loss: 0.2850 | Train F1: 0.8590
Val Loss: 1.5065 | Val F1: 0.4565
Epoch Time: 82.60s

Finalised: 180/3776 conv1 channels zeroed (4.8%)
Saved → trained_models/pwkd_self_r50_r5/pwkd_self_r50_r5_full.pth

Warming up pwkd_self_r50_r5...
Running inference...
  ratio: 5% | F1: 0.4553 | params: 22,880,637 | latency: 1.13ms

============================================================
  PWKD Option 2 (ResNet50) — pruning ratio 10%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.581]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.49batch/s]

Epoch 1/10
Train Loss: 0.7965 | Train F1: 0.6754
Val Loss: 1.4891 | Val F1: 0.4475
Epoch Time: 82.51s

Epoch 2/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.358]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.45batch/s]

Epoch 2/10
Train Loss: 0.4901 | Train F1: 0.7581
Val Loss: 1.4226 | Val F1: 0.4507
Epoch Time: 82.73s

Epoch 3/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.521]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.58batch/s]

Epoch 3/10
Train Loss: 0.4130 | Train F1: 0.7903
Val Loss: 1.4571 | Val F1: 0.4325
Epoch Time: 82.47s

Epoch 4/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.388]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.41batch/s]

Epoch 4/10
Train Loss: 0.3695 | Train F1: 0.8166
Val Loss: 1.4021 | Val F1: 0.4536
Epoch Time: 82.53s

Epoch 5/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.633]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.55batch/s]

Epoch 5/10
Train Loss: 0.3514 | Train F1: 0.8243
Val Loss: 1.4224 | Val F1: 0.4571
Epoch Time: 82.43s

Epoch 6/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.396]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.52batch/s]

Epoch 6/10
Train Loss: 0.3302 | Train F1: 0.8330
Val Loss: 1.4302 | Val F1: 0.4476
Epoch Time: 82.49s

Epoch 7/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.481]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.51batch/s]

Epoch 7/10
Train Loss: 0.3233 | Train F1: 0.8456
Val Loss: 1.4058 | Val F1: 0.4657
Epoch Time: 82.43s

Epoch 8/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.374]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.53batch/s]

Epoch 8/10
Train Loss: 0.3183 | Train F1: 0.8489
Val Loss: 1.4062 | Val F1: 0.4627
Epoch Time: 82.47s

Epoch 9/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.437]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.56batch/s]

Epoch 9/10
Train Loss: 0.3000 | Train F1: 0.8638
Val Loss: 1.4176 | Val F1: 0.4675
Epoch Time: 82.58s

Epoch 10/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.589]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.53batch/s]

Epoch 10/10
Train Loss: 0.3078 | Train F1: 0.8582
Val Loss: 1.4630 | Val F1: 0.4628
Epoch Time: 82.51s

Finalised: 369/3776 conv1 channels zeroed (9.8%)
Saved → trained_models/pwkd_self_r50_r10/pwkd_self_r50_r10_full.pth

Warming up pwkd_self_r50_r10...
Running inference...
  ratio: 10% | F1: 0.4161 | params: 22,089,853 | latency: 1.13ms

============================================================
  PWKD Option 2 (ResNet50) — pruning ratio 15%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.867]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.53batch/s]

Epoch 1/10
Train Loss: 0.8293 | Train F1: 0.6763
Val Loss: 1.4827 | Val F1: 0.4454
Epoch Time: 82.61s

Epoch 2/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.751]
Validating: 100%|██████████| 50/50 [00:03<00:00, 14.01batch/s]

Epoch 2/10
Train Loss: 0.4987 | Train F1: 0.7495
Val Loss: 1.4398 | Val F1: 0.4487
Epoch Time: 83.02s

Epoch 3/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.313]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.43batch/s]

Epoch 3/10
Train Loss: 0.4349 | Train F1: 0.7797
Val Loss: 1.3864 | Val F1: 0.4456
Epoch Time: 82.52s

Epoch 4/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.506]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.62batch/s]

Epoch 4/10
Train Loss: 0.3947 | Train F1: 0.8119
Val Loss: 1.4542 | Val F1: 0.4546
Epoch Time: 82.52s

Epoch 5/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.462]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.46batch/s]

Epoch 5/10
Train Loss: 0.3508 | Train F1: 0.8270
Val Loss: 1.3977 | Val F1: 0.4420
Epoch Time: 82.54s

Epoch 6/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.385]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.44batch/s]

Epoch 6/10
Train Loss: 0.3410 | Train F1: 0.8343
Val Loss: 1.4189 | Val F1: 0.4317
Epoch Time: 82.64s

Epoch 7/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.323]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.54batch/s]

Epoch 7/10
Train Loss: 0.3338 | Train F1: 0.8462
Val Loss: 1.4629 | Val F1: 0.4476
Epoch Time: 82.62s

Epoch 8/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.275]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.48batch/s]

Epoch 8/10
Train Loss: 0.3278 | Train F1: 0.8429
Val Loss: 1.4697 | Val F1: 0.4339
Epoch Time: 82.62s

Epoch 9/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.236]
Validating: 100%|██████████| 50/50 [00:03<00:00, 13.99batch/s]

Epoch 9/10
Train Loss: 0.3233 | Train F1: 0.8496
Val Loss: 1.4521 | Val F1: 0.4550
Epoch Time: 82.96s

Epoch 10/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.394]
Validating: 100%|██████████| 50/50 [00:03<00:00, 13.98batch/s]

Epoch 10/10
Train Loss: 0.3196 | Train F1: 0.8602
Val Loss: 1.4557 | Val F1: 0.4395
Epoch Time: 82.90s

Finalised: 559/3776 conv1 channels zeroed (14.8%)
Saved → trained_models/pwkd_self_r50_r15/pwkd_self_r50_r15_full.pth

Warming up pwkd_self_r50_r15...
Running inference...
  ratio: 15% | F1: 0.3867 | params: 21,311,613 | latency: 1.13ms

============================================================
  PWKD Option 2 (ResNet50) — pruning ratio 20%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [01:19<00:00,  3.12batch/s, loss=0.527]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.45batch/s]

Epoch 1/10
Train Loss: 0.8588 | Train F1: 0.6659
Val Loss: 1.5140 | Val F1: 0.4194
Epoch Time: 83.12s

Epoch 2/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.725]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.53batch/s]

Epoch 2/10
Train Loss: 0.5226 | Train F1: 0.7552
Val Loss: 1.5079 | Val F1: 0.4322
Epoch Time: 82.61s

Epoch 3/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.381]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.51batch/s]

Epoch 3/10
Train Loss: 0.4306 | Train F1: 0.7897
Val Loss: 1.4933 | Val F1: 0.4368
Epoch Time: 82.56s

Epoch 4/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.683]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.57batch/s]

Epoch 4/10
Train Loss: 0.4113 | Train F1: 0.8057
Val Loss: 1.4687 | Val F1: 0.4569
Epoch Time: 82.61s

Epoch 5/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.537]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.50batch/s]

Epoch 5/10
Train Loss: 0.3659 | Train F1: 0.8253
Val Loss: 1.4515 | Val F1: 0.4491
Epoch Time: 82.61s

Epoch 6/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.497]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.51batch/s]

Epoch 6/10
Train Loss: 0.3490 | Train F1: 0.8346
Val Loss: 1.4060 | Val F1: 0.4627
Epoch Time: 82.58s

Epoch 7/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.36]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.53batch/s]

Epoch 7/10
Train Loss: 0.3379 | Train F1: 0.8472
Val Loss: 1.5628 | Val F1: 0.4526
Epoch Time: 82.73s

Epoch 8/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.476]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.60batch/s]

Epoch 8/10
Train Loss: 0.3574 | Train F1: 0.8385
Val Loss: 1.3646 | Val F1: 0.4434
Epoch Time: 82.51s

Epoch 9/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.6]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.48batch/s]

Epoch 9/10
Train Loss: 0.3337 | Train F1: 0.8534
Val Loss: 1.4645 | Val F1: 0.4441
Epoch Time: 82.53s

Epoch 10/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.347]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.48batch/s]

Epoch 10/10
Train Loss: 0.3352 | Train F1: 0.8584
Val Loss: 1.4849 | Val F1: 0.4420
Epoch Time: 82.63s

Finalised: 748/3776 conv1 channels zeroed (19.8%)
Saved → trained_models/pwkd_self_r50_r20/pwkd_self_r50_r20_full.pth

Warming up pwkd_self_r50_r20...
Running inference...
  ratio: 20% | F1: 0.3585 | params: 20,520,829 | latency: 1.12ms

============================================================
  PWKD Option 2 (ResNet50) — pruning ratio 25%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.868]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.55batch/s]

Epoch 1/10
Train Loss: 0.8540 | Train F1: 0.6731
Val Loss: 1.5474 | Val F1: 0.4341
Epoch Time: 82.67s

Epoch 2/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.572]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.53batch/s]

Epoch 2/10
Train Loss: 0.5088 | Train F1: 0.7659
Val Loss: 1.4615 | Val F1: 0.4272
Epoch Time: 82.59s

Epoch 3/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.857]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.46batch/s]

Epoch 3/10
Train Loss: 0.4381 | Train F1: 0.7914
Val Loss: 1.4467 | Val F1: 0.4172
Epoch Time: 82.61s

Epoch 4/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.453]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.55batch/s]

Epoch 4/10
Train Loss: 0.3981 | Train F1: 0.8142
Val Loss: 1.5278 | Val F1: 0.4237
Epoch Time: 82.60s

Epoch 5/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.456]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.53batch/s]

Epoch 5/10
Train Loss: 0.3960 | Train F1: 0.8246
Val Loss: 1.4525 | Val F1: 0.4273
Epoch Time: 82.59s

Epoch 6/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.36]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.55batch/s]

Epoch 6/10
Train Loss: 0.3641 | Train F1: 0.8336
Val Loss: 1.4776 | Val F1: 0.4471
Epoch Time: 82.64s

Epoch 7/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.303]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.51batch/s]

Epoch 7/10
Train Loss: 0.3475 | Train F1: 0.8478
Val Loss: 1.4643 | Val F1: 0.4336
Epoch Time: 82.59s

Epoch 8/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.403]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.56batch/s]

Epoch 8/10
Train Loss: 0.3484 | Train F1: 0.8498
Val Loss: 1.4504 | Val F1: 0.4384
Epoch Time: 82.60s

Epoch 9/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.57]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.46batch/s]

Epoch 9/10
Train Loss: 0.3510 | Train F1: 0.8478
Val Loss: 1.4648 | Val F1: 0.4382
Epoch Time: 82.58s

Epoch 10/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.433]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.49batch/s]

Epoch 10/10
Train Loss: 0.3498 | Train F1: 0.8491
Val Loss: 1.4643 | Val F1: 0.4336
Epoch Time: 82.54s

Finalised: 944/3776 conv1 channels zeroed (25.0%)
Saved → trained_models/pwkd_self_r50_r25/pwkd_self_r50_r25_full.pth

Warming up pwkd_self_r50_r25...
Running inference...
  ratio: 25% | F1: 0.3113 | params: 19,721,341 | latency: 1.13ms

============================================================
  PWKD Option 2 (ResNet50) — pruning ratio 30%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.851]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.47batch/s]

Epoch 1/10
Train Loss: 0.8839 | Train F1: 0.6615
Val Loss: 1.4591 | Val F1: 0.4160
Epoch Time: 82.63s

Epoch 2/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=1.05]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.52batch/s]

Epoch 2/10
Train Loss: 0.5105 | Train F1: 0.7684
Val Loss: 1.3986 | Val F1: 0.4388
Epoch Time: 82.68s

Epoch 3/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.585]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.45batch/s]

Epoch 3/10
Train Loss: 0.4482 | Train F1: 0.7872
Val Loss: 1.3626 | Val F1: 0.4472
Epoch Time: 82.53s

Epoch 4/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.641]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.45batch/s]

Epoch 4/10
Train Loss: 0.4056 | Train F1: 0.8163
Val Loss: 1.4959 | Val F1: 0.4402
Epoch Time: 82.59s

Epoch 5/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.451]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.48batch/s]

Epoch 5/10
Train Loss: 0.4021 | Train F1: 0.8192
Val Loss: 1.4264 | Val F1: 0.4612
Epoch Time: 82.63s

Epoch 6/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.304]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.56batch/s]

Epoch 6/10
Train Loss: 0.3793 | Train F1: 0.8384
Val Loss: 1.4823 | Val F1: 0.4502
Epoch Time: 82.57s

Epoch 7/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.506]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.48batch/s]

Epoch 7/10
Train Loss: 0.3738 | Train F1: 0.8479
Val Loss: 1.4120 | Val F1: 0.4291
Epoch Time: 82.55s

Epoch 8/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.492]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.47batch/s]

Epoch 8/10
Train Loss: 0.3612 | Train F1: 0.8515
Val Loss: 1.3284 | Val F1: 0.4727
Epoch Time: 82.57s

Epoch 9/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.401]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.54batch/s]

Epoch 9/10
Train Loss: 0.3530 | Train F1: 0.8486
Val Loss: 1.3597 | Val F1: 0.4562
Epoch Time: 82.54s

Epoch 10/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.385]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.59batch/s]

Epoch 10/10
Train Loss: 0.3601 | Train F1: 0.8529
Val Loss: 1.4100 | Val F1: 0.4521
Epoch Time: 82.57s

Finalised: 1124/3776 conv1 channels zeroed (29.8%)
Saved → trained_models/pwkd_self_r50_r30/pwkd_self_r50_r30_full.pth

Warming up pwkd_self_r50_r30...
Running inference...
  ratio: 30% | F1: 0.1447 | params: 18,968,957 | latency: 1.12ms

============================================================
  PWKD Option 2 (ResNet50) — pruning ratio 35%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.919]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.45batch/s]

Epoch 1/10
Train Loss: 0.8927 | Train F1: 0.6556
Val Loss: 1.4596 | Val F1: 0.4299
Epoch Time: 82.77s

Epoch 2/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.914]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.45batch/s]

Epoch 2/10
Train Loss: 0.5528 | Train F1: 0.7634
Val Loss: 1.3972 | Val F1: 0.4500
Epoch Time: 82.62s

Epoch 3/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.693]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.43batch/s]

Epoch 3/10
Train Loss: 0.4597 | Train F1: 0.7844
Val Loss: 1.3862 | Val F1: 0.4437
Epoch Time: 82.58s

Epoch 4/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.736]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.43batch/s]

Epoch 4/10
Train Loss: 0.4276 | Train F1: 0.8179
Val Loss: 1.3898 | Val F1: 0.4585
Epoch Time: 82.57s

Epoch 5/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.672]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.55batch/s]

Epoch 5/10
Train Loss: 0.4146 | Train F1: 0.8253
Val Loss: 1.4337 | Val F1: 0.4570
Epoch Time: 82.59s

Epoch 6/10: 100%|██████████| 249/249 [01:20<00:00,  3.08batch/s, loss=0.55]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.46batch/s]

Epoch 6/10
Train Loss: 0.3919 | Train F1: 0.8331
Val Loss: 1.3927 | Val F1: 0.4663
Epoch Time: 83.99s

Epoch 7/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.454]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.54batch/s]

Epoch 7/10
Train Loss: 0.3781 | Train F1: 0.8411
Val Loss: 1.3517 | Val F1: 0.4638
Epoch Time: 82.54s

Epoch 8/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.42]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.40batch/s]

Epoch 8/10
Train Loss: 0.3684 | Train F1: 0.8507
Val Loss: 1.4436 | Val F1: 0.4485
Epoch Time: 82.61s

Epoch 9/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.405]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.54batch/s]

Epoch 9/10
Train Loss: 0.3829 | Train F1: 0.8396
Val Loss: 1.4384 | Val F1: 0.4466
Epoch Time: 82.68s

Epoch 10/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.33]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.57batch/s]

Epoch 10/10
Train Loss: 0.3547 | Train F1: 0.8638
Val Loss: 1.3608 | Val F1: 0.4625
Epoch Time: 82.54s

Finalised: 1313/3776 conv1 channels zeroed (34.8%)
Saved → trained_models/pwkd_self_r50_r35/pwkd_self_r50_r35_full.pth

Warming up pwkd_self_r50_r35...
Running inference...
  ratio: 35% | F1: 0.0763 | params: 18,178,173 | latency: 1.12ms

============================================================
  PWKD Option 2 (ResNet50) — pruning ratio 40%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.738]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.50batch/s]

Epoch 1/10
Train Loss: 0.8952 | Train F1: 0.6617
Val Loss: 1.4734 | Val F1: 0.4296
Epoch Time: 82.75s

Epoch 2/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=1]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.53batch/s]

Epoch 2/10
Train Loss: 0.5416 | Train F1: 0.7588
Val Loss: 1.4542 | Val F1: 0.4577
Epoch Time: 82.72s

Epoch 3/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.601]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.48batch/s]

Epoch 3/10
Train Loss: 0.4910 | Train F1: 0.7868
Val Loss: 1.5316 | Val F1: 0.4219
Epoch Time: 82.64s

Epoch 4/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.486]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.51batch/s]

Epoch 4/10
Train Loss: 0.4455 | Train F1: 0.8085
Val Loss: 1.3881 | Val F1: 0.4822
Epoch Time: 82.62s

Epoch 5/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.579]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.51batch/s]

Epoch 5/10
Train Loss: 0.4127 | Train F1: 0.8312
Val Loss: 1.4360 | Val F1: 0.4524
Epoch Time: 82.56s

Epoch 6/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.412]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.52batch/s]

Epoch 6/10
Train Loss: 0.3929 | Train F1: 0.8397
Val Loss: 1.3739 | Val F1: 0.4585
Epoch Time: 82.58s

Epoch 7/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.496]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.51batch/s]

Epoch 7/10
Train Loss: 0.3746 | Train F1: 0.8461
Val Loss: 1.3633 | Val F1: 0.4491
Epoch Time: 82.72s

Epoch 8/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.303]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.47batch/s]

Epoch 8/10
Train Loss: 0.3773 | Train F1: 0.8486
Val Loss: 1.4921 | Val F1: 0.4316
Epoch Time: 82.73s

Epoch 9/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.743]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.38batch/s]

Epoch 9/10
Train Loss: 0.4782 | Train F1: 0.8218
Val Loss: 1.6173 | Val F1: 0.3949
Epoch Time: 82.66s

Epoch 10/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.367]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.51batch/s]

Epoch 10/10
Train Loss: 0.4910 | Train F1: 0.8021
Val Loss: 1.5533 | Val F1: 0.4100
Epoch Time: 82.78s

Finalised: 1502/3776 conv1 channels zeroed (39.8%)
Saved → trained_models/pwkd_self_r50_r40/pwkd_self_r50_r40_full.pth

Warming up pwkd_self_r50_r40...
Running inference...
  ratio: 40% | F1: 0.0471 | params: 17,403,261 | latency: 1.13ms

============================================================
  PWKD Option 2 (ResNet50) — pruning ratio 45%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.661]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.44batch/s]

Epoch 1/10
Train Loss: 0.8925 | Train F1: 0.6696
Val Loss: 1.4899 | Val F1: 0.4378
Epoch Time: 82.68s

Epoch 2/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.481]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.40batch/s]

Epoch 2/10
Train Loss: 0.5633 | Train F1: 0.7571
Val Loss: 1.4244 | Val F1: 0.4611
Epoch Time: 82.63s

Epoch 3/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.459]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.54batch/s]

Epoch 3/10
Train Loss: 0.4799 | Train F1: 0.7989
Val Loss: 1.4899 | Val F1: 0.4482
Epoch Time: 82.57s

Epoch 4/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.422]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.44batch/s]

Epoch 4/10
Train Loss: 0.4561 | Train F1: 0.8019
Val Loss: 1.4453 | Val F1: 0.4533
Epoch Time: 82.61s

Epoch 5/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.596]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.43batch/s]

Epoch 5/10
Train Loss: 0.4429 | Train F1: 0.8160
Val Loss: 1.4175 | Val F1: 0.4441
Epoch Time: 82.68s

Epoch 6/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.504]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.41batch/s]

Epoch 6/10
Train Loss: 0.4205 | Train F1: 0.8312
Val Loss: 1.4269 | Val F1: 0.4382
Epoch Time: 82.73s

Epoch 7/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.714]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.45batch/s]

Epoch 7/10
Train Loss: 0.3922 | Train F1: 0.8448
Val Loss: 1.4545 | Val F1: 0.4412
Epoch Time: 82.67s

Epoch 8/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.352]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.42batch/s]

Epoch 8/10
Train Loss: 0.3901 | Train F1: 0.8447
Val Loss: 1.5278 | Val F1: 0.4328
Epoch Time: 82.69s

Epoch 9/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.302]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.55batch/s]

Epoch 9/10
Train Loss: 0.3807 | Train F1: 0.8499
Val Loss: 1.4799 | Val F1: 0.4471
Epoch Time: 82.64s

Epoch 10/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.6]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.52batch/s]

Epoch 10/10
Train Loss: 0.3796 | Train F1: 0.8606
Val Loss: 1.5419 | Val F1: 0.4391
Epoch Time: 82.65s

Finalised: 1692/3776 conv1 channels zeroed (44.8%)
Saved → trained_models/pwkd_self_r50_r45/pwkd_self_r50_r45_full.pth

Warming up pwkd_self_r50_r45...
Running inference...
  ratio: 45% | F1: 0.0208 | params: 16,609,149 | latency: 1.14ms

============================================================
  PWKD Option 2 (ResNet50) — pruning ratio 50%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=1.65]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.47batch/s]

Epoch 1/10
Train Loss: 0.9291 | Train F1: 0.6646
Val Loss: 1.5876 | Val F1: 0.4071
Epoch Time: 82.62s

Epoch 2/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.573]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.47batch/s]

Epoch 2/10
Train Loss: 0.5727 | Train F1: 0.7597
Val Loss: 1.4512 | Val F1: 0.4436
Epoch Time: 82.61s

Epoch 3/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.445]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.42batch/s]

Epoch 3/10
Train Loss: 0.4791 | Train F1: 0.8014
Val Loss: 1.4756 | Val F1: 0.4436
Epoch Time: 82.64s

Epoch 4/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.413]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.54batch/s]

Epoch 4/10
Train Loss: 0.4524 | Train F1: 0.8177
Val Loss: 1.3762 | Val F1: 0.4548
Epoch Time: 82.69s

Epoch 5/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.525]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.56batch/s]

Epoch 5/10
Train Loss: 0.4419 | Train F1: 0.8229
Val Loss: 1.5263 | Val F1: 0.4538
Epoch Time: 82.56s

Epoch 6/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.566]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.57batch/s]

Epoch 6/10
Train Loss: 0.4577 | Train F1: 0.8205
Val Loss: 1.5095 | Val F1: 0.4169
Epoch Time: 82.64s

Epoch 7/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.484]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.48batch/s]

Epoch 7/10
Train Loss: 0.4218 | Train F1: 0.8362
Val Loss: 1.4097 | Val F1: 0.4553
Epoch Time: 82.65s

Epoch 8/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.363]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.53batch/s]

Epoch 8/10
Train Loss: 0.3945 | Train F1: 0.8495
Val Loss: 1.4366 | Val F1: 0.4633
Epoch Time: 82.63s

Epoch 9/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.387]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.53batch/s]

Epoch 9/10
Train Loss: 0.3831 | Train F1: 0.8558
Val Loss: 1.4509 | Val F1: 0.4416
Epoch Time: 82.67s

Epoch 10/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.562]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.56batch/s]

Epoch 10/10
Train Loss: 0.3836 | Train F1: 0.8668
Val Loss: 1.5393 | Val F1: 0.4423
Epoch Time: 82.67s

Finalised: 1888/3776 conv1 channels zeroed (50.0%)
Saved → trained_models/pwkd_self_r50_r50/pwkd_self_r50_r50_full.pth

Warming up pwkd_self_r50_r50...
Running inference...
  ratio: 50% | F1: 0.0094 | params: 15,809,661 | latency: 1.13ms

============================================================
  PWKD Option 2 (ResNet50) — pruning ratio 70%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.631]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.35batch/s]

Epoch 1/10
Train Loss: 0.9375 | Train F1: 0.6630
Val Loss: 1.5153 | Val F1: 0.4250
Epoch Time: 82.84s

Epoch 2/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.926]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.44batch/s]

Epoch 2/10
Train Loss: 0.6042 | Train F1: 0.7675
Val Loss: 1.4361 | Val F1: 0.4478
Epoch Time: 82.63s

Epoch 3/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.551]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.49batch/s]

Epoch 3/10
Train Loss: 0.5319 | Train F1: 0.7964
Val Loss: 1.3566 | Val F1: 0.4670
Epoch Time: 82.76s

Epoch 4/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.508]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.47batch/s]

Epoch 4/10
Train Loss: 0.5095 | Train F1: 0.8026
Val Loss: 1.3695 | Val F1: 0.4628
Epoch Time: 82.65s

Epoch 5/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.49]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.41batch/s]

Epoch 5/10
Train Loss: 0.4750 | Train F1: 0.8226
Val Loss: 1.4384 | Val F1: 0.4304
Epoch Time: 82.61s

Epoch 6/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.808]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.53batch/s]

Epoch 6/10
Train Loss: 0.4823 | Train F1: 0.8353
Val Loss: 1.4420 | Val F1: 0.4419
Epoch Time: 82.58s

Epoch 7/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.7]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.51batch/s]

Epoch 7/10
Train Loss: 0.4504 | Train F1: 0.8465
Val Loss: 1.3882 | Val F1: 0.4394
Epoch Time: 82.62s

Epoch 8/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.523]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.42batch/s]

Epoch 8/10
Train Loss: 0.4423 | Train F1: 0.8478
Val Loss: 1.4550 | Val F1: 0.4502
Epoch Time: 82.74s

Epoch 9/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.47]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.45batch/s]

Epoch 9/10
Train Loss: 0.4533 | Train F1: 0.8402
Val Loss: 1.4965 | Val F1: 0.4385
Epoch Time: 82.67s

Epoch 10/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.549]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.43batch/s]

Epoch 10/10
Train Loss: 0.4399 | Train F1: 0.8492
Val Loss: 1.4904 | Val F1: 0.4293
Epoch Time: 82.70s

Finalised: 2636/3776 conv1 channels zeroed (69.8%)
Saved → trained_models/pwkd_self_r50_r70/pwkd_self_r50_r70_full.pth

Warming up pwkd_self_r50_r70...
Running inference...
  ratio: 70% | F1: 0.0008 | params: 12,697,469 | latency: 1.12ms

============================================================
  PWKD Option 2 (ResNet50) — pruning ratio 90%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.831]
Validating: 100%|██████████| 50/50 [00:03<00:00, 13.82batch/s]

Epoch 1/10
Train Loss: 0.9857 | Train F1: 0.6712
Val Loss: 1.5569 | Val F1: 0.4295
Epoch Time: 83.10s

Epoch 2/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.576]
Validating: 100%|██████████| 50/50 [00:03<00:00, 13.85batch/s]

Epoch 2/10
Train Loss: 0.6635 | Train F1: 0.7644
Val Loss: 1.4600 | Val F1: 0.4317
Epoch Time: 83.22s

Epoch 3/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.517]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.49batch/s]

Epoch 3/10
Train Loss: 0.5844 | Train F1: 0.7901
Val Loss: 1.5286 | Val F1: 0.4300
Epoch Time: 82.60s

Epoch 4/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.528]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.45batch/s]

Epoch 4/10
Train Loss: 0.5495 | Train F1: 0.8058
Val Loss: 1.4215 | Val F1: 0.4540
Epoch Time: 82.64s

Epoch 5/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.656]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.52batch/s]

Epoch 5/10
Train Loss: 0.5140 | Train F1: 0.8341
Val Loss: 1.4568 | Val F1: 0.4501
Epoch Time: 82.58s

Epoch 6/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.511]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.54batch/s]

Epoch 6/10
Train Loss: 0.4996 | Train F1: 0.8405
Val Loss: 1.4560 | Val F1: 0.4576
Epoch Time: 82.56s

Epoch 7/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.721]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.56batch/s]

Epoch 7/10
Train Loss: 0.5004 | Train F1: 0.8432
Val Loss: 1.4846 | Val F1: 0.4178
Epoch Time: 82.62s

Epoch 8/10: 100%|██████████| 249/249 [01:19<00:00,  3.14batch/s, loss=0.637]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.45batch/s]

Epoch 8/10
Train Loss: 0.5262 | Train F1: 0.8303
Val Loss: 1.5443 | Val F1: 0.4157
Epoch Time: 82.58s

Epoch 9/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.884]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.53batch/s]

Epoch 9/10
Train Loss: 0.4927 | Train F1: 0.8462
Val Loss: 1.4909 | Val F1: 0.4517
Epoch Time: 82.66s

Epoch 10/10: 100%|██████████| 249/249 [01:19<00:00,  3.13batch/s, loss=0.555]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.57batch/s]

Epoch 10/10
Train Loss: 0.5002 | Train F1: 0.8470
Val Loss: 1.4490 | Val F1: 0.4721
Epoch Time: 82.73s

Finalised: 3391/3776 conv1 channels zeroed (89.8%)
Saved → trained_models/pwkd_self_r50_r90/pwkd_self_r50_r90_full.pth

Warming up pwkd_self_r50_r90...
Running inference...
  ratio: 90% | F1: 0.0006 | params: 9,576,573 | latency: 1.13ms

PWKD Option 2 (ResNet50) — Results

               Size Reduction (%)  F1 Score  Size (MB)  Latency (ms)
Pruning Ratio
0%                           0.00    0.4952       90.4          1.12
5%                           3.18    0.4553       90.4          1.13
10%                          6.53    0.4161       90.4          1.13
15%                          9.82    0.3867       90.4          1.13
20%                         13.17    0.3585       90.4          1.12
25%                         16.55    0.3113       90.4          1.13
30%                         19.74    0.1447       90.4          1.12
35%                         23.08    0.0763       90.4          1.12
40%                         26.36    0.0471       90.4          1.13
45%                         29.72    0.0208       90.4          1.14
50%                         33.10    0.0094       90.4          1.13
70%                         46.27    0.0008       90.4          1.12
90%                         59.48    0.0006       90.4          1.13

In [5]:
print('\nPWKD Option 2 (ResNet50) — Results')
display(summary_df)

PWKD Option 2 (ResNet50) — Results

               Size Reduction (%)  F1 Score  Size (MB)  Latency (ms)
Pruning Ratio
0%                           0.00    0.4952       90.4          1.12
5%                           3.18    0.4553       90.4          1.13
10%                          6.53    0.4161       90.4          1.13
15%                          9.82    0.3867       90.4          1.13
20%                         13.17    0.3585       90.4          1.12
25%                         16.55    0.3113       90.4          1.13
30%                         19.74    0.1447       90.4          1.12
35%                         23.08    0.0763       90.4          1.12
40%                         26.36    0.0471       90.4          1.13
45%                         29.72    0.0208       90.4          1.14
50%                         33.10    0.0094       90.4          1.13
70%                         46.27    0.0008       90.4          1.12
90%                         59.48    0.0006       90.4          1.13