# PWKD Option 2 — Prune ResNet50 Directly

Implements **Pruning While Knowledge Distillation** (Wang et al., 2025) using:
- **Teacher**: frozen pretrained ResNet50 (RadImageNet weights)
- **Student**: a deep copy of the *same* pretrained ResNet50, fine-tuned
  with PWKD simultaneously pruning and distilling

This is a same-architecture setup, closely analogous to the paper's
EDSR-32-256 → EDSR-16-64 setup but keeping the architecture fixed and
instead driving channels to zero through the differentiable sparsity penalty.
The wavelet channel-projection step is skipped (teacher/student channels match).

Starting from pretrained weights means the student begins at the teacher's
F1 level (~0.49) and PWKD nudges it toward a smaller, slightly lower-F1 model —
a much more favourable trade-off than training from scratch.

Produces 5 compressed models at pruning ratios [10%, 25%, 50%, 70%, 90%],
saved to `trained_models/pwkd_self_r50_<ratio>/` and uploaded to HuggingFace.

**Run all cells top to bottom. Requires GPU.**

In [2]:
import os, copy, subprocess
import torch

target = 'CS6423_knowledge_distillation_project'
if not os.getcwd().endswith(target):
    import sys
    os.chdir(os.path.join(os.getcwd(), target))
    if os.getcwd() not in sys.path:
        sys.path.insert(0, os.getcwd())

print(f'Working dir: {os.getcwd()}')
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device: {device}')

subprocess.run(['pip', 'install', 'PyWavelets', '--quiet'], check=True)

Working dir: /home/cor10/CS6423_knowledge_distillation_project
Device: cuda

CompletedProcess(args=['pip', 'install', 'PyWavelets', '--quiet'], returncode=0)

In [3]:
import pandas as pd
from modules.dataset_prepper import datasetPrepper

data_prep = datasetPrepper(
    dataframe_path='data/labels.csv',
    image_dir='data/test_images',
).prepare(compute_class_weights=True)

NUM_CLASSES = len(data_prep.class_names)
print(f'Classes: {NUM_CLASSES}')
print(f'Train batches: {len(data_prep.train_loader)} | Val batches: {len(data_prep.val_loader)}')

Classes: 61
Train batches: 249 | Val batches: 50

In [4]:
from modules.imagenet_loader import ImagenetLoader
from modules.evaluate_model import ModelEvaluator

loader = ImagenetLoader()

# Load pretrained ResNet50 — this serves as both the frozen teacher
# and the starting point for each student deep copy
resnet50_pretrained = loader.load_radimagenet_resnet50(
    weights_path='trained_models/resnet50_baseline_gpu_new/resnet50_baseline_gpu_new.pth',
    load_type='load'
)
resnet50_pretrained = resnet50_pretrained.to(device)

evaluator = ModelEvaluator(
    data_loader=data_prep.val_loader,
    class_names=data_prep.class_names,
    device=str(device),
)

baseline_metrics = evaluator.evaluate_single(resnet50_pretrained, 'ResNet50_baseline')
BASELINE_PARAMS  = baseline_metrics['total_parameters']
print(f'ResNet50 baseline F1:    {baseline_metrics["f1_macro"]:.4f}')
print(f'ResNet50 baseline params: {BASELINE_PARAMS:,}')

Warming up ResNet50_baseline...
Running inference...
ResNet50 baseline F1:    0.4867
ResNet50 baseline params: 23,633,021

## Same-architecture note

Because teacher and student are both ResNet50, their channel counts match at
every stage. The MVRM projection step (`teacher_proj`) becomes an identity
operation — `PWKDLoss` handles this automatically when `teacher_channels ==
student_channels`.

| Stage   | ResNet50 teacher | ResNet50 student |
|---------|-----------------|------------------|
| layer2  | 512             | 512              |
| layer3  | 1024            | 1024             |
| layer4  | 2048            | 2048             |

In [4]:
import torch.nn as nn
import copy
from modules.model_trainer import modelTrainer
from modules.evaluate_model import ModelEvaluator
from pwkd import PWKDLoss, make_aux_fn, finalise_student

RESNET50_CHANNELS = {'layer2': 512, 'layer3': 1024, 'layer4': 2048}

PRUNING_RATIOS = [0.10, 0.25, 0.50, 0.70, 0.90]
NUM_EPOCHS     = 10
LAM            = 0.2
KD_TEMP        = 4.0
SPARSE_WEIGHT  = 1e-4

evaluator = ModelEvaluator(
    data_loader=data_prep.val_loader,
    class_names=data_prep.class_names,
    device=str(device),
)

teacher = copy.deepcopy(resnet50_pretrained).eval()
for p in teacher.parameters():
    p.requires_grad = False

pwkd_metrics = []

print(f'ResNet50 baseline F1:    {baseline_metrics["f1_macro"]:.4f}')
print(f'ResNet50 baseline params: {BASELINE_PARAMS:,}')


for ratio in PRUNING_RATIOS:
    label = f'pwkd_self_r50_r{int(ratio * 100)}'
    print(f'\n{"="*60}')
    print(f'  PWKD Option 2 (ResNet50) — pruning ratio {ratio:.0%}')
    print(f'{"="*60}')

    student = copy.deepcopy(resnet50_pretrained).to(device)
    for p in student.parameters():
        p.requires_grad = True

    pwkd_loss = PWKDLoss(
        student          = student,
        teacher          = teacher,
        pruning_ratio    = ratio,
        teacher_channels = RESNET50_CHANNELS,
        student_channels = RESNET50_CHANNELS,
        class_weights    = data_prep.class_weights.to(device)
                           if data_prep.class_weights is not None else None,
        lam              = LAM,
        kd_temp          = KD_TEMP,
        sparse_weight    = SPARSE_WEIGHT,
    ).to(device)

    trainer = modelTrainer(
        model      = student,
        data_prep  = data_prep,
        device     = device,
        learn_rate = 2e-4,
        num_epochs = NUM_EPOCHS,
        model_name = label,
    )
    trainer.loss_fn   = pwkd_loss
    trainer.optimizer = torch.optim.AdamW(
        list(student.parameters()) + list(pwkd_loss.parameters()),
        lr=2e-4, weight_decay=1e-2,
    )
    trainer.create_classnum_to_label_map(data_prep.class_names)
    trainer.train_all(save_as_object=True, aux_forward_fn=make_aux_fn(teacher), pwkd=True)

    student = finalise_student(student, pwkd_loss, data_prep.train_loader, device)

    import os
    save_dir = os.path.join('trained_models', label)
    os.makedirs(save_dir, exist_ok=True)
    torch.save({'model': student, 'epoch': NUM_EPOCHS},
               os.path.join(save_dir, f'{label}_full.pth'))
    print(f'Saved → {save_dir}/{label}_full.pth')

    student.eval()
    metrics = evaluator.evaluate_single(student, label)

    pwkd_metrics.append({
        'Pruning Ratio':      f'{int(ratio*100)}%',
        'Size Reduction (%)': round((BASELINE_PARAMS - metrics['total_parameters'])
                                    / BASELINE_PARAMS * 100, 2),
        'F1 Score':           round(metrics['f1_macro'],     4),
        'Size (MB)':          round(metrics['model_size_mb'], 1),
        'Latency (ms)':       round(metrics['avg_latency_ms'], 2),
    })
    print(f'  ratio: {ratio:.0%} | F1: {metrics["f1_macro"]:.4f} | '
          f'params: {metrics["total_parameters"]:,} | '
          f'latency: {metrics["avg_latency_ms"]:.2f}ms')

summary_df = pd.DataFrame(pwkd_metrics).set_index('Pruning Ratio')
print('\nPWKD Option 2 (ResNet50) — Results')
display(summary_df)

ResNet50 baseline F1:    0.4867
ResNet50 baseline params: 23,633,021

============================================================
  PWKD Option 2 (ResNet50) — pruning ratio 10%
============================================================
  Epoch 1/10 [  4.8%]  loss: 1.6986
  Epoch 1/10 [  9.6%]  loss: 1.8080
  Epoch 1/10 [ 14.5%]  loss: 1.6390
  Epoch 1/10 [ 19.3%]  loss: 1.7549
  Epoch 1/10 [ 24.1%]  loss: 1.6983
  Epoch 1/10 [ 28.9%]  loss: 1.5767
  Epoch 1/10 [ 33.7%]  loss: 1.3698
  Epoch 1/10 [ 38.6%]  loss: 1.3338
  Epoch 1/10 [ 43.4%]  loss: 1.2441
  Epoch 1/10 [ 48.2%]  loss: 1.2156
  Epoch 1/10 [ 53.0%]  loss: 1.0117
  Epoch 1/10 [ 57.8%]  loss: 1.0255
  Epoch 1/10 [ 62.7%]  loss: 0.8561
  Epoch 1/10 [ 67.5%]  loss: 0.9334
  Epoch 1/10 [ 72.3%]  loss: 0.8918
  Epoch 1/10 [ 77.1%]  loss: 0.8055
  Epoch 1/10 [ 81.9%]  loss: 0.7813
  Epoch 1/10 [ 86.7%]  loss: 0.8445
  Epoch 1/10 [ 91.6%]  loss: 0.7270
  Epoch 1/10 [ 96.4%]  loss: 0.7205
  Epoch 1/10 [100.0%]  loss: 0.6381

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.52batch/s]

Epoch 1/10
Train Loss: 1.1766 | Train F1: 0.5508
Val Loss: 1.8624 | Val F1: 0.3392
Epoch Time: 83.09s

  Epoch 2/10 [  4.8%]  loss: 0.6421
  Epoch 2/10 [  9.6%]  loss: 0.7673
  Epoch 2/10 [ 14.5%]  loss: 0.6194
  Epoch 2/10 [ 19.3%]  loss: 0.7054
  Epoch 2/10 [ 24.1%]  loss: 0.6418
  Epoch 2/10 [ 28.9%]  loss: 0.6113
  Epoch 2/10 [ 33.7%]  loss: 0.5786
  Epoch 2/10 [ 38.6%]  loss: 0.6168
  Epoch 2/10 [ 43.4%]  loss: 0.6297
  Epoch 2/10 [ 48.2%]  loss: 0.5810
  Epoch 2/10 [ 53.0%]  loss: 0.5850
  Epoch 2/10 [ 57.8%]  loss: 0.5506
  Epoch 2/10 [ 62.7%]  loss: 0.5951
  Epoch 2/10 [ 67.5%]  loss: 0.5492
  Epoch 2/10 [ 72.3%]  loss: 0.5798
  Epoch 2/10 [ 77.1%]  loss: 0.5027
  Epoch 2/10 [ 81.9%]  loss: 0.5502
  Epoch 2/10 [ 86.7%]  loss: 0.5543
  Epoch 2/10 [ 91.6%]  loss: 0.5796
  Epoch 2/10 [ 96.4%]  loss: 0.5313
  Epoch 2/10 [100.0%]  loss: 0.5922

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.63batch/s]

Epoch 2/10
Train Loss: 0.5983 | Train F1: 0.6944
Val Loss: 1.7453 | Val F1: 0.3756
Epoch Time: 82.45s

  Epoch 3/10 [  4.8%]  loss: 0.5583
  Epoch 3/10 [  9.6%]  loss: 0.5152
  Epoch 3/10 [ 14.5%]  loss: 0.5257
  Epoch 3/10 [ 19.3%]  loss: 0.5228
  Epoch 3/10 [ 24.1%]  loss: 0.4995
  Epoch 3/10 [ 28.9%]  loss: 0.4980
  Epoch 3/10 [ 33.7%]  loss: 0.4892
  Epoch 3/10 [ 38.6%]  loss: 0.4763
  Epoch 3/10 [ 43.4%]  loss: 0.4469
  Epoch 3/10 [ 48.2%]  loss: 0.4479
  Epoch 3/10 [ 53.0%]  loss: 0.4822
  Epoch 3/10 [ 57.8%]  loss: 0.4725
  Epoch 3/10 [ 62.7%]  loss: 0.4319
  Epoch 3/10 [ 67.5%]  loss: 0.4931
  Epoch 3/10 [ 72.3%]  loss: 0.4413
  Epoch 3/10 [ 77.1%]  loss: 0.4430
  Epoch 3/10 [ 81.9%]  loss: 0.4286
  Epoch 3/10 [ 86.7%]  loss: 0.4508
  Epoch 3/10 [ 91.6%]  loss: 0.4837
  Epoch 3/10 [ 96.4%]  loss: 0.4490
  Epoch 3/10 [100.0%]  loss: 0.4456

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.58batch/s]

Epoch 3/10
Train Loss: 0.4766 | Train F1: 0.7401
Val Loss: 1.7349 | Val F1: 0.3868
Epoch Time: 82.58s

  Epoch 4/10 [  4.8%]  loss: 0.4230
  Epoch 4/10 [  9.6%]  loss: 0.4204
  Epoch 4/10 [ 14.5%]  loss: 0.4362
  Epoch 4/10 [ 19.3%]  loss: 0.4367
  Epoch 4/10 [ 24.1%]  loss: 0.4279
  Epoch 4/10 [ 28.9%]  loss: 0.4310
  Epoch 4/10 [ 33.7%]  loss: 0.4451
  Epoch 4/10 [ 38.6%]  loss: 0.4615
  Epoch 4/10 [ 43.4%]  loss: 0.4432
  Epoch 4/10 [ 48.2%]  loss: 0.4447
  Epoch 4/10 [ 53.0%]  loss: 0.4018
  Epoch 4/10 [ 57.8%]  loss: 0.4309
  Epoch 4/10 [ 62.7%]  loss: 0.4832
  Epoch 4/10 [ 67.5%]  loss: 0.4485
  Epoch 4/10 [ 72.3%]  loss: 0.4443
  Epoch 4/10 [ 77.1%]  loss: 0.4495
  Epoch 4/10 [ 81.9%]  loss: 0.4549
  Epoch 4/10 [ 86.7%]  loss: 0.4228
  Epoch 4/10 [ 91.6%]  loss: 0.4078
  Epoch 4/10 [ 96.4%]  loss: 0.4822
  Epoch 4/10 [100.0%]  loss: 0.4291

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.62batch/s]

Epoch 4/10
Train Loss: 0.4394 | Train F1: 0.7698
Val Loss: 1.7180 | Val F1: 0.3733
Epoch Time: 82.55s

  Epoch 5/10 [  4.8%]  loss: 0.4241
  Epoch 5/10 [  9.6%]  loss: 0.4012
  Epoch 5/10 [ 14.5%]  loss: 0.4080
  Epoch 5/10 [ 19.3%]  loss: 0.4276
  Epoch 5/10 [ 24.1%]  loss: 0.4310
  Epoch 5/10 [ 28.9%]  loss: 0.4279
  Epoch 5/10 [ 33.7%]  loss: 0.3975
  Epoch 5/10 [ 38.6%]  loss: 0.3829
  Epoch 5/10 [ 43.4%]  loss: 0.4120
  Epoch 5/10 [ 48.2%]  loss: 0.4080
  Epoch 5/10 [ 53.0%]  loss: 0.4115
  Epoch 5/10 [ 57.8%]  loss: 0.4019
  Epoch 5/10 [ 62.7%]  loss: 0.3750
  Epoch 5/10 [ 67.5%]  loss: 0.3643
  Epoch 5/10 [ 72.3%]  loss: 0.3928
  Epoch 5/10 [ 77.1%]  loss: 0.3608
  Epoch 5/10 [ 81.9%]  loss: 0.3601
  Epoch 5/10 [ 86.7%]  loss: 0.3954
  Epoch 5/10 [ 91.6%]  loss: 0.4494
  Epoch 5/10 [ 96.4%]  loss: 0.4437
  Epoch 5/10 [100.0%]  loss: 0.4416

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.53batch/s]

Epoch 5/10
Train Loss: 0.4051 | Train F1: 0.7872
Val Loss: 1.8112 | Val F1: 0.3675
Epoch Time: 82.57s

  Epoch 6/10 [  4.8%]  loss: 0.4736
  Epoch 6/10 [  9.6%]  loss: 0.4382
  Epoch 6/10 [ 14.5%]  loss: 0.4605
  Epoch 6/10 [ 19.3%]  loss: 0.4508
  Epoch 6/10 [ 24.1%]  loss: 0.4349
  Epoch 6/10 [ 28.9%]  loss: 0.4153
  Epoch 6/10 [ 33.7%]  loss: 0.4161
  Epoch 6/10 [ 38.6%]  loss: 0.4394
  Epoch 6/10 [ 43.4%]  loss: 0.4583
  Epoch 6/10 [ 48.2%]  loss: 0.4069
  Epoch 6/10 [ 53.0%]  loss: 0.4534
  Epoch 6/10 [ 57.8%]  loss: 0.4113
  Epoch 6/10 [ 62.7%]  loss: 0.4191
  Epoch 6/10 [ 67.5%]  loss: 0.4156
  Epoch 6/10 [ 72.3%]  loss: 0.4004
  Epoch 6/10 [ 77.1%]  loss: 0.4133
  Epoch 6/10 [ 81.9%]  loss: 0.4486
  Epoch 6/10 [ 86.7%]  loss: 0.4607
  Epoch 6/10 [ 91.6%]  loss: 0.4918
  Epoch 6/10 [ 96.4%]  loss: 0.4693
  Epoch 6/10 [100.0%]  loss: 0.4309

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.58batch/s]

Epoch 6/10
Train Loss: 0.4386 | Train F1: 0.7728
Val Loss: 1.7463 | Val F1: 0.3666
Epoch Time: 82.59s

  Epoch 7/10 [  4.8%]  loss: 0.4329
  Epoch 7/10 [  9.6%]  loss: 0.4034
  Epoch 7/10 [ 14.5%]  loss: 0.4386
  Epoch 7/10 [ 19.3%]  loss: 0.3908
  Epoch 7/10 [ 24.1%]  loss: 0.4387
  Epoch 7/10 [ 28.9%]  loss: 0.4077
  Epoch 7/10 [ 33.7%]  loss: 0.3916
  Epoch 7/10 [ 38.6%]  loss: 0.3841
  Epoch 7/10 [ 43.4%]  loss: 0.3714
  Epoch 7/10 [ 48.2%]  loss: 0.3899
  Epoch 7/10 [ 53.0%]  loss: 0.3397
  Epoch 7/10 [ 57.8%]  loss: 0.3788
  Epoch 7/10 [ 62.7%]  loss: 0.3917
  Epoch 7/10 [ 67.5%]  loss: 0.3990
  Epoch 7/10 [ 72.3%]  loss: 0.3798
  Epoch 7/10 [ 77.1%]  loss: 0.3726
  Epoch 7/10 [ 81.9%]  loss: 0.3779
  Epoch 7/10 [ 86.7%]  loss: 0.3701
  Epoch 7/10 [ 91.6%]  loss: 0.3895
  Epoch 7/10 [ 96.4%]  loss: 0.3745
  Epoch 7/10 [100.0%]  loss: 0.4066

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.57batch/s]

Epoch 7/10
Train Loss: 0.3917 | Train F1: 0.7865
Val Loss: 1.7255 | Val F1: 0.3967
Epoch Time: 82.57s

  Epoch 8/10 [  4.8%]  loss: 0.3977
  Epoch 8/10 [  9.6%]  loss: 0.3823
  Epoch 8/10 [ 14.5%]  loss: 0.4022
  Epoch 8/10 [ 19.3%]  loss: 0.3623
  Epoch 8/10 [ 24.1%]  loss: 0.3343
  Epoch 8/10 [ 28.9%]  loss: 0.3415
  Epoch 8/10 [ 33.7%]  loss: 0.3297
  Epoch 8/10 [ 38.6%]  loss: 0.3639
  Epoch 8/10 [ 43.4%]  loss: 0.3586
  Epoch 8/10 [ 48.2%]  loss: 0.3862
  Epoch 8/10 [ 53.0%]  loss: 0.3674
  Epoch 8/10 [ 57.8%]  loss: 0.3239
  Epoch 8/10 [ 62.7%]  loss: 0.3481
  Epoch 8/10 [ 67.5%]  loss: 0.3509
  Epoch 8/10 [ 72.3%]  loss: 0.3696
  Epoch 8/10 [ 77.1%]  loss: 0.3540
  Epoch 8/10 [ 81.9%]  loss: 0.3870
  Epoch 8/10 [ 86.7%]  loss: 0.4545
  Epoch 8/10 [ 91.6%]  loss: 0.4781
  Epoch 8/10 [ 96.4%]  loss: 0.5440
  Epoch 8/10 [100.0%]  loss: 0.5094

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.53batch/s]

Epoch 8/10
Train Loss: 0.3864 | Train F1: 0.7998
Val Loss: 1.9055 | Val F1: 0.3362
Epoch Time: 82.56s

  Epoch 9/10 [  4.8%]  loss: 0.5024
  Epoch 9/10 [  9.6%]  loss: 0.4963
  Epoch 9/10 [ 14.5%]  loss: 0.5126
  Epoch 9/10 [ 19.3%]  loss: 0.4541
  Epoch 9/10 [ 24.1%]  loss: 0.5212
  Epoch 9/10 [ 28.9%]  loss: 0.4995
  Epoch 9/10 [ 33.7%]  loss: 0.5236
  Epoch 9/10 [ 38.6%]  loss: 0.5612
  Epoch 9/10 [ 43.4%]  loss: 0.5489
  Epoch 9/10 [ 48.2%]  loss: 0.6555
  Epoch 9/10 [ 53.0%]  loss: 0.5822
  Epoch 9/10 [ 57.8%]  loss: 0.5823
  Epoch 9/10 [ 62.7%]  loss: 0.6429
  Epoch 9/10 [ 67.5%]  loss: 0.6014
  Epoch 9/10 [ 72.3%]  loss: 0.6620
  Epoch 9/10 [ 77.1%]  loss: 0.7416
  Epoch 9/10 [ 81.9%]  loss: 0.8079
  Epoch 9/10 [ 86.7%]  loss: 0.8676
  Epoch 9/10 [ 91.6%]  loss: 0.8363
  Epoch 9/10 [ 96.4%]  loss: 0.9175
  Epoch 9/10 [100.0%]  loss: 0.8628

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.54batch/s]

Epoch 9/10
Train Loss: 0.6344 | Train F1: 0.7085
Val Loss: 2.4423 | Val F1: 0.2840
Epoch Time: 82.27s

  Epoch 10/10 [  4.8%]  loss: 1.0083
  Epoch 10/10 [  9.6%]  loss: 0.9186
  Epoch 10/10 [ 14.5%]  loss: 0.9825
  Epoch 10/10 [ 19.3%]  loss: 0.9558
  Epoch 10/10 [ 24.1%]  loss: 0.8055
  Epoch 10/10 [ 28.9%]  loss: 0.7494
  Epoch 10/10 [ 33.7%]  loss: 0.7231
  Epoch 10/10 [ 38.6%]  loss: 0.7610
  Epoch 10/10 [ 43.4%]  loss: 0.6962
  Epoch 10/10 [ 48.2%]  loss: 0.6873
  Epoch 10/10 [ 53.0%]  loss: 0.6086
  Epoch 10/10 [ 57.8%]  loss: 0.5979
  Epoch 10/10 [ 62.7%]  loss: 0.5600
  Epoch 10/10 [ 67.5%]  loss: 0.5843
  Epoch 10/10 [ 72.3%]  loss: 0.4983
  Epoch 10/10 [ 77.1%]  loss: 0.5726
  Epoch 10/10 [ 81.9%]  loss: 0.5357
  Epoch 10/10 [ 86.7%]  loss: 0.4820
  Epoch 10/10 [ 91.6%]  loss: 0.5108
  Epoch 10/10 [ 96.4%]  loss: 0.5012
  Epoch 10/10 [100.0%]  loss: 0.4838

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.59batch/s]

Epoch 10/10
Train Loss: 0.6796 | Train F1: 0.6797
Val Loss: 1.7868 | Val F1: 0.3759
Epoch Time: 82.74s

Finalised: 369/3776 conv1 channels zeroed (9.8%)
Saved → trained_models/pwkd_self_r50_r10/pwkd_self_r50_r10_full.pth

Warming up pwkd_self_r50_r10...
Running inference...
  ratio: 10% | F1: 0.3489 | params: 22,089,853 | latency: 1.13ms

============================================================
  PWKD Option 2 (ResNet50) — pruning ratio 25%
============================================================
  Epoch 1/10 [  4.8%]  loss: 1.7566
  Epoch 1/10 [  9.6%]  loss: 2.1304
  Epoch 1/10 [ 14.5%]  loss: 1.8270
  Epoch 1/10 [ 19.3%]  loss: 1.6538
  Epoch 1/10 [ 24.1%]  loss: 1.5752
  Epoch 1/10 [ 28.9%]  loss: 1.3864
  Epoch 1/10 [ 33.7%]  loss: 1.3433
  Epoch 1/10 [ 38.6%]  loss: 1.0982
  Epoch 1/10 [ 43.4%]  loss: 1.1587
  Epoch 1/10 [ 48.2%]  loss: 1.0469
  Epoch 1/10 [ 53.0%]  loss: 1.0327
  Epoch 1/10 [ 57.8%]  loss: 1.0244
  Epoch 1/10 [ 62.7%]  loss: 0.8422
  Epoch 1/10 [ 67.5%]  loss: 0.8564
  Epoch 1/10 [ 72.3%]  loss: 0.8513
  Epoch 1/10 [ 77.1%]  loss: 0.7995
  Epoch 1/10 [ 81.9%]  loss: 0.8850
  Epoch 1/10 [ 86.7%]  loss: 0.8620
  Epoch 1/10 [ 91.6%]  loss: 0.7232
  Epoch 1/10 [ 96.4%]  loss: 0.7603
  Epoch 1/10 [100.0%]  loss: 0.7410

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.54batch/s]

Epoch 1/10
Train Loss: 1.1648 | Train F1: 0.5612
Val Loss: 1.9695 | Val F1: 0.3353
Epoch Time: 82.44s

  Epoch 2/10 [  4.8%]  loss: 0.8281
  Epoch 2/10 [  9.6%]  loss: 0.7321
  Epoch 2/10 [ 14.5%]  loss: 0.7073
  Epoch 2/10 [ 19.3%]  loss: 0.7041
  Epoch 2/10 [ 24.1%]  loss: 0.6776
  Epoch 2/10 [ 28.9%]  loss: 0.6567
  Epoch 2/10 [ 33.7%]  loss: 0.6078
  Epoch 2/10 [ 38.6%]  loss: 0.6353
  Epoch 2/10 [ 43.4%]  loss: 0.5954
  Epoch 2/10 [ 48.2%]  loss: 0.6101
  Epoch 2/10 [ 53.0%]  loss: 0.6115
  Epoch 2/10 [ 57.8%]  loss: 0.5626
  Epoch 2/10 [ 62.7%]  loss: 0.5690
  Epoch 2/10 [ 67.5%]  loss: 0.5852
  Epoch 2/10 [ 72.3%]  loss: 0.5866
  Epoch 2/10 [ 77.1%]  loss: 0.5115
  Epoch 2/10 [ 81.9%]  loss: 0.5691
  Epoch 2/10 [ 86.7%]  loss: 0.6077
  Epoch 2/10 [ 91.6%]  loss: 0.5414
  Epoch 2/10 [ 96.4%]  loss: 0.5302
  Epoch 2/10 [100.0%]  loss: 0.5408

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.54batch/s]

Epoch 2/10
Train Loss: 0.6186 | Train F1: 0.6824
Val Loss: 1.6261 | Val F1: 0.3914
Epoch Time: 82.59s

  Epoch 3/10 [  4.8%]  loss: 0.5247
  Epoch 3/10 [  9.6%]  loss: 0.4743
  Epoch 3/10 [ 14.5%]  loss: 0.5075
  Epoch 3/10 [ 19.3%]  loss: 0.4996
  Epoch 3/10 [ 24.1%]  loss: 0.5470
  Epoch 3/10 [ 28.9%]  loss: 0.4910
  Epoch 3/10 [ 33.7%]  loss: 0.4930
  Epoch 3/10 [ 38.6%]  loss: 0.4833
  Epoch 3/10 [ 43.4%]  loss: 0.4783
  Epoch 3/10 [ 48.2%]  loss: 0.4749
  Epoch 3/10 [ 53.0%]  loss: 0.4541
  Epoch 3/10 [ 57.8%]  loss: 0.4640
  Epoch 3/10 [ 62.7%]  loss: 0.4587
  Epoch 3/10 [ 67.5%]  loss: 0.5120
  Epoch 3/10 [ 72.3%]  loss: 0.4665
  Epoch 3/10 [ 77.1%]  loss: 0.4542
  Epoch 3/10 [ 81.9%]  loss: 0.4105
  Epoch 3/10 [ 86.7%]  loss: 0.4401
  Epoch 3/10 [ 91.6%]  loss: 0.4587
  Epoch 3/10 [ 96.4%]  loss: 0.4459
  Epoch 3/10 [100.0%]  loss: 0.4800

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.65batch/s]

Epoch 3/10
Train Loss: 0.4770 | Train F1: 0.7458
Val Loss: 1.6574 | Val F1: 0.4090
Epoch Time: 82.54s

  Epoch 4/10 [  4.8%]  loss: 0.4772
  Epoch 4/10 [  9.6%]  loss: 0.4325
  Epoch 4/10 [ 14.5%]  loss: 0.4307
  Epoch 4/10 [ 19.3%]  loss: 0.4054
  Epoch 4/10 [ 24.1%]  loss: 0.4906
  Epoch 4/10 [ 28.9%]  loss: 0.4330
  Epoch 4/10 [ 33.7%]  loss: 0.4885
  Epoch 4/10 [ 38.6%]  loss: 0.4440
  Epoch 4/10 [ 43.4%]  loss: 0.4423
  Epoch 4/10 [ 48.2%]  loss: 0.4708
  Epoch 4/10 [ 53.0%]  loss: 0.3876
  Epoch 4/10 [ 57.8%]  loss: 0.4276
  Epoch 4/10 [ 62.7%]  loss: 0.4269
  Epoch 4/10 [ 67.5%]  loss: 0.4464
  Epoch 4/10 [ 72.3%]  loss: 0.4366
  Epoch 4/10 [ 77.1%]  loss: 0.4211
  Epoch 4/10 [ 81.9%]  loss: 0.4275
  Epoch 4/10 [ 86.7%]  loss: 0.4221
  Epoch 4/10 [ 91.6%]  loss: 0.4201
  Epoch 4/10 [ 96.4%]  loss: 0.4372
  Epoch 4/10 [100.0%]  loss: 0.4135

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.62batch/s]

Epoch 4/10
Train Loss: 0.4375 | Train F1: 0.7671
Val Loss: 1.6945 | Val F1: 0.3624
Epoch Time: 82.57s

  Epoch 5/10 [  4.8%]  loss: 0.4104
  Epoch 5/10 [  9.6%]  loss: 0.4521
  Epoch 5/10 [ 14.5%]  loss: 0.4270
  Epoch 5/10 [ 19.3%]  loss: 0.4583
  Epoch 5/10 [ 24.1%]  loss: 0.4571
  Epoch 5/10 [ 28.9%]  loss: 0.4996
  Epoch 5/10 [ 33.7%]  loss: 0.5009
  Epoch 5/10 [ 38.6%]  loss: 0.5048
  Epoch 5/10 [ 43.4%]  loss: 0.5072
  Epoch 5/10 [ 48.2%]  loss: 0.5300
  Epoch 5/10 [ 53.0%]  loss: 0.4845
  Epoch 5/10 [ 57.8%]  loss: 0.4994
  Epoch 5/10 [ 62.7%]  loss: 0.4956
  Epoch 5/10 [ 67.5%]  loss: 0.4904
  Epoch 5/10 [ 72.3%]  loss: 0.4654
  Epoch 5/10 [ 77.1%]  loss: 0.4572
  Epoch 5/10 [ 81.9%]  loss: 0.4949
  Epoch 5/10 [ 86.7%]  loss: 0.4670
  Epoch 5/10 [ 91.6%]  loss: 0.4827
  Epoch 5/10 [ 96.4%]  loss: 0.4396
  Epoch 5/10 [100.0%]  loss: 0.5654

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.58batch/s]

Epoch 5/10
Train Loss: 0.4794 | Train F1: 0.7579
Val Loss: 1.6397 | Val F1: 0.3803
Epoch Time: 82.51s

  Epoch 6/10 [  4.8%]  loss: 0.4996
  Epoch 6/10 [  9.6%]  loss: 0.4914
  Epoch 6/10 [ 14.5%]  loss: 0.5333
  Epoch 6/10 [ 19.3%]  loss: 0.5171
  Epoch 6/10 [ 24.1%]  loss: 0.4669
  Epoch 6/10 [ 28.9%]  loss: 0.5193
  Epoch 6/10 [ 33.7%]  loss: 0.5039
  Epoch 6/10 [ 38.6%]  loss: 0.4752
  Epoch 6/10 [ 43.4%]  loss: 0.4861
  Epoch 6/10 [ 48.2%]  loss: 0.4927
  Epoch 6/10 [ 53.0%]  loss: 0.4797
  Epoch 6/10 [ 57.8%]  loss: 0.4549
  Epoch 6/10 [ 62.7%]  loss: 0.4588
  Epoch 6/10 [ 67.5%]  loss: 0.4257
  Epoch 6/10 [ 72.3%]  loss: 0.4161
  Epoch 6/10 [ 77.1%]  loss: 0.4484
  Epoch 6/10 [ 81.9%]  loss: 0.4516
  Epoch 6/10 [ 86.7%]  loss: 0.4273
  Epoch 6/10 [ 91.6%]  loss: 0.4089
  Epoch 6/10 [ 96.4%]  loss: 0.4306
  Epoch 6/10 [100.0%]  loss: 0.4495

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.60batch/s]

Epoch 6/10
Train Loss: 0.4687 | Train F1: 0.7665
Val Loss: 1.6835 | Val F1: 0.3848
Epoch Time: 82.58s

  Epoch 7/10 [  4.8%]  loss: 0.4078
  Epoch 7/10 [  9.6%]  loss: 0.4327
  Epoch 7/10 [ 14.5%]  loss: 0.4895
  Epoch 7/10 [ 19.3%]  loss: 0.4391
  Epoch 7/10 [ 24.1%]  loss: 0.4417
  Epoch 7/10 [ 28.9%]  loss: 0.4737
  Epoch 7/10 [ 33.7%]  loss: 0.5124
  Epoch 7/10 [ 38.6%]  loss: 0.4625
  Epoch 7/10 [ 43.4%]  loss: 0.5341
  Epoch 7/10 [ 48.2%]  loss: 0.5186
  Epoch 7/10 [ 53.0%]  loss: 0.5184
  Epoch 7/10 [ 57.8%]  loss: 0.4882
  Epoch 7/10 [ 62.7%]  loss: 0.4807
  Epoch 7/10 [ 67.5%]  loss: 0.4467
  Epoch 7/10 [ 72.3%]  loss: 0.4550
  Epoch 7/10 [ 77.1%]  loss: 0.4305
  Epoch 7/10 [ 81.9%]  loss: 0.4370
  Epoch 7/10 [ 86.7%]  loss: 0.4842
  Epoch 7/10 [ 91.6%]  loss: 0.4333
  Epoch 7/10 [ 96.4%]  loss: 0.4281
  Epoch 7/10 [100.0%]  loss: 0.4059

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.51batch/s]

Epoch 7/10
Train Loss: 0.4636 | Train F1: 0.7644
Val Loss: 1.8496 | Val F1: 0.3649
Epoch Time: 82.56s

  Epoch 8/10 [  4.8%]  loss: 0.4253
  Epoch 8/10 [  9.6%]  loss: 0.3955
  Epoch 8/10 [ 14.5%]  loss: 0.3981
  Epoch 8/10 [ 19.3%]  loss: 0.3895
  Epoch 8/10 [ 24.1%]  loss: 0.4078
  Epoch 8/10 [ 28.9%]  loss: 0.4186
  Epoch 8/10 [ 33.7%]  loss: 0.3986
  Epoch 8/10 [ 38.6%]  loss: 0.4049
  Epoch 8/10 [ 43.4%]  loss: 0.3564
  Epoch 8/10 [ 48.2%]  loss: 0.3924
  Epoch 8/10 [ 53.0%]  loss: 0.4005
  Epoch 8/10 [ 57.8%]  loss: 0.4221
  Epoch 8/10 [ 62.7%]  loss: 0.3739
  Epoch 8/10 [ 67.5%]  loss: 0.3734
  Epoch 8/10 [ 72.3%]  loss: 0.3541
  Epoch 8/10 [ 77.1%]  loss: 0.3682
  Epoch 8/10 [ 81.9%]  loss: 0.3791
  Epoch 8/10 [ 86.7%]  loss: 0.3781
  Epoch 8/10 [ 91.6%]  loss: 0.3770
  Epoch 8/10 [ 96.4%]  loss: 0.3576
  Epoch 8/10 [100.0%]  loss: 0.3906

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.46batch/s]

Epoch 8/10
Train Loss: 0.3886 | Train F1: 0.7963
Val Loss: 1.6367 | Val F1: 0.4044
Epoch Time: 82.59s

  Epoch 9/10 [  4.8%]  loss: 0.3642
  Epoch 9/10 [  9.6%]  loss: 0.3936
  Epoch 9/10 [ 14.5%]  loss: 0.3781
  Epoch 9/10 [ 19.3%]  loss: 0.3499
  Epoch 9/10 [ 24.1%]  loss: 0.3695
  Epoch 9/10 [ 28.9%]  loss: 0.3482
  Epoch 9/10 [ 33.7%]  loss: 0.3647
  Epoch 9/10 [ 38.6%]  loss: 0.3692
  Epoch 9/10 [ 43.4%]  loss: 0.3974
  Epoch 9/10 [ 48.2%]  loss: 0.3716
  Epoch 9/10 [ 53.0%]  loss: 0.4077
  Epoch 9/10 [ 57.8%]  loss: 0.3559
  Epoch 9/10 [ 62.7%]  loss: 0.4187
  Epoch 9/10 [ 67.5%]  loss: 0.4674
  Epoch 9/10 [ 72.3%]  loss: 0.4341
  Epoch 9/10 [ 77.1%]  loss: 0.4447
  Epoch 9/10 [ 81.9%]  loss: 0.4118
  Epoch 9/10 [ 86.7%]  loss: 0.4174
  Epoch 9/10 [ 91.6%]  loss: 0.4214
  Epoch 9/10 [ 96.4%]  loss: 0.3567
  Epoch 9/10 [100.0%]  loss: 0.4112

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.60batch/s]

Epoch 9/10
Train Loss: 0.3928 | Train F1: 0.7991
Val Loss: 1.6796 | Val F1: 0.4048
Epoch Time: 82.57s

  Epoch 10/10 [  4.8%]  loss: 0.3861
  Epoch 10/10 [  9.6%]  loss: 0.4155
  Epoch 10/10 [ 14.5%]  loss: 0.3799
  Epoch 10/10 [ 19.3%]  loss: 0.3665
  Epoch 10/10 [ 24.1%]  loss: 0.3517
  Epoch 10/10 [ 28.9%]  loss: 0.3746
  Epoch 10/10 [ 33.7%]  loss: 0.3712
  Epoch 10/10 [ 38.6%]  loss: 0.3786
  Epoch 10/10 [ 43.4%]  loss: 0.3369
  Epoch 10/10 [ 48.2%]  loss: 0.3648
  Epoch 10/10 [ 53.0%]  loss: 0.3565
  Epoch 10/10 [ 57.8%]  loss: 0.3717
  Epoch 10/10 [ 62.7%]  loss: 0.3717
  Epoch 10/10 [ 67.5%]  loss: 0.3703
  Epoch 10/10 [ 72.3%]  loss: 0.3341
  Epoch 10/10 [ 77.1%]  loss: 0.3757
  Epoch 10/10 [ 81.9%]  loss: 0.3765
  Epoch 10/10 [ 86.7%]  loss: 0.3454
  Epoch 10/10 [ 91.6%]  loss: 0.3372
  Epoch 10/10 [ 96.4%]  loss: 0.3736
  Epoch 10/10 [100.0%]  loss: 0.3630

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.61batch/s]

Epoch 10/10
Train Loss: 0.3668 | Train F1: 0.8152
Val Loss: 1.6449 | Val F1: 0.4071
Epoch Time: 82.57s

Finalised: 944/3776 conv1 channels zeroed (25.0%)
Saved → trained_models/pwkd_self_r50_r25/pwkd_self_r50_r25_full.pth

Warming up pwkd_self_r50_r25...
Running inference...
  ratio: 25% | F1: 0.2388 | params: 19,721,341 | latency: 1.12ms

============================================================
  PWKD Option 2 (ResNet50) — pruning ratio 50%
============================================================
  Epoch 1/10 [  4.8%]  loss: 1.6995
  Epoch 1/10 [  9.6%]  loss: 2.2356
  Epoch 1/10 [ 14.5%]  loss: 1.9275
  Epoch 1/10 [ 19.3%]  loss: 1.8016
  Epoch 1/10 [ 24.1%]  loss: 1.5798
  Epoch 1/10 [ 28.9%]  loss: 1.4979
  Epoch 1/10 [ 33.7%]  loss: 1.3618
  Epoch 1/10 [ 38.6%]  loss: 1.3142
  Epoch 1/10 [ 43.4%]  loss: 1.3369
  Epoch 1/10 [ 48.2%]  loss: 1.0863
  Epoch 1/10 [ 53.0%]  loss: 1.0191
  Epoch 1/10 [ 57.8%]  loss: 0.9827
  Epoch 1/10 [ 62.7%]  loss: 0.9613
  Epoch 1/10 [ 67.5%]  loss: 0.8771
  Epoch 1/10 [ 72.3%]  loss: 0.7797
  Epoch 1/10 [ 77.1%]  loss: 0.7198
  Epoch 1/10 [ 81.9%]  loss: 0.7218
  Epoch 1/10 [ 86.7%]  loss: 0.7210
  Epoch 1/10 [ 91.6%]  loss: 0.6611
  Epoch 1/10 [ 96.4%]  loss: 0.8096
  Epoch 1/10 [100.0%]  loss: 0.6787

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.55batch/s]

Epoch 1/10
Train Loss: 1.1857 | Train F1: 0.5503
Val Loss: 1.7822 | Val F1: 0.3637
Epoch Time: 82.65s

  Epoch 2/10 [  4.8%]  loss: 0.7376
  Epoch 2/10 [  9.6%]  loss: 0.7143
  Epoch 2/10 [ 14.5%]  loss: 0.6399
  Epoch 2/10 [ 19.3%]  loss: 0.6730
  Epoch 2/10 [ 24.1%]  loss: 0.6613
  Epoch 2/10 [ 28.9%]  loss: 0.7322
  Epoch 2/10 [ 33.7%]  loss: 0.7920
  Epoch 2/10 [ 38.6%]  loss: 0.6313
  Epoch 2/10 [ 43.4%]  loss: 0.6929
  Epoch 2/10 [ 48.2%]  loss: 0.6578
  Epoch 2/10 [ 53.0%]  loss: 0.5894
  Epoch 2/10 [ 57.8%]  loss: 0.6557
  Epoch 2/10 [ 62.7%]  loss: 0.6065
  Epoch 2/10 [ 67.5%]  loss: 0.5772
  Epoch 2/10 [ 72.3%]  loss: 0.5914
  Epoch 2/10 [ 77.1%]  loss: 0.5913
  Epoch 2/10 [ 81.9%]  loss: 0.5780
  Epoch 2/10 [ 86.7%]  loss: 0.6234
  Epoch 2/10 [ 91.6%]  loss: 0.5734
  Epoch 2/10 [ 96.4%]  loss: 0.5638
  Epoch 2/10 [100.0%]  loss: 0.5490

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.58batch/s]

Epoch 2/10
Train Loss: 0.6407 | Train F1: 0.6821
Val Loss: 1.6892 | Val F1: 0.3748
Epoch Time: 82.64s

  Epoch 3/10 [  4.8%]  loss: 0.5493
  Epoch 3/10 [  9.6%]  loss: 0.4786
  Epoch 3/10 [ 14.5%]  loss: 0.5039
  Epoch 3/10 [ 19.3%]  loss: 0.6036
  Epoch 3/10 [ 24.1%]  loss: 0.5093
  Epoch 3/10 [ 28.9%]  loss: 0.5745
  Epoch 3/10 [ 33.7%]  loss: 0.5721
  Epoch 3/10 [ 38.6%]  loss: 0.6250
  Epoch 3/10 [ 43.4%]  loss: 0.5658
  Epoch 3/10 [ 48.2%]  loss: 0.6013
  Epoch 3/10 [ 53.0%]  loss: 0.5596
  Epoch 3/10 [ 57.8%]  loss: 0.6138
  Epoch 3/10 [ 62.7%]  loss: 0.5452
  Epoch 3/10 [ 67.5%]  loss: 0.5212
  Epoch 3/10 [ 72.3%]  loss: 0.5258
  Epoch 3/10 [ 77.1%]  loss: 0.4993
  Epoch 3/10 [ 81.9%]  loss: 0.5048
  Epoch 3/10 [ 86.7%]  loss: 0.4903
  Epoch 3/10 [ 91.6%]  loss: 0.4686
  Epoch 3/10 [ 96.4%]  loss: 0.5015
  Epoch 3/10 [100.0%]  loss: 0.5361

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.52batch/s]

Epoch 3/10
Train Loss: 0.5405 | Train F1: 0.7278
Val Loss: 1.7037 | Val F1: 0.3846
Epoch Time: 82.55s

  Epoch 4/10 [  4.8%]  loss: 0.4795
  Epoch 4/10 [  9.6%]  loss: 0.4811
  Epoch 4/10 [ 14.5%]  loss: 0.4807
  Epoch 4/10 [ 19.3%]  loss: 0.4517
  Epoch 4/10 [ 24.1%]  loss: 0.4461
  Epoch 4/10 [ 28.9%]  loss: 0.4532
  Epoch 4/10 [ 33.7%]  loss: 0.4509
  Epoch 4/10 [ 38.6%]  loss: 0.4502
  Epoch 4/10 [ 43.4%]  loss: 0.4470
  Epoch 4/10 [ 48.2%]  loss: 0.4774
  Epoch 4/10 [ 53.0%]  loss: 0.4650
  Epoch 4/10 [ 57.8%]  loss: 0.4674
  Epoch 4/10 [ 62.7%]  loss: 0.4480
  Epoch 4/10 [ 67.5%]  loss: 0.4754
  Epoch 4/10 [ 72.3%]  loss: 0.4418
  Epoch 4/10 [ 77.1%]  loss: 0.5139
  Epoch 4/10 [ 81.9%]  loss: 0.5026
  Epoch 4/10 [ 86.7%]  loss: 0.4959
  Epoch 4/10 [ 91.6%]  loss: 0.5195
  Epoch 4/10 [ 96.4%]  loss: 0.4983
  Epoch 4/10 [100.0%]  loss: 0.5213

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.22batch/s]

Epoch 4/10
Train Loss: 0.4741 | Train F1: 0.7591
Val Loss: 1.7329 | Val F1: 0.3980
Epoch Time: 82.65s

  Epoch 5/10 [  4.8%]  loss: 0.4639
  Epoch 5/10 [  9.6%]  loss: 0.4494
  Epoch 5/10 [ 14.5%]  loss: 0.4852
  Epoch 5/10 [ 19.3%]  loss: 0.4612
  Epoch 5/10 [ 24.1%]  loss: 0.4507
  Epoch 5/10 [ 28.9%]  loss: 0.4714
  Epoch 5/10 [ 33.7%]  loss: 0.5010
  Epoch 5/10 [ 38.6%]  loss: 0.4926
  Epoch 5/10 [ 43.4%]  loss: 0.5121
  Epoch 5/10 [ 48.2%]  loss: 0.4864
  Epoch 5/10 [ 53.0%]  loss: 0.5019
  Epoch 5/10 [ 57.8%]  loss: 0.4825
  Epoch 5/10 [ 62.7%]  loss: 0.4768
  Epoch 5/10 [ 67.5%]  loss: 0.4712
  Epoch 5/10 [ 72.3%]  loss: 0.5054
  Epoch 5/10 [ 77.1%]  loss: 0.4868
  Epoch 5/10 [ 81.9%]  loss: 0.4946
  Epoch 5/10 [ 86.7%]  loss: 0.5273
  Epoch 5/10 [ 91.6%]  loss: 0.4689
  Epoch 5/10 [ 96.4%]  loss: 0.4811
  Epoch 5/10 [100.0%]  loss: 0.6048

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.54batch/s]

Epoch 5/10
Train Loss: 0.4879 | Train F1: 0.7560
Val Loss: 1.7906 | Val F1: 0.3808
Epoch Time: 82.48s

  Epoch 6/10 [  4.8%]  loss: 0.5266
  Epoch 6/10 [  9.6%]  loss: 0.4623
  Epoch 6/10 [ 14.5%]  loss: 0.4674
  Epoch 6/10 [ 19.3%]  loss: 0.4502
  Epoch 6/10 [ 24.1%]  loss: 0.5136
  Epoch 6/10 [ 28.9%]  loss: 0.5041
  Epoch 6/10 [ 33.7%]  loss: 0.4658
  Epoch 6/10 [ 38.6%]  loss: 0.4857
  Epoch 6/10 [ 43.4%]  loss: 0.5297
  Epoch 6/10 [ 48.2%]  loss: 0.4267
  Epoch 6/10 [ 53.0%]  loss: 0.4397
  Epoch 6/10 [ 57.8%]  loss: 0.4743
  Epoch 6/10 [ 62.7%]  loss: 0.4761
  Epoch 6/10 [ 67.5%]  loss: 0.4624
  Epoch 6/10 [ 72.3%]  loss: 0.4564
  Epoch 6/10 [ 77.1%]  loss: 0.4498
  Epoch 6/10 [ 81.9%]  loss: 0.4486
  Epoch 6/10 [ 86.7%]  loss: 0.4758
  Epoch 6/10 [ 91.6%]  loss: 0.4327
  Epoch 6/10 [ 96.4%]  loss: 0.4139
  Epoch 6/10 [100.0%]  loss: 0.4700

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.60batch/s]

Epoch 6/10
Train Loss: 0.4682 | Train F1: 0.7713
Val Loss: 1.7712 | Val F1: 0.3779
Epoch Time: 82.56s

  Epoch 7/10 [  4.8%]  loss: 0.4312
  Epoch 7/10 [  9.6%]  loss: 0.4735
  Epoch 7/10 [ 14.5%]  loss: 0.4158
  Epoch 7/10 [ 19.3%]  loss: 0.4275
  Epoch 7/10 [ 24.1%]  loss: 0.4378
  Epoch 7/10 [ 28.9%]  loss: 0.4156
  Epoch 7/10 [ 33.7%]  loss: 0.4146
  Epoch 7/10 [ 38.6%]  loss: 0.4686
  Epoch 7/10 [ 43.4%]  loss: 0.4099
  Epoch 7/10 [ 48.2%]  loss: 0.4555
  Epoch 7/10 [ 53.0%]  loss: 0.4202
  Epoch 7/10 [ 57.8%]  loss: 0.4376
  Epoch 7/10 [ 62.7%]  loss: 0.4150
  Epoch 7/10 [ 67.5%]  loss: 0.3859
  Epoch 7/10 [ 72.3%]  loss: 0.4115
  Epoch 7/10 [ 77.1%]  loss: 0.4090
  Epoch 7/10 [ 81.9%]  loss: 0.3825
  Epoch 7/10 [ 86.7%]  loss: 0.4029
  Epoch 7/10 [ 91.6%]  loss: 0.4020
  Epoch 7/10 [ 96.4%]  loss: 0.3700
  Epoch 7/10 [100.0%]  loss: 0.3896

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.60batch/s]

Epoch 7/10
Train Loss: 0.4183 | Train F1: 0.7925
Val Loss: 1.6234 | Val F1: 0.4161
Epoch Time: 82.57s

  Epoch 8/10 [  4.8%]  loss: 0.3757
  Epoch 8/10 [  9.6%]  loss: 0.4063
  Epoch 8/10 [ 14.5%]  loss: 0.3884
  Epoch 8/10 [ 19.3%]  loss: 0.3747
  Epoch 8/10 [ 24.1%]  loss: 0.3788
  Epoch 8/10 [ 28.9%]  loss: 0.3846
  Epoch 8/10 [ 33.7%]  loss: 0.3699
  Epoch 8/10 [ 38.6%]  loss: 0.3627
  Epoch 8/10 [ 43.4%]  loss: 0.3453
  Epoch 8/10 [ 48.2%]  loss: 0.3627
  Epoch 8/10 [ 53.0%]  loss: 0.3575
  Epoch 8/10 [ 57.8%]  loss: 0.3984
  Epoch 8/10 [ 62.7%]  loss: 0.3777
  Epoch 8/10 [ 67.5%]  loss: 0.3845
  Epoch 8/10 [ 72.3%]  loss: 0.3789
  Epoch 8/10 [ 77.1%]  loss: 0.3647
  Epoch 8/10 [ 81.9%]  loss: 0.3800
  Epoch 8/10 [ 86.7%]  loss: 0.3704
  Epoch 8/10 [ 91.6%]  loss: 0.3938
  Epoch 8/10 [ 96.4%]  loss: 0.3780
  Epoch 8/10 [100.0%]  loss: 0.4276

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.55batch/s]

Epoch 8/10
Train Loss: 0.3785 | Train F1: 0.8117
Val Loss: 1.8083 | Val F1: 0.3707
Epoch Time: 82.62s

  Epoch 9/10 [  4.8%]  loss: 0.3993
  Epoch 9/10 [  9.6%]  loss: 0.3828
  Epoch 9/10 [ 14.5%]  loss: 0.4056
  Epoch 9/10 [ 19.3%]  loss: 0.3897
  Epoch 9/10 [ 24.1%]  loss: 0.4278
  Epoch 9/10 [ 28.9%]  loss: 0.3573
  Epoch 9/10 [ 33.7%]  loss: 0.3574
  Epoch 9/10 [ 38.6%]  loss: 0.3891
  Epoch 9/10 [ 43.4%]  loss: 0.4646
  Epoch 9/10 [ 48.2%]  loss: 0.4654
  Epoch 9/10 [ 53.0%]  loss: 0.4867
  Epoch 9/10 [ 57.8%]  loss: 0.4795
  Epoch 9/10 [ 62.7%]  loss: 0.4358
  Epoch 9/10 [ 67.5%]  loss: 0.4882
  Epoch 9/10 [ 72.3%]  loss: 0.4674
  Epoch 9/10 [ 77.1%]  loss: 0.4365
  Epoch 9/10 [ 81.9%]  loss: 0.4279
  Epoch 9/10 [ 86.7%]  loss: 0.4476
  Epoch 9/10 [ 91.6%]  loss: 0.4442
  Epoch 9/10 [ 96.4%]  loss: 0.4325
  Epoch 9/10 [100.0%]  loss: 0.4251

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.58batch/s]

Epoch 9/10
Train Loss: 0.4291 | Train F1: 0.7909
Val Loss: 1.8790 | Val F1: 0.3919
Epoch Time: 82.60s

  Epoch 10/10 [  4.8%]  loss: 0.3875
  Epoch 10/10 [  9.6%]  loss: 0.3899
  Epoch 10/10 [ 14.5%]  loss: 0.4137
  Epoch 10/10 [ 19.3%]  loss: 0.3965
  Epoch 10/10 [ 24.1%]  loss: 0.3879
  Epoch 10/10 [ 28.9%]  loss: 0.4134
  Epoch 10/10 [ 33.7%]  loss: 0.3800
  Epoch 10/10 [ 38.6%]  loss: 0.3956
  Epoch 10/10 [ 43.4%]  loss: 0.4118
  Epoch 10/10 [ 48.2%]  loss: 0.3908
  Epoch 10/10 [ 53.0%]  loss: 0.4246
  Epoch 10/10 [ 57.8%]  loss: 0.4259
  Epoch 10/10 [ 62.7%]  loss: 0.3887
  Epoch 10/10 [ 67.5%]  loss: 0.4230
  Epoch 10/10 [ 72.3%]  loss: 0.4094
  Epoch 10/10 [ 77.1%]  loss: 0.4060
  Epoch 10/10 [ 81.9%]  loss: 0.4027
  Epoch 10/10 [ 86.7%]  loss: 0.4192
  Epoch 10/10 [ 91.6%]  loss: 0.4437
  Epoch 10/10 [ 96.4%]  loss: 0.3949
  Epoch 10/10 [100.0%]  loss: 0.4707

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.63batch/s]

Epoch 10/10
Train Loss: 0.4076 | Train F1: 0.8089
Val Loss: 1.8327 | Val F1: 0.3626
Epoch Time: 82.44s

Finalised: 1888/3776 conv1 channels zeroed (50.0%)
Saved → trained_models/pwkd_self_r50_r50/pwkd_self_r50_r50_full.pth

Warming up pwkd_self_r50_r50...
Running inference...
  ratio: 50% | F1: 0.0102 | params: 15,809,661 | latency: 1.12ms

============================================================
  PWKD Option 2 (ResNet50) — pruning ratio 70%
============================================================
  Epoch 1/10 [  4.8%]  loss: 1.8153
  Epoch 1/10 [  9.6%]  loss: 2.1958
  Epoch 1/10 [ 14.5%]  loss: 2.0175
  Epoch 1/10 [ 19.3%]  loss: 1.7245
  Epoch 1/10 [ 24.1%]  loss: 1.6536
  Epoch 1/10 [ 28.9%]  loss: 1.4720
  Epoch 1/10 [ 33.7%]  loss: 1.3831
  Epoch 1/10 [ 38.6%]  loss: 1.2803
  Epoch 1/10 [ 43.4%]  loss: 1.1590
  Epoch 1/10 [ 48.2%]  loss: 1.0957
  Epoch 1/10 [ 53.0%]  loss: 1.0561
  Epoch 1/10 [ 57.8%]  loss: 1.0030
  Epoch 1/10 [ 62.7%]  loss: 0.9601
  Epoch 1/10 [ 67.5%]  loss: 0.9210
  Epoch 1/10 [ 72.3%]  loss: 0.8338
  Epoch 1/10 [ 77.1%]  loss: 0.8525
  Epoch 1/10 [ 81.9%]  loss: 0.8072
  Epoch 1/10 [ 86.7%]  loss: 0.7208
  Epoch 1/10 [ 91.6%]  loss: 0.8001
  Epoch 1/10 [ 96.4%]  loss: 0.6814
  Epoch 1/10 [100.0%]  loss: 0.7197

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.42batch/s]

Epoch 1/10
Train Loss: 1.2035 | Train F1: 0.5475
Val Loss: 1.6928 | Val F1: 0.3979
Epoch Time: 82.63s

  Epoch 2/10 [  4.8%]  loss: 0.7227
  Epoch 2/10 [  9.6%]  loss: 0.6699
  Epoch 2/10 [ 14.5%]  loss: 0.6407
  Epoch 2/10 [ 19.3%]  loss: 0.7195
  Epoch 2/10 [ 24.1%]  loss: 0.7843
  Epoch 2/10 [ 28.9%]  loss: 0.6160
  Epoch 2/10 [ 33.7%]  loss: 0.6896
  Epoch 2/10 [ 38.6%]  loss: 0.6959
  Epoch 2/10 [ 43.4%]  loss: 0.7092
  Epoch 2/10 [ 48.2%]  loss: 0.6947
  Epoch 2/10 [ 53.0%]  loss: 0.7124
  Epoch 2/10 [ 57.8%]  loss: 0.6115
  Epoch 2/10 [ 62.7%]  loss: 0.6413
  Epoch 2/10 [ 67.5%]  loss: 0.6166
  Epoch 2/10 [ 72.3%]  loss: 0.6080
  Epoch 2/10 [ 77.1%]  loss: 0.5948
  Epoch 2/10 [ 81.9%]  loss: 0.5482
  Epoch 2/10 [ 86.7%]  loss: 0.5649
  Epoch 2/10 [ 91.6%]  loss: 0.5873
  Epoch 2/10 [ 96.4%]  loss: 0.5328
  Epoch 2/10 [100.0%]  loss: 0.5480

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.55batch/s]

Epoch 2/10
Train Loss: 0.6444 | Train F1: 0.6862
Val Loss: 1.7702 | Val F1: 0.3888
Epoch Time: 82.61s

  Epoch 3/10 [  4.8%]  loss: 0.6019
  Epoch 3/10 [  9.6%]  loss: 0.5480
  Epoch 3/10 [ 14.5%]  loss: 0.5622
  Epoch 3/10 [ 19.3%]  loss: 0.5252
  Epoch 3/10 [ 24.1%]  loss: 0.4796
  Epoch 3/10 [ 28.9%]  loss: 0.5103
  Epoch 3/10 [ 33.7%]  loss: 0.5216
  Epoch 3/10 [ 38.6%]  loss: 0.5128
  Epoch 3/10 [ 43.4%]  loss: 0.4876
  Epoch 3/10 [ 48.2%]  loss: 0.4474
  Epoch 3/10 [ 53.0%]  loss: 0.4786
  Epoch 3/10 [ 57.8%]  loss: 0.4480
  Epoch 3/10 [ 62.7%]  loss: 0.5111
  Epoch 3/10 [ 67.5%]  loss: 0.4902
  Epoch 3/10 [ 72.3%]  loss: 0.5080
  Epoch 3/10 [ 77.1%]  loss: 0.5009
  Epoch 3/10 [ 81.9%]  loss: 0.4715
  Epoch 3/10 [ 86.7%]  loss: 0.5053
  Epoch 3/10 [ 91.6%]  loss: 0.4669
  Epoch 3/10 [ 96.4%]  loss: 0.4792
  Epoch 3/10 [100.0%]  loss: 0.5669

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.50batch/s]

Epoch 3/10
Train Loss: 0.5051 | Train F1: 0.7354
Val Loss: 1.5965 | Val F1: 0.4061
Epoch Time: 82.70s

  Epoch 4/10 [  4.8%]  loss: 0.4754
  Epoch 4/10 [  9.6%]  loss: 0.4808
  Epoch 4/10 [ 14.5%]  loss: 0.4858
  Epoch 4/10 [ 19.3%]  loss: 0.4768
  Epoch 4/10 [ 24.1%]  loss: 0.4854
  Epoch 4/10 [ 28.9%]  loss: 0.4426
  Epoch 4/10 [ 33.7%]  loss: 0.4474
  Epoch 4/10 [ 38.6%]  loss: 0.4816
  Epoch 4/10 [ 43.4%]  loss: 0.4703
  Epoch 4/10 [ 48.2%]  loss: 0.4052
  Epoch 4/10 [ 53.0%]  loss: 0.4477
  Epoch 4/10 [ 57.8%]  loss: 0.4553
  Epoch 4/10 [ 62.7%]  loss: 0.4386
  Epoch 4/10 [ 67.5%]  loss: 0.4747
  Epoch 4/10 [ 72.3%]  loss: 0.4408
  Epoch 4/10 [ 77.1%]  loss: 0.4605
  Epoch 4/10 [ 81.9%]  loss: 0.4277
  Epoch 4/10 [ 86.7%]  loss: 0.4401
  Epoch 4/10 [ 91.6%]  loss: 0.4160
  Epoch 4/10 [ 96.4%]  loss: 0.4185
  Epoch 4/10 [100.0%]  loss: 0.4037

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.59batch/s]

Epoch 4/10
Train Loss: 0.4518 | Train F1: 0.7761
Val Loss: 1.6310 | Val F1: 0.3938
Epoch Time: 82.64s

  Epoch 5/10 [  4.8%]  loss: 0.3989
  Epoch 5/10 [  9.6%]  loss: 0.4054
  Epoch 5/10 [ 14.5%]  loss: 0.4188
  Epoch 5/10 [ 19.3%]  loss: 0.4352
  Epoch 5/10 [ 24.1%]  loss: 0.4323
  Epoch 5/10 [ 28.9%]  loss: 0.4204
  Epoch 5/10 [ 33.7%]  loss: 0.4307
  Epoch 5/10 [ 38.6%]  loss: 0.4220
  Epoch 5/10 [ 43.4%]  loss: 0.4448
  Epoch 5/10 [ 48.2%]  loss: 0.4477
  Epoch 5/10 [ 53.0%]  loss: 0.4255
  Epoch 5/10 [ 57.8%]  loss: 0.4389
  Epoch 5/10 [ 62.7%]  loss: 0.4296
  Epoch 5/10 [ 67.5%]  loss: 0.4112
  Epoch 5/10 [ 72.3%]  loss: 0.4214
  Epoch 5/10 [ 77.1%]  loss: 0.4143
  Epoch 5/10 [ 81.9%]  loss: 0.4255
  Epoch 5/10 [ 86.7%]  loss: 0.4248
  Epoch 5/10 [ 91.6%]  loss: 0.4445
  Epoch 5/10 [ 96.4%]  loss: 0.3992
  Epoch 5/10 [100.0%]  loss: 0.4237

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.58batch/s]

Epoch 5/10
Train Loss: 0.4245 | Train F1: 0.7941
Val Loss: 1.7376 | Val F1: 0.3915
Epoch Time: 82.59s

  Epoch 6/10 [  4.8%]  loss: 0.3889
  Epoch 6/10 [  9.6%]  loss: 0.4005
  Epoch 6/10 [ 14.5%]  loss: 0.3937
  Epoch 6/10 [ 19.3%]  loss: 0.4006
  Epoch 6/10 [ 24.1%]  loss: 0.4674
  Epoch 6/10 [ 28.9%]  loss: 0.4328
  Epoch 6/10 [ 33.7%]  loss: 0.3987
  Epoch 6/10 [ 38.6%]  loss: 0.4073
  Epoch 6/10 [ 43.4%]  loss: 0.4242
  Epoch 6/10 [ 48.2%]  loss: 0.4315
  Epoch 6/10 [ 53.0%]  loss: 0.4185
  Epoch 6/10 [ 57.8%]  loss: 0.4304
  Epoch 6/10 [ 62.7%]  loss: 0.4050
  Epoch 6/10 [ 67.5%]  loss: 0.4436
  Epoch 6/10 [ 72.3%]  loss: 0.4540
  Epoch 6/10 [ 77.1%]  loss: 0.4508
  Epoch 6/10 [ 81.9%]  loss: 0.4448
  Epoch 6/10 [ 86.7%]  loss: 0.4751
  Epoch 6/10 [ 91.6%]  loss: 0.4858
  Epoch 6/10 [ 96.4%]  loss: 0.4326
  Epoch 6/10 [100.0%]  loss: 0.4390

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.59batch/s]

Epoch 6/10
Train Loss: 0.4297 | Train F1: 0.7853
Val Loss: 1.7461 | Val F1: 0.4040
Epoch Time: 82.64s

  Epoch 7/10 [  4.8%]  loss: 0.4165
  Epoch 7/10 [  9.6%]  loss: 0.4087
  Epoch 7/10 [ 14.5%]  loss: 0.4371
  Epoch 7/10 [ 19.3%]  loss: 0.4735
  Epoch 7/10 [ 24.1%]  loss: 0.4296
  Epoch 7/10 [ 28.9%]  loss: 0.4256
  Epoch 7/10 [ 33.7%]  loss: 0.4808
  Epoch 7/10 [ 38.6%]  loss: 0.4566
  Epoch 7/10 [ 43.4%]  loss: 0.4760
  Epoch 7/10 [ 48.2%]  loss: 0.4942
  Epoch 7/10 [ 53.0%]  loss: 0.5108
  Epoch 7/10 [ 57.8%]  loss: 0.5401
  Epoch 7/10 [ 62.7%]  loss: 0.6194
  Epoch 7/10 [ 67.5%]  loss: 0.5572
  Epoch 7/10 [ 72.3%]  loss: 0.6088
  Epoch 7/10 [ 77.1%]  loss: 0.5595
  Epoch 7/10 [ 81.9%]  loss: 0.5825
  Epoch 7/10 [ 86.7%]  loss: 0.6217
  Epoch 7/10 [ 91.6%]  loss: 0.6070
  Epoch 7/10 [ 96.4%]  loss: 0.6878
  Epoch 7/10 [100.0%]  loss: 0.7878

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.56batch/s]

Epoch 7/10
Train Loss: 0.5294 | Train F1: 0.7517
Val Loss: 2.1878 | Val F1: 0.3039
Epoch Time: 82.55s

  Epoch 8/10 [  4.8%]  loss: 0.7820
  Epoch 8/10 [  9.6%]  loss: 0.8026
  Epoch 8/10 [ 14.5%]  loss: 0.7621
  Epoch 8/10 [ 19.3%]  loss: 0.7134
  Epoch 8/10 [ 24.1%]  loss: 0.7874
  Epoch 8/10 [ 28.9%]  loss: 1.0409
  Epoch 8/10 [ 33.7%]  loss: 0.9493
  Epoch 8/10 [ 38.6%]  loss: 1.0631
  Epoch 8/10 [ 43.4%]  loss: 1.0101
  Epoch 8/10 [ 48.2%]  loss: 1.0496
  Epoch 8/10 [ 53.0%]  loss: 1.0851
  Epoch 8/10 [ 57.8%]  loss: 0.9852
  Epoch 8/10 [ 62.7%]  loss: 0.8784
  Epoch 8/10 [ 67.5%]  loss: 0.8531
  Epoch 8/10 [ 72.3%]  loss: 0.7851
  Epoch 8/10 [ 77.1%]  loss: 0.7368
  Epoch 8/10 [ 81.9%]  loss: 0.7017
  Epoch 8/10 [ 86.7%]  loss: 0.6245
  Epoch 8/10 [ 91.6%]  loss: 0.5921
  Epoch 8/10 [ 96.4%]  loss: 0.6255
  Epoch 8/10 [100.0%]  loss: 0.6466

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.56batch/s]

Epoch 8/10
Train Loss: 0.8344 | Train F1: 0.6390
Val Loss: 1.9272 | Val F1: 0.3478
Epoch Time: 82.59s

  Epoch 9/10 [  4.8%]  loss: 0.6194
  Epoch 9/10 [  9.6%]  loss: 0.5580
  Epoch 9/10 [ 14.5%]  loss: 0.5243
  Epoch 9/10 [ 19.3%]  loss: 0.5549
  Epoch 9/10 [ 24.1%]  loss: 0.4685
  Epoch 9/10 [ 28.9%]  loss: 0.4857
  Epoch 9/10 [ 33.7%]  loss: 0.4956
  Epoch 9/10 [ 38.6%]  loss: 0.5435
  Epoch 9/10 [ 43.4%]  loss: 0.5004
  Epoch 9/10 [ 48.2%]  loss: 0.4918
  Epoch 9/10 [ 53.0%]  loss: 0.4235
  Epoch 9/10 [ 57.8%]  loss: 0.4215
  Epoch 9/10 [ 62.7%]  loss: 0.4479
  Epoch 9/10 [ 67.5%]  loss: 0.4495
  Epoch 9/10 [ 72.3%]  loss: 0.4285
  Epoch 9/10 [ 77.1%]  loss: 0.4115
  Epoch 9/10 [ 81.9%]  loss: 0.4399
  Epoch 9/10 [ 86.7%]  loss: 0.3908
  Epoch 9/10 [ 91.6%]  loss: 0.3950
  Epoch 9/10 [ 96.4%]  loss: 0.4203
  Epoch 9/10 [100.0%]  loss: 0.4335

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.52batch/s]

Epoch 9/10
Train Loss: 0.4721 | Train F1: 0.7625
Val Loss: 1.6852 | Val F1: 0.4033
Epoch Time: 82.62s

  Epoch 10/10 [  4.8%]  loss: 0.3864
  Epoch 10/10 [  9.6%]  loss: 0.4156
  Epoch 10/10 [ 14.5%]  loss: 0.4213
  Epoch 10/10 [ 19.3%]  loss: 0.4194
  Epoch 10/10 [ 24.1%]  loss: 0.4085
  Epoch 10/10 [ 28.9%]  loss: 0.4024
  Epoch 10/10 [ 33.7%]  loss: 0.4017
  Epoch 10/10 [ 38.6%]  loss: 0.3927
  Epoch 10/10 [ 43.4%]  loss: 0.4168
  Epoch 10/10 [ 48.2%]  loss: 0.3950
  Epoch 10/10 [ 53.0%]  loss: 0.4064
  Epoch 10/10 [ 57.8%]  loss: 0.3854
  Epoch 10/10 [ 62.7%]  loss: 0.3856
  Epoch 10/10 [ 67.5%]  loss: 0.3697
  Epoch 10/10 [ 72.3%]  loss: 0.3689
  Epoch 10/10 [ 77.1%]  loss: 0.3874
  Epoch 10/10 [ 81.9%]  loss: 0.3742
  Epoch 10/10 [ 86.7%]  loss: 0.3715
  Epoch 10/10 [ 91.6%]  loss: 0.3971
  Epoch 10/10 [ 96.4%]  loss: 0.3637
  Epoch 10/10 [100.0%]  loss: 0.3647

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.57batch/s]

Epoch 10/10
Train Loss: 0.3925 | Train F1: 0.8092
Val Loss: 1.7973 | Val F1: 0.4013
Epoch Time: 82.52s

Finalised: 2636/3776 conv1 channels zeroed (69.8%)
Saved → trained_models/pwkd_self_r50_r70/pwkd_self_r50_r70_full.pth

Warming up pwkd_self_r50_r70...
Running inference...
  ratio: 70% | F1: 0.0019 | params: 12,697,469 | latency: 1.13ms

============================================================
  PWKD Option 2 (ResNet50) — pruning ratio 90%
============================================================
  Epoch 1/10 [  4.8%]  loss: 1.8639
  Epoch 1/10 [  9.6%]  loss: 1.9679
  Epoch 1/10 [ 14.5%]  loss: 1.9612
  Epoch 1/10 [ 19.3%]  loss: 1.5648
  Epoch 1/10 [ 24.1%]  loss: 1.6218
  Epoch 1/10 [ 28.9%]  loss: 1.3009
  Epoch 1/10 [ 33.7%]  loss: 1.3476
  Epoch 1/10 [ 38.6%]  loss: 1.1319
  Epoch 1/10 [ 43.4%]  loss: 1.2698
  Epoch 1/10 [ 48.2%]  loss: 1.1485
  Epoch 1/10 [ 53.0%]  loss: 1.0923
  Epoch 1/10 [ 57.8%]  loss: 0.9551
  Epoch 1/10 [ 62.7%]  loss: 1.0037
  Epoch 1/10 [ 67.5%]  loss: 1.0398
  Epoch 1/10 [ 72.3%]  loss: 0.8659
  Epoch 1/10 [ 77.1%]  loss: 0.8259
  Epoch 1/10 [ 81.9%]  loss: 0.7630
  Epoch 1/10 [ 86.7%]  loss: 0.7971
  Epoch 1/10 [ 91.6%]  loss: 0.8555
  Epoch 1/10 [ 96.4%]  loss: 0.8118
  Epoch 1/10 [100.0%]  loss: 0.7802

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.57batch/s]

Epoch 1/10
Train Loss: 1.1939 | Train F1: 0.5568
Val Loss: 2.0310 | Val F1: 0.3290
Epoch Time: 82.61s

  Epoch 2/10 [  4.8%]  loss: 0.8261
  Epoch 2/10 [  9.6%]  loss: 0.6913
  Epoch 2/10 [ 14.5%]  loss: 0.7156
  Epoch 2/10 [ 19.3%]  loss: 0.7289
  Epoch 2/10 [ 24.1%]  loss: 0.7042
  Epoch 2/10 [ 28.9%]  loss: 0.7112
  Epoch 2/10 [ 33.7%]  loss: 0.6540
  Epoch 2/10 [ 38.6%]  loss: 0.6293
  Epoch 2/10 [ 43.4%]  loss: 0.6201
  Epoch 2/10 [ 48.2%]  loss: 0.5680
  Epoch 2/10 [ 53.0%]  loss: 0.6559
  Epoch 2/10 [ 57.8%]  loss: 0.6038
  Epoch 2/10 [ 62.7%]  loss: 0.5693
  Epoch 2/10 [ 67.5%]  loss: 0.5175
  Epoch 2/10 [ 72.3%]  loss: 0.5827
  Epoch 2/10 [ 77.1%]  loss: 0.5935
  Epoch 2/10 [ 81.9%]  loss: 0.5357
  Epoch 2/10 [ 86.7%]  loss: 0.5961
  Epoch 2/10 [ 91.6%]  loss: 0.5338
  Epoch 2/10 [ 96.4%]  loss: 0.6201
  Epoch 2/10 [100.0%]  loss: 0.5986

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.54batch/s]

Epoch 2/10
Train Loss: 0.6316 | Train F1: 0.6902
Val Loss: 1.7833 | Val F1: 0.3611
Epoch Time: 82.62s

  Epoch 3/10 [  4.8%]  loss: 0.5948
  Epoch 3/10 [  9.6%]  loss: 0.5317
  Epoch 3/10 [ 14.5%]  loss: 0.5729
  Epoch 3/10 [ 19.3%]  loss: 0.5620
  Epoch 3/10 [ 24.1%]  loss: 0.5824
  Epoch 3/10 [ 28.9%]  loss: 0.6303
  Epoch 3/10 [ 33.7%]  loss: 0.5497
  Epoch 3/10 [ 38.6%]  loss: 0.5830
  Epoch 3/10 [ 43.4%]  loss: 0.5274
  Epoch 3/10 [ 48.2%]  loss: 0.5850
  Epoch 3/10 [ 53.0%]  loss: 0.5778
  Epoch 3/10 [ 57.8%]  loss: 0.5489
  Epoch 3/10 [ 62.7%]  loss: 0.5194
  Epoch 3/10 [ 67.5%]  loss: 0.5296
  Epoch 3/10 [ 72.3%]  loss: 0.5843
  Epoch 3/10 [ 77.1%]  loss: 0.6186
  Epoch 3/10 [ 81.9%]  loss: 0.5351
  Epoch 3/10 [ 86.7%]  loss: 0.5259
  Epoch 3/10 [ 91.6%]  loss: 0.4990
  Epoch 3/10 [ 96.4%]  loss: 0.5502
  Epoch 3/10 [100.0%]  loss: 0.4890

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.49batch/s]

Epoch 3/10
Train Loss: 0.5578 | Train F1: 0.7285
Val Loss: 1.8040 | Val F1: 0.3816
Epoch Time: 82.62s

  Epoch 4/10 [  4.8%]  loss: 0.5519
  Epoch 4/10 [  9.6%]  loss: 0.5135
  Epoch 4/10 [ 14.5%]  loss: 0.5894
  Epoch 4/10 [ 19.3%]  loss: 0.5395
  Epoch 4/10 [ 24.1%]  loss: 0.5322
  Epoch 4/10 [ 28.9%]  loss: 0.5009
  Epoch 4/10 [ 33.7%]  loss: 0.4689
  Epoch 4/10 [ 38.6%]  loss: 0.4672
  Epoch 4/10 [ 43.4%]  loss: 0.4423
  Epoch 4/10 [ 48.2%]  loss: 0.4671
  Epoch 4/10 [ 53.0%]  loss: 0.5081
  Epoch 4/10 [ 57.8%]  loss: 0.4356
  Epoch 4/10 [ 62.7%]  loss: 0.5110
  Epoch 4/10 [ 67.5%]  loss: 0.5330
  Epoch 4/10 [ 72.3%]  loss: 0.5207
  Epoch 4/10 [ 77.1%]  loss: 0.5678
  Epoch 4/10 [ 81.9%]  loss: 0.5730
  Epoch 4/10 [ 86.7%]  loss: 0.5954
  Epoch 4/10 [ 91.6%]  loss: 0.6357
  Epoch 4/10 [ 96.4%]  loss: 0.5598
  Epoch 4/10 [100.0%]  loss: 0.6626

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.59batch/s]

Epoch 4/10
Train Loss: 0.5306 | Train F1: 0.7373
Val Loss: 2.0942 | Val F1: 0.3432
Epoch Time: 82.60s

  Epoch 5/10 [  4.8%]  loss: 0.6279
  Epoch 5/10 [  9.6%]  loss: 0.6251
  Epoch 5/10 [ 14.5%]  loss: 0.6350
  Epoch 5/10 [ 19.3%]  loss: 0.6037
  Epoch 5/10 [ 24.1%]  loss: 0.6109
  Epoch 5/10 [ 28.9%]  loss: 0.6439
  Epoch 5/10 [ 33.7%]  loss: 0.6441
  Epoch 5/10 [ 38.6%]  loss: 0.6791
  Epoch 5/10 [ 43.4%]  loss: 0.6832
  Epoch 5/10 [ 48.2%]  loss: 0.7370
  Epoch 5/10 [ 53.0%]  loss: 0.7263
  Epoch 5/10 [ 57.8%]  loss: 0.6777
  Epoch 5/10 [ 62.7%]  loss: 0.5996
  Epoch 5/10 [ 67.5%]  loss: 0.5825
  Epoch 5/10 [ 72.3%]  loss: 0.5101
  Epoch 5/10 [ 77.1%]  loss: 0.5376
  Epoch 5/10 [ 81.9%]  loss: 0.4592
  Epoch 5/10 [ 86.7%]  loss: 0.5036
  Epoch 5/10 [ 91.6%]  loss: 0.4925
  Epoch 5/10 [ 96.4%]  loss: 0.4717
  Epoch 5/10 [100.0%]  loss: 0.5081

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.57batch/s]

Epoch 5/10
Train Loss: 0.5991 | Train F1: 0.7186
Val Loss: 1.7207 | Val F1: 0.3872
Epoch Time: 82.62s

  Epoch 6/10 [  4.8%]  loss: 0.4749
  Epoch 6/10 [  9.6%]  loss: 0.4898
  Epoch 6/10 [ 14.5%]  loss: 0.4802
  Epoch 6/10 [ 19.3%]  loss: 0.4849
  Epoch 6/10 [ 24.1%]  loss: 0.4595
  Epoch 6/10 [ 28.9%]  loss: 0.4509
  Epoch 6/10 [ 33.7%]  loss: 0.4632
  Epoch 6/10 [ 38.6%]  loss: 0.4712
  Epoch 6/10 [ 43.4%]  loss: 0.4650
  Epoch 6/10 [ 48.2%]  loss: 0.4825
  Epoch 6/10 [ 53.0%]  loss: 0.4230
  Epoch 6/10 [ 57.8%]  loss: 0.4655
  Epoch 6/10 [ 62.7%]  loss: 0.4470
  Epoch 6/10 [ 67.5%]  loss: 0.4187
  Epoch 6/10 [ 72.3%]  loss: 0.4426
  Epoch 6/10 [ 77.1%]  loss: 0.4202
  Epoch 6/10 [ 81.9%]  loss: 0.4190
  Epoch 6/10 [ 86.7%]  loss: 0.3833
  Epoch 6/10 [ 91.6%]  loss: 0.4055
  Epoch 6/10 [ 96.4%]  loss: 0.4097
  Epoch 6/10 [100.0%]  loss: 0.4336

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.58batch/s]

Epoch 6/10
Train Loss: 0.4473 | Train F1: 0.7768
Val Loss: 1.5982 | Val F1: 0.4254
Epoch Time: 82.56s

  Epoch 7/10 [  4.8%]  loss: 0.3940
  Epoch 7/10 [  9.6%]  loss: 0.4314
  Epoch 7/10 [ 14.5%]  loss: 0.4682
  Epoch 7/10 [ 19.3%]  loss: 0.4128
  Epoch 7/10 [ 24.1%]  loss: 0.4452
  Epoch 7/10 [ 28.9%]  loss: 0.3844
  Epoch 7/10 [ 33.7%]  loss: 0.3971
  Epoch 7/10 [ 38.6%]  loss: 0.3909
  Epoch 7/10 [ 43.4%]  loss: 0.4074
  Epoch 7/10 [ 48.2%]  loss: 0.4218
  Epoch 7/10 [ 53.0%]  loss: 0.3986
  Epoch 7/10 [ 57.8%]  loss: 0.4198
  Epoch 7/10 [ 62.7%]  loss: 0.3903
  Epoch 7/10 [ 67.5%]  loss: 0.3901
  Epoch 7/10 [ 72.3%]  loss: 0.3978
  Epoch 7/10 [ 77.1%]  loss: 0.4198
  Epoch 7/10 [ 81.9%]  loss: 0.4006
  Epoch 7/10 [ 86.7%]  loss: 0.4249
  Epoch 7/10 [ 91.6%]  loss: 0.3834
  Epoch 7/10 [ 96.4%]  loss: 0.3679
  Epoch 7/10 [100.0%]  loss: 0.3742

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.60batch/s]

Epoch 7/10
Train Loss: 0.4061 | Train F1: 0.8043
Val Loss: 1.5824 | Val F1: 0.4080
Epoch Time: 82.48s

  Epoch 8/10 [  4.8%]  loss: 0.4054
  Epoch 8/10 [  9.6%]  loss: 0.3542
  Epoch 8/10 [ 14.5%]  loss: 0.3712
  Epoch 8/10 [ 19.3%]  loss: 0.4033
  Epoch 8/10 [ 24.1%]  loss: 0.4103
  Epoch 8/10 [ 28.9%]  loss: 0.3800
  Epoch 8/10 [ 33.7%]  loss: 0.3722
  Epoch 8/10 [ 38.6%]  loss: 0.3930
  Epoch 8/10 [ 43.4%]  loss: 0.3791
  Epoch 8/10 [ 48.2%]  loss: 0.3637
  Epoch 8/10 [ 53.0%]  loss: 0.3926
  Epoch 8/10 [ 57.8%]  loss: 0.3679
  Epoch 8/10 [ 62.7%]  loss: 0.3844
  Epoch 8/10 [ 67.5%]  loss: 0.3944
  Epoch 8/10 [ 72.3%]  loss: 0.4171
  Epoch 8/10 [ 77.1%]  loss: 0.4118
  Epoch 8/10 [ 81.9%]  loss: 0.4328
  Epoch 8/10 [ 86.7%]  loss: 0.4114
  Epoch 8/10 [ 91.6%]  loss: 0.3853
  Epoch 8/10 [ 96.4%]  loss: 0.3849
  Epoch 8/10 [100.0%]  loss: 0.3962

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.49batch/s]

Epoch 8/10
Train Loss: 0.3909 | Train F1: 0.8142
Val Loss: 1.6073 | Val F1: 0.3963
Epoch Time: 82.59s

  Epoch 9/10 [  4.8%]  loss: 0.3831
  Epoch 9/10 [  9.6%]  loss: 0.3679
  Epoch 9/10 [ 14.5%]  loss: 0.3775
  Epoch 9/10 [ 19.3%]  loss: 0.4017
  Epoch 9/10 [ 24.1%]  loss: 0.3902
  Epoch 9/10 [ 28.9%]  loss: 0.4144
  Epoch 9/10 [ 33.7%]  loss: 0.4018
  Epoch 9/10 [ 38.6%]  loss: 0.3776
  Epoch 9/10 [ 43.4%]  loss: 0.3844
  Epoch 9/10 [ 48.2%]  loss: 0.3537
  Epoch 9/10 [ 53.0%]  loss: 0.3563
  Epoch 9/10 [ 57.8%]  loss: 0.3728
  Epoch 9/10 [ 62.7%]  loss: 0.3634
  Epoch 9/10 [ 67.5%]  loss: 0.3895
  Epoch 9/10 [ 72.3%]  loss: 0.4233
  Epoch 9/10 [ 77.1%]  loss: 0.3760
  Epoch 9/10 [ 81.9%]  loss: 0.3967
  Epoch 9/10 [ 86.7%]  loss: 0.3967
  Epoch 9/10 [ 91.6%]  loss: 0.3929
  Epoch 9/10 [ 96.4%]  loss: 0.3567
  Epoch 9/10 [100.0%]  loss: 0.4053

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.59batch/s]

Epoch 9/10
Train Loss: 0.3846 | Train F1: 0.8239
Val Loss: 1.7216 | Val F1: 0.3906
Epoch Time: 82.57s

  Epoch 10/10 [  4.8%]  loss: 0.3982
  Epoch 10/10 [  9.6%]  loss: 0.3564
  Epoch 10/10 [ 14.5%]  loss: 0.3408
  Epoch 10/10 [ 19.3%]  loss: 0.3664
  Epoch 10/10 [ 24.1%]  loss: 0.3722
  Epoch 10/10 [ 28.9%]  loss: 0.3783
  Epoch 10/10 [ 33.7%]  loss: 0.3789
  Epoch 10/10 [ 38.6%]  loss: 0.3754
  Epoch 10/10 [ 43.4%]  loss: 0.3891
  Epoch 10/10 [ 48.2%]  loss: 0.3700
  Epoch 10/10 [ 53.0%]  loss: 0.3513
  Epoch 10/10 [ 57.8%]  loss: 0.3604
  Epoch 10/10 [ 62.7%]  loss: 0.3932
  Epoch 10/10 [ 67.5%]  loss: 0.3916
  Epoch 10/10 [ 72.3%]  loss: 0.3582
  Epoch 10/10 [ 77.1%]  loss: 0.4043
  Epoch 10/10 [ 81.9%]  loss: 0.3748
  Epoch 10/10 [ 86.7%]  loss: 0.3988
  Epoch 10/10 [ 91.6%]  loss: 0.3861
  Epoch 10/10 [ 96.4%]  loss: 0.4014
  Epoch 10/10 [100.0%]  loss: 0.3741

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.56batch/s]

Epoch 10/10
Train Loss: 0.3772 | Train F1: 0.8293
Val Loss: 1.6153 | Val F1: 0.4295
Epoch Time: 82.56s

Finalised: 3391/3776 conv1 channels zeroed (89.8%)
Saved → trained_models/pwkd_self_r50_r90/pwkd_self_r50_r90_full.pth

Warming up pwkd_self_r50_r90...
Running inference...
  ratio: 90% | F1: 0.0001 | params: 9,576,573 | latency: 1.13ms

PWKD Option 2 (ResNet50) — Results

               Size Reduction (%)  F1 Score  Size (MB)  Latency (ms)
Pruning Ratio
10%                          6.53    0.3489       90.4          1.13
25%                         16.55    0.2388       90.4          1.12
50%                         33.10    0.0102       90.4          1.12
70%                         46.27    0.0019       90.4          1.13
90%                         59.48    0.0001       90.4          1.13

In [6]:
# only run this cell if not running the previous cell
import torch.nn as nn
import copy
from modules.model_trainer import modelTrainer
from modules.evaluate_model import ModelEvaluator
from pwkd import PWKDLoss, make_aux_fn, finalise_student

RESNET50_CHANNELS = {'layer2': 512, 'layer3': 1024, 'layer4': 2048}

PRUNING_RATIOS = [0.10, 0.25, 0.50, 0.70, 0.90]
NUM_EPOCHS     = 10
LAM            = 0.2
KD_TEMP        = 4.0
SPARSE_WEIGHT  = 1e-4

evaluator = ModelEvaluator(
    data_loader=data_prep.val_loader,
    class_names=data_prep.class_names,
    device=str(device),
)

teacher = copy.deepcopy(resnet50_pretrained).eval()
for p in teacher.parameters():
    p.requires_grad = False

pwkd_metrics = []

In [7]:
# ── Extra ratios to better capture the Pareto curve descent ──────────────────
# Run this cell independently — existing trained models are not affected.

EXTRA_RATIOS = [0.2, 0.3, 0.35, 0.40, 0.45]   # between the good and collapsed points

for ratio in EXTRA_RATIOS:
    label = f'pwkd_self_r50_r{int(ratio * 100)}'
    print(f'\n{"="*60}')
    print(f'  PWKD Option 2 (ResNet50) — pruning ratio {ratio:.0%}')
    print(f'{"="*60}')

    student = copy.deepcopy(resnet50_pretrained).to(device)
    for p in student.parameters():
        p.requires_grad = True

    pwkd_loss = PWKDLoss(
        student          = student,
        teacher          = teacher,
        pruning_ratio    = ratio,
        teacher_channels = RESNET50_CHANNELS,
        student_channels = RESNET50_CHANNELS,
        class_weights    = data_prep.class_weights.to(device)
                           if data_prep.class_weights is not None else None,
        lam              = LAM,
        kd_temp          = KD_TEMP,
        sparse_weight    = SPARSE_WEIGHT,
    ).to(device)

    trainer = modelTrainer(
        model      = student,
        data_prep  = data_prep,
        device     = device,
        learn_rate = 5e-4,
        num_epochs = NUM_EPOCHS,
        model_name = label,
    )
    trainer.loss_fn   = pwkd_loss
    trainer.optimizer = torch.optim.AdamW(
        list(student.parameters()) + list(pwkd_loss.parameters()),
        lr=5e-4, weight_decay=1e-2,
    )
    trainer.create_classnum_to_label_map(data_prep.class_names)
    trainer.train_all(save_as_object=True, aux_forward_fn=make_aux_fn(teacher), pwkd=True)

    student = finalise_student(student, pwkd_loss, data_prep.train_loader, device)

    save_dir = os.path.join('trained_models', label)
    os.makedirs(save_dir, exist_ok=True)
    torch.save({'model': student, 'epoch': NUM_EPOCHS},
               os.path.join(save_dir, f'{label}_full.pth'))
    print(f'Saved → {save_dir}/{label}_full.pth')

    student.eval()
    metrics = evaluator.evaluate_single(student, label)

    pwkd_metrics.append({
        'Pruning Ratio':      f'{int(ratio*100)}%',
        'Size Reduction (%)': round((BASELINE_PARAMS - metrics['total_parameters'])
                                    / BASELINE_PARAMS * 100, 2),
        'F1 Score':           round(metrics['f1_macro'],     4),
        'Size (MB)':          round(metrics['model_size_mb'], 1),
        'Latency (ms)':       round(metrics['avg_latency_ms'], 2),
    })
    print(f'  ratio: {ratio:.0%} | F1: {metrics["f1_macro"]:.4f} | '
          f'params: {metrics["total_parameters"]:,}')

summary_df = pd.DataFrame(pwkd_metrics).set_index('Pruning Ratio')
display(summary_df)

============================================================
  PWKD Option 2 (ResNet50) — pruning ratio 20%
============================================================
  Epoch 1/10 [  4.8%]  loss: 3.6317
  Epoch 1/10 [  9.6%]  loss: 3.5960
  Epoch 1/10 [ 14.5%]  loss: 3.0203
  Epoch 1/10 [ 19.3%]  loss: 2.6702
  Epoch 1/10 [ 24.1%]  loss: 2.6090
  Epoch 1/10 [ 28.9%]  loss: 2.5252
  Epoch 1/10 [ 33.7%]  loss: 2.2256
  Epoch 1/10 [ 38.6%]  loss: 2.1543
  Epoch 1/10 [ 43.4%]  loss: 2.3726
  Epoch 1/10 [ 48.2%]  loss: 2.1686
  Epoch 1/10 [ 53.0%]  loss: 1.9540
  Epoch 1/10 [ 57.8%]  loss: 1.8281
  Epoch 1/10 [ 62.7%]  loss: 1.7994
  Epoch 1/10 [ 67.5%]  loss: 1.8400
  Epoch 1/10 [ 72.3%]  loss: 1.6397
  Epoch 1/10 [ 77.1%]  loss: 1.8097
  Epoch 1/10 [ 81.9%]  loss: 1.6320
  Epoch 1/10 [ 86.7%]  loss: 1.7169
  Epoch 1/10 [ 91.6%]  loss: 1.7350
  Epoch 1/10 [ 96.4%]  loss: 1.5231
  Epoch 1/10 [100.0%]  loss: 1.6263

Validating: 100%|██████████| 50/50 [00:03<00:00, 14.95batch/s]

Epoch 1/10
Train Loss: 2.2010 | Train F1: 0.2951
Val Loss: 2.7077 | Val F1: 0.1768
Epoch Time: 96.60s

  Epoch 2/10 [  4.8%]  loss: 1.7177
  Epoch 2/10 [  9.6%]  loss: 1.5105
  Epoch 2/10 [ 14.5%]  loss: 1.4171
  Epoch 2/10 [ 19.3%]  loss: 1.4433
  Epoch 2/10 [ 24.1%]  loss: 1.2419
  Epoch 2/10 [ 28.9%]  loss: 1.2691
  Epoch 2/10 [ 33.7%]  loss: 1.1385
  Epoch 2/10 [ 38.6%]  loss: 1.2358
  Epoch 2/10 [ 43.4%]  loss: 1.2034
  Epoch 2/10 [ 48.2%]  loss: 1.2803
  Epoch 2/10 [ 53.0%]  loss: 1.2598
  Epoch 2/10 [ 57.8%]  loss: 1.1804
  Epoch 2/10 [ 62.7%]  loss: 1.1559
  Epoch 2/10 [ 67.5%]  loss: 1.1494
  Epoch 2/10 [ 72.3%]  loss: 1.2451
  Epoch 2/10 [ 77.1%]  loss: 1.0964
  Epoch 2/10 [ 81.9%]  loss: 1.1944
  Epoch 2/10 [ 86.7%]  loss: 1.1717
  Epoch 2/10 [ 91.6%]  loss: 1.1339
  Epoch 2/10 [ 96.4%]  loss: 1.0322
  Epoch 2/10 [100.0%]  loss: 0.9967

Validating: 100%|██████████| 50/50 [00:04<00:00, 11.19batch/s]

Epoch 2/10
Train Loss: 1.2446 | Train F1: 0.4424
Val Loss: 3.7714 | Val F1: 0.1321
Epoch Time: 100.77s

  Epoch 3/10 [  4.8%]  loss: 1.2294
  Epoch 3/10 [  9.6%]  loss: 1.0468
  Epoch 3/10 [ 14.5%]  loss: 0.9534
  Epoch 3/10 [ 19.3%]  loss: 0.9415
  Epoch 3/10 [ 24.1%]  loss: 0.9267
  Epoch 3/10 [ 28.9%]  loss: 0.9517
  Epoch 3/10 [ 33.7%]  loss: 1.0725
  Epoch 3/10 [ 38.6%]  loss: 1.0125
  Epoch 3/10 [ 43.4%]  loss: 0.9589
  Epoch 3/10 [ 48.2%]  loss: 0.9992
  Epoch 3/10 [ 53.0%]  loss: 1.0206
  Epoch 3/10 [ 57.8%]  loss: 1.0965
  Epoch 3/10 [ 62.7%]  loss: 0.9417
  Epoch 3/10 [ 67.5%]  loss: 0.9533
  Epoch 3/10 [ 72.3%]  loss: 0.9317
  Epoch 3/10 [ 77.1%]  loss: 0.9012
  Epoch 3/10 [ 81.9%]  loss: 0.9190
  Epoch 3/10 [ 86.7%]  loss: 0.9101
  Epoch 3/10 [ 91.6%]  loss: 0.9343
  Epoch 3/10 [ 96.4%]  loss: 0.8536
  Epoch 3/10 [100.0%]  loss: 0.9416

Validating: 100%|██████████| 50/50 [00:03<00:00, 12.60batch/s]

Epoch 3/10
Train Loss: 0.9764 | Train F1: 0.5279
Val Loss: 2.2169 | Val F1: 0.2555
Epoch Time: 122.84s

  Epoch 4/10 [  4.8%]  loss: 0.8238
  Epoch 4/10 [  9.6%]  loss: 0.8751
  Epoch 4/10 [ 14.5%]  loss: 0.8751
  Epoch 4/10 [ 19.3%]  loss: 0.8182
  Epoch 4/10 [ 24.1%]  loss: 0.8428
  Epoch 4/10 [ 28.9%]  loss: 0.8856
  Epoch 4/10 [ 33.7%]  loss: 0.8811
  Epoch 4/10 [ 38.6%]  loss: 0.9361
  Epoch 4/10 [ 43.4%]  loss: 0.8057
  Epoch 4/10 [ 48.2%]  loss: 0.8506
  Epoch 4/10 [ 53.0%]  loss: 0.7683
  Epoch 4/10 [ 57.8%]  loss: 0.7607
  Epoch 4/10 [ 62.7%]  loss: 0.8635
  Epoch 4/10 [ 67.5%]  loss: 0.7800
  Epoch 4/10 [ 72.3%]  loss: 0.8847
  Epoch 4/10 [ 77.1%]  loss: 0.8497
  Epoch 4/10 [ 81.9%]  loss: 0.8835
  Epoch 4/10 [ 86.7%]  loss: 0.8473
  Epoch 4/10 [ 91.6%]  loss: 0.7551
  Epoch 4/10 [ 96.4%]  loss: 0.8212
  Epoch 4/10 [100.0%]  loss: 0.7565

Validating: 100%|██████████| 50/50 [00:03<00:00, 14.19batch/s]

Epoch 4/10
Train Loss: 0.8374 | Train F1: 0.5771
Val Loss: 2.2641 | Val F1: 0.2798
Epoch Time: 105.12s

  Epoch 5/10 [  4.8%]  loss: 0.7397
  Epoch 5/10 [  9.6%]  loss: 0.8587
  Epoch 5/10 [ 14.5%]  loss: 0.7853
  Epoch 5/10 [ 19.3%]  loss: 0.8326
  Epoch 5/10 [ 24.1%]  loss: 0.7626
  Epoch 5/10 [ 28.9%]  loss: 0.8212
  Epoch 5/10 [ 33.7%]  loss: 0.7199
  Epoch 5/10 [ 38.6%]  loss: 0.7767
  Epoch 5/10 [ 43.4%]  loss: 0.7050
  Epoch 5/10 [ 48.2%]  loss: 0.6907
  Epoch 5/10 [ 53.0%]  loss: 0.7263
  Epoch 5/10 [ 57.8%]  loss: 0.7000
  Epoch 5/10 [ 62.7%]  loss: 0.7499
  Epoch 5/10 [ 67.5%]  loss: 0.7017
  Epoch 5/10 [ 72.3%]  loss: 0.6944
  Epoch 5/10 [ 77.1%]  loss: 0.6681
  Epoch 5/10 [ 81.9%]  loss: 0.6853
  Epoch 5/10 [ 86.7%]  loss: 0.6387
  Epoch 5/10 [ 91.6%]  loss: 0.6290
  Epoch 5/10 [ 96.4%]  loss: 0.6783
  Epoch 5/10 [100.0%]  loss: 0.6596

Validating: 100%|██████████| 50/50 [00:04<00:00, 11.07batch/s]

Epoch 5/10
Train Loss: 0.7257 | Train F1: 0.6131
Val Loss: 2.2052 | Val F1: 0.2705
Epoch Time: 104.89s

  Epoch 6/10 [  4.8%]  loss: 0.7038
  Epoch 6/10 [  9.6%]  loss: 0.7249
  Epoch 6/10 [ 14.5%]  loss: 0.7207
  Epoch 6/10 [ 19.3%]  loss: 0.7065
  Epoch 6/10 [ 24.1%]  loss: 0.7170
  Epoch 6/10 [ 28.9%]  loss: 0.6185
  Epoch 6/10 [ 33.7%]  loss: 0.6740
  Epoch 6/10 [ 38.6%]  loss: 0.5783
  Epoch 6/10 [ 43.4%]  loss: 0.5811
  Epoch 6/10 [ 48.2%]  loss: 0.6094
  Epoch 6/10 [ 53.0%]  loss: 0.6655
  Epoch 6/10 [ 57.8%]  loss: 0.6316
  Epoch 6/10 [ 62.7%]  loss: 0.6099
  Epoch 6/10 [ 67.5%]  loss: 0.5952
  Epoch 6/10 [ 72.3%]  loss: 0.6156
  Epoch 6/10 [ 77.1%]  loss: 0.5749
  Epoch 6/10 [ 81.9%]  loss: 0.5816
  Epoch 6/10 [ 86.7%]  loss: 0.6071
  Epoch 6/10 [ 91.6%]  loss: 0.5778
  Epoch 6/10 [ 96.4%]  loss: 0.6356
  Epoch 6/10 [100.0%]  loss: 0.6322

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.63batch/s]

Epoch 6/10
Train Loss: 0.6363 | Train F1: 0.6485
Val Loss: 2.1650 | Val F1: 0.3205
Epoch Time: 103.99s

  Epoch 7/10 [  4.8%]  loss: 0.5851
  Epoch 7/10 [  9.6%]  loss: 0.6436
  Epoch 7/10 [ 14.5%]  loss: 0.7048
  Epoch 7/10 [ 19.3%]  loss: 0.7087
  Epoch 7/10 [ 24.1%]  loss: 0.6846
  Epoch 7/10 [ 28.9%]  loss: 0.6417
  Epoch 7/10 [ 33.7%]  loss: 0.6691
  Epoch 7/10 [ 38.6%]  loss: 0.6301
  Epoch 7/10 [ 43.4%]  loss: 0.6367
  Epoch 7/10 [ 48.2%]  loss: 0.6918
  Epoch 7/10 [ 53.0%]  loss: 0.8202
  Epoch 7/10 [ 57.8%]  loss: 0.7266
  Epoch 7/10 [ 62.7%]  loss: 0.7795
  Epoch 7/10 [ 67.5%]  loss: 0.7387
  Epoch 7/10 [ 72.3%]  loss: 0.6374
  Epoch 7/10 [ 77.1%]  loss: 0.6457
  Epoch 7/10 [ 81.9%]  loss: 0.6193
  Epoch 7/10 [ 86.7%]  loss: 0.6481
  Epoch 7/10 [ 91.6%]  loss: 0.6221
  Epoch 7/10 [ 96.4%]  loss: 0.6072
  Epoch 7/10 [100.0%]  loss: 0.6750

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.51batch/s]

Epoch 7/10
Train Loss: 0.6722 | Train F1: 0.6422
Val Loss: 2.2037 | Val F1: 0.2978
Epoch Time: 82.22s

  Epoch 8/10 [  4.8%]  loss: 0.6798
  Epoch 8/10 [  9.6%]  loss: 0.6654
  Epoch 8/10 [ 14.5%]  loss: 0.6691
  Epoch 8/10 [ 19.3%]  loss: 0.6043
  Epoch 8/10 [ 24.1%]  loss: 0.6006
  Epoch 8/10 [ 28.9%]  loss: 0.5804
  Epoch 8/10 [ 33.7%]  loss: 0.5829
  Epoch 8/10 [ 38.6%]  loss: 0.5699
  Epoch 8/10 [ 43.4%]  loss: 0.6072
  Epoch 8/10 [ 48.2%]  loss: 0.6147
  Epoch 8/10 [ 53.0%]  loss: 0.6410
  Epoch 8/10 [ 57.8%]  loss: 0.6261
  Epoch 8/10 [ 62.7%]  loss: 0.6003
  Epoch 8/10 [ 67.5%]  loss: 0.5727
  Epoch 8/10 [ 72.3%]  loss: 0.6274
  Epoch 8/10 [ 77.1%]  loss: 0.5163
  Epoch 8/10 [ 81.9%]  loss: 0.4965
  Epoch 8/10 [ 86.7%]  loss: 0.5864
  Epoch 8/10 [ 91.6%]  loss: 0.5894
  Epoch 8/10 [ 96.4%]  loss: 0.5738
  Epoch 8/10 [100.0%]  loss: 0.5991

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.58batch/s]

Epoch 8/10
Train Loss: 0.6002 | Train F1: 0.6687
Val Loss: 2.0926 | Val F1: 0.2954
Epoch Time: 82.30s

  Epoch 9/10 [  4.8%]  loss: 0.5454
  Epoch 9/10 [  9.6%]  loss: 0.5166
  Epoch 9/10 [ 14.5%]  loss: 0.5876
  Epoch 9/10 [ 19.3%]  loss: 0.5294
  Epoch 9/10 [ 24.1%]  loss: 0.5454
  Epoch 9/10 [ 28.9%]  loss: 0.5132
  Epoch 9/10 [ 33.7%]  loss: 0.4881
  Epoch 9/10 [ 38.6%]  loss: 0.5040
  Epoch 9/10 [ 43.4%]  loss: 0.5057
  Epoch 9/10 [ 48.2%]  loss: 0.4299
  Epoch 9/10 [ 53.0%]  loss: 0.4834
  Epoch 9/10 [ 57.8%]  loss: 0.4824
  Epoch 9/10 [ 62.7%]  loss: 0.4671
  Epoch 9/10 [ 67.5%]  loss: 0.4633
  Epoch 9/10 [ 72.3%]  loss: 0.4737
  Epoch 9/10 [ 77.1%]  loss: 0.4394
  Epoch 9/10 [ 81.9%]  loss: 0.4626
  Epoch 9/10 [ 86.7%]  loss: 0.4806
  Epoch 9/10 [ 91.6%]  loss: 0.4825
  Epoch 9/10 [ 96.4%]  loss: 0.4583
  Epoch 9/10 [100.0%]  loss: 0.4815

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.58batch/s]

Epoch 9/10
Train Loss: 0.4925 | Train F1: 0.7137
Val Loss: 2.1477 | Val F1: 0.3045
Epoch Time: 82.27s

  Epoch 10/10 [  4.8%]  loss: 0.4952
  Epoch 10/10 [  9.6%]  loss: 0.4965
  Epoch 10/10 [ 14.5%]  loss: 0.4740
  Epoch 10/10 [ 19.3%]  loss: 0.4772
  Epoch 10/10 [ 24.1%]  loss: 0.4776
  Epoch 10/10 [ 28.9%]  loss: 0.4657
  Epoch 10/10 [ 33.7%]  loss: 0.4952
  Epoch 10/10 [ 38.6%]  loss: 0.4995
  Epoch 10/10 [ 43.4%]  loss: 0.5030
  Epoch 10/10 [ 48.2%]  loss: 0.4887
  Epoch 10/10 [ 53.0%]  loss: 0.5624
  Epoch 10/10 [ 57.8%]  loss: 0.5694
  Epoch 10/10 [ 62.7%]  loss: 0.5847
  Epoch 10/10 [ 67.5%]  loss: 0.5605
  Epoch 10/10 [ 72.3%]  loss: 0.5664
  Epoch 10/10 [ 77.1%]  loss: 0.5966
  Epoch 10/10 [ 81.9%]  loss: 0.5698
  Epoch 10/10 [ 86.7%]  loss: 0.5600
  Epoch 10/10 [ 91.6%]  loss: 0.5783
  Epoch 10/10 [ 96.4%]  loss: 0.5600
  Epoch 10/10 [100.0%]  loss: 0.5587

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.51batch/s]

Epoch 10/10
Train Loss: 0.5301 | Train F1: 0.7100
Val Loss: 2.1625 | Val F1: 0.2919
Epoch Time: 82.36s

Finalised: 748/3776 conv1 channels zeroed (19.8%)
Saved → trained_models/pwkd_self_r50_r20/pwkd_self_r50_r20_full.pth

Warming up pwkd_self_r50_r20...
Running inference...
  ratio: 20% | F1: 0.2588 | params: 20,520,829

============================================================
  PWKD Option 2 (ResNet50) — pruning ratio 30%
============================================================
  Epoch 1/10 [  4.8%]  loss: 3.2467
  Epoch 1/10 [  9.6%]  loss: 3.6785
  Epoch 1/10 [ 14.5%]  loss: 3.2975
  Epoch 1/10 [ 19.3%]  loss: 2.7196
  Epoch 1/10 [ 24.1%]  loss: 2.9262
  Epoch 1/10 [ 28.9%]  loss: 2.3418
  Epoch 1/10 [ 33.7%]  loss: 2.1855
  Epoch 1/10 [ 38.6%]  loss: 2.4463
  Epoch 1/10 [ 43.4%]  loss: 2.0624
  Epoch 1/10 [ 48.2%]  loss: 2.0840
  Epoch 1/10 [ 53.0%]  loss: 1.9356
  Epoch 1/10 [ 57.8%]  loss: 1.9780
  Epoch 1/10 [ 62.7%]  loss: 1.9608
  Epoch 1/10 [ 67.5%]  loss: 1.9608
  Epoch 1/10 [ 72.3%]  loss: 1.7832
  Epoch 1/10 [ 77.1%]  loss: 1.9113
  Epoch 1/10 [ 81.9%]  loss: 1.8202
  Epoch 1/10 [ 86.7%]  loss: 1.7378
  Epoch 1/10 [ 91.6%]  loss: 1.6829
  Epoch 1/10 [ 96.4%]  loss: 1.7340
  Epoch 1/10 [100.0%]  loss: 1.8444

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.57batch/s]

Epoch 1/10
Train Loss: 2.2591 | Train F1: 0.2776
Val Loss: 2.8524 | Val F1: 0.1499
Epoch Time: 82.29s

  Epoch 2/10 [  4.8%]  loss: 1.7372
  Epoch 2/10 [  9.6%]  loss: 1.6022
  Epoch 2/10 [ 14.5%]  loss: 1.5180
  Epoch 2/10 [ 19.3%]  loss: 1.4731
  Epoch 2/10 [ 24.1%]  loss: 1.3864
  Epoch 2/10 [ 28.9%]  loss: 1.4720
  Epoch 2/10 [ 33.7%]  loss: 1.4225
  Epoch 2/10 [ 38.6%]  loss: 1.3627
  Epoch 2/10 [ 43.4%]  loss: 1.3968
  Epoch 2/10 [ 48.2%]  loss: 1.3683
  Epoch 2/10 [ 53.0%]  loss: 1.2071
  Epoch 2/10 [ 57.8%]  loss: 1.2734
  Epoch 2/10 [ 62.7%]  loss: 1.1969
  Epoch 2/10 [ 67.5%]  loss: 1.5511
  Epoch 2/10 [ 72.3%]  loss: 1.2533
  Epoch 2/10 [ 77.1%]  loss: 1.2925
  Epoch 2/10 [ 81.9%]  loss: 1.2032
  Epoch 2/10 [ 86.7%]  loss: 1.2592
  Epoch 2/10 [ 91.6%]  loss: 1.2700
  Epoch 2/10 [ 96.4%]  loss: 1.1737
  Epoch 2/10 [100.0%]  loss: 1.1842

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.62batch/s]

Epoch 2/10
Train Loss: 1.3642 | Train F1: 0.4183
Val Loss: 2.6874 | Val F1: 0.2032
Epoch Time: 82.26s

  Epoch 3/10 [  4.8%]  loss: 1.2754
  Epoch 3/10 [  9.6%]  loss: 1.1803
  Epoch 3/10 [ 14.5%]  loss: 1.0275
  Epoch 3/10 [ 19.3%]  loss: 1.0760
  Epoch 3/10 [ 24.1%]  loss: 1.0231
  Epoch 3/10 [ 28.9%]  loss: 1.0914
  Epoch 3/10 [ 33.7%]  loss: 0.9960
  Epoch 3/10 [ 38.6%]  loss: 1.1240
  Epoch 3/10 [ 43.4%]  loss: 1.0168
  Epoch 3/10 [ 48.2%]  loss: 1.0889
  Epoch 3/10 [ 53.0%]  loss: 0.9302
  Epoch 3/10 [ 57.8%]  loss: 0.9720
  Epoch 3/10 [ 62.7%]  loss: 0.8867
  Epoch 3/10 [ 67.5%]  loss: 0.8824
  Epoch 3/10 [ 72.3%]  loss: 0.8837
  Epoch 3/10 [ 77.1%]  loss: 0.9229
  Epoch 3/10 [ 81.9%]  loss: 0.9250
  Epoch 3/10 [ 86.7%]  loss: 0.9232
  Epoch 3/10 [ 91.6%]  loss: 0.9486
  Epoch 3/10 [ 96.4%]  loss: 0.9055
  Epoch 3/10 [100.0%]  loss: 0.9423

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.56batch/s]

Epoch 3/10
Train Loss: 1.0018 | Train F1: 0.5084
Val Loss: 2.3873 | Val F1: 0.2335
Epoch Time: 82.26s

  Epoch 4/10 [  4.8%]  loss: 0.9120
  Epoch 4/10 [  9.6%]  loss: 0.8756
  Epoch 4/10 [ 14.5%]  loss: 0.8448
  Epoch 4/10 [ 19.3%]  loss: 0.8973
  Epoch 4/10 [ 24.1%]  loss: 0.9022
  Epoch 4/10 [ 28.9%]  loss: 1.0703
  Epoch 4/10 [ 33.7%]  loss: 0.8962
  Epoch 4/10 [ 38.6%]  loss: 1.0510
  Epoch 4/10 [ 43.4%]  loss: 0.8781
  Epoch 4/10 [ 48.2%]  loss: 0.8237
  Epoch 4/10 [ 53.0%]  loss: 0.8530
  Epoch 4/10 [ 57.8%]  loss: 0.9112
  Epoch 4/10 [ 62.7%]  loss: 0.8573
  Epoch 4/10 [ 67.5%]  loss: 0.8972
  Epoch 4/10 [ 72.3%]  loss: 0.7375
  Epoch 4/10 [ 77.1%]  loss: 0.7933
  Epoch 4/10 [ 81.9%]  loss: 0.7836
  Epoch 4/10 [ 86.7%]  loss: 0.7366
  Epoch 4/10 [ 91.6%]  loss: 0.8734
  Epoch 4/10 [ 96.4%]  loss: 0.8315
  Epoch 4/10 [100.0%]  loss: 0.8484

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.54batch/s]

Epoch 4/10
Train Loss: 0.8705 | Train F1: 0.5639
Val Loss: 2.8805 | Val F1: 0.2196
Epoch Time: 82.28s

  Epoch 5/10 [  4.8%]  loss: 0.7855
  Epoch 5/10 [  9.6%]  loss: 0.7781
  Epoch 5/10 [ 14.5%]  loss: 0.8603
  Epoch 5/10 [ 19.3%]  loss: 0.8848
  Epoch 5/10 [ 24.1%]  loss: 0.7958
  Epoch 5/10 [ 28.9%]  loss: 0.7941
  Epoch 5/10 [ 33.7%]  loss: 0.8423
  Epoch 5/10 [ 38.6%]  loss: 0.7463
  Epoch 5/10 [ 43.4%]  loss: 0.6982
  Epoch 5/10 [ 48.2%]  loss: 0.7406
  Epoch 5/10 [ 53.0%]  loss: 0.7169
  Epoch 5/10 [ 57.8%]  loss: 0.7482
  Epoch 5/10 [ 62.7%]  loss: 0.7712
  Epoch 5/10 [ 67.5%]  loss: 0.7226
  Epoch 5/10 [ 72.3%]  loss: 0.7155
  Epoch 5/10 [ 77.1%]  loss: 0.7131
  Epoch 5/10 [ 81.9%]  loss: 0.7465
  Epoch 5/10 [ 86.7%]  loss: 0.7115
  Epoch 5/10 [ 91.6%]  loss: 0.7881
  Epoch 5/10 [ 96.4%]  loss: 0.7631
  Epoch 5/10 [100.0%]  loss: 0.8037

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.58batch/s]

Epoch 5/10
Train Loss: 0.7675 | Train F1: 0.5973
Val Loss: 2.5126 | Val F1: 0.2590
Epoch Time: 82.33s

  Epoch 6/10 [  4.8%]  loss: 0.7434
  Epoch 6/10 [  9.6%]  loss: 0.7645
  Epoch 6/10 [ 14.5%]  loss: 0.8018
  Epoch 6/10 [ 19.3%]  loss: 0.7763
  Epoch 6/10 [ 24.1%]  loss: 0.8015
  Epoch 6/10 [ 28.9%]  loss: 0.7816
  Epoch 6/10 [ 33.7%]  loss: 0.8189
  Epoch 6/10 [ 38.6%]  loss: 0.7872
  Epoch 6/10 [ 43.4%]  loss: 0.8456
  Epoch 6/10 [ 48.2%]  loss: 0.7616
  Epoch 6/10 [ 53.0%]  loss: 0.7126
  Epoch 6/10 [ 57.8%]  loss: 0.7329
  Epoch 6/10 [ 62.7%]  loss: 0.6976
  Epoch 6/10 [ 67.5%]  loss: 0.6581
  Epoch 6/10 [ 72.3%]  loss: 0.6937
  Epoch 6/10 [ 77.1%]  loss: 0.6600
  Epoch 6/10 [ 81.9%]  loss: 0.6529
  Epoch 6/10 [ 86.7%]  loss: 0.7024
  Epoch 6/10 [ 91.6%]  loss: 0.6578
  Epoch 6/10 [ 96.4%]  loss: 0.6973
  Epoch 6/10 [100.0%]  loss: 0.6139

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.58batch/s]

Epoch 6/10
Train Loss: 0.7329 | Train F1: 0.6195
Val Loss: 2.0237 | Val F1: 0.3000
Epoch Time: 82.35s

  Epoch 7/10 [  4.8%]  loss: 0.6847
  Epoch 7/10 [  9.6%]  loss: 0.6340
  Epoch 7/10 [ 14.5%]  loss: 0.6878
  Epoch 7/10 [ 19.3%]  loss: 0.7533
  Epoch 7/10 [ 24.1%]  loss: 0.7670
  Epoch 7/10 [ 28.9%]  loss: 0.7079
  Epoch 7/10 [ 33.7%]  loss: 0.7171
  Epoch 7/10 [ 38.6%]  loss: 0.7484
  Epoch 7/10 [ 43.4%]  loss: 0.8323
  Epoch 7/10 [ 48.2%]  loss: 0.8467
  Epoch 7/10 [ 53.0%]  loss: 0.8061
  Epoch 7/10 [ 57.8%]  loss: 0.8953
  Epoch 7/10 [ 62.7%]  loss: 0.9220
  Epoch 7/10 [ 67.5%]  loss: 0.7843
  Epoch 7/10 [ 72.3%]  loss: 0.7448
  Epoch 7/10 [ 77.1%]  loss: 0.7429
  Epoch 7/10 [ 81.9%]  loss: 0.7581
  Epoch 7/10 [ 86.7%]  loss: 0.6846
  Epoch 7/10 [ 91.6%]  loss: 0.6996
  Epoch 7/10 [ 96.4%]  loss: 0.6913
  Epoch 7/10 [100.0%]  loss: 0.8139

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.56batch/s]

Epoch 7/10
Train Loss: 0.7575 | Train F1: 0.6201
Val Loss: 2.3019 | Val F1: 0.2797
Epoch Time: 82.27s

  Epoch 8/10 [  4.8%]  loss: 0.7537
  Epoch 8/10 [  9.6%]  loss: 0.8824
  Epoch 8/10 [ 14.5%]  loss: 0.7324
  Epoch 8/10 [ 19.3%]  loss: 0.7472
  Epoch 8/10 [ 24.1%]  loss: 0.7673
  Epoch 8/10 [ 28.9%]  loss: 0.7644
  Epoch 8/10 [ 33.7%]  loss: 0.6940
  Epoch 8/10 [ 38.6%]  loss: 0.6511
  Epoch 8/10 [ 43.4%]  loss: 0.6916
  Epoch 8/10 [ 48.2%]  loss: 0.5919
  Epoch 8/10 [ 53.0%]  loss: 0.6219
  Epoch 8/10 [ 57.8%]  loss: 0.6574
  Epoch 8/10 [ 62.7%]  loss: 0.6355
  Epoch 8/10 [ 67.5%]  loss: 0.6179
  Epoch 8/10 [ 72.3%]  loss: 0.5984
  Epoch 8/10 [ 77.1%]  loss: 0.5521
  Epoch 8/10 [ 81.9%]  loss: 0.5614
  Epoch 8/10 [ 86.7%]  loss: 0.6199
  Epoch 8/10 [ 91.6%]  loss: 0.5873
  Epoch 8/10 [ 96.4%]  loss: 0.5931
  Epoch 8/10 [100.0%]  loss: 0.5724

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.62batch/s]

Epoch 8/10
Train Loss: 0.6627 | Train F1: 0.6488
Val Loss: 2.1096 | Val F1: 0.3062
Epoch Time: 82.28s

  Epoch 9/10 [  4.8%]  loss: 0.6255
  Epoch 9/10 [  9.6%]  loss: 0.6133
  Epoch 9/10 [ 14.5%]  loss: 0.5850
  Epoch 9/10 [ 19.3%]  loss: 0.5800
  Epoch 9/10 [ 24.1%]  loss: 0.5806
  Epoch 9/10 [ 28.9%]  loss: 0.5116
  Epoch 9/10 [ 33.7%]  loss: 0.5381
  Epoch 9/10 [ 38.6%]  loss: 0.5566
  Epoch 9/10 [ 43.4%]  loss: 0.5580
  Epoch 9/10 [ 48.2%]  loss: 0.4893
  Epoch 9/10 [ 53.0%]  loss: 0.5497
  Epoch 9/10 [ 57.8%]  loss: 0.5222
  Epoch 9/10 [ 62.7%]  loss: 0.5740
  Epoch 9/10 [ 67.5%]  loss: 0.5424
  Epoch 9/10 [ 72.3%]  loss: 0.5399
  Epoch 9/10 [ 77.1%]  loss: 0.5561
  Epoch 9/10 [ 81.9%]  loss: 0.6185
  Epoch 9/10 [ 86.7%]  loss: 0.5544
  Epoch 9/10 [ 91.6%]  loss: 0.4999
  Epoch 9/10 [ 96.4%]  loss: 0.5102
  Epoch 9/10 [100.0%]  loss: 0.4930

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.60batch/s]

Epoch 9/10
Train Loss: 0.5530 | Train F1: 0.7106
Val Loss: 2.0835 | Val F1: 0.3178
Epoch Time: 82.32s

  Epoch 10/10 [  4.8%]  loss: 0.5235
  Epoch 10/10 [  9.6%]  loss: 0.5283
  Epoch 10/10 [ 14.5%]  loss: 0.5405
  Epoch 10/10 [ 19.3%]  loss: 0.5005
  Epoch 10/10 [ 24.1%]  loss: 0.5420
  Epoch 10/10 [ 28.9%]  loss: 0.5156
  Epoch 10/10 [ 33.7%]  loss: 0.5189
  Epoch 10/10 [ 38.6%]  loss: 0.5698
  Epoch 10/10 [ 43.4%]  loss: 0.5536
  Epoch 10/10 [ 48.2%]  loss: 0.5246
  Epoch 10/10 [ 53.0%]  loss: 0.5944
  Epoch 10/10 [ 57.8%]  loss: 0.5400
  Epoch 10/10 [ 62.7%]  loss: 0.5410
  Epoch 10/10 [ 67.5%]  loss: 0.5271
  Epoch 10/10 [ 72.3%]  loss: 0.5388
  Epoch 10/10 [ 77.1%]  loss: 0.5213
  Epoch 10/10 [ 81.9%]  loss: 0.5419
  Epoch 10/10 [ 86.7%]  loss: 0.5209
  Epoch 10/10 [ 91.6%]  loss: 0.5121
  Epoch 10/10 [ 96.4%]  loss: 0.5086
  Epoch 10/10 [100.0%]  loss: 0.5023

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.59batch/s]

Epoch 10/10
Train Loss: 0.5321 | Train F1: 0.7187
Val Loss: 2.0336 | Val F1: 0.3326
Epoch Time: 82.32s

Finalised: 1124/3776 conv1 channels zeroed (29.8%)
Saved → trained_models/pwkd_self_r50_r30/pwkd_self_r50_r30_full.pth

Warming up pwkd_self_r50_r30...
Running inference...
  ratio: 30% | F1: 0.1981 | params: 18,968,957

============================================================
  PWKD Option 2 (ResNet50) — pruning ratio 35%
============================================================
  Epoch 1/10 [  4.8%]  loss: 3.4508
  Epoch 1/10 [  9.6%]  loss: 4.0011
  Epoch 1/10 [ 14.5%]  loss: 3.4470
  Epoch 1/10 [ 19.3%]  loss: 2.8451
  Epoch 1/10 [ 24.1%]  loss: 3.0057
  Epoch 1/10 [ 28.9%]  loss: 2.5388
  Epoch 1/10 [ 33.7%]  loss: 2.5354
  Epoch 1/10 [ 38.6%]  loss: 2.3725
  Epoch 1/10 [ 43.4%]  loss: 2.3584
  Epoch 1/10 [ 48.2%]  loss: 2.4524
  Epoch 1/10 [ 53.0%]  loss: 2.0396
  Epoch 1/10 [ 57.8%]  loss: 2.1362
  Epoch 1/10 [ 62.7%]  loss: 1.9591
  Epoch 1/10 [ 67.5%]  loss: 2.1011
  Epoch 1/10 [ 72.3%]  loss: 1.8945
  Epoch 1/10 [ 77.1%]  loss: 1.9520
  Epoch 1/10 [ 81.9%]  loss: 1.6467
  Epoch 1/10 [ 86.7%]  loss: 1.6461
  Epoch 1/10 [ 91.6%]  loss: 1.7272
  Epoch 1/10 [ 96.4%]  loss: 1.6714
  Epoch 1/10 [100.0%]  loss: 1.7250

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.67batch/s]

Epoch 1/10
Train Loss: 2.3650 | Train F1: 0.2717
Val Loss: 2.7163 | Val F1: 0.1503
Epoch Time: 82.33s

  Epoch 2/10 [  4.8%]  loss: 1.6636
  Epoch 2/10 [  9.6%]  loss: 1.4674
  Epoch 2/10 [ 14.5%]  loss: 1.2401
  Epoch 2/10 [ 19.3%]  loss: 1.4900
  Epoch 2/10 [ 24.1%]  loss: 1.3851
  Epoch 2/10 [ 28.9%]  loss: 1.4206
  Epoch 2/10 [ 33.7%]  loss: 1.4334
  Epoch 2/10 [ 38.6%]  loss: 1.4433
  Epoch 2/10 [ 43.4%]  loss: 1.4494
  Epoch 2/10 [ 48.2%]  loss: 1.3147
  Epoch 2/10 [ 53.0%]  loss: 1.2486
  Epoch 2/10 [ 57.8%]  loss: 1.2374
  Epoch 2/10 [ 62.7%]  loss: 1.2823
  Epoch 2/10 [ 67.5%]  loss: 1.1092
  Epoch 2/10 [ 72.3%]  loss: 1.1952
  Epoch 2/10 [ 77.1%]  loss: 1.1389
  Epoch 2/10 [ 81.9%]  loss: 1.1494
  Epoch 2/10 [ 86.7%]  loss: 1.1228
  Epoch 2/10 [ 91.6%]  loss: 1.1157
  Epoch 2/10 [ 96.4%]  loss: 1.1448
  Epoch 2/10 [100.0%]  loss: 1.0568

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.58batch/s]

Epoch 2/10
Train Loss: 1.2937 | Train F1: 0.4312
Val Loss: 2.3783 | Val F1: 0.2176
Epoch Time: 82.29s

  Epoch 3/10 [  4.8%]  loss: 0.9924
  Epoch 3/10 [  9.6%]  loss: 1.0243
  Epoch 3/10 [ 14.5%]  loss: 1.0213
  Epoch 3/10 [ 19.3%]  loss: 0.9236
  Epoch 3/10 [ 24.1%]  loss: 1.0082
  Epoch 3/10 [ 28.9%]  loss: 0.9804
  Epoch 3/10 [ 33.7%]  loss: 1.0467
  Epoch 3/10 [ 38.6%]  loss: 1.1033
  Epoch 3/10 [ 43.4%]  loss: 1.0377
  Epoch 3/10 [ 48.2%]  loss: 0.9157
  Epoch 3/10 [ 53.0%]  loss: 1.0227
  Epoch 3/10 [ 57.8%]  loss: 1.0632
  Epoch 3/10 [ 62.7%]  loss: 0.9844
  Epoch 3/10 [ 67.5%]  loss: 1.0951
  Epoch 3/10 [ 72.3%]  loss: 1.2437
  Epoch 3/10 [ 77.1%]  loss: 1.0045
  Epoch 3/10 [ 81.9%]  loss: 0.9538
  Epoch 3/10 [ 86.7%]  loss: 1.0165
  Epoch 3/10 [ 91.6%]  loss: 0.9377
  Epoch 3/10 [ 96.4%]  loss: 1.0262
  Epoch 3/10 [100.0%]  loss: 0.8833

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.52batch/s]

Epoch 3/10
Train Loss: 1.0151 | Train F1: 0.4997
Val Loss: 2.2811 | Val F1: 0.2559
Epoch Time: 82.27s

  Epoch 4/10 [  4.8%]  loss: 0.9209
  Epoch 4/10 [  9.6%]  loss: 0.9019
  Epoch 4/10 [ 14.5%]  loss: 0.9411
  Epoch 4/10 [ 19.3%]  loss: 0.9913
  Epoch 4/10 [ 24.1%]  loss: 0.9320
  Epoch 4/10 [ 28.9%]  loss: 0.9662
  Epoch 4/10 [ 33.7%]  loss: 0.9372
  Epoch 4/10 [ 38.6%]  loss: 0.9297
  Epoch 4/10 [ 43.4%]  loss: 0.8803
  Epoch 4/10 [ 48.2%]  loss: 0.8036
  Epoch 4/10 [ 53.0%]  loss: 0.8731
  Epoch 4/10 [ 57.8%]  loss: 0.9673
  Epoch 4/10 [ 62.7%]  loss: 0.8058
  Epoch 4/10 [ 67.5%]  loss: 1.0276
  Epoch 4/10 [ 72.3%]  loss: 0.9660
  Epoch 4/10 [ 77.1%]  loss: 0.9808
  Epoch 4/10 [ 81.9%]  loss: 0.9660
  Epoch 4/10 [ 86.7%]  loss: 1.2045
  Epoch 4/10 [ 91.6%]  loss: 1.0156
  Epoch 4/10 [ 96.4%]  loss: 1.0179
  Epoch 4/10 [100.0%]  loss: 0.9973

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.56batch/s]

Epoch 4/10
Train Loss: 0.9531 | Train F1: 0.5464
Val Loss: 2.4524 | Val F1: 0.2229
Epoch Time: 82.25s

  Epoch 5/10 [  4.8%]  loss: 0.9285
  Epoch 5/10 [  9.6%]  loss: 0.7908
  Epoch 5/10 [ 14.5%]  loss: 0.9148
  Epoch 5/10 [ 19.3%]  loss: 0.8846
  Epoch 5/10 [ 24.1%]  loss: 0.8351
  Epoch 5/10 [ 28.9%]  loss: 0.8141
  Epoch 5/10 [ 33.7%]  loss: 0.7944
  Epoch 5/10 [ 38.6%]  loss: 0.7540
  Epoch 5/10 [ 43.4%]  loss: 0.7936
  Epoch 5/10 [ 48.2%]  loss: 0.8022
  Epoch 5/10 [ 53.0%]  loss: 0.7801
  Epoch 5/10 [ 57.8%]  loss: 0.7328
  Epoch 5/10 [ 62.7%]  loss: 0.7311
  Epoch 5/10 [ 67.5%]  loss: 0.7420
  Epoch 5/10 [ 72.3%]  loss: 0.7166
  Epoch 5/10 [ 77.1%]  loss: 0.7197
  Epoch 5/10 [ 81.9%]  loss: 0.7241
  Epoch 5/10 [ 86.7%]  loss: 0.7178
  Epoch 5/10 [ 91.6%]  loss: 0.7078
  Epoch 5/10 [ 96.4%]  loss: 0.6804
  Epoch 5/10 [100.0%]  loss: 0.7287

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.62batch/s]

Epoch 5/10
Train Loss: 0.7764 | Train F1: 0.5884
Val Loss: 2.2379 | Val F1: 0.2735
Epoch Time: 82.23s

  Epoch 6/10 [  4.8%]  loss: 0.7681
  Epoch 6/10 [  9.6%]  loss: 0.7803
  Epoch 6/10 [ 14.5%]  loss: 0.8504
  Epoch 6/10 [ 19.3%]  loss: 0.7920
  Epoch 6/10 [ 24.1%]  loss: 0.7237
  Epoch 6/10 [ 28.9%]  loss: 0.7108
  Epoch 6/10 [ 33.7%]  loss: 0.7684
  Epoch 6/10 [ 38.6%]  loss: 0.7224
  Epoch 6/10 [ 43.4%]  loss: 0.6588
  Epoch 6/10 [ 48.2%]  loss: 0.7332
  Epoch 6/10 [ 53.0%]  loss: 0.6645
  Epoch 6/10 [ 57.8%]  loss: 0.6592
  Epoch 6/10 [ 62.7%]  loss: 0.6880
  Epoch 6/10 [ 67.5%]  loss: 0.6620
  Epoch 6/10 [ 72.3%]  loss: 0.6661
  Epoch 6/10 [ 77.1%]  loss: 0.6675
  Epoch 6/10 [ 81.9%]  loss: 0.6210
  Epoch 6/10 [ 86.7%]  loss: 0.6308
  Epoch 6/10 [ 91.6%]  loss: 0.6551
  Epoch 6/10 [ 96.4%]  loss: 0.6268
  Epoch 6/10 [100.0%]  loss: 0.6632

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.63batch/s]

Epoch 6/10
Train Loss: 0.7010 | Train F1: 0.6337
Val Loss: 2.3471 | Val F1: 0.2648
Epoch Time: 82.25s

  Epoch 7/10 [  4.8%]  loss: 0.6550
  Epoch 7/10 [  9.6%]  loss: 0.5890
  Epoch 7/10 [ 14.5%]  loss: 0.6043
  Epoch 7/10 [ 19.3%]  loss: 0.6740
  Epoch 7/10 [ 24.1%]  loss: 0.6603
  Epoch 7/10 [ 28.9%]  loss: 0.6581
  Epoch 7/10 [ 33.7%]  loss: 0.6784
  Epoch 7/10 [ 38.6%]  loss: 0.6513
  Epoch 7/10 [ 43.4%]  loss: 0.6096
  Epoch 7/10 [ 48.2%]  loss: 0.6473
  Epoch 7/10 [ 53.0%]  loss: 0.6911
  Epoch 7/10 [ 57.8%]  loss: 0.6206
  Epoch 7/10 [ 62.7%]  loss: 0.6545
  Epoch 7/10 [ 67.5%]  loss: 0.6603
  Epoch 7/10 [ 72.3%]  loss: 0.6776
  Epoch 7/10 [ 77.1%]  loss: 0.6385
  Epoch 7/10 [ 81.9%]  loss: 0.6553
  Epoch 7/10 [ 86.7%]  loss: 0.5976
  Epoch 7/10 [ 91.6%]  loss: 0.6786
  Epoch 7/10 [ 96.4%]  loss: 0.6504
  Epoch 7/10 [100.0%]  loss: 0.5862

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.58batch/s]

Epoch 7/10
Train Loss: 0.6454 | Train F1: 0.6649
Val Loss: 2.1500 | Val F1: 0.2887
Epoch Time: 82.29s

  Epoch 8/10 [  4.8%]  loss: 0.6343
  Epoch 8/10 [  9.6%]  loss: 0.6251
  Epoch 8/10 [ 14.5%]  loss: 0.6324
  Epoch 8/10 [ 19.3%]  loss: 0.6203
  Epoch 8/10 [ 24.1%]  loss: 0.6330
  Epoch 8/10 [ 28.9%]  loss: 0.6173
  Epoch 8/10 [ 33.7%]  loss: 0.5876
  Epoch 8/10 [ 38.6%]  loss: 0.5872
  Epoch 8/10 [ 43.4%]  loss: 0.5806
  Epoch 8/10 [ 48.2%]  loss: 0.5683
  Epoch 8/10 [ 53.0%]  loss: 0.5607
  Epoch 8/10 [ 57.8%]  loss: 0.5823
  Epoch 8/10 [ 62.7%]  loss: 0.5757
  Epoch 8/10 [ 67.5%]  loss: 0.5612
  Epoch 8/10 [ 72.3%]  loss: 0.5877
  Epoch 8/10 [ 77.1%]  loss: 0.5343
  Epoch 8/10 [ 81.9%]  loss: 0.5154
  Epoch 8/10 [ 86.7%]  loss: 0.6180
  Epoch 8/10 [ 91.6%]  loss: 0.5894
  Epoch 8/10 [ 96.4%]  loss: 0.5264
  Epoch 8/10 [100.0%]  loss: 0.6004

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.54batch/s]

Epoch 8/10
Train Loss: 0.5873 | Train F1: 0.6823
Val Loss: 2.3734 | Val F1: 0.2920
Epoch Time: 82.26s

  Epoch 9/10 [  4.8%]  loss: 0.5606
  Epoch 9/10 [  9.6%]  loss: 0.6348
  Epoch 9/10 [ 14.5%]  loss: 0.5490
  Epoch 9/10 [ 19.3%]  loss: 0.5053
  Epoch 9/10 [ 24.1%]  loss: 0.5626
  Epoch 9/10 [ 28.9%]  loss: 0.5454
  Epoch 9/10 [ 33.7%]  loss: 0.5433
  Epoch 9/10 [ 38.6%]  loss: 0.5280
  Epoch 9/10 [ 43.4%]  loss: 0.5864
  Epoch 9/10 [ 48.2%]  loss: 0.5316
  Epoch 9/10 [ 53.0%]  loss: 0.5575
  Epoch 9/10 [ 57.8%]  loss: 0.5236
  Epoch 9/10 [ 62.7%]  loss: 0.5317
  Epoch 9/10 [ 67.5%]  loss: 0.5018
  Epoch 9/10 [ 72.3%]  loss: 0.5043
  Epoch 9/10 [ 77.1%]  loss: 0.5272
  Epoch 9/10 [ 81.9%]  loss: 0.5340
  Epoch 9/10 [ 86.7%]  loss: 0.5444
  Epoch 9/10 [ 91.6%]  loss: 0.5964
  Epoch 9/10 [ 96.4%]  loss: 0.5966
  Epoch 9/10 [100.0%]  loss: 0.6406

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.56batch/s]

Epoch 9/10
Train Loss: 0.5516 | Train F1: 0.6984
Val Loss: 2.1979 | Val F1: 0.3086
Epoch Time: 82.29s

  Epoch 10/10 [  4.8%]  loss: 0.5973
  Epoch 10/10 [  9.6%]  loss: 0.7758
  Epoch 10/10 [ 14.5%]  loss: 0.8856
  Epoch 10/10 [ 19.3%]  loss: 0.8824
  Epoch 10/10 [ 24.1%]  loss: 1.0611
  Epoch 10/10 [ 28.9%]  loss: 1.1365
  Epoch 10/10 [ 33.7%]  loss: 1.1199
  Epoch 10/10 [ 38.6%]  loss: 1.4763
  Epoch 10/10 [ 43.4%]  loss: 1.4757
  Epoch 10/10 [ 48.2%]  loss: 1.6573
  Epoch 10/10 [ 53.0%]  loss: 1.5369
  Epoch 10/10 [ 57.8%]  loss: 1.3484
  Epoch 10/10 [ 62.7%]  loss: 1.1958
  Epoch 10/10 [ 67.5%]  loss: 1.1249
  Epoch 10/10 [ 72.3%]  loss: 1.0062
  Epoch 10/10 [ 77.1%]  loss: 0.9907
  Epoch 10/10 [ 81.9%]  loss: 1.0085
  Epoch 10/10 [ 86.7%]  loss: 0.9043
  Epoch 10/10 [ 91.6%]  loss: 0.8617
  Epoch 10/10 [ 96.4%]  loss: 0.7439
  Epoch 10/10 [100.0%]  loss: 0.8414

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.55batch/s]

Epoch 10/10
Train Loss: 1.0805 | Train F1: 0.5494
Val Loss: 2.3578 | Val F1: 0.2574
Epoch Time: 82.27s

Finalised: 1313/3776 conv1 channels zeroed (34.8%)
Saved → trained_models/pwkd_self_r50_r35/pwkd_self_r50_r35_full.pth

Warming up pwkd_self_r50_r35...
Running inference...
  ratio: 35% | F1: 0.0631 | params: 18,178,173

============================================================
  PWKD Option 2 (ResNet50) — pruning ratio 40%
============================================================
  Epoch 1/10 [  4.8%]  loss: 3.6246
  Epoch 1/10 [  9.6%]  loss: 3.8454
  Epoch 1/10 [ 14.5%]  loss: 2.9898
  Epoch 1/10 [ 19.3%]  loss: 3.0658
  Epoch 1/10 [ 24.1%]  loss: 2.7574
  Epoch 1/10 [ 28.9%]  loss: 2.6805
  Epoch 1/10 [ 33.7%]  loss: 2.6189
  Epoch 1/10 [ 38.6%]  loss: 2.2042
  Epoch 1/10 [ 43.4%]  loss: 2.2522
  Epoch 1/10 [ 48.2%]  loss: 2.1035
  Epoch 1/10 [ 53.0%]  loss: 2.1655
  Epoch 1/10 [ 57.8%]  loss: 2.0299
  Epoch 1/10 [ 62.7%]  loss: 1.8018
  Epoch 1/10 [ 67.5%]  loss: 1.7657
  Epoch 1/10 [ 72.3%]  loss: 1.7818
  Epoch 1/10 [ 77.1%]  loss: 1.8164
  Epoch 1/10 [ 81.9%]  loss: 1.8819
  Epoch 1/10 [ 86.7%]  loss: 1.8988
  Epoch 1/10 [ 91.6%]  loss: 1.9277
  Epoch 1/10 [ 96.4%]  loss: 1.8032
  Epoch 1/10 [100.0%]  loss: 1.4795

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.60batch/s]

Epoch 1/10
Train Loss: 2.3193 | Train F1: 0.2798
Val Loss: 2.6155 | Val F1: 0.1559
Epoch Time: 82.29s

  Epoch 2/10 [  4.8%]  loss: 1.4071
  Epoch 2/10 [  9.6%]  loss: 1.6261
  Epoch 2/10 [ 14.5%]  loss: 1.4439
  Epoch 2/10 [ 19.3%]  loss: 1.4673
  Epoch 2/10 [ 24.1%]  loss: 1.5896
  Epoch 2/10 [ 28.9%]  loss: 1.4961
  Epoch 2/10 [ 33.7%]  loss: 1.5958
  Epoch 2/10 [ 38.6%]  loss: 1.5235
  Epoch 2/10 [ 43.4%]  loss: 1.3737
  Epoch 2/10 [ 48.2%]  loss: 1.3329
  Epoch 2/10 [ 53.0%]  loss: 1.2056
  Epoch 2/10 [ 57.8%]  loss: 1.3328
  Epoch 2/10 [ 62.7%]  loss: 1.1483
  Epoch 2/10 [ 67.5%]  loss: 1.2585
  Epoch 2/10 [ 72.3%]  loss: 1.1854
  Epoch 2/10 [ 77.1%]  loss: 1.1424
  Epoch 2/10 [ 81.9%]  loss: 1.1024
  Epoch 2/10 [ 86.7%]  loss: 1.1725
  Epoch 2/10 [ 91.6%]  loss: 1.2137
  Epoch 2/10 [ 96.4%]  loss: 1.4070
  Epoch 2/10 [100.0%]  loss: 1.3367

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.59batch/s]

Epoch 2/10
Train Loss: 1.3507 | Train F1: 0.4141
Val Loss: 2.6629 | Val F1: 0.1448
Epoch Time: 82.30s

  Epoch 3/10 [  4.8%]  loss: 1.4790
  Epoch 3/10 [  9.6%]  loss: 1.2680
  Epoch 3/10 [ 14.5%]  loss: 1.2725
  Epoch 3/10 [ 19.3%]  loss: 1.1939
  Epoch 3/10 [ 24.1%]  loss: 1.3229
  Epoch 3/10 [ 28.9%]  loss: 1.1052
  Epoch 3/10 [ 33.7%]  loss: 1.1189
  Epoch 3/10 [ 38.6%]  loss: 1.1321
  Epoch 3/10 [ 43.4%]  loss: 1.0447
  Epoch 3/10 [ 48.2%]  loss: 1.0722
  Epoch 3/10 [ 53.0%]  loss: 0.9779
  Epoch 3/10 [ 57.8%]  loss: 0.9812
  Epoch 3/10 [ 62.7%]  loss: 0.9664
  Epoch 3/10 [ 67.5%]  loss: 0.8257
  Epoch 3/10 [ 72.3%]  loss: 0.9126
  Epoch 3/10 [ 77.1%]  loss: 0.8503
  Epoch 3/10 [ 81.9%]  loss: 0.9914
  Epoch 3/10 [ 86.7%]  loss: 1.0064
  Epoch 3/10 [ 91.6%]  loss: 1.0169
  Epoch 3/10 [ 96.4%]  loss: 1.0220
  Epoch 3/10 [100.0%]  loss: 0.9828

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.48batch/s]

Epoch 3/10
Train Loss: 1.0746 | Train F1: 0.4975
Val Loss: 2.2929 | Val F1: 0.2440
Epoch Time: 82.29s

  Epoch 4/10 [  4.8%]  loss: 0.8964
  Epoch 4/10 [  9.6%]  loss: 0.8360
  Epoch 4/10 [ 14.5%]  loss: 0.8887
  Epoch 4/10 [ 19.3%]  loss: 0.9259
  Epoch 4/10 [ 24.1%]  loss: 0.9273
  Epoch 4/10 [ 28.9%]  loss: 0.8422
  Epoch 4/10 [ 33.7%]  loss: 0.8285
  Epoch 4/10 [ 38.6%]  loss: 0.8098
  Epoch 4/10 [ 43.4%]  loss: 0.8944
  Epoch 4/10 [ 48.2%]  loss: 0.9603
  Epoch 4/10 [ 53.0%]  loss: 0.7751
  Epoch 4/10 [ 57.8%]  loss: 0.8001
  Epoch 4/10 [ 62.7%]  loss: 0.8206
  Epoch 4/10 [ 67.5%]  loss: 0.8652
  Epoch 4/10 [ 72.3%]  loss: 0.9300
  Epoch 4/10 [ 77.1%]  loss: 0.9003
  Epoch 4/10 [ 81.9%]  loss: 0.9080
  Epoch 4/10 [ 86.7%]  loss: 0.8750
  Epoch 4/10 [ 91.6%]  loss: 0.7909
  Epoch 4/10 [ 96.4%]  loss: 0.8549
  Epoch 4/10 [100.0%]  loss: 0.9092

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.57batch/s]

Epoch 4/10
Train Loss: 0.8680 | Train F1: 0.5661
Val Loss: 2.2505 | Val F1: 0.2654
Epoch Time: 82.29s

  Epoch 5/10 [  4.8%]  loss: 0.8549
  Epoch 5/10 [  9.6%]  loss: 0.8610
  Epoch 5/10 [ 14.5%]  loss: 0.8712
  Epoch 5/10 [ 19.3%]  loss: 0.9157
  Epoch 5/10 [ 24.1%]  loss: 0.8260
  Epoch 5/10 [ 28.9%]  loss: 0.8306
  Epoch 5/10 [ 33.7%]  loss: 0.8379
  Epoch 5/10 [ 38.6%]  loss: 0.7895
  Epoch 5/10 [ 43.4%]  loss: 0.7590
  Epoch 5/10 [ 48.2%]  loss: 0.7644
  Epoch 5/10 [ 53.0%]  loss: 0.8293
  Epoch 5/10 [ 57.8%]  loss: 0.7119
  Epoch 5/10 [ 62.7%]  loss: 0.7290
  Epoch 5/10 [ 67.5%]  loss: 0.7305
  Epoch 5/10 [ 72.3%]  loss: 0.6862
  Epoch 5/10 [ 77.1%]  loss: 0.6585
  Epoch 5/10 [ 81.9%]  loss: 0.7604
  Epoch 5/10 [ 86.7%]  loss: 0.6661
  Epoch 5/10 [ 91.6%]  loss: 0.6778
  Epoch 5/10 [ 96.4%]  loss: 0.7002
  Epoch 5/10 [100.0%]  loss: 0.7196

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.53batch/s]

Epoch 5/10
Train Loss: 0.7711 | Train F1: 0.6051
Val Loss: 2.2995 | Val F1: 0.2879
Epoch Time: 82.22s

  Epoch 6/10 [  4.8%]  loss: 0.7855
  Epoch 6/10 [  9.6%]  loss: 0.7410
  Epoch 6/10 [ 14.5%]  loss: 0.7147
  Epoch 6/10 [ 19.3%]  loss: 0.6354
  Epoch 6/10 [ 24.1%]  loss: 0.6724
  Epoch 6/10 [ 28.9%]  loss: 0.7145
  Epoch 6/10 [ 33.7%]  loss: 0.6441
  Epoch 6/10 [ 38.6%]  loss: 0.7301
  Epoch 6/10 [ 43.4%]  loss: 0.6129
  Epoch 6/10 [ 48.2%]  loss: 0.5975
  Epoch 6/10 [ 53.0%]  loss: 0.6340
  Epoch 6/10 [ 57.8%]  loss: 0.6364
  Epoch 6/10 [ 62.7%]  loss: 0.6164
  Epoch 6/10 [ 67.5%]  loss: 0.7206
  Epoch 6/10 [ 72.3%]  loss: 0.6772
  Epoch 6/10 [ 77.1%]  loss: 0.6150
  Epoch 6/10 [ 81.9%]  loss: 0.5938
  Epoch 6/10 [ 86.7%]  loss: 0.6377
  Epoch 6/10 [ 91.6%]  loss: 0.6567
  Epoch 6/10 [ 96.4%]  loss: 0.7122
  Epoch 6/10 [100.0%]  loss: 0.7254

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.59batch/s]

Epoch 6/10
Train Loss: 0.6695 | Train F1: 0.6471
Val Loss: 2.2403 | Val F1: 0.2719
Epoch Time: 82.23s

  Epoch 7/10 [  4.8%]  loss: 0.7225
  Epoch 7/10 [  9.6%]  loss: 0.6710
  Epoch 7/10 [ 14.5%]  loss: 0.6061
  Epoch 7/10 [ 19.3%]  loss: 0.6004
  Epoch 7/10 [ 24.1%]  loss: 0.6679
  Epoch 7/10 [ 28.9%]  loss: 0.6585
  Epoch 7/10 [ 33.7%]  loss: 0.6018
  Epoch 7/10 [ 38.6%]  loss: 0.6423
  Epoch 7/10 [ 43.4%]  loss: 0.6328
  Epoch 7/10 [ 48.2%]  loss: 0.5742
  Epoch 7/10 [ 53.0%]  loss: 0.6021
  Epoch 7/10 [ 57.8%]  loss: 0.5895
  Epoch 7/10 [ 62.7%]  loss: 0.6425
  Epoch 7/10 [ 67.5%]  loss: 0.5690
  Epoch 7/10 [ 72.3%]  loss: 0.6302
  Epoch 7/10 [ 77.1%]  loss: 0.6112
  Epoch 7/10 [ 81.9%]  loss: 0.6171
  Epoch 7/10 [ 86.7%]  loss: 0.6691
  Epoch 7/10 [ 91.6%]  loss: 0.5602
  Epoch 7/10 [ 96.4%]  loss: 0.5519
  Epoch 7/10 [100.0%]  loss: 0.5690

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.58batch/s]

Epoch 7/10
Train Loss: 0.6191 | Train F1: 0.6654
Val Loss: 2.0418 | Val F1: 0.3097
Epoch Time: 82.24s

  Epoch 8/10 [  4.8%]  loss: 0.5653
  Epoch 8/10 [  9.6%]  loss: 0.6141
  Epoch 8/10 [ 14.5%]  loss: 0.5913
  Epoch 8/10 [ 19.3%]  loss: 0.5709
  Epoch 8/10 [ 24.1%]  loss: 0.5280
  Epoch 8/10 [ 28.9%]  loss: 0.5431
  Epoch 8/10 [ 33.7%]  loss: 0.6335
  Epoch 8/10 [ 38.6%]  loss: 0.5689
  Epoch 8/10 [ 43.4%]  loss: 0.5337
  Epoch 8/10 [ 48.2%]  loss: 0.6051
  Epoch 8/10 [ 53.0%]  loss: 0.5344
  Epoch 8/10 [ 57.8%]  loss: 0.5472
  Epoch 8/10 [ 62.7%]  loss: 0.6235
  Epoch 8/10 [ 67.5%]  loss: 0.5202
  Epoch 8/10 [ 72.3%]  loss: 0.5284
  Epoch 8/10 [ 77.1%]  loss: 0.5554
  Epoch 8/10 [ 81.9%]  loss: 0.5262
  Epoch 8/10 [ 86.7%]  loss: 0.5664
  Epoch 8/10 [ 91.6%]  loss: 0.6550
  Epoch 8/10 [ 96.4%]  loss: 0.6280
  Epoch 8/10 [100.0%]  loss: 0.6527

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.59batch/s]

Epoch 8/10
Train Loss: 0.5749 | Train F1: 0.6913
Val Loss: 2.3231 | Val F1: 0.2860
Epoch Time: 82.29s

  Epoch 9/10 [  4.8%]  loss: 0.6827
  Epoch 9/10 [  9.6%]  loss: 0.6440
  Epoch 9/10 [ 14.5%]  loss: 0.6114
  Epoch 9/10 [ 19.3%]  loss: 0.6234
  Epoch 9/10 [ 24.1%]  loss: 0.6367
  Epoch 9/10 [ 28.9%]  loss: 0.5890
  Epoch 9/10 [ 33.7%]  loss: 0.6520
  Epoch 9/10 [ 38.6%]  loss: 0.6355
  Epoch 9/10 [ 43.4%]  loss: 0.6738
  Epoch 9/10 [ 48.2%]  loss: 0.6456
  Epoch 9/10 [ 53.0%]  loss: 0.6501
  Epoch 9/10 [ 57.8%]  loss: 0.6939
  Epoch 9/10 [ 62.7%]  loss: 0.7027
  Epoch 9/10 [ 67.5%]  loss: 0.6763
  Epoch 9/10 [ 72.3%]  loss: 0.7031
  Epoch 9/10 [ 77.1%]  loss: 0.7342
  Epoch 9/10 [ 81.9%]  loss: 0.7613
  Epoch 9/10 [ 86.7%]  loss: 0.7632
  Epoch 9/10 [ 91.6%]  loss: 0.7769
  Epoch 9/10 [ 96.4%]  loss: 0.7667
  Epoch 9/10 [100.0%]  loss: 0.8893

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.55batch/s]

Epoch 9/10
Train Loss: 0.6887 | Train F1: 0.6589
Val Loss: 2.4699 | Val F1: 0.2696
Epoch Time: 82.33s

  Epoch 10/10 [  4.8%]  loss: 0.9100
  Epoch 10/10 [  9.6%]  loss: 0.8553
  Epoch 10/10 [ 14.5%]  loss: 0.7804
  Epoch 10/10 [ 19.3%]  loss: 0.7667
  Epoch 10/10 [ 24.1%]  loss: 0.8357
  Epoch 10/10 [ 28.9%]  loss: 0.7695
  Epoch 10/10 [ 33.7%]  loss: 0.8682
  Epoch 10/10 [ 38.6%]  loss: 1.3622
  Epoch 10/10 [ 43.4%]  loss: 1.3788
  Epoch 10/10 [ 48.2%]  loss: 1.9295
  Epoch 10/10 [ 53.0%]  loss: 1.6516
  Epoch 10/10 [ 57.8%]  loss: 1.5114
  Epoch 10/10 [ 62.7%]  loss: 1.2813
  Epoch 10/10 [ 67.5%]  loss: 1.2107
  Epoch 10/10 [ 72.3%]  loss: 1.1358
  Epoch 10/10 [ 77.1%]  loss: 1.1334
  Epoch 10/10 [ 81.9%]  loss: 1.0503
  Epoch 10/10 [ 86.7%]  loss: 1.0023
  Epoch 10/10 [ 91.6%]  loss: 0.8680
  Epoch 10/10 [ 96.4%]  loss: 0.9085
  Epoch 10/10 [100.0%]  loss: 0.8598

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.66batch/s]

Epoch 10/10
Train Loss: 1.1014 | Train F1: 0.5483
Val Loss: 2.2669 | Val F1: 0.2495
Epoch Time: 82.22s

Finalised: 1503/3776 conv1 channels zeroed (39.8%)
Saved → trained_models/pwkd_self_r50_r40/pwkd_self_r50_r40_full.pth

Warming up pwkd_self_r50_r40...
Running inference...
  ratio: 40% | F1: 0.0348 | params: 17,399,933

============================================================
  PWKD Option 2 (ResNet50) — pruning ratio 45%
============================================================
  Epoch 1/10 [  4.8%]  loss: 3.6157
  Epoch 1/10 [  9.6%]  loss: 4.0756
  Epoch 1/10 [ 14.5%]  loss: 3.5524
  Epoch 1/10 [ 19.3%]  loss: 3.2694
  Epoch 1/10 [ 24.1%]  loss: 2.9189
  Epoch 1/10 [ 28.9%]  loss: 2.7948
  Epoch 1/10 [ 33.7%]  loss: 2.6835
  Epoch 1/10 [ 38.6%]  loss: 2.6399
  Epoch 1/10 [ 43.4%]  loss: 2.4229
  Epoch 1/10 [ 48.2%]  loss: 2.2646
  Epoch 1/10 [ 53.0%]  loss: 2.1083
  Epoch 1/10 [ 57.8%]  loss: 2.3968
  Epoch 1/10 [ 62.7%]  loss: 2.2422
  Epoch 1/10 [ 67.5%]  loss: 2.1661
  Epoch 1/10 [ 72.3%]  loss: 1.9342
  Epoch 1/10 [ 77.1%]  loss: 1.9835
  Epoch 1/10 [ 81.9%]  loss: 1.6917
  Epoch 1/10 [ 86.7%]  loss: 1.9075
  Epoch 1/10 [ 91.6%]  loss: 1.8706
  Epoch 1/10 [ 96.4%]  loss: 1.7461
  Epoch 1/10 [100.0%]  loss: 1.7816

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.49batch/s]

Epoch 1/10
Train Loss: 2.4878 | Train F1: 0.2479
Val Loss: 2.6072 | Val F1: 0.1424
Epoch Time: 82.35s

  Epoch 2/10 [  4.8%]  loss: 1.6931
  Epoch 2/10 [  9.6%]  loss: 1.6355
  Epoch 2/10 [ 14.5%]  loss: 1.5305
  Epoch 2/10 [ 19.3%]  loss: 1.5326
  Epoch 2/10 [ 24.1%]  loss: 1.4564
  Epoch 2/10 [ 28.9%]  loss: 1.4284
  Epoch 2/10 [ 33.7%]  loss: 1.2484
  Epoch 2/10 [ 38.6%]  loss: 1.4995
  Epoch 2/10 [ 43.4%]  loss: 1.3421
  Epoch 2/10 [ 48.2%]  loss: 1.4530
  Epoch 2/10 [ 53.0%]  loss: 1.3614
  Epoch 2/10 [ 57.8%]  loss: 1.4208
  Epoch 2/10 [ 62.7%]  loss: 1.4720
  Epoch 2/10 [ 67.5%]  loss: 1.2997
  Epoch 2/10 [ 72.3%]  loss: 1.2640
  Epoch 2/10 [ 77.1%]  loss: 1.2135
  Epoch 2/10 [ 81.9%]  loss: 1.3394
  Epoch 2/10 [ 86.7%]  loss: 1.3798
  Epoch 2/10 [ 91.6%]  loss: 1.1985
  Epoch 2/10 [ 96.4%]  loss: 1.3188
  Epoch 2/10 [100.0%]  loss: 1.4426

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.57batch/s]

Epoch 2/10
Train Loss: 1.4058 | Train F1: 0.4025
Val Loss: 2.4929 | Val F1: 0.1931
Epoch Time: 82.29s

  Epoch 3/10 [  4.8%]  loss: 1.3993
  Epoch 3/10 [  9.6%]  loss: 1.5043
  Epoch 3/10 [ 14.5%]  loss: 1.2279
  Epoch 3/10 [ 19.3%]  loss: 1.3758
  Epoch 3/10 [ 24.1%]  loss: 1.3486
  Epoch 3/10 [ 28.9%]  loss: 1.3266
  Epoch 3/10 [ 33.7%]  loss: 1.1328
  Epoch 3/10 [ 38.6%]  loss: 1.2004
  Epoch 3/10 [ 43.4%]  loss: 1.0495
  Epoch 3/10 [ 48.2%]  loss: 1.0281
  Epoch 3/10 [ 53.0%]  loss: 0.9755
  Epoch 3/10 [ 57.8%]  loss: 1.0564
  Epoch 3/10 [ 62.7%]  loss: 0.9892
  Epoch 3/10 [ 67.5%]  loss: 0.9439
  Epoch 3/10 [ 72.3%]  loss: 0.9200
  Epoch 3/10 [ 77.1%]  loss: 0.9818
  Epoch 3/10 [ 81.9%]  loss: 1.0105
  Epoch 3/10 [ 86.7%]  loss: 0.9613
  Epoch 3/10 [ 91.6%]  loss: 0.9881
  Epoch 3/10 [ 96.4%]  loss: 1.0127
  Epoch 3/10 [100.0%]  loss: 1.0091

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.53batch/s]

Epoch 3/10
Train Loss: 1.1176 | Train F1: 0.4879
Val Loss: 2.3097 | Val F1: 0.2498
Epoch Time: 82.35s

  Epoch 4/10 [  4.8%]  loss: 0.9617
  Epoch 4/10 [  9.6%]  loss: 1.1306
  Epoch 4/10 [ 14.5%]  loss: 1.0662
  Epoch 4/10 [ 19.3%]  loss: 0.9723
  Epoch 4/10 [ 24.1%]  loss: 0.9825
  Epoch 4/10 [ 28.9%]  loss: 0.9128
  Epoch 4/10 [ 33.7%]  loss: 0.8462
  Epoch 4/10 [ 38.6%]  loss: 0.8005
  Epoch 4/10 [ 43.4%]  loss: 0.7975
  Epoch 4/10 [ 48.2%]  loss: 0.9883
  Epoch 4/10 [ 53.0%]  loss: 0.7829
  Epoch 4/10 [ 57.8%]  loss: 0.8401
  Epoch 4/10 [ 62.7%]  loss: 0.8433
  Epoch 4/10 [ 67.5%]  loss: 1.0763
  Epoch 4/10 [ 72.3%]  loss: 0.8885
  Epoch 4/10 [ 77.1%]  loss: 0.8821
  Epoch 4/10 [ 81.9%]  loss: 0.8073
  Epoch 4/10 [ 86.7%]  loss: 0.8395
  Epoch 4/10 [ 91.6%]  loss: 0.7873
  Epoch 4/10 [ 96.4%]  loss: 0.7902
  Epoch 4/10 [100.0%]  loss: 0.7509

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.58batch/s]

Epoch 4/10
Train Loss: 0.8944 | Train F1: 0.5580
Val Loss: 2.2252 | Val F1: 0.2609
Epoch Time: 82.26s

  Epoch 5/10 [  4.8%]  loss: 0.7619
  Epoch 5/10 [  9.6%]  loss: 0.7357
  Epoch 5/10 [ 14.5%]  loss: 0.8166
  Epoch 5/10 [ 19.3%]  loss: 0.7787
  Epoch 5/10 [ 24.1%]  loss: 0.7351
  Epoch 5/10 [ 28.9%]  loss: 0.7610
  Epoch 5/10 [ 33.7%]  loss: 0.6978
  Epoch 5/10 [ 38.6%]  loss: 0.6916
  Epoch 5/10 [ 43.4%]  loss: 0.7437
  Epoch 5/10 [ 48.2%]  loss: 0.6712
  Epoch 5/10 [ 53.0%]  loss: 0.7630
  Epoch 5/10 [ 57.8%]  loss: 0.6629
  Epoch 5/10 [ 62.7%]  loss: 0.7364
  Epoch 5/10 [ 67.5%]  loss: 0.7828
  Epoch 5/10 [ 72.3%]  loss: 0.7419
  Epoch 5/10 [ 77.1%]  loss: 0.7225
  Epoch 5/10 [ 81.9%]  loss: 0.6956
  Epoch 5/10 [ 86.7%]  loss: 0.8306
  Epoch 5/10 [ 91.6%]  loss: 0.8890
  Epoch 5/10 [ 96.4%]  loss: 0.8646
  Epoch 5/10 [100.0%]  loss: 1.0262

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.55batch/s]

Epoch 5/10
Train Loss: 0.7640 | Train F1: 0.6087
Val Loss: 2.2397 | Val F1: 0.2561
Epoch Time: 82.32s

  Epoch 6/10 [  4.8%]  loss: 0.8254
  Epoch 6/10 [  9.6%]  loss: 0.8178
  Epoch 6/10 [ 14.5%]  loss: 0.7608
  Epoch 6/10 [ 19.3%]  loss: 0.9103
  Epoch 6/10 [ 24.1%]  loss: 0.8447
  Epoch 6/10 [ 28.9%]  loss: 0.8287
  Epoch 6/10 [ 33.7%]  loss: 0.8979
  Epoch 6/10 [ 38.6%]  loss: 0.9583
  Epoch 6/10 [ 43.4%]  loss: 0.9069
  Epoch 6/10 [ 48.2%]  loss: 0.9335
  Epoch 6/10 [ 53.0%]  loss: 0.8797
  Epoch 6/10 [ 57.8%]  loss: 0.8955
  Epoch 6/10 [ 62.7%]  loss: 0.9655
  Epoch 6/10 [ 67.5%]  loss: 1.0356
  Epoch 6/10 [ 72.3%]  loss: 1.1911
  Epoch 6/10 [ 77.1%]  loss: 1.1408
  Epoch 6/10 [ 81.9%]  loss: 0.9954
  Epoch 6/10 [ 86.7%]  loss: 1.0827
  Epoch 6/10 [ 91.6%]  loss: 0.9007
  Epoch 6/10 [ 96.4%]  loss: 0.9111
  Epoch 6/10 [100.0%]  loss: 0.8094

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.50batch/s]

Epoch 6/10
Train Loss: 0.9296 | Train F1: 0.5618
Val Loss: 2.3842 | Val F1: 0.2572
Epoch Time: 82.32s

  Epoch 7/10 [  4.8%]  loss: 0.9645
  Epoch 7/10 [  9.6%]  loss: 0.8469
  Epoch 7/10 [ 14.5%]  loss: 0.7708
  Epoch 7/10 [ 19.3%]  loss: 0.8004
  Epoch 7/10 [ 24.1%]  loss: 0.8191
  Epoch 7/10 [ 28.9%]  loss: 0.8732
  Epoch 7/10 [ 33.7%]  loss: 0.8304
  Epoch 7/10 [ 38.6%]  loss: 0.8896
  Epoch 7/10 [ 43.4%]  loss: 0.7871
  Epoch 7/10 [ 48.2%]  loss: 0.8175
  Epoch 7/10 [ 53.0%]  loss: 0.7855
  Epoch 7/10 [ 57.8%]  loss: 0.7660
  Epoch 7/10 [ 62.7%]  loss: 0.7747
  Epoch 7/10 [ 67.5%]  loss: 0.6773
  Epoch 7/10 [ 72.3%]  loss: 0.6808
  Epoch 7/10 [ 77.1%]  loss: 0.6217
  Epoch 7/10 [ 81.9%]  loss: 0.5955
  Epoch 7/10 [ 86.7%]  loss: 0.6527
  Epoch 7/10 [ 91.6%]  loss: 0.6445
  Epoch 7/10 [ 96.4%]  loss: 0.6020
  Epoch 7/10 [100.0%]  loss: 0.6887

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.50batch/s]

Epoch 7/10
Train Loss: 0.7574 | Train F1: 0.6144
Val Loss: 2.0793 | Val F1: 0.3052
Epoch Time: 82.33s

  Epoch 8/10 [  4.8%]  loss: 0.6888
  Epoch 8/10 [  9.6%]  loss: 0.6809
  Epoch 8/10 [ 14.5%]  loss: 0.6459
  Epoch 8/10 [ 19.3%]  loss: 0.6576
  Epoch 8/10 [ 24.1%]  loss: 0.6054
  Epoch 8/10 [ 28.9%]  loss: 0.6332
  Epoch 8/10 [ 33.7%]  loss: 0.6180
  Epoch 8/10 [ 38.6%]  loss: 0.6182
  Epoch 8/10 [ 43.4%]  loss: 0.5872
  Epoch 8/10 [ 48.2%]  loss: 0.5863
  Epoch 8/10 [ 53.0%]  loss: 0.5046
  Epoch 8/10 [ 57.8%]  loss: 0.5352
  Epoch 8/10 [ 62.7%]  loss: 0.5695
  Epoch 8/10 [ 67.5%]  loss: 0.6162
  Epoch 8/10 [ 72.3%]  loss: 0.6156
  Epoch 8/10 [ 77.1%]  loss: 0.6082
  Epoch 8/10 [ 81.9%]  loss: 0.5858
  Epoch 8/10 [ 86.7%]  loss: 0.5267
  Epoch 8/10 [ 91.6%]  loss: 0.6263
  Epoch 8/10 [ 96.4%]  loss: 0.5612
  Epoch 8/10 [100.0%]  loss: 0.6191

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.61batch/s]

Epoch 8/10
Train Loss: 0.6041 | Train F1: 0.6685
Val Loss: 2.1401 | Val F1: 0.3143
Epoch Time: 82.31s

  Epoch 9/10 [  4.8%]  loss: 0.5523
  Epoch 9/10 [  9.6%]  loss: 0.5786
  Epoch 9/10 [ 14.5%]  loss: 0.5596
  Epoch 9/10 [ 19.3%]  loss: 0.5842
  Epoch 9/10 [ 24.1%]  loss: 0.5134
  Epoch 9/10 [ 28.9%]  loss: 0.5603
  Epoch 9/10 [ 33.7%]  loss: 0.5155
  Epoch 9/10 [ 38.6%]  loss: 0.5367
  Epoch 9/10 [ 43.4%]  loss: 0.5524
  Epoch 9/10 [ 48.2%]  loss: 0.5556
  Epoch 9/10 [ 53.0%]  loss: 0.5398
  Epoch 9/10 [ 57.8%]  loss: 0.5527
  Epoch 9/10 [ 62.7%]  loss: 0.5339
  Epoch 9/10 [ 67.5%]  loss: 0.5515
  Epoch 9/10 [ 72.3%]  loss: 0.5741
  Epoch 9/10 [ 77.1%]  loss: 0.5777
  Epoch 9/10 [ 81.9%]  loss: 0.5972
  Epoch 9/10 [ 86.7%]  loss: 0.5602
  Epoch 9/10 [ 91.6%]  loss: 0.5300
  Epoch 9/10 [ 96.4%]  loss: 0.5606
  Epoch 9/10 [100.0%]  loss: 0.5717

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.59batch/s]

Epoch 9/10
Train Loss: 0.5550 | Train F1: 0.6956
Val Loss: 2.1021 | Val F1: 0.3039
Epoch Time: 82.24s

  Epoch 10/10 [  4.8%]  loss: 0.5437
  Epoch 10/10 [  9.6%]  loss: 0.5692
  Epoch 10/10 [ 14.5%]  loss: 0.5383
  Epoch 10/10 [ 19.3%]  loss: 0.4909
  Epoch 10/10 [ 24.1%]  loss: 0.5051
  Epoch 10/10 [ 28.9%]  loss: 0.5370
  Epoch 10/10 [ 33.7%]  loss: 0.5289
  Epoch 10/10 [ 38.6%]  loss: 0.5394
  Epoch 10/10 [ 43.4%]  loss: 0.4940
  Epoch 10/10 [ 48.2%]  loss: 0.5046
  Epoch 10/10 [ 53.0%]  loss: 0.5151
  Epoch 10/10 [ 57.8%]  loss: 0.5146
  Epoch 10/10 [ 62.7%]  loss: 0.5092
  Epoch 10/10 [ 67.5%]  loss: 0.4867
  Epoch 10/10 [ 72.3%]  loss: 0.4902
  Epoch 10/10 [ 77.1%]  loss: 0.5251
  Epoch 10/10 [ 81.9%]  loss: 0.5129
  Epoch 10/10 [ 86.7%]  loss: 0.5250
  Epoch 10/10 [ 91.6%]  loss: 0.5089
  Epoch 10/10 [ 96.4%]  loss: 0.4941
  Epoch 10/10 [100.0%]  loss: 0.5755

Validating: 100%|██████████| 50/50 [00:03<00:00, 15.62batch/s]

Epoch 10/10
Train Loss: 0.5188 | Train F1: 0.7167
Val Loss: 1.9995 | Val F1: 0.3125
Epoch Time: 82.29s

Finalised: 1692/3776 conv1 channels zeroed (44.8%)
Saved → trained_models/pwkd_self_r50_r45/pwkd_self_r50_r45_full.pth

Warming up pwkd_self_r50_r45...
Running inference...
  ratio: 45% | F1: 0.0055 | params: 16,609,149

               Size Reduction (%)  F1 Score  Size (MB)  Latency (ms)
Pruning Ratio
20%                         13.17    0.2588       90.4          1.14
30%                         19.74    0.1981       90.4          1.13
35%                         23.08    0.0631       90.4          1.13
40%                         26.37    0.0348       90.4          1.12
45%                         29.72    0.0055       90.4          1.14