# PWKD Option 1 — Pretrained ResNet18 Student

Implements **Pruning While Knowledge Distillation** (Wang et al., 2025) using:
- **Teacher**: frozen pretrained ResNet50 (RadImageNet weights)
- **Student**: pretrained ResNet18 (RadImageNet weights), trained from a
  warm starting point rather than random initialisation

This is a cross-architecture setup. The student is smaller by design
(ResNet18 vs ResNet50), and PWKD simultaneously prunes it further and
distils knowledge from the teacher.

Produces 5 compressed models at pruning ratios [10%, 25%, 50%, 70%, 90%],
saved to `trained_models/pwkd_r18_<ratio>/` and uploaded to HuggingFace.

**Run all cells top to bottom. Requires GPU.**

In [1]:
import os, copy, subprocess
import torch

# navigate to project root
target = 'CS6423_knowledge_distillation_project'
if not os.getcwd().endswith(target):
    import sys
    os.chdir(os.path.join(os.getcwd(), target))
    if os.getcwd() not in sys.path:
        sys.path.insert(0, os.getcwd())

print(f'Working dir: {os.getcwd()}')
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device: {device}')

subprocess.run(['pip', 'install', 'PyWavelets', '--quiet'], check=True)

Working dir: /home/cor10/CS6423_knowledge_distillation_project
Device: cuda

CompletedProcess(args=['pip', 'install', 'PyWavelets', '--quiet'], returncode=0)

In [2]:
import pandas as pd
from modules.dataset_prepper import datasetPrepper

data_prep = datasetPrepper(
    dataframe_path='data/labels.csv',
    image_dir='data/test_images',
).prepare(compute_class_weights=True)

NUM_CLASSES = len(data_prep.class_names)
print(f'Classes: {NUM_CLASSES}')
print(f'Train batches: {len(data_prep.train_loader)} | Val batches: {len(data_prep.val_loader)}')

Classes: 61
Train batches: 249 | Val batches: 50

In [3]:
from modules.imagenet_loader import ImagenetLoader
from modules.evaluate_model import ModelEvaluator

loader = ImagenetLoader()

# Teacher: frozen pretrained ResNet50
teacher = loader.load_radimagenet_resnet50(
    weights_path='trained_models/resnet50_baseline_gpu_new/resnet50_baseline_gpu_new.pth',
    load_type='load'
)
teacher = teacher.to(device).eval()
for p in teacher.parameters():
    p.requires_grad = False

evaluator = ModelEvaluator(
    data_loader=data_prep.val_loader,
    class_names=data_prep.class_names,
    device=str(device),
)

teacher_metrics = evaluator.evaluate_single(teacher, 'ResNet50_teacher')
print(f'Teacher F1: {teacher_metrics["f1_macro"]:.4f}')
print(f'Teacher params: {teacher_metrics["total_parameters"]:,}')

Warming up ResNet50_teacher...
Running inference...
Teacher F1: 0.4867
Teacher params: 23,633,021

In [4]:
# Student baseline: pretrained ResNet18 before any PWKD
# This gives us a warm starting point (F1 ~ 0.4) rather than random init
loader.load_radimagenet_resnet18(
    weights_path='trained_models/resnet18_baseline_gpu_new/resnet18_baseline_gpu_new.pth',
    load_type='load'
)
# loader.freeze_backbone()
student_base = loader.model
student_base = student_base.to(device)

baseline_metrics = evaluator.evaluate_single(student_base, 'ResNet18_pretrained_baseline')
BASELINE_PARAMS  = baseline_metrics['total_parameters']
print(f'ResNet18 pretrained baseline F1:    {baseline_metrics["f1_macro"]:.4f}')
print(f'ResNet18 pretrained baseline params: {BASELINE_PARAMS:,}')

Warming up ResNet18_pretrained_baseline...
Running inference...
ResNet18 pretrained baseline F1:    0.4054
ResNet18 pretrained baseline params: 11,207,805

## Channel count reference

ResNet18 and ResNet50 have different channel widths at each stage, so the
wavelet alignment modules need a 1×1 projection to match teacher → student:

| Stage   | ResNet50 (teacher) | ResNet18 (student) |
|---------|-------------------|-------------------|
| layer2  | 512               | 128               |
| layer3  | 1024              | 256               |
| layer4  | 2048              | 512               |

In [5]:
import torch.nn as nn
import copy
from modules.model_trainer import modelTrainer
from modules.evaluate_model import ModelEvaluator
# from pwkd import PWKDLoss, make_aux_fn, finalise_student
import importlib, pwkd
# importlib.reload(pwkd)
from pwkd.pwkd import PWKDLoss, make_aux_fn, finalise_student

TEACHER_CHANNELS = {'layer2': 512,  'layer3': 1024, 'layer4': 2048}
STUDENT_CHANNELS = {'layer2': 128,  'layer3': 256,  'layer4': 512}

PRUNING_RATIOS = [0, 0.05, 0.10, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.50, 0.70, 0.90]
NUM_EPOCHS     = 10
# LAM            = 0.2
KD_TEMP        = 4.0
SPARSE_WEIGHT  = 5e-4

LAM            = 0.5    # increase KD weight so teacher signal is stronger
# SPARSE_WEIGHT  = 0.0    # 0 ratio so no point having sparsity penalty
learn_rate     = 1e-4   # much lower — fine-tuning a pretrained model

evaluator = ModelEvaluator(
    data_loader=data_prep.val_loader,
    class_names=data_prep.class_names,
    device=str(device),
)




pwkd_metrics = []

print(f'Teacher F1: {teacher_metrics["f1_macro"]:.4f}')
print(f'Teacher params: {teacher_metrics["total_parameters"]:,}')

print(f'ResNet18 pretrained baseline F1:    {baseline_metrics["f1_macro"]:.4f}')
print(f'ResNet18 pretrained baseline params: {BASELINE_PARAMS:,}')


for ratio in PRUNING_RATIOS:
    label = f'pwkd_r18_r{int(ratio * 100)}'
    print(f'\n{"="*60}')
    print(f'  PWKD Option 1 (ResNet18) — pruning ratio {ratio:.0%}')
    print(f'{"="*60}')

    # Each ratio starts from the same pretrained weights
    student = copy.deepcopy(student_base).to(device)
    for p in student.parameters():
        p.requires_grad = True
        
    
    # reset teacher each experiment
    teacher_copy = copy.deepcopy(teacher).to(device)
    teacher_copy.eval()
    

        
    pwkd_loss = PWKDLoss(
        student          = student,
        teacher          = teacher_copy,
        pruning_ratio    = ratio,
        teacher_channels = TEACHER_CHANNELS,
        student_channels = STUDENT_CHANNELS,
        class_weights    = data_prep.class_weights.to(device)
                           if data_prep.class_weights is not None else None,
        lam              = LAM,
        kd_temp          = KD_TEMP,
        sparse_weight    = 0 if ratio == 0 else SPARSE_WEIGHT,
    ).to(device)

    trainer = modelTrainer(
        model      = student,
        data_prep  = data_prep,
        device     = device,
        # learn_rate = 5e-4,
        learn_rate = learn_rate,
        num_epochs = NUM_EPOCHS,
        model_name = label,
    )
    trainer.loss_fn   = pwkd_loss
    trainer.optimizer = torch.optim.AdamW(
        list(student.parameters()) + list(pwkd_loss.parameters()),
        lr=learn_rate, weight_decay=1e-4,
    )
    trainer.create_classnum_to_label_map(data_prep.class_names)
    trainer.train_all(save_as_object=True, aux_forward_fn=make_aux_fn(teacher_copy), pwkd=True)

    student = finalise_student(student, pwkd_loss, data_prep.train_loader, device)

    # Save
    import os
    save_dir = os.path.join('trained_models', label)
    os.makedirs(save_dir, exist_ok=True)
    torch.save({'model': student, 'epoch': NUM_EPOCHS},
               os.path.join(save_dir, f'{label}_full.pth'))
    print(f'Saved → {save_dir}/{label}_full.pth')

    # Evaluate
    student.eval()
    metrics = evaluator.evaluate_single(student, label)

    pwkd_metrics.append({
        'Pruning Ratio':      f'{int(ratio*100)}%',
        'Size Reduction (%)': round((BASELINE_PARAMS - metrics['total_parameters'])
                                    / BASELINE_PARAMS * 100, 2),
        'F1 Score':           round(metrics['f1_macro'],     4),
        'Size (MB)':          round(metrics['model_size_mb'], 1),
        'Latency (ms)':       round(metrics['avg_latency_ms'], 2),
    })
    print(f'  ratio {ratio:.0%} | F1: {metrics["f1_macro"]:.4f} | '
          f'params: {metrics["total_parameters"]:,} | '
          f'latency: {metrics["avg_latency_ms"]:.2f}ms')

summary_df = pd.DataFrame(pwkd_metrics).set_index('Pruning Ratio')
print('\nPWKD Option 1 (ResNet18) — Results')
display(summary_df)

Teacher F1: 0.4867
Teacher params: 23,633,021
ResNet18 pretrained baseline F1:    0.4054
ResNet18 pretrained baseline params: 11,207,805

============================================================
  PWKD Option 1 (ResNet18) — pruning ratio 0%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:34<00:00,  7.20batch/s, loss=1.58]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.11batch/s]

Epoch 1/10
Train Loss: 1.3073 | Train F1: 0.6374
Val Loss: 1.5710 | Val F1: 0.4002
Epoch Time: 37.34s

Epoch 2/10: 100%|██████████| 249/249 [00:34<00:00,  7.14batch/s, loss=0.821]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.09batch/s]

Epoch 2/10
Train Loss: 0.9745 | Train F1: 0.7004
Val Loss: 1.5115 | Val F1: 0.4071
Epoch Time: 37.65s

Epoch 3/10: 100%|██████████| 249/249 [00:34<00:00,  7.31batch/s, loss=1.3]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.18batch/s]

Epoch 3/10
Train Loss: 0.8782 | Train F1: 0.7293
Val Loss: 1.5184 | Val F1: 0.3962
Epoch Time: 36.83s

Epoch 4/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=1.03]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.13batch/s]

Epoch 4/10
Train Loss: 0.8040 | Train F1: 0.7483
Val Loss: 1.4857 | Val F1: 0.4210
Epoch Time: 37.69s

Epoch 5/10: 100%|██████████| 249/249 [00:34<00:00,  7.14batch/s, loss=1.45]
Validating: 100%|██████████| 50/50 [00:02<00:00, 19.12batch/s]

Epoch 5/10
Train Loss: 0.7509 | Train F1: 0.7640
Val Loss: 1.5280 | Val F1: 0.4105
Epoch Time: 37.50s

Epoch 6/10: 100%|██████████| 249/249 [00:34<00:00,  7.11batch/s, loss=0.771]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.00batch/s]

Epoch 6/10
Train Loss: 0.7260 | Train F1: 0.7821
Val Loss: 1.4471 | Val F1: 0.4172
Epoch Time: 37.79s

Epoch 7/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=0.82]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.07batch/s]

Epoch 7/10
Train Loss: 0.6969 | Train F1: 0.7796
Val Loss: 1.4900 | Val F1: 0.4243
Epoch Time: 37.75s

Epoch 8/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=0.652]
Validating: 100%|██████████| 50/50 [00:02<00:00, 19.19batch/s]

Epoch 8/10
Train Loss: 0.6815 | Train F1: 0.7904
Val Loss: 1.4879 | Val F1: 0.4204
Epoch Time: 37.53s

Epoch 9/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=1.25]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.88batch/s]

Epoch 9/10
Train Loss: 0.6612 | Train F1: 0.8014
Val Loss: 1.5126 | Val F1: 0.4288
Epoch Time: 37.75s

Epoch 10/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=0.605]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.96batch/s]

Epoch 10/10
Train Loss: 0.6565 | Train F1: 0.7931
Val Loss: 1.4706 | Val F1: 0.4340
Epoch Time: 37.71s

Finalised: 8/1920 conv1 channels zeroed (0.4%)
Saved → trained_models/pwkd_r18_r0/pwkd_r18_r0_full.pth

Warming up pwkd_r18_r0...
Running inference...
  ratio 0% | F1: 0.4250 | params: 11,177,277 | latency: 0.39ms

============================================================
  PWKD Option 1 (ResNet18) — pruning ratio 5%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:34<00:00,  7.30batch/s, loss=1.11]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.11batch/s]

Epoch 1/10
Train Loss: 1.3155 | Train F1: 0.6344
Val Loss: 1.5995 | Val F1: 0.3743
Epoch Time: 36.89s

Epoch 2/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=0.901]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.95batch/s]

Epoch 2/10
Train Loss: 0.9478 | Train F1: 0.7035
Val Loss: 1.4933 | Val F1: 0.4109
Epoch Time: 37.70s

Epoch 3/10: 100%|██████████| 249/249 [00:34<00:00,  7.30batch/s, loss=1.05]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.85batch/s]

Epoch 3/10
Train Loss: 0.8646 | Train F1: 0.7342
Val Loss: 1.5256 | Val F1: 0.4065
Epoch Time: 36.91s

Epoch 4/10: 100%|██████████| 249/249 [00:35<00:00,  7.11batch/s, loss=1.11]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.00batch/s]

Epoch 4/10
Train Loss: 0.7975 | Train F1: 0.7552
Val Loss: 1.4381 | Val F1: 0.4007
Epoch Time: 37.83s

Epoch 5/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=0.94]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.04batch/s]

Epoch 5/10
Train Loss: 0.7701 | Train F1: 0.7609
Val Loss: 1.5011 | Val F1: 0.4140
Epoch Time: 37.73s

Epoch 6/10: 100%|██████████| 249/249 [00:34<00:00,  7.30batch/s, loss=1.27]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.08batch/s]

Epoch 6/10
Train Loss: 0.7394 | Train F1: 0.7728
Val Loss: 1.4798 | Val F1: 0.4191
Epoch Time: 36.88s

Epoch 7/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=0.633]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.08batch/s]

Epoch 7/10
Train Loss: 0.7031 | Train F1: 0.7835
Val Loss: 1.5052 | Val F1: 0.4104
Epoch Time: 37.71s

Epoch 8/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=1.31]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.98batch/s]

Epoch 8/10
Train Loss: 0.7074 | Train F1: 0.7844
Val Loss: 1.5458 | Val F1: 0.4040
Epoch Time: 37.76s

Epoch 9/10: 100%|██████████| 249/249 [00:34<00:00,  7.31batch/s, loss=0.84]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.05batch/s]

Epoch 9/10
Train Loss: 0.6865 | Train F1: 0.7986
Val Loss: 1.5556 | Val F1: 0.4057
Epoch Time: 36.86s

Epoch 10/10: 100%|██████████| 249/249 [00:34<00:00,  7.32batch/s, loss=0.82]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.05batch/s]

Epoch 10/10
Train Loss: 0.6720 | Train F1: 0.8027
Val Loss: 1.4908 | Val F1: 0.4225
Epoch Time: 36.81s

Finalised: 92/1920 conv1 channels zeroed (4.8%)
Saved → trained_models/pwkd_r18_r5/pwkd_r18_r5_full.pth

Warming up pwkd_r18_r5...
Running inference...
  ratio 5% | F1: 0.3930 | params: 10,676,733 | latency: 0.39ms

============================================================
  PWKD Option 1 (ResNet18) — pruning ratio 10%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:35<00:00,  7.11batch/s, loss=1.13]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.03batch/s]

Epoch 1/10
Train Loss: 1.3246 | Train F1: 0.6323
Val Loss: 1.5641 | Val F1: 0.3763
Epoch Time: 37.82s

Epoch 2/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=1.08]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.99batch/s]

Epoch 2/10
Train Loss: 0.9796 | Train F1: 0.6983
Val Loss: 1.4805 | Val F1: 0.4071
Epoch Time: 37.69s

Epoch 3/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=1.04]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.02batch/s]

Epoch 3/10
Train Loss: 0.8789 | Train F1: 0.7317
Val Loss: 1.5251 | Val F1: 0.4011
Epoch Time: 37.70s

Epoch 4/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=1.21]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.95batch/s]

Epoch 4/10
Train Loss: 0.8065 | Train F1: 0.7498
Val Loss: 1.4666 | Val F1: 0.4096
Epoch Time: 37.72s

Epoch 5/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=1]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.05batch/s]

Epoch 5/10
Train Loss: 0.7692 | Train F1: 0.7634
Val Loss: 1.4871 | Val F1: 0.4151
Epoch Time: 37.71s

Epoch 6/10: 100%|██████████| 249/249 [00:35<00:00,  7.11batch/s, loss=1.15]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.00batch/s]

Epoch 6/10
Train Loss: 0.7469 | Train F1: 0.7707
Val Loss: 1.4994 | Val F1: 0.4139
Epoch Time: 37.80s

Epoch 7/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=1.14]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.99batch/s]

Epoch 7/10
Train Loss: 0.7245 | Train F1: 0.7848
Val Loss: 1.4873 | Val F1: 0.4142
Epoch Time: 37.73s

Epoch 8/10: 100%|██████████| 249/249 [00:35<00:00,  7.11batch/s, loss=0.846]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.02batch/s]

Epoch 8/10
Train Loss: 0.7061 | Train F1: 0.7856
Val Loss: 1.5273 | Val F1: 0.4031
Epoch Time: 37.83s

Epoch 9/10: 100%|██████████| 249/249 [00:35<00:00,  7.06batch/s, loss=0.735]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.93batch/s]

Epoch 9/10
Train Loss: 0.6824 | Train F1: 0.7961
Val Loss: 1.4948 | Val F1: 0.4206
Epoch Time: 38.06s

Epoch 10/10: 100%|██████████| 249/249 [00:35<00:00,  7.11batch/s, loss=1.17]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.93batch/s]

Epoch 10/10
Train Loss: 0.6864 | Train F1: 0.8002
Val Loss: 1.5174 | Val F1: 0.4006
Epoch Time: 37.80s

Finalised: 188/1920 conv1 channels zeroed (9.8%)
Saved → trained_models/pwkd_r18_r10/pwkd_r18_r10_full.pth

Warming up pwkd_r18_r10...
Running inference...
  ratio 10% | F1: 0.3673 | params: 10,121,469 | latency: 0.39ms

============================================================
  PWKD Option 1 (ResNet18) — pruning ratio 15%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:34<00:00,  7.28batch/s, loss=1.75]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.00batch/s]

Epoch 1/10
Train Loss: 1.3441 | Train F1: 0.6351
Val Loss: 1.5528 | Val F1: 0.3849
Epoch Time: 36.98s

Epoch 2/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=0.99]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.06batch/s]

Epoch 2/10
Train Loss: 1.0016 | Train F1: 0.7026
Val Loss: 1.4570 | Val F1: 0.3981
Epoch Time: 37.73s

Epoch 3/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=1.15]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.04batch/s]

Epoch 3/10
Train Loss: 0.8850 | Train F1: 0.7294
Val Loss: 1.4939 | Val F1: 0.4054
Epoch Time: 37.74s

Epoch 4/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=0.865]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.97batch/s]

Epoch 4/10
Train Loss: 0.8129 | Train F1: 0.7538
Val Loss: 1.4734 | Val F1: 0.4300
Epoch Time: 37.73s

Epoch 5/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=1.05]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.90batch/s]

Epoch 5/10
Train Loss: 0.7779 | Train F1: 0.7637
Val Loss: 1.4969 | Val F1: 0.4194
Epoch Time: 37.73s

Epoch 6/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=0.923]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.99batch/s]

Epoch 6/10
Train Loss: 0.7531 | Train F1: 0.7758
Val Loss: 1.4845 | Val F1: 0.4300
Epoch Time: 37.74s

Epoch 7/10: 100%|██████████| 249/249 [00:35<00:00,  7.10batch/s, loss=0.838]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.96batch/s]

Epoch 7/10
Train Loss: 0.7337 | Train F1: 0.7827
Val Loss: 1.5259 | Val F1: 0.4291
Epoch Time: 37.85s

Epoch 8/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=0.644]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.99batch/s]

Epoch 8/10
Train Loss: 0.7070 | Train F1: 0.7985
Val Loss: 1.5020 | Val F1: 0.4183
Epoch Time: 37.75s

Epoch 9/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=0.836]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.97batch/s]

Epoch 9/10
Train Loss: 0.6767 | Train F1: 0.7966
Val Loss: 1.5399 | Val F1: 0.4039
Epoch Time: 37.78s

Epoch 10/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=0.735]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.05batch/s]

Epoch 10/10
Train Loss: 0.6720 | Train F1: 0.7992
Val Loss: 1.4892 | Val F1: 0.4295
Epoch Time: 37.72s

Finalised: 284/1920 conv1 channels zeroed (14.8%)
Saved → trained_models/pwkd_r18_r15/pwkd_r18_r15_full.pth

Warming up pwkd_r18_r15...
Running inference...
  ratio 15% | F1: 0.3140 | params: 9,578,301 | latency: 0.39ms

============================================================
  PWKD Option 1 (ResNet18) — pruning ratio 20%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=0.906]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.06batch/s]

Epoch 1/10
Train Loss: 1.3307 | Train F1: 0.6266
Val Loss: 1.5371 | Val F1: 0.3957
Epoch Time: 37.73s

Epoch 2/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=1.04]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.99batch/s]

Epoch 2/10
Train Loss: 0.9937 | Train F1: 0.6972
Val Loss: 1.5218 | Val F1: 0.4124
Epoch Time: 37.76s

Epoch 3/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=1.14]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.97batch/s]

Epoch 3/10
Train Loss: 0.8884 | Train F1: 0.7292
Val Loss: 1.5175 | Val F1: 0.4047
Epoch Time: 37.73s

Epoch 4/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=1.02]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.05batch/s]

Epoch 4/10
Train Loss: 0.8329 | Train F1: 0.7523
Val Loss: 1.4869 | Val F1: 0.4026
Epoch Time: 37.71s

Epoch 5/10: 100%|██████████| 249/249 [00:34<00:00,  7.30batch/s, loss=0.873]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.98batch/s]

Epoch 5/10
Train Loss: 0.7895 | Train F1: 0.7656
Val Loss: 1.4926 | Val F1: 0.4224
Epoch Time: 36.89s

Epoch 6/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=0.699]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.07batch/s]

Epoch 6/10
Train Loss: 0.7483 | Train F1: 0.7836
Val Loss: 1.4957 | Val F1: 0.4228
Epoch Time: 37.69s

Epoch 7/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=0.761]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.01batch/s]

Epoch 7/10
Train Loss: 0.7456 | Train F1: 0.7782
Val Loss: 1.4671 | Val F1: 0.4135
Epoch Time: 37.73s

Epoch 8/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=0.733]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.85batch/s]

Epoch 8/10
Train Loss: 0.7223 | Train F1: 0.7866
Val Loss: 1.5192 | Val F1: 0.4228
Epoch Time: 37.72s

Epoch 9/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=0.82]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.03batch/s]

Epoch 9/10
Train Loss: 0.7052 | Train F1: 0.7892
Val Loss: 1.5325 | Val F1: 0.4079
Epoch Time: 37.74s

Epoch 10/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=0.726]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.04batch/s]

Epoch 10/10
Train Loss: 0.6923 | Train F1: 0.8007
Val Loss: 1.5027 | Val F1: 0.4344
Epoch Time: 37.78s

Finalised: 380/1920 conv1 channels zeroed (19.8%)
Saved → trained_models/pwkd_r18_r20/pwkd_r18_r20_full.pth

Warming up pwkd_r18_r20...
Running inference...
  ratio 20% | F1: 0.2998 | params: 9,023,037 | latency: 0.40ms

============================================================
  PWKD Option 1 (ResNet18) — pruning ratio 25%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=1.31]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.86batch/s]

Epoch 1/10
Train Loss: 1.3573 | Train F1: 0.6329
Val Loss: 1.5131 | Val F1: 0.3989
Epoch Time: 37.77s

Epoch 2/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=0.96]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.05batch/s]

Epoch 2/10
Train Loss: 1.0175 | Train F1: 0.7002
Val Loss: 1.5712 | Val F1: 0.3972
Epoch Time: 37.78s

Epoch 3/10: 100%|██████████| 249/249 [00:34<00:00,  7.30batch/s, loss=0.851]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.04batch/s]

Epoch 3/10
Train Loss: 0.9002 | Train F1: 0.7314
Val Loss: 1.5006 | Val F1: 0.4161
Epoch Time: 36.88s

Epoch 4/10: 100%|██████████| 249/249 [00:35<00:00,  7.11batch/s, loss=1.95]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.97batch/s]

Epoch 4/10
Train Loss: 0.8389 | Train F1: 0.7502
Val Loss: 1.5389 | Val F1: 0.4138
Epoch Time: 37.80s

Epoch 5/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=0.742]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.00batch/s]

Epoch 5/10
Train Loss: 0.7955 | Train F1: 0.7634
Val Loss: 1.4970 | Val F1: 0.4135
Epoch Time: 37.73s

Epoch 6/10: 100%|██████████| 249/249 [00:35<00:00,  7.11batch/s, loss=0.99]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.01batch/s]

Epoch 6/10
Train Loss: 0.7645 | Train F1: 0.7711
Val Loss: 1.4892 | Val F1: 0.4099
Epoch Time: 37.80s

Epoch 7/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=1.06]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.80batch/s]

Epoch 7/10
Train Loss: 0.7491 | Train F1: 0.7799
Val Loss: 1.5284 | Val F1: 0.4130
Epoch Time: 37.76s

Epoch 8/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=1.05]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.87batch/s]

Epoch 8/10
Train Loss: 0.7289 | Train F1: 0.7962
Val Loss: 1.5313 | Val F1: 0.4257
Epoch Time: 37.78s

Epoch 9/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=0.884]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.89batch/s]

Epoch 9/10
Train Loss: 0.7183 | Train F1: 0.7949
Val Loss: 1.5233 | Val F1: 0.4152
Epoch Time: 37.76s

Epoch 10/10: 100%|██████████| 249/249 [00:35<00:00,  7.09batch/s, loss=0.722]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.00batch/s]

Epoch 10/10
Train Loss: 0.6974 | Train F1: 0.8001
Val Loss: 1.5154 | Val F1: 0.4355
Epoch Time: 37.92s

Finalised: 479/1920 conv1 channels zeroed (24.9%)
Saved → trained_models/pwkd_r18_r25/pwkd_r18_r25_full.pth

Warming up pwkd_r18_r25...
Running inference...
  ratio 25% | F1: 0.2371 | params: 8,466,045 | latency: 0.39ms

============================================================
  PWKD Option 1 (ResNet18) — pruning ratio 30%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:34<00:00,  7.31batch/s, loss=1.2]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.91batch/s]

Epoch 1/10
Train Loss: 1.3784 | Train F1: 0.6280
Val Loss: 1.4918 | Val F1: 0.3846
Epoch Time: 36.85s

Epoch 2/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=1.03]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.07batch/s]

Epoch 2/10
Train Loss: 1.0150 | Train F1: 0.7006
Val Loss: 1.5150 | Val F1: 0.4074
Epoch Time: 37.74s

Epoch 3/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=1.21]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.98batch/s]

Epoch 3/10
Train Loss: 0.9333 | Train F1: 0.7368
Val Loss: 1.5258 | Val F1: 0.4038
Epoch Time: 37.75s

Epoch 4/10: 100%|██████████| 249/249 [00:35<00:00,  7.11batch/s, loss=0.936]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.00batch/s]

Epoch 4/10
Train Loss: 0.8410 | Train F1: 0.7531
Val Loss: 1.5422 | Val F1: 0.3970
Epoch Time: 37.81s

Epoch 5/10: 100%|██████████| 249/249 [00:34<00:00,  7.28batch/s, loss=1.18]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.12batch/s]

Epoch 5/10
Train Loss: 0.8170 | Train F1: 0.7599
Val Loss: 1.5400 | Val F1: 0.4085
Epoch Time: 36.96s

Epoch 6/10: 100%|██████████| 249/249 [00:34<00:00,  7.14batch/s, loss=0.838]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.06batch/s]

Epoch 6/10
Train Loss: 0.7831 | Train F1: 0.7649
Val Loss: 1.4909 | Val F1: 0.4270
Epoch Time: 37.67s

Epoch 7/10: 100%|██████████| 249/249 [00:35<00:00,  7.11batch/s, loss=0.849]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.98batch/s]

Epoch 7/10
Train Loss: 0.7485 | Train F1: 0.7799
Val Loss: 1.5025 | Val F1: 0.4183
Epoch Time: 37.81s

Epoch 8/10: 100%|██████████| 249/249 [00:35<00:00,  7.10batch/s, loss=1.24]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.83batch/s]

Epoch 8/10
Train Loss: 0.7296 | Train F1: 0.7868
Val Loss: 1.4949 | Val F1: 0.4179
Epoch Time: 37.87s

Epoch 9/10: 100%|██████████| 249/249 [00:39<00:00,  6.35batch/s, loss=1.27]
Validating: 100%|██████████| 50/50 [00:05<00:00,  8.74batch/s]

Epoch 9/10
Train Loss: 0.7219 | Train F1: 0.7903
Val Loss: 1.5403 | Val F1: 0.4076
Epoch Time: 44.97s

Epoch 10/10: 100%|██████████| 249/249 [00:45<00:00,  5.43batch/s, loss=0.641]
Validating: 100%|██████████| 50/50 [00:05<00:00,  8.71batch/s]

Epoch 10/10
Train Loss: 0.7038 | Train F1: 0.7993
Val Loss: 1.5640 | Val F1: 0.4106
Epoch Time: 51.65s

Finalised: 572/1920 conv1 channels zeroed (29.8%)
Saved → trained_models/pwkd_r18_r30/pwkd_r18_r30_full.pth

Warming up pwkd_r18_r30...
Running inference...
  ratio 30% | F1: 0.0893 | params: 7,930,365 | latency: 0.42ms

============================================================
  PWKD Option 1 (ResNet18) — pruning ratio 35%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:43<00:00,  5.66batch/s, loss=1.23]
Validating: 100%|██████████| 50/50 [00:03<00:00, 14.13batch/s]

Epoch 1/10
Train Loss: 1.3643 | Train F1: 0.6300
Val Loss: 1.5208 | Val F1: 0.3838
Epoch Time: 47.53s

Epoch 2/10: 100%|██████████| 249/249 [00:41<00:00,  6.01batch/s, loss=1.03]
Validating: 100%|██████████| 50/50 [00:04<00:00, 11.23batch/s]

Epoch 2/10
Train Loss: 1.0234 | Train F1: 0.6982
Val Loss: 1.5259 | Val F1: 0.3839
Epoch Time: 45.91s

Epoch 3/10: 100%|██████████| 249/249 [01:04<00:00,  3.86batch/s, loss=1.29]
Validating: 100%|██████████| 50/50 [00:08<00:00,  5.84batch/s]

Epoch 3/10
Train Loss: 0.9289 | Train F1: 0.7349
Val Loss: 1.4992 | Val F1: 0.4098
Epoch Time: 73.07s

Epoch 4/10: 100%|██████████| 249/249 [01:04<00:00,  3.84batch/s, loss=1.11]
Validating: 100%|██████████| 50/50 [00:04<00:00, 11.93batch/s]

Epoch 4/10
Train Loss: 0.8533 | Train F1: 0.7532
Val Loss: 1.5741 | Val F1: 0.3959
Epoch Time: 69.03s

Epoch 5/10: 100%|██████████| 249/249 [00:48<00:00,  5.13batch/s, loss=1.18]
Validating: 100%|██████████| 50/50 [00:04<00:00, 10.78batch/s]

Epoch 5/10
Train Loss: 0.8083 | Train F1: 0.7710
Val Loss: 1.4975 | Val F1: 0.3914
Epoch Time: 53.22s

Epoch 6/10: 100%|██████████| 249/249 [00:46<00:00,  5.36batch/s, loss=0.714]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.13batch/s]

Epoch 6/10
Train Loss: 0.7909 | Train F1: 0.7674
Val Loss: 1.5279 | Val F1: 0.4166
Epoch Time: 49.73s

Epoch 7/10: 100%|██████████| 249/249 [00:51<00:00,  4.80batch/s, loss=0.918]
Validating: 100%|██████████| 50/50 [00:03<00:00, 13.58batch/s]

Epoch 7/10
Train Loss: 0.7492 | Train F1: 0.7875
Val Loss: 1.5286 | Val F1: 0.4214
Epoch Time: 55.60s

Epoch 8/10: 100%|██████████| 249/249 [00:55<00:00,  4.45batch/s, loss=0.799]
Validating: 100%|██████████| 50/50 [00:03<00:00, 13.64batch/s]

Epoch 8/10
Train Loss: 0.7370 | Train F1: 0.7876
Val Loss: 1.4797 | Val F1: 0.4244
Epoch Time: 59.59s

Epoch 9/10: 100%|██████████| 249/249 [00:52<00:00,  4.73batch/s, loss=1.01]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.87batch/s]

Epoch 9/10
Train Loss: 0.7382 | Train F1: 0.7914
Val Loss: 1.4944 | Val F1: 0.4151
Epoch Time: 55.77s

Epoch 10/10: 100%|██████████| 249/249 [00:44<00:00,  5.54batch/s, loss=0.872]
Validating: 100%|██████████| 50/50 [00:02<00:00, 16.79batch/s]

Epoch 10/10
Train Loss: 0.7273 | Train F1: 0.7970
Val Loss: 1.4955 | Val F1: 0.4199
Epoch Time: 47.95s

Finalised: 668/1920 conv1 channels zeroed (34.8%)
Saved → trained_models/pwkd_r18_r35/pwkd_r18_r35_full.pth

Warming up pwkd_r18_r35...
Running inference...
  ratio 35% | F1: 0.0176 | params: 7,375,101 | latency: 0.78ms

============================================================
  PWKD Option 1 (ResNet18) — pruning ratio 40%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:45<00:00,  5.44batch/s, loss=1.32]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.74batch/s]

Epoch 1/10
Train Loss: 1.3751 | Train F1: 0.6311
Val Loss: 1.5226 | Val F1: 0.3857
Epoch Time: 48.64s

Epoch 2/10: 100%|██████████| 249/249 [00:42<00:00,  5.83batch/s, loss=1.76]
Validating: 100%|██████████| 50/50 [00:03<00:00, 14.96batch/s]

Epoch 2/10
Train Loss: 1.0346 | Train F1: 0.7058
Val Loss: 1.5145 | Val F1: 0.3974
Epoch Time: 46.05s

Epoch 3/10: 100%|██████████| 249/249 [00:38<00:00,  6.52batch/s, loss=0.996]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.27batch/s]

Epoch 3/10
Train Loss: 0.9159 | Train F1: 0.7335
Val Loss: 1.4963 | Val F1: 0.4164
Epoch Time: 41.51s

Epoch 4/10: 100%|██████████| 249/249 [00:44<00:00,  5.61batch/s, loss=0.88]
Validating: 100%|██████████| 50/50 [00:05<00:00,  9.92batch/s]

Epoch 4/10
Train Loss: 0.8643 | Train F1: 0.7440
Val Loss: 1.5382 | Val F1: 0.3987
Epoch Time: 49.46s

Epoch 5/10: 100%|██████████| 249/249 [00:48<00:00,  5.19batch/s, loss=1.38]
Validating: 100%|██████████| 50/50 [00:03<00:00, 13.74batch/s]

Epoch 5/10
Train Loss: 0.8382 | Train F1: 0.7564
Val Loss: 1.5158 | Val F1: 0.4136
Epoch Time: 51.68s

Epoch 6/10: 100%|██████████| 249/249 [00:51<00:00,  4.87batch/s, loss=0.961]
Validating: 100%|██████████| 50/50 [00:03<00:00, 14.87batch/s]

Epoch 6/10
Train Loss: 0.7947 | Train F1: 0.7807
Val Loss: 1.5116 | Val F1: 0.4064
Epoch Time: 54.54s

Epoch 7/10: 100%|██████████| 249/249 [00:43<00:00,  5.70batch/s, loss=0.819]
Validating: 100%|██████████| 50/50 [00:03<00:00, 14.46batch/s]

Epoch 7/10
Train Loss: 0.7650 | Train F1: 0.7791
Val Loss: 1.5200 | Val F1: 0.4207
Epoch Time: 47.11s

Epoch 8/10: 100%|██████████| 249/249 [00:36<00:00,  6.87batch/s, loss=0.831]
Validating: 100%|██████████| 50/50 [00:03<00:00, 15.12batch/s]

Epoch 8/10
Train Loss: 0.7532 | Train F1: 0.7890
Val Loss: 1.5164 | Val F1: 0.4080
Epoch Time: 39.58s

Epoch 9/10: 100%|██████████| 249/249 [00:44<00:00,  5.57batch/s, loss=0.968]
Validating: 100%|██████████| 50/50 [00:03<00:00, 13.91batch/s]

Epoch 9/10
Train Loss: 0.7378 | Train F1: 0.7908
Val Loss: 1.5004 | Val F1: 0.4266
Epoch Time: 48.32s

Epoch 10/10: 100%|██████████| 249/249 [00:50<00:00,  4.93batch/s, loss=0.656]
Validating: 100%|██████████| 50/50 [00:03<00:00, 14.23batch/s]

Epoch 10/10
Train Loss: 0.7132 | Train F1: 0.8024
Val Loss: 1.5070 | Val F1: 0.4085
Epoch Time: 54.03s

Finalised: 764/1920 conv1 channels zeroed (39.8%)
Saved → trained_models/pwkd_r18_r40/pwkd_r18_r40_full.pth

Warming up pwkd_r18_r40...
Running inference...
  ratio 40% | F1: 0.0104 | params: 6,831,933 | latency: 1.09ms

============================================================
  PWKD Option 1 (ResNet18) — pruning ratio 45%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:54<00:00,  4.54batch/s, loss=1.08]
Validating: 100%|██████████| 50/50 [00:03<00:00, 13.35batch/s]

Epoch 1/10
Train Loss: 1.3804 | Train F1: 0.6306
Val Loss: 1.5010 | Val F1: 0.3992
Epoch Time: 58.60s

Epoch 2/10: 100%|██████████| 249/249 [00:44<00:00,  5.64batch/s, loss=0.849]
Validating: 100%|██████████| 50/50 [00:04<00:00, 10.28batch/s]

Epoch 2/10
Train Loss: 1.0387 | Train F1: 0.6942
Val Loss: 1.5451 | Val F1: 0.3915
Epoch Time: 49.03s

Epoch 3/10: 100%|██████████| 249/249 [00:35<00:00,  6.96batch/s, loss=1.64]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.87batch/s]

Epoch 3/10
Train Loss: 0.9319 | Train F1: 0.7370
Val Loss: 1.5546 | Val F1: 0.4077
Epoch Time: 38.56s

Epoch 4/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=1.04]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.80batch/s]

Epoch 4/10
Train Loss: 0.8794 | Train F1: 0.7513
Val Loss: 1.5373 | Val F1: 0.4146
Epoch Time: 37.78s

Epoch 5/10: 100%|██████████| 249/249 [00:35<00:00,  7.11batch/s, loss=0.907]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.89batch/s]

Epoch 5/10
Train Loss: 0.8428 | Train F1: 0.7590
Val Loss: 1.5446 | Val F1: 0.4030
Epoch Time: 37.85s

Epoch 6/10: 100%|██████████| 249/249 [00:35<00:00,  7.10batch/s, loss=1.06]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.93batch/s]

Epoch 6/10
Train Loss: 0.8085 | Train F1: 0.7717
Val Loss: 1.5235 | Val F1: 0.4144
Epoch Time: 37.85s

Epoch 7/10: 100%|██████████| 249/249 [00:34<00:00,  7.11batch/s, loss=1.23]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.99batch/s]

Epoch 7/10
Train Loss: 0.7734 | Train F1: 0.7798
Val Loss: 1.4721 | Val F1: 0.4208
Epoch Time: 37.79s

Epoch 8/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=1.12]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.94batch/s]

Epoch 8/10
Train Loss: 0.7596 | Train F1: 0.7900
Val Loss: 1.5099 | Val F1: 0.4068
Epoch Time: 37.76s

Epoch 9/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=1.08]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.05batch/s]

Epoch 9/10
Train Loss: 0.7488 | Train F1: 0.8017
Val Loss: 1.5410 | Val F1: 0.4099
Epoch Time: 37.71s

Epoch 10/10: 100%|██████████| 249/249 [00:34<00:00,  7.31batch/s, loss=0.981]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.99batch/s]

Epoch 10/10
Train Loss: 0.7258 | Train F1: 0.8020
Val Loss: 1.4837 | Val F1: 0.4339
Epoch Time: 36.87s

Finalised: 860/1920 conv1 channels zeroed (44.8%)
Saved → trained_models/pwkd_r18_r45/pwkd_r18_r45_full.pth

Warming up pwkd_r18_r45...
Running inference...
  ratio 45% | F1: 0.0010 | params: 6,276,669 | latency: 0.39ms

============================================================
  PWKD Option 1 (ResNet18) — pruning ratio 50%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=1.37]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.99batch/s]

Epoch 1/10
Train Loss: 1.4031 | Train F1: 0.6314
Val Loss: 1.5587 | Val F1: 0.3880
Epoch Time: 37.73s

Epoch 2/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=1.38]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.98batch/s]

Epoch 2/10
Train Loss: 1.0444 | Train F1: 0.7070
Val Loss: 1.5200 | Val F1: 0.4113
Epoch Time: 37.74s

Epoch 3/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=0.897]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.01batch/s]

Epoch 3/10
Train Loss: 0.9552 | Train F1: 0.7352
Val Loss: 1.4864 | Val F1: 0.4055
Epoch Time: 37.78s

Epoch 4/10: 100%|██████████| 249/249 [00:34<00:00,  7.13batch/s, loss=1.06]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.05batch/s]

Epoch 4/10
Train Loss: 0.9014 | Train F1: 0.7458
Val Loss: 1.4730 | Val F1: 0.4228
Epoch Time: 37.72s

Epoch 5/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=1.01]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.99batch/s]

Epoch 5/10
Train Loss: 0.8225 | Train F1: 0.7710
Val Loss: 1.4553 | Val F1: 0.4252
Epoch Time: 37.74s

Epoch 6/10: 100%|██████████| 249/249 [00:35<00:00,  7.11batch/s, loss=1.16]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.91batch/s]

Epoch 6/10
Train Loss: 0.7990 | Train F1: 0.7773
Val Loss: 1.5141 | Val F1: 0.4256
Epoch Time: 37.82s

Epoch 7/10: 100%|██████████| 249/249 [00:35<00:00,  7.11batch/s, loss=1.39]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.00batch/s]

Epoch 7/10
Train Loss: 0.7870 | Train F1: 0.7849
Val Loss: 1.5150 | Val F1: 0.4121
Epoch Time: 37.79s

Epoch 8/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=0.689]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.00batch/s]

Epoch 8/10
Train Loss: 0.7634 | Train F1: 0.7942
Val Loss: 1.5219 | Val F1: 0.4096
Epoch Time: 37.77s

Epoch 9/10: 100%|██████████| 249/249 [00:35<00:00,  7.11batch/s, loss=1.39]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.02batch/s]

Epoch 9/10
Train Loss: 0.7515 | Train F1: 0.7943
Val Loss: 1.5006 | Val F1: 0.4221
Epoch Time: 37.80s

Epoch 10/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=1.48]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.00batch/s]

Epoch 10/10
Train Loss: 0.7583 | Train F1: 0.7969
Val Loss: 1.4864 | Val F1: 0.4261
Epoch Time: 37.77s

Finalised: 960/1920 conv1 channels zeroed (50.0%)
Saved → trained_models/pwkd_r18_r50/pwkd_r18_r50_full.pth

Warming up pwkd_r18_r50...
Running inference...
  ratio 50% | F1: 0.0015 | params: 5,715,069 | latency: 0.39ms

============================================================
  PWKD Option 1 (ResNet18) — pruning ratio 70%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:34<00:00,  7.28batch/s, loss=1.54]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.95batch/s]

Epoch 1/10
Train Loss: 1.4330 | Train F1: 0.6329
Val Loss: 1.5114 | Val F1: 0.3928
Epoch Time: 36.99s

Epoch 2/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=1.07]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.04batch/s]

Epoch 2/10
Train Loss: 1.0967 | Train F1: 0.6954
Val Loss: 1.5418 | Val F1: 0.3940
Epoch Time: 37.77s

Epoch 3/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=1.24]
Validating: 100%|██████████| 50/50 [00:03<00:00, 16.22batch/s]

Epoch 3/10
Train Loss: 0.9669 | Train F1: 0.7358
Val Loss: 1.5235 | Val F1: 0.4041
Epoch Time: 38.07s

Epoch 4/10: 100%|██████████| 249/249 [00:35<00:00,  7.11batch/s, loss=1.19]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.00batch/s]

Epoch 4/10
Train Loss: 0.9338 | Train F1: 0.7415
Val Loss: 1.5131 | Val F1: 0.4229
Epoch Time: 37.80s

Epoch 5/10: 100%|██████████| 249/249 [00:35<00:00,  7.11batch/s, loss=1.18]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.88batch/s]

Epoch 5/10
Train Loss: 0.8700 | Train F1: 0.7587
Val Loss: 1.4506 | Val F1: 0.4132
Epoch Time: 37.83s

Epoch 6/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=1.04]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.06batch/s]

Epoch 6/10
Train Loss: 0.8479 | Train F1: 0.7737
Val Loss: 1.4766 | Val F1: 0.4232
Epoch Time: 37.76s

Epoch 7/10: 100%|██████████| 249/249 [00:35<00:00,  7.11batch/s, loss=0.722]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.07batch/s]

Epoch 7/10
Train Loss: 0.8204 | Train F1: 0.7816
Val Loss: 1.4839 | Val F1: 0.4211
Epoch Time: 37.80s

Epoch 8/10: 100%|██████████| 249/249 [00:35<00:00,  7.09batch/s, loss=1.56]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.07batch/s]

Epoch 8/10
Train Loss: 0.8045 | Train F1: 0.7904
Val Loss: 1.4674 | Val F1: 0.4360
Epoch Time: 37.88s

Epoch 9/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=0.986]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.98batch/s]

Epoch 9/10
Train Loss: 0.8001 | Train F1: 0.7958
Val Loss: 1.5569 | Val F1: 0.4155
Epoch Time: 37.75s

Epoch 10/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=1.11]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.93batch/s]

Epoch 10/10
Train Loss: 0.7838 | Train F1: 0.7929
Val Loss: 1.4799 | Val F1: 0.4230
Epoch Time: 37.78s

Finalised: 1340/1920 conv1 channels zeroed (69.8%)
Saved → trained_models/pwkd_r18_r70/pwkd_r18_r70_full.pth

Warming up pwkd_r18_r70...
Running inference...
  ratio 70% | F1: 0.0002 | params: 3,530,301 | latency: 0.39ms

============================================================
  PWKD Option 1 (ResNet18) — pruning ratio 90%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:35<00:00,  7.10batch/s, loss=1.52]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.88batch/s]

Epoch 1/10
Train Loss: 1.4718 | Train F1: 0.6251
Val Loss: 1.5136 | Val F1: 0.3938
Epoch Time: 37.88s

Epoch 2/10: 100%|██████████| 249/249 [00:34<00:00,  7.30batch/s, loss=1.26]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.00batch/s]

Epoch 2/10
Train Loss: 1.0911 | Train F1: 0.7058
Val Loss: 1.6246 | Val F1: 0.3744
Epoch Time: 36.92s

Epoch 3/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=1.19]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.97batch/s]

Epoch 3/10
Train Loss: 1.0177 | Train F1: 0.7350
Val Loss: 1.5109 | Val F1: 0.4052
Epoch Time: 37.76s

Epoch 4/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=0.891]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.89batch/s]

Epoch 4/10
Train Loss: 0.9454 | Train F1: 0.7486
Val Loss: 1.4941 | Val F1: 0.4223
Epoch Time: 37.80s

Epoch 5/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=1.25]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.00batch/s]

Epoch 5/10
Train Loss: 0.9082 | Train F1: 0.7696
Val Loss: 1.5332 | Val F1: 0.4071
Epoch Time: 37.78s

Epoch 6/10: 100%|██████████| 249/249 [00:34<00:00,  7.31batch/s, loss=0.794]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.95batch/s]

Epoch 6/10
Train Loss: 0.8654 | Train F1: 0.7767
Val Loss: 1.5357 | Val F1: 0.4099
Epoch Time: 36.86s

Epoch 7/10: 100%|██████████| 249/249 [00:35<00:00,  7.09batch/s, loss=1.64]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.00batch/s]

Epoch 7/10
Train Loss: 0.8644 | Train F1: 0.7746
Val Loss: 1.5171 | Val F1: 0.4122
Epoch Time: 37.92s

Epoch 8/10: 100%|██████████| 249/249 [00:35<00:00,  7.11batch/s, loss=1.05]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.97batch/s]

Epoch 8/10
Train Loss: 0.8436 | Train F1: 0.7852
Val Loss: 1.5304 | Val F1: 0.4190
Epoch Time: 37.81s

Epoch 9/10: 100%|██████████| 249/249 [00:35<00:00,  7.10batch/s, loss=0.818]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.92batch/s]

Epoch 9/10
Train Loss: 0.8210 | Train F1: 0.7977
Val Loss: 1.5137 | Val F1: 0.4201
Epoch Time: 37.85s

Epoch 10/10: 100%|██████████| 249/249 [00:34<00:00,  7.12batch/s, loss=0.751]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.04batch/s]

Epoch 10/10
Train Loss: 0.8109 | Train F1: 0.7969
Val Loss: 1.4725 | Val F1: 0.4380
Epoch Time: 37.73s

Finalised: 1724/1920 conv1 channels zeroed (89.8%)
Saved → trained_models/pwkd_r18_r90/pwkd_r18_r90_full.pth

Warming up pwkd_r18_r90...
Running inference...
  ratio 90% | F1: 0.0003 | params: 1,339,197 | latency: 0.39ms

PWKD Option 1 (ResNet18) — Results

               Size Reduction (%)  F1 Score  Size (MB)  Latency (ms)
Pruning Ratio
0%                           0.27    0.4250       42.8          0.39
5%                           4.74    0.3930       42.8          0.39
10%                          9.69    0.3673       42.8          0.39
15%                         14.54    0.3140       42.8          0.39
20%                         19.49    0.2998       42.8          0.40
25%                         24.46    0.2371       42.8          0.39
30%                         29.24    0.0893       42.8          0.42
35%                         34.20    0.0176       42.8          0.78
40%                         39.04    0.0104       42.8          1.09
45%                         44.00    0.0010       42.8          0.39
50%                         49.01    0.0015       42.8          0.39
70%                         68.50    0.0002       42.8          0.39
90%                         88.05    0.0003       42.8          0.39

<!-- # only run this cell if not running the previous cell

import torch.nn as nn
import copy
from modules.model_trainer import modelTrainer
from modules.evaluate_model import ModelEvaluator
# from pwkd import PWKDLoss, make_aux_fn, finalise_student
import importlib, pwkd
importlib.reload(pwkd)
from pwkd import PWKDLoss, make_aux_fn, finalise_student

TEACHER_CHANNELS = {'layer2': 512,  'layer3': 1024, 'layer4': 2048}
STUDENT_CHANNELS = {'layer2': 128,  'layer3': 256,  'layer4': 512}

PRUNING_RATIOS = [0.10, 0.25, 0.50, 0.70, 0.90]
NUM_EPOCHS     = 10
LAM            = 0.2
KD_TEMP        = 4.0
SPARSE_WEIGHT  = 1e-4

evaluator = ModelEvaluator(
    data_loader=data_prep.val_loader,
    class_names=data_prep.class_names,
    device=str(device),
)




pwkd_metrics = [] -->

In [12]:
# # ── Extra ratios to better capture the Pareto curve descent ──────────────────
# # Run this cell independently — existing trained models are not affected.

# EXTRA_RATIOS = [0.2, 0.3, 0.35, 0.40, 0.45]   # between the good and collapsed points

# # for ratio in EXTRA_RATIOS:
#     label = f'pwkd_r18_r{int(ratio * 100)}'
#     print(f'\n{"="*60}')
#     print(f'  PWKD Option 1 (ResNet18) — pruning ratio {ratio:.0%}')
#     print(f'{"="*60}')

#     student = copy.deepcopy(student_base).to(device)
#     for p in student.parameters():
#         p.requires_grad = True

#     pwkd_loss = PWKDLoss(
#         student          = student,
#         teacher          = teacher,
#         pruning_ratio    = ratio,
#         teacher_channels = TEACHER_CHANNELS,
#         student_channels = STUDENT_CHANNELS,
#         class_weights    = data_prep.class_weights.to(device)
#                            if data_prep.class_weights is not None else None,
#         lam              = LAM,
#         kd_temp          = KD_TEMP,
#         sparse_weight    = SPARSE_WEIGHT,
#     ).to(device)

#     trainer = modelTrainer(
#         model      = student,
#         data_prep  = data_prep,
#         device     = device,
#         learn_rate = 5e-4,
#         num_epochs = NUM_EPOCHS,
#         model_name = label,
#     )
#     trainer.loss_fn   = pwkd_loss
#     trainer.optimizer = torch.optim.AdamW(
#         list(student.parameters()) + list(pwkd_loss.parameters()),
#         lr=5e-4, weight_decay=1e-2,
#     )
#     trainer.create_classnum_to_label_map(data_prep.class_names)
#     trainer.train_all(save_as_object=True, aux_forward_fn=make_aux_fn(teacher), pwkd=True)

#     student = finalise_student(student, pwkd_loss, data_prep.train_loader, device)

#     save_dir = os.path.join('trained_models', label)
#     os.makedirs(save_dir, exist_ok=True)
#     torch.save({'model': student, 'epoch': NUM_EPOCHS},
#                os.path.join(save_dir, f'{label}_full.pth'))
#     print(f'Saved → {save_dir}/{label}_full.pth')

#     student.eval()
#     metrics = evaluator.evaluate_single(student, label)

#     pwkd_metrics.append({
#         'Pruning Ratio':      f'{int(ratio*100)}%',
#         'Size Reduction (%)': round((BASELINE_PARAMS - metrics['total_parameters'])
#                                     / BASELINE_PARAMS * 100, 2),
#         'F1 Score':           round(metrics['f1_macro'],     4),
#         'Size (MB)':          round(metrics['model_size_mb'], 1),
#         'Latency (ms)':       round(metrics['avg_latency_ms'], 2),
#     })
#     print(f'  ratio {ratio:.0%} | F1: {metrics["f1_macro"]:.4f} | '
#           f'params: {metrics["total_parameters"]:,}')

# summary_df = pd.DataFrame(pwkd_metrics).set_index('Pruning Ratio')
# display(summary_df)

In [6]:
print('\nPWKD Option 1 (ResNet18) — Results')
display(summary_df)

PWKD Option 1 (ResNet18) — Results

               Size Reduction (%)  F1 Score  Size (MB)  Latency (ms)
Pruning Ratio
0%                           0.27    0.4250       42.8          0.39
5%                           4.74    0.3930       42.8          0.39
10%                          9.69    0.3673       42.8          0.39
15%                         14.54    0.3140       42.8          0.39
20%                         19.49    0.2998       42.8          0.40
25%                         24.46    0.2371       42.8          0.39
30%                         29.24    0.0893       42.8          0.42
35%                         34.20    0.0176       42.8          0.78
40%                         39.04    0.0104       42.8          1.09
45%                         44.00    0.0010       42.8          0.39
50%                         49.01    0.0015       42.8          0.39
70%                         68.50    0.0002       42.8          0.39
90%                         88.05    0.0003       42.8          0.39