# PWKD Option 1 — Pretrained ResNet18 Student

Implements **Pruning While Knowledge Distillation** (Wang et al., 2025) using:
- **Teacher**: frozen pretrained ResNet50 (RadImageNet weights)
- **Student**: pretrained ResNet18 (RadImageNet weights), trained from a
  warm starting point rather than random initialisation

This is a cross-architecture setup. The student is smaller by design
(ResNet18 vs ResNet50), and PWKD simultaneously prunes it further and
distils knowledge from the teacher.

Produces 5 compressed models at pruning ratios [10%, 25%, 50%, 70%, 90%],
saved to `trained_models/pwkd_r18_<ratio>/` and uploaded to HuggingFace.

**Run all cells top to bottom. Requires GPU.**

In [1]:
import os, copy, subprocess
import torch

# navigate to project root
target = 'CS6423_knowledge_distillation_project'
if not os.getcwd().endswith(target):
    import sys
    os.chdir(os.path.join(os.getcwd(), target))
    if os.getcwd() not in sys.path:
        sys.path.insert(0, os.getcwd())

print(f'Working dir: {os.getcwd()}')
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device: {device}')

subprocess.run(['pip', 'install', 'PyWavelets', '--quiet'], check=True)

Working dir: /home/cor10/CS6423_knowledge_distillation_project
Device: cuda

CompletedProcess(args=['pip', 'install', 'PyWavelets', '--quiet'], returncode=0)

In [2]:
import pandas as pd
from modules.dataset_prepper import datasetPrepper

data_prep = datasetPrepper(
    dataframe_path='data/labels.csv',
    image_dir='data/test_images',
).prepare(compute_class_weights=True)

NUM_CLASSES = len(data_prep.class_names)
print(f'Classes: {NUM_CLASSES}')
print(f'Train batches: {len(data_prep.train_loader)} | Val batches: {len(data_prep.val_loader)}')

Classes: 61
Train batches: 249 | Val batches: 50

In [3]:
from modules.imagenet_loader import ImagenetLoader
from modules.evaluate_model import ModelEvaluator

loader = ImagenetLoader()

# Teacher: frozen pretrained ResNet50
teacher = loader.load_radimagenet_resnet50(
    weights_path='trained_models/resnet50_baseline_gpu_new/resnet50_baseline_gpu_new.pth',
    load_type='load'
)
teacher = teacher.to(device).eval()
for p in teacher.parameters():
    p.requires_grad = False

evaluator = ModelEvaluator(
    data_loader=data_prep.val_loader,
    class_names=data_prep.class_names,
    device=str(device),
)

teacher_metrics = evaluator.evaluate_single(teacher, 'ResNet50_teacher')
print(f'Teacher F1: {teacher_metrics["f1_macro"]:.4f}')
print(f'Teacher params: {teacher_metrics["total_parameters"]:,}')

Warming up ResNet50_teacher...
Running inference...
Teacher F1: 0.4867
Teacher params: 23,633,021

In [4]:
# Student baseline: pretrained ResNet18 before any PWKD
# This gives us a warm starting point (F1 ~ 0.4) rather than random init
student_base = loader.load_radimagenet_resnet18(
    weights_path='trained_models/resnet18_baseline_gpu_new/resnet18_baseline_gpu_new.pth',
    load_type='load'
)
student_base = student_base.to(device)

baseline_metrics = evaluator.evaluate_single(student_base, 'ResNet18_pretrained_baseline')
BASELINE_PARAMS  = baseline_metrics['total_parameters']
print(f'ResNet18 pretrained baseline F1:    {baseline_metrics["f1_macro"]:.4f}')
print(f'ResNet18 pretrained baseline params: {BASELINE_PARAMS:,}')

Warming up ResNet18_pretrained_baseline...
Running inference...
ResNet18 pretrained baseline F1:    0.4054
ResNet18 pretrained baseline params: 11,207,805

## Channel count reference

ResNet18 and ResNet50 have different channel widths at each stage, so the
wavelet alignment modules need a 1×1 projection to match teacher → student:

| Stage   | ResNet50 (teacher) | ResNet18 (student) |
|---------|-------------------|-------------------|
| layer2  | 512               | 128               |
| layer3  | 1024              | 256               |
| layer4  | 2048              | 512               |

In [5]:
import torch.nn as nn
import copy
from modules.model_trainer import modelTrainer
from modules.evaluate_model import ModelEvaluator
# from pwkd import PWKDLoss, make_aux_fn, finalise_student
import importlib, pwkd
importlib.reload(pwkd)
from pwkd import PWKDLoss, make_aux_fn, finalise_student

TEACHER_CHANNELS = {'layer2': 512,  'layer3': 1024, 'layer4': 2048}
STUDENT_CHANNELS = {'layer2': 128,  'layer3': 256,  'layer4': 512}

PRUNING_RATIOS = [0.10, 0.25, 0.50, 0.70, 0.90]
NUM_EPOCHS     = 10
LAM            = 0.2
KD_TEMP        = 4.0
SPARSE_WEIGHT  = 1e-4

evaluator = ModelEvaluator(
    data_loader=data_prep.val_loader,
    class_names=data_prep.class_names,
    device=str(device),
)




pwkd_metrics = []

print(f'Teacher F1: {teacher_metrics["f1_macro"]:.4f}')
print(f'Teacher params: {teacher_metrics["total_parameters"]:,}')

print(f'ResNet18 pretrained baseline F1:    {baseline_metrics["f1_macro"]:.4f}')
print(f'ResNet18 pretrained baseline params: {BASELINE_PARAMS:,}')


for ratio in PRUNING_RATIOS:
    label = f'pwkd_r18_r{int(ratio * 100)}'
    print(f'\n{"="*60}')
    print(f'  PWKD Option 1 (ResNet18) — pruning ratio {ratio:.0%}')
    print(f'{"="*60}')

    # Each ratio starts from the same pretrained weights
    student = copy.deepcopy(student_base).to(device)
    for p in student.parameters():
        p.requires_grad = True

    pwkd_loss = PWKDLoss(
        student          = student,
        teacher          = teacher,
        pruning_ratio    = ratio,
        teacher_channels = TEACHER_CHANNELS,
        student_channels = STUDENT_CHANNELS,
        class_weights    = data_prep.class_weights.to(device)
                           if data_prep.class_weights is not None else None,
        lam              = LAM,
        kd_temp          = KD_TEMP,
        sparse_weight    = SPARSE_WEIGHT,
    ).to(device)

    trainer = modelTrainer(
        model      = student,
        data_prep  = data_prep,
        device     = device,
        learn_rate = 5e-4,
        num_epochs = NUM_EPOCHS,
        model_name = label,
    )
    trainer.loss_fn   = pwkd_loss
    trainer.optimizer = torch.optim.AdamW(
        list(student.parameters()) + list(pwkd_loss.parameters()),
        lr=5e-4, weight_decay=1e-2,
    )
    trainer.create_classnum_to_label_map(data_prep.class_names)
    trainer.train_all(save_as_object=True, aux_forward_fn=make_aux_fn(teacher), pwkd=True)

    student = finalise_student(student, pwkd_loss, data_prep.train_loader, device)

    # Save
    import os
    save_dir = os.path.join('trained_models', label)
    os.makedirs(save_dir, exist_ok=True)
    torch.save({'model': student, 'epoch': NUM_EPOCHS},
               os.path.join(save_dir, f'{label}_full.pth'))
    print(f'Saved → {save_dir}/{label}_full.pth')

    # Evaluate
    student.eval()
    metrics = evaluator.evaluate_single(student, label)

    pwkd_metrics.append({
        'Pruning Ratio':      f'{int(ratio*100)}%',
        'Size Reduction (%)': round((BASELINE_PARAMS - metrics['total_parameters'])
                                    / BASELINE_PARAMS * 100, 2),
        'F1 Score':           round(metrics['f1_macro'],     4),
        'Size (MB)':          round(metrics['model_size_mb'], 1),
        'Latency (ms)':       round(metrics['avg_latency_ms'], 2),
    })
    print(f'  ratio {ratio:.0%} | F1: {metrics["f1_macro"]:.4f} | '
          f'params: {metrics["total_parameters"]:,} | '
          f'latency: {metrics["avg_latency_ms"]:.2f}ms')

summary_df = pd.DataFrame(pwkd_metrics).set_index('Pruning Ratio')
print('\nPWKD Option 1 (ResNet18) — Results')
display(summary_df)

Teacher F1: 0.4867
Teacher params: 23,633,021
ResNet18 pretrained baseline F1:    0.4054
ResNet18 pretrained baseline params: 11,207,805

============================================================
  PWKD Option 1 (ResNet18) — pruning ratio 10%
============================================================
  Epoch 1/10 [  4.8%]  loss: 2.4408
  Epoch 1/10 [  9.6%]  loss: 2.8545
  Epoch 1/10 [ 14.5%]  loss: 2.3419
  Epoch 1/10 [ 19.3%]  loss: 2.1466
  Epoch 1/10 [ 24.1%]  loss: 2.0009
  Epoch 1/10 [ 28.9%]  loss: 1.8433
  Epoch 1/10 [ 33.7%]  loss: 1.9103
  Epoch 1/10 [ 38.6%]  loss: 1.7448
  Epoch 1/10 [ 43.4%]  loss: 1.3310
  Epoch 1/10 [ 48.2%]  loss: 1.4084
  Epoch 1/10 [ 53.0%]  loss: 1.3874
  Epoch 1/10 [ 57.8%]  loss: 1.2904
  Epoch 1/10 [ 62.7%]  loss: 1.1842
  Epoch 1/10 [ 67.5%]  loss: 1.3218
  Epoch 1/10 [ 72.3%]  loss: 1.1949
  Epoch 1/10 [ 77.1%]  loss: 1.2818
  Epoch 1/10 [ 81.9%]  loss: 1.1967
  Epoch 1/10 [ 86.7%]  loss: 1.1878
  Epoch 1/10 [ 91.6%]  loss: 1.0461
  Epoch 1/10 [ 96.4%]  loss: 1.0707
  Epoch 1/10 [100.0%]  loss: 1.0757

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.27batch/s]

Epoch 1/10
Train Loss: 1.5899 | Train F1: 0.4362
Val Loss: 2.1114 | Val F1: 0.2586
Epoch Time: 38.05s

  Epoch 2/10 [  4.8%]  loss: 0.9068
  Epoch 2/10 [  9.6%]  loss: 1.1005
  Epoch 2/10 [ 14.5%]  loss: 1.0496
  Epoch 2/10 [ 19.3%]  loss: 0.9510
  Epoch 2/10 [ 24.1%]  loss: 0.9796
  Epoch 2/10 [ 28.9%]  loss: 0.9695
  Epoch 2/10 [ 33.7%]  loss: 0.9246
  Epoch 2/10 [ 38.6%]  loss: 0.8854
  Epoch 2/10 [ 43.4%]  loss: 0.8808
  Epoch 2/10 [ 48.2%]  loss: 0.8564
  Epoch 2/10 [ 53.0%]  loss: 0.8375
  Epoch 2/10 [ 57.8%]  loss: 0.8559
  Epoch 2/10 [ 62.7%]  loss: 0.8140
  Epoch 2/10 [ 67.5%]  loss: 0.8068
  Epoch 2/10 [ 72.3%]  loss: 0.8375
  Epoch 2/10 [ 77.1%]  loss: 0.7806
  Epoch 2/10 [ 81.9%]  loss: 0.7978
  Epoch 2/10 [ 86.7%]  loss: 0.8493
  Epoch 2/10 [ 91.6%]  loss: 0.7624
  Epoch 2/10 [ 96.4%]  loss: 0.7301
  Epoch 2/10 [100.0%]  loss: 0.7060

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.16batch/s]

Epoch 2/10
Train Loss: 0.8726 | Train F1: 0.5773
Val Loss: 1.9590 | Val F1: 0.3164
Epoch Time: 38.49s

  Epoch 3/10 [  4.8%]  loss: 0.7460
  Epoch 3/10 [  9.6%]  loss: 0.7730
  Epoch 3/10 [ 14.5%]  loss: 0.7069
  Epoch 3/10 [ 19.3%]  loss: 0.7379
  Epoch 3/10 [ 24.1%]  loss: 0.7624
  Epoch 3/10 [ 28.9%]  loss: 0.7453
  Epoch 3/10 [ 33.7%]  loss: 0.6420
  Epoch 3/10 [ 38.6%]  loss: 0.7782
  Epoch 3/10 [ 43.4%]  loss: 0.7563
  Epoch 3/10 [ 48.2%]  loss: 0.6831
  Epoch 3/10 [ 53.0%]  loss: 0.6379
  Epoch 3/10 [ 57.8%]  loss: 0.6551
  Epoch 3/10 [ 62.7%]  loss: 0.6350
  Epoch 3/10 [ 67.5%]  loss: 0.6005
  Epoch 3/10 [ 72.3%]  loss: 0.6425
  Epoch 3/10 [ 77.1%]  loss: 0.6320
  Epoch 3/10 [ 81.9%]  loss: 0.6805
  Epoch 3/10 [ 86.7%]  loss: 0.5971
  Epoch 3/10 [ 91.6%]  loss: 0.7155
  Epoch 3/10 [ 96.4%]  loss: 0.6327
  Epoch 3/10 [100.0%]  loss: 0.6369

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.19batch/s]

Epoch 3/10
Train Loss: 0.6862 | Train F1: 0.6529
Val Loss: 1.9436 | Val F1: 0.3248
Epoch Time: 37.38s

  Epoch 4/10 [  4.8%]  loss: 0.6196
  Epoch 4/10 [  9.6%]  loss: 0.6272
  Epoch 4/10 [ 14.5%]  loss: 0.6236
  Epoch 4/10 [ 19.3%]  loss: 0.6530
  Epoch 4/10 [ 24.1%]  loss: 0.5909
  Epoch 4/10 [ 28.9%]  loss: 0.5912
  Epoch 4/10 [ 33.7%]  loss: 0.6419
  Epoch 4/10 [ 38.6%]  loss: 0.6593
  Epoch 4/10 [ 43.4%]  loss: 0.6632
  Epoch 4/10 [ 48.2%]  loss: 0.5846
  Epoch 4/10 [ 53.0%]  loss: 0.6641
  Epoch 4/10 [ 57.8%]  loss: 0.6248
  Epoch 4/10 [ 62.7%]  loss: 0.6633
  Epoch 4/10 [ 67.5%]  loss: 0.6614
  Epoch 4/10 [ 72.3%]  loss: 0.6692
  Epoch 4/10 [ 77.1%]  loss: 0.6585
  Epoch 4/10 [ 81.9%]  loss: 0.5871
  Epoch 4/10 [ 86.7%]  loss: 0.6090
  Epoch 4/10 [ 91.6%]  loss: 0.6999
  Epoch 4/10 [ 96.4%]  loss: 0.6339
  Epoch 4/10 [100.0%]  loss: 0.5989

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.22batch/s]

Epoch 4/10
Train Loss: 0.6349 | Train F1: 0.6753
Val Loss: 1.9454 | Val F1: 0.3126
Epoch Time: 38.34s

  Epoch 5/10 [  4.8%]  loss: 0.5889
  Epoch 5/10 [  9.6%]  loss: 0.6264
  Epoch 5/10 [ 14.5%]  loss: 0.6123
  Epoch 5/10 [ 19.3%]  loss: 0.5856
  Epoch 5/10 [ 24.1%]  loss: 0.5874
  Epoch 5/10 [ 28.9%]  loss: 0.6173
  Epoch 5/10 [ 33.7%]  loss: 0.5788
  Epoch 5/10 [ 38.6%]  loss: 0.5557
  Epoch 5/10 [ 43.4%]  loss: 0.5555
  Epoch 5/10 [ 48.2%]  loss: 0.5573
  Epoch 5/10 [ 53.0%]  loss: 0.5903
  Epoch 5/10 [ 57.8%]  loss: 0.5747
  Epoch 5/10 [ 62.7%]  loss: 0.5592
  Epoch 5/10 [ 67.5%]  loss: 0.5240
  Epoch 5/10 [ 72.3%]  loss: 0.5857
  Epoch 5/10 [ 77.1%]  loss: 0.5321
  Epoch 5/10 [ 81.9%]  loss: 0.5085
  Epoch 5/10 [ 86.7%]  loss: 0.5086
  Epoch 5/10 [ 91.6%]  loss: 0.5650
  Epoch 5/10 [ 96.4%]  loss: 0.5526
  Epoch 5/10 [100.0%]  loss: 0.5670

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.04batch/s]

Epoch 5/10
Train Loss: 0.5683 | Train F1: 0.7091
Val Loss: 1.8785 | Val F1: 0.3404
Epoch Time: 38.29s

  Epoch 6/10 [  4.8%]  loss: 0.5466
  Epoch 6/10 [  9.6%]  loss: 0.5298
  Epoch 6/10 [ 14.5%]  loss: 0.5366
  Epoch 6/10 [ 19.3%]  loss: 0.5354
  Epoch 6/10 [ 24.1%]  loss: 0.5064
  Epoch 6/10 [ 28.9%]  loss: 0.5867
  Epoch 6/10 [ 33.7%]  loss: 0.5259
  Epoch 6/10 [ 38.6%]  loss: 0.5310
  Epoch 6/10 [ 43.4%]  loss: 0.5227
  Epoch 6/10 [ 48.2%]  loss: 0.5284
  Epoch 6/10 [ 53.0%]  loss: 0.5318
  Epoch 6/10 [ 57.8%]  loss: 0.5584
  Epoch 6/10 [ 62.7%]  loss: 0.5356
  Epoch 6/10 [ 67.5%]  loss: 0.5323
  Epoch 6/10 [ 72.3%]  loss: 0.5198
  Epoch 6/10 [ 77.1%]  loss: 0.5434
  Epoch 6/10 [ 81.9%]  loss: 0.5223
  Epoch 6/10 [ 86.7%]  loss: 0.5447
  Epoch 6/10 [ 91.6%]  loss: 0.5013
  Epoch 6/10 [ 96.4%]  loss: 0.4468
  Epoch 6/10 [100.0%]  loss: 0.5045

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.06batch/s]

Epoch 6/10
Train Loss: 0.5284 | Train F1: 0.7288
Val Loss: 1.8707 | Val F1: 0.3377
Epoch Time: 37.48s

  Epoch 7/10 [  4.8%]  loss: 0.5020
  Epoch 7/10 [  9.6%]  loss: 0.5470
  Epoch 7/10 [ 14.5%]  loss: 0.4763
  Epoch 7/10 [ 19.3%]  loss: 0.4676
  Epoch 7/10 [ 24.1%]  loss: 0.5090
  Epoch 7/10 [ 28.9%]  loss: 0.5270
  Epoch 7/10 [ 33.7%]  loss: 0.4891
  Epoch 7/10 [ 38.6%]  loss: 0.4827
  Epoch 7/10 [ 43.4%]  loss: 0.4735
  Epoch 7/10 [ 48.2%]  loss: 0.5337
  Epoch 7/10 [ 53.0%]  loss: 0.4981
  Epoch 7/10 [ 57.8%]  loss: 0.4964
  Epoch 7/10 [ 62.7%]  loss: 0.5321
  Epoch 7/10 [ 67.5%]  loss: 0.4836
  Epoch 7/10 [ 72.3%]  loss: 0.5001
  Epoch 7/10 [ 77.1%]  loss: 0.5077
  Epoch 7/10 [ 81.9%]  loss: 0.4620
  Epoch 7/10 [ 86.7%]  loss: 0.4282
  Epoch 7/10 [ 91.6%]  loss: 0.4824
  Epoch 7/10 [ 96.4%]  loss: 0.4308
  Epoch 7/10 [100.0%]  loss: 0.4799

Validating: 100%|██████████| 50/50 [00:02<00:00, 19.22batch/s]

Epoch 7/10
Train Loss: 0.4910 | Train F1: 0.7402
Val Loss: 1.8187 | Val F1: 0.3406
Epoch Time: 38.31s

  Epoch 8/10 [  4.8%]  loss: 0.4782
  Epoch 8/10 [  9.6%]  loss: 0.4551
  Epoch 8/10 [ 14.5%]  loss: 0.4521
  Epoch 8/10 [ 19.3%]  loss: 0.4268
  Epoch 8/10 [ 24.1%]  loss: 0.4336
  Epoch 8/10 [ 28.9%]  loss: 0.4563
  Epoch 8/10 [ 33.7%]  loss: 0.4647
  Epoch 8/10 [ 38.6%]  loss: 0.4457
  Epoch 8/10 [ 43.4%]  loss: 0.4679
  Epoch 8/10 [ 48.2%]  loss: 0.4318
  Epoch 8/10 [ 53.0%]  loss: 0.4374
  Epoch 8/10 [ 57.8%]  loss: 0.4748
  Epoch 8/10 [ 62.7%]  loss: 0.4516
  Epoch 8/10 [ 67.5%]  loss: 0.4686
  Epoch 8/10 [ 72.3%]  loss: 0.4678
  Epoch 8/10 [ 77.1%]  loss: 0.5055
  Epoch 8/10 [ 81.9%]  loss: 0.4487
  Epoch 8/10 [ 86.7%]  loss: 0.4578
  Epoch 8/10 [ 91.6%]  loss: 0.4391
  Epoch 8/10 [ 96.4%]  loss: 0.4426
  Epoch 8/10 [100.0%]  loss: 0.4026

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.13batch/s]

Epoch 8/10
Train Loss: 0.4534 | Train F1: 0.7626
Val Loss: 1.8356 | Val F1: 0.3530
Epoch Time: 38.33s

  Epoch 9/10 [  4.8%]  loss: 0.4446
  Epoch 9/10 [  9.6%]  loss: 0.4556
  Epoch 9/10 [ 14.5%]  loss: 0.4497
  Epoch 9/10 [ 19.3%]  loss: 0.4691
  Epoch 9/10 [ 24.1%]  loss: 0.4576
  Epoch 9/10 [ 28.9%]  loss: 0.4447
  Epoch 9/10 [ 33.7%]  loss: 0.4149
  Epoch 9/10 [ 38.6%]  loss: 0.4068
  Epoch 9/10 [ 43.4%]  loss: 0.4427
  Epoch 9/10 [ 48.2%]  loss: 0.4232
  Epoch 9/10 [ 53.0%]  loss: 0.4090
  Epoch 9/10 [ 57.8%]  loss: 0.4417
  Epoch 9/10 [ 62.7%]  loss: 0.4085
  Epoch 9/10 [ 67.5%]  loss: 0.4476
  Epoch 9/10 [ 72.3%]  loss: 0.4577
  Epoch 9/10 [ 77.1%]  loss: 0.4580
  Epoch 9/10 [ 81.9%]  loss: 0.4896
  Epoch 9/10 [ 86.7%]  loss: 0.4523
  Epoch 9/10 [ 91.6%]  loss: 0.4763
  Epoch 9/10 [ 96.4%]  loss: 0.4888
  Epoch 9/10 [100.0%]  loss: 0.4696

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.20batch/s]

Epoch 9/10
Train Loss: 0.4477 | Train F1: 0.7664
Val Loss: 1.9335 | Val F1: 0.3569
Epoch Time: 38.51s

  Epoch 10/10 [  4.8%]  loss: 0.4693
  Epoch 10/10 [  9.6%]  loss: 0.4627
  Epoch 10/10 [ 14.5%]  loss: 0.4712
  Epoch 10/10 [ 19.3%]  loss: 0.5130
  Epoch 10/10 [ 24.1%]  loss: 0.4878
  Epoch 10/10 [ 28.9%]  loss: 0.4719
  Epoch 10/10 [ 33.7%]  loss: 0.4377
  Epoch 10/10 [ 38.6%]  loss: 0.4850
  Epoch 10/10 [ 43.4%]  loss: 0.4565
  Epoch 10/10 [ 48.2%]  loss: 0.4537
  Epoch 10/10 [ 53.0%]  loss: 0.4586
  Epoch 10/10 [ 57.8%]  loss: 0.4476
  Epoch 10/10 [ 62.7%]  loss: 0.4999
  Epoch 10/10 [ 67.5%]  loss: 0.4640
  Epoch 10/10 [ 72.3%]  loss: 0.4305
  Epoch 10/10 [ 77.1%]  loss: 0.4575
  Epoch 10/10 [ 81.9%]  loss: 0.4761
  Epoch 10/10 [ 86.7%]  loss: 0.4316
  Epoch 10/10 [ 91.6%]  loss: 0.4496
  Epoch 10/10 [ 96.4%]  loss: 0.4548
  Epoch 10/10 [100.0%]  loss: 0.4642

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.18batch/s]

Epoch 10/10
Train Loss: 0.4640 | Train F1: 0.7675
Val Loss: 1.8643 | Val F1: 0.3551
Epoch Time: 37.47s

Finalised: 188/1920 conv1 channels zeroed (9.8%)
Saved → trained_models/pwkd_r18_r10/pwkd_r18_r10_full.pth

Warming up pwkd_r18_r10...
Running inference...
  ratio 10% | F1: 0.3370 | params: 10,121,469 | latency: 0.38ms

============================================================
  PWKD Option 1 (ResNet18) — pruning ratio 25%
============================================================
  Epoch 1/10 [  4.8%]  loss: 2.8952
  Epoch 1/10 [  9.6%]  loss: 3.1335
  Epoch 1/10 [ 14.5%]  loss: 2.5740
  Epoch 1/10 [ 19.3%]  loss: 2.2575
  Epoch 1/10 [ 24.1%]  loss: 1.9292
  Epoch 1/10 [ 28.9%]  loss: 1.7700
  Epoch 1/10 [ 33.7%]  loss: 1.7568
  Epoch 1/10 [ 38.6%]  loss: 1.6519
  Epoch 1/10 [ 43.4%]  loss: 1.5527
  Epoch 1/10 [ 48.2%]  loss: 1.4332
  Epoch 1/10 [ 53.0%]  loss: 1.5047
  Epoch 1/10 [ 57.8%]  loss: 1.4330
  Epoch 1/10 [ 62.7%]  loss: 1.3102
  Epoch 1/10 [ 67.5%]  loss: 1.4556
  Epoch 1/10 [ 72.3%]  loss: 1.3879
  Epoch 1/10 [ 77.1%]  loss: 1.3263
  Epoch 1/10 [ 81.9%]  loss: 1.2548
  Epoch 1/10 [ 86.7%]  loss: 1.1781
  Epoch 1/10 [ 91.6%]  loss: 1.0923
  Epoch 1/10 [ 96.4%]  loss: 1.1769
  Epoch 1/10 [100.0%]  loss: 1.0491

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.12batch/s]

Epoch 1/10
Train Loss: 1.6800 | Train F1: 0.4127
Val Loss: 2.3619 | Val F1: 0.2434
Epoch Time: 38.37s

  Epoch 2/10 [  4.8%]  loss: 1.1833
  Epoch 2/10 [  9.6%]  loss: 1.0631
  Epoch 2/10 [ 14.5%]  loss: 1.0738
  Epoch 2/10 [ 19.3%]  loss: 1.0667
  Epoch 2/10 [ 24.1%]  loss: 1.0554
  Epoch 2/10 [ 28.9%]  loss: 1.0267
  Epoch 2/10 [ 33.7%]  loss: 1.0043
  Epoch 2/10 [ 38.6%]  loss: 0.9426
  Epoch 2/10 [ 43.4%]  loss: 0.9359
  Epoch 2/10 [ 48.2%]  loss: 0.9003
  Epoch 2/10 [ 53.0%]  loss: 0.9192
  Epoch 2/10 [ 57.8%]  loss: 0.8726
  Epoch 2/10 [ 62.7%]  loss: 0.8390
  Epoch 2/10 [ 67.5%]  loss: 0.8886
  Epoch 2/10 [ 72.3%]  loss: 0.8493
  Epoch 2/10 [ 77.1%]  loss: 0.8606
  Epoch 2/10 [ 81.9%]  loss: 0.8456
  Epoch 2/10 [ 86.7%]  loss: 0.7910
  Epoch 2/10 [ 91.6%]  loss: 0.8883
  Epoch 2/10 [ 96.4%]  loss: 0.8153
  Epoch 2/10 [100.0%]  loss: 0.8596

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.19batch/s]

Epoch 2/10
Train Loss: 0.9381 | Train F1: 0.5591
Val Loss: 2.0484 | Val F1: 0.2873
Epoch Time: 38.38s

  Epoch 3/10 [  4.8%]  loss: 0.8748
  Epoch 3/10 [  9.6%]  loss: 0.8780
  Epoch 3/10 [ 14.5%]  loss: 0.7786
  Epoch 3/10 [ 19.3%]  loss: 0.8042
  Epoch 3/10 [ 24.1%]  loss: 0.7599
  Epoch 3/10 [ 28.9%]  loss: 0.7896
  Epoch 3/10 [ 33.7%]  loss: 0.8264
  Epoch 3/10 [ 38.6%]  loss: 0.7495
  Epoch 3/10 [ 43.4%]  loss: 0.7124
  Epoch 3/10 [ 48.2%]  loss: 0.7075
  Epoch 3/10 [ 53.0%]  loss: 0.8004
  Epoch 3/10 [ 57.8%]  loss: 0.7311
  Epoch 3/10 [ 62.7%]  loss: 0.6856
  Epoch 3/10 [ 67.5%]  loss: 0.6931
  Epoch 3/10 [ 72.3%]  loss: 0.7095
  Epoch 3/10 [ 77.1%]  loss: 0.6306
  Epoch 3/10 [ 81.9%]  loss: 0.6652
  Epoch 3/10 [ 86.7%]  loss: 0.6794
  Epoch 3/10 [ 91.6%]  loss: 0.5911
  Epoch 3/10 [ 96.4%]  loss: 0.6705
  Epoch 3/10 [100.0%]  loss: 0.6424

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.24batch/s]

Epoch 3/10
Train Loss: 0.7335 | Train F1: 0.6368
Val Loss: 1.8798 | Val F1: 0.3365
Epoch Time: 38.39s

  Epoch 4/10 [  4.8%]  loss: 0.6363
  Epoch 4/10 [  9.6%]  loss: 0.6168
  Epoch 4/10 [ 14.5%]  loss: 0.6294
  Epoch 4/10 [ 19.3%]  loss: 0.6267
  Epoch 4/10 [ 24.1%]  loss: 0.5575
  Epoch 4/10 [ 28.9%]  loss: 0.6193
  Epoch 4/10 [ 33.7%]  loss: 0.5857
  Epoch 4/10 [ 38.6%]  loss: 0.6002
  Epoch 4/10 [ 43.4%]  loss: 0.6086
  Epoch 4/10 [ 48.2%]  loss: 0.6713
  Epoch 4/10 [ 53.0%]  loss: 0.6766
  Epoch 4/10 [ 57.8%]  loss: 0.6421
  Epoch 4/10 [ 62.7%]  loss: 0.6063
  Epoch 4/10 [ 67.5%]  loss: 0.5484
  Epoch 4/10 [ 72.3%]  loss: 0.5811
  Epoch 4/10 [ 77.1%]  loss: 0.5834
  Epoch 4/10 [ 81.9%]  loss: 0.6259
  Epoch 4/10 [ 86.7%]  loss: 0.6391
  Epoch 4/10 [ 91.6%]  loss: 0.6070
  Epoch 4/10 [ 96.4%]  loss: 0.6188
  Epoch 4/10 [100.0%]  loss: 0.6261

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.15batch/s]

Epoch 4/10
Train Loss: 0.6145 | Train F1: 0.6853
Val Loss: 1.9214 | Val F1: 0.3390
Epoch Time: 38.53s

  Epoch 5/10 [  4.8%]  loss: 0.6508
  Epoch 5/10 [  9.6%]  loss: 0.6225
  Epoch 5/10 [ 14.5%]  loss: 0.6317
  Epoch 5/10 [ 19.3%]  loss: 0.5745
  Epoch 5/10 [ 24.1%]  loss: 0.6031
  Epoch 5/10 [ 28.9%]  loss: 0.6411
  Epoch 5/10 [ 33.7%]  loss: 0.6083
  Epoch 5/10 [ 38.6%]  loss: 0.6249
  Epoch 5/10 [ 43.4%]  loss: 0.5766
  Epoch 5/10 [ 48.2%]  loss: 0.6147
  Epoch 5/10 [ 53.0%]  loss: 0.6154
  Epoch 5/10 [ 57.8%]  loss: 0.6648
  Epoch 5/10 [ 62.7%]  loss: 0.7760
  Epoch 5/10 [ 67.5%]  loss: 0.7354
  Epoch 5/10 [ 72.3%]  loss: 0.8431
  Epoch 5/10 [ 77.1%]  loss: 0.7601
  Epoch 5/10 [ 81.9%]  loss: 0.6843
  Epoch 5/10 [ 86.7%]  loss: 0.6453
  Epoch 5/10 [ 91.6%]  loss: 0.7231
  Epoch 5/10 [ 96.4%]  loss: 0.6885
  Epoch 5/10 [100.0%]  loss: 0.6254

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.84batch/s]

Epoch 5/10
Train Loss: 0.6628 | Train F1: 0.6826
Val Loss: 1.9468 | Val F1: 0.3070
Epoch Time: 38.45s

  Epoch 6/10 [  4.8%]  loss: 0.6476
  Epoch 6/10 [  9.6%]  loss: 0.7351
  Epoch 6/10 [ 14.5%]  loss: 0.7588
  Epoch 6/10 [ 19.3%]  loss: 0.6876
  Epoch 6/10 [ 24.1%]  loss: 0.6436
  Epoch 6/10 [ 28.9%]  loss: 0.6076
  Epoch 6/10 [ 33.7%]  loss: 0.5636
  Epoch 6/10 [ 38.6%]  loss: 0.5911
  Epoch 6/10 [ 43.4%]  loss: 0.5938
  Epoch 6/10 [ 48.2%]  loss: 0.5621
  Epoch 6/10 [ 53.0%]  loss: 0.5485
  Epoch 6/10 [ 57.8%]  loss: 0.5775
  Epoch 6/10 [ 62.7%]  loss: 0.5765
  Epoch 6/10 [ 67.5%]  loss: 0.5605
  Epoch 6/10 [ 72.3%]  loss: 0.5630
  Epoch 6/10 [ 77.1%]  loss: 0.5326
  Epoch 6/10 [ 81.9%]  loss: 0.5324
  Epoch 6/10 [ 86.7%]  loss: 0.5240
  Epoch 6/10 [ 91.6%]  loss: 0.5478
  Epoch 6/10 [ 96.4%]  loss: 0.5344
  Epoch 6/10 [100.0%]  loss: 0.5542

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.13batch/s]

Epoch 6/10
Train Loss: 0.5930 | Train F1: 0.7025
Val Loss: 1.7998 | Val F1: 0.3528
Epoch Time: 37.55s

  Epoch 7/10 [  4.8%]  loss: 0.5461
  Epoch 7/10 [  9.6%]  loss: 0.5239
  Epoch 7/10 [ 14.5%]  loss: 0.5009
  Epoch 7/10 [ 19.3%]  loss: 0.5161
  Epoch 7/10 [ 24.1%]  loss: 0.5629
  Epoch 7/10 [ 28.9%]  loss: 0.5032
  Epoch 7/10 [ 33.7%]  loss: 0.5175
  Epoch 7/10 [ 38.6%]  loss: 0.4885
  Epoch 7/10 [ 43.4%]  loss: 0.5568
  Epoch 7/10 [ 48.2%]  loss: 0.5097
  Epoch 7/10 [ 53.0%]  loss: 0.4795
  Epoch 7/10 [ 57.8%]  loss: 0.5119
  Epoch 7/10 [ 62.7%]  loss: 0.5627
  Epoch 7/10 [ 67.5%]  loss: 0.5664
  Epoch 7/10 [ 72.3%]  loss: 0.4919
  Epoch 7/10 [ 77.1%]  loss: 0.4831
  Epoch 7/10 [ 81.9%]  loss: 0.4821
  Epoch 7/10 [ 86.7%]  loss: 0.4893
  Epoch 7/10 [ 91.6%]  loss: 0.4847
  Epoch 7/10 [ 96.4%]  loss: 0.5060
  Epoch 7/10 [100.0%]  loss: 0.5240

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.24batch/s]

Epoch 7/10
Train Loss: 0.5145 | Train F1: 0.7389
Val Loss: 1.8434 | Val F1: 0.3414
Epoch Time: 38.53s

  Epoch 8/10 [  4.8%]  loss: 0.5082
  Epoch 8/10 [  9.6%]  loss: 0.5696
  Epoch 8/10 [ 14.5%]  loss: 0.5330
  Epoch 8/10 [ 19.3%]  loss: 0.5682
  Epoch 8/10 [ 24.1%]  loss: 0.5191
  Epoch 8/10 [ 28.9%]  loss: 0.5047
  Epoch 8/10 [ 33.7%]  loss: 0.4810
  Epoch 8/10 [ 38.6%]  loss: 0.4910
  Epoch 8/10 [ 43.4%]  loss: 0.4613
  Epoch 8/10 [ 48.2%]  loss: 0.4666
  Epoch 8/10 [ 53.0%]  loss: 0.4455
  Epoch 8/10 [ 57.8%]  loss: 0.4468
  Epoch 8/10 [ 62.7%]  loss: 0.4740
  Epoch 8/10 [ 67.5%]  loss: 0.4624
  Epoch 8/10 [ 72.3%]  loss: 0.4614
  Epoch 8/10 [ 77.1%]  loss: 0.4651
  Epoch 8/10 [ 81.9%]  loss: 0.4900
  Epoch 8/10 [ 86.7%]  loss: 0.4534
  Epoch 8/10 [ 91.6%]  loss: 0.5145
  Epoch 8/10 [ 96.4%]  loss: 0.5499
  Epoch 8/10 [100.0%]  loss: 0.4968

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.14batch/s]

Epoch 8/10
Train Loss: 0.4934 | Train F1: 0.7484
Val Loss: 1.8279 | Val F1: 0.3344
Epoch Time: 38.35s

  Epoch 9/10 [  4.8%]  loss: 0.5155
  Epoch 9/10 [  9.6%]  loss: 0.5021
  Epoch 9/10 [ 14.5%]  loss: 0.4630
  Epoch 9/10 [ 19.3%]  loss: 0.4722
  Epoch 9/10 [ 24.1%]  loss: 0.5020
  Epoch 9/10 [ 28.9%]  loss: 0.4423
  Epoch 9/10 [ 33.7%]  loss: 0.5008
  Epoch 9/10 [ 38.6%]  loss: 0.4964
  Epoch 9/10 [ 43.4%]  loss: 0.4355
  Epoch 9/10 [ 48.2%]  loss: 0.4302
  Epoch 9/10 [ 53.0%]  loss: 0.4246
  Epoch 9/10 [ 57.8%]  loss: 0.4699
  Epoch 9/10 [ 62.7%]  loss: 0.4637
  Epoch 9/10 [ 67.5%]  loss: 0.4613
  Epoch 9/10 [ 72.3%]  loss: 0.4125
  Epoch 9/10 [ 77.1%]  loss: 0.4307
  Epoch 9/10 [ 81.9%]  loss: 0.4088
  Epoch 9/10 [ 86.7%]  loss: 0.4202
  Epoch 9/10 [ 91.6%]  loss: 0.4602
  Epoch 9/10 [ 96.4%]  loss: 0.4631
  Epoch 9/10 [100.0%]  loss: 0.4516

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.22batch/s]

Epoch 9/10
Train Loss: 0.4585 | Train F1: 0.7615
Val Loss: 1.7851 | Val F1: 0.3730
Epoch Time: 38.38s

  Epoch 10/10 [  4.8%]  loss: 0.4432
  Epoch 10/10 [  9.6%]  loss: 0.4292
  Epoch 10/10 [ 14.5%]  loss: 0.4483
  Epoch 10/10 [ 19.3%]  loss: 0.4318
  Epoch 10/10 [ 24.1%]  loss: 0.4256
  Epoch 10/10 [ 28.9%]  loss: 0.4245
  Epoch 10/10 [ 33.7%]  loss: 0.4301
  Epoch 10/10 [ 38.6%]  loss: 0.4604
  Epoch 10/10 [ 43.4%]  loss: 0.4218
  Epoch 10/10 [ 48.2%]  loss: 0.4367
  Epoch 10/10 [ 53.0%]  loss: 0.4455
  Epoch 10/10 [ 57.8%]  loss: 0.4026
  Epoch 10/10 [ 62.7%]  loss: 0.4144
  Epoch 10/10 [ 67.5%]  loss: 0.4440
  Epoch 10/10 [ 72.3%]  loss: 0.4155
  Epoch 10/10 [ 77.1%]  loss: 0.4565
  Epoch 10/10 [ 81.9%]  loss: 0.4473
  Epoch 10/10 [ 86.7%]  loss: 0.4275
  Epoch 10/10 [ 91.6%]  loss: 0.4354
  Epoch 10/10 [ 96.4%]  loss: 0.4471
  Epoch 10/10 [100.0%]  loss: 0.4237

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.21batch/s]

Epoch 10/10
Train Loss: 0.4340 | Train F1: 0.7859
Val Loss: 1.7548 | Val F1: 0.3589
Epoch Time: 38.35s

Finalised: 480/1920 conv1 channels zeroed (25.0%)
Saved → trained_models/pwkd_r18_r25/pwkd_r18_r25_full.pth

Warming up pwkd_r18_r25...
Running inference...
  ratio 25% | F1: 0.2729 | params: 8,461,437 | latency: 0.40ms

============================================================
  PWKD Option 1 (ResNet18) — pruning ratio 50%
============================================================
  Epoch 1/10 [  4.8%]  loss: 2.3970
  Epoch 1/10 [  9.6%]  loss: 3.2486
  Epoch 1/10 [ 14.5%]  loss: 2.7733
  Epoch 1/10 [ 19.3%]  loss: 2.2893
  Epoch 1/10 [ 24.1%]  loss: 2.1030
  Epoch 1/10 [ 28.9%]  loss: 1.9278
  Epoch 1/10 [ 33.7%]  loss: 1.5679
  Epoch 1/10 [ 38.6%]  loss: 1.5720
  Epoch 1/10 [ 43.4%]  loss: 1.5258
  Epoch 1/10 [ 48.2%]  loss: 1.4913
  Epoch 1/10 [ 53.0%]  loss: 1.4835
  Epoch 1/10 [ 57.8%]  loss: 1.3527
  Epoch 1/10 [ 62.7%]  loss: 1.3540
  Epoch 1/10 [ 67.5%]  loss: 1.2750
  Epoch 1/10 [ 72.3%]  loss: 1.3147
  Epoch 1/10 [ 77.1%]  loss: 1.2300
  Epoch 1/10 [ 81.9%]  loss: 1.2033
  Epoch 1/10 [ 86.7%]  loss: 1.1807
  Epoch 1/10 [ 91.6%]  loss: 1.1361
  Epoch 1/10 [ 96.4%]  loss: 1.0997
  Epoch 1/10 [100.0%]  loss: 1.0763

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.26batch/s]

Epoch 1/10
Train Loss: 1.6546 | Train F1: 0.4169
Val Loss: 2.2938 | Val F1: 0.2285
Epoch Time: 38.27s

  Epoch 2/10 [  4.8%]  loss: 1.1837
  Epoch 2/10 [  9.6%]  loss: 1.3070
  Epoch 2/10 [ 14.5%]  loss: 1.1373
  Epoch 2/10 [ 19.3%]  loss: 1.1227
  Epoch 2/10 [ 24.1%]  loss: 1.1458
  Epoch 2/10 [ 28.9%]  loss: 1.0827
  Epoch 2/10 [ 33.7%]  loss: 1.0347
  Epoch 2/10 [ 38.6%]  loss: 0.9370
  Epoch 2/10 [ 43.4%]  loss: 0.9400
  Epoch 2/10 [ 48.2%]  loss: 0.9078
  Epoch 2/10 [ 53.0%]  loss: 0.8759
  Epoch 2/10 [ 57.8%]  loss: 0.8406
  Epoch 2/10 [ 62.7%]  loss: 1.0022
  Epoch 2/10 [ 67.5%]  loss: 0.9932
  Epoch 2/10 [ 72.3%]  loss: 0.8972
  Epoch 2/10 [ 77.1%]  loss: 0.9940
  Epoch 2/10 [ 81.9%]  loss: 0.8581
  Epoch 2/10 [ 86.7%]  loss: 0.8944
  Epoch 2/10 [ 91.6%]  loss: 0.8384
  Epoch 2/10 [ 96.4%]  loss: 0.8641
  Epoch 2/10 [100.0%]  loss: 0.9076

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.14batch/s]

Epoch 2/10
Train Loss: 0.9898 | Train F1: 0.5484
Val Loss: 2.1667 | Val F1: 0.2805
Epoch Time: 38.46s

  Epoch 3/10 [  4.8%]  loss: 0.9034
  Epoch 3/10 [  9.6%]  loss: 0.7721
  Epoch 3/10 [ 14.5%]  loss: 0.7133
  Epoch 3/10 [ 19.3%]  loss: 0.7446
  Epoch 3/10 [ 24.1%]  loss: 0.6872
  Epoch 3/10 [ 28.9%]  loss: 0.7263
  Epoch 3/10 [ 33.7%]  loss: 0.6488
  Epoch 3/10 [ 38.6%]  loss: 0.7262
  Epoch 3/10 [ 43.4%]  loss: 0.7294
  Epoch 3/10 [ 48.2%]  loss: 0.6542
  Epoch 3/10 [ 53.0%]  loss: 0.7060
  Epoch 3/10 [ 57.8%]  loss: 0.6801
  Epoch 3/10 [ 62.7%]  loss: 0.6573
  Epoch 3/10 [ 67.5%]  loss: 0.6305
  Epoch 3/10 [ 72.3%]  loss: 0.6801
  Epoch 3/10 [ 77.1%]  loss: 0.6237
  Epoch 3/10 [ 81.9%]  loss: 0.6353
  Epoch 3/10 [ 86.7%]  loss: 0.7181
  Epoch 3/10 [ 91.6%]  loss: 0.6275
  Epoch 3/10 [ 96.4%]  loss: 0.6467
  Epoch 3/10 [100.0%]  loss: 0.6151

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.10batch/s]

Epoch 3/10
Train Loss: 0.6926 | Train F1: 0.6453
Val Loss: 1.9774 | Val F1: 0.2969
Epoch Time: 38.31s

  Epoch 4/10 [  4.8%]  loss: 0.6546
  Epoch 4/10 [  9.6%]  loss: 0.5951
  Epoch 4/10 [ 14.5%]  loss: 0.6393
  Epoch 4/10 [ 19.3%]  loss: 0.6617
  Epoch 4/10 [ 24.1%]  loss: 0.6262
  Epoch 4/10 [ 28.9%]  loss: 0.6018
  Epoch 4/10 [ 33.7%]  loss: 0.5649
  Epoch 4/10 [ 38.6%]  loss: 0.6635
  Epoch 4/10 [ 43.4%]  loss: 0.6506
  Epoch 4/10 [ 48.2%]  loss: 0.5691
  Epoch 4/10 [ 53.0%]  loss: 0.6259
  Epoch 4/10 [ 57.8%]  loss: 0.6160
  Epoch 4/10 [ 62.7%]  loss: 0.6471
  Epoch 4/10 [ 67.5%]  loss: 0.6344
  Epoch 4/10 [ 72.3%]  loss: 0.6150
  Epoch 4/10 [ 77.1%]  loss: 0.5958
  Epoch 4/10 [ 81.9%]  loss: 0.5912
  Epoch 4/10 [ 86.7%]  loss: 0.6355
  Epoch 4/10 [ 91.6%]  loss: 0.5864
  Epoch 4/10 [ 96.4%]  loss: 0.6567
  Epoch 4/10 [100.0%]  loss: 0.6637

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.12batch/s]

Epoch 4/10
Train Loss: 0.6231 | Train F1: 0.6813
Val Loss: 2.0577 | Val F1: 0.3117
Epoch Time: 38.33s

  Epoch 5/10 [  4.8%]  loss: 0.6430
  Epoch 5/10 [  9.6%]  loss: 0.6407
  Epoch 5/10 [ 14.5%]  loss: 0.5939
  Epoch 5/10 [ 19.3%]  loss: 0.6229
  Epoch 5/10 [ 24.1%]  loss: 0.6297
  Epoch 5/10 [ 28.9%]  loss: 0.5835
  Epoch 5/10 [ 33.7%]  loss: 0.6134
  Epoch 5/10 [ 38.6%]  loss: 0.5326
  Epoch 5/10 [ 43.4%]  loss: 0.5825
  Epoch 5/10 [ 48.2%]  loss: 0.5723
  Epoch 5/10 [ 53.0%]  loss: 0.5858
  Epoch 5/10 [ 57.8%]  loss: 0.6098
  Epoch 5/10 [ 62.7%]  loss: 0.6056
  Epoch 5/10 [ 67.5%]  loss: 0.5727
  Epoch 5/10 [ 72.3%]  loss: 0.5508
  Epoch 5/10 [ 77.1%]  loss: 0.5315
  Epoch 5/10 [ 81.9%]  loss: 0.6060
  Epoch 5/10 [ 86.7%]  loss: 0.5361
  Epoch 5/10 [ 91.6%]  loss: 0.5910
  Epoch 5/10 [ 96.4%]  loss: 0.5479
  Epoch 5/10 [100.0%]  loss: 0.5436

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.06batch/s]

Epoch 5/10
Train Loss: 0.5860 | Train F1: 0.7032
Val Loss: 2.0222 | Val F1: 0.3213
Epoch Time: 38.39s

  Epoch 6/10 [  4.8%]  loss: 0.5235
  Epoch 6/10 [  9.6%]  loss: 0.5501
  Epoch 6/10 [ 14.5%]  loss: 0.5422
  Epoch 6/10 [ 19.3%]  loss: 0.5646
  Epoch 6/10 [ 24.1%]  loss: 0.5897
  Epoch 6/10 [ 28.9%]  loss: 0.5628
  Epoch 6/10 [ 33.7%]  loss: 0.5309
  Epoch 6/10 [ 38.6%]  loss: 0.5836
  Epoch 6/10 [ 43.4%]  loss: 0.5677
  Epoch 6/10 [ 48.2%]  loss: 0.5201
  Epoch 6/10 [ 53.0%]  loss: 0.5568
  Epoch 6/10 [ 57.8%]  loss: 0.5465
  Epoch 6/10 [ 62.7%]  loss: 0.5849
  Epoch 6/10 [ 67.5%]  loss: 0.5479
  Epoch 6/10 [ 72.3%]  loss: 0.5442
  Epoch 6/10 [ 77.1%]  loss: 0.5652
  Epoch 6/10 [ 81.9%]  loss: 0.5275
  Epoch 6/10 [ 86.7%]  loss: 0.5263
  Epoch 6/10 [ 91.6%]  loss: 0.5243
  Epoch 6/10 [ 96.4%]  loss: 0.5222
  Epoch 6/10 [100.0%]  loss: 0.4918

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.19batch/s]

Epoch 6/10
Train Loss: 0.5470 | Train F1: 0.7269
Val Loss: 1.8371 | Val F1: 0.3531
Epoch Time: 38.61s

  Epoch 7/10 [  4.8%]  loss: 0.4852
  Epoch 7/10 [  9.6%]  loss: 0.4760
  Epoch 7/10 [ 14.5%]  loss: 0.5510
  Epoch 7/10 [ 19.3%]  loss: 0.5256
  Epoch 7/10 [ 24.1%]  loss: 0.4918
  Epoch 7/10 [ 28.9%]  loss: 0.5363
  Epoch 7/10 [ 33.7%]  loss: 0.5524
  Epoch 7/10 [ 38.6%]  loss: 0.5647
  Epoch 7/10 [ 43.4%]  loss: 0.5350
  Epoch 7/10 [ 48.2%]  loss: 0.4414
  Epoch 7/10 [ 53.0%]  loss: 0.5135
  Epoch 7/10 [ 57.8%]  loss: 0.5385
  Epoch 7/10 [ 62.7%]  loss: 0.4770
  Epoch 7/10 [ 67.5%]  loss: 0.5419
  Epoch 7/10 [ 72.3%]  loss: 0.5462
  Epoch 7/10 [ 77.1%]  loss: 0.5249
  Epoch 7/10 [ 81.9%]  loss: 0.5022
  Epoch 7/10 [ 86.7%]  loss: 0.5487
  Epoch 7/10 [ 91.6%]  loss: 0.5231
  Epoch 7/10 [ 96.4%]  loss: 0.5402
  Epoch 7/10 [100.0%]  loss: 0.5173

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.23batch/s]

Epoch 7/10
Train Loss: 0.5207 | Train F1: 0.7352
Val Loss: 1.9574 | Val F1: 0.3463
Epoch Time: 38.40s

  Epoch 8/10 [  4.8%]  loss: 0.5324
  Epoch 8/10 [  9.6%]  loss: 0.5183
  Epoch 8/10 [ 14.5%]  loss: 0.5150
  Epoch 8/10 [ 19.3%]  loss: 0.4965
  Epoch 8/10 [ 24.1%]  loss: 0.4830
  Epoch 8/10 [ 28.9%]  loss: 0.5067
  Epoch 8/10 [ 33.7%]  loss: 0.4978
  Epoch 8/10 [ 38.6%]  loss: 0.4739
  Epoch 8/10 [ 43.4%]  loss: 0.4546
  Epoch 8/10 [ 48.2%]  loss: 0.5094
  Epoch 8/10 [ 53.0%]  loss: 0.4751
  Epoch 8/10 [ 57.8%]  loss: 0.4730
  Epoch 8/10 [ 62.7%]  loss: 0.4898
  Epoch 8/10 [ 67.5%]  loss: 0.5020
  Epoch 8/10 [ 72.3%]  loss: 0.5036
  Epoch 8/10 [ 77.1%]  loss: 0.4382
  Epoch 8/10 [ 81.9%]  loss: 0.4909
  Epoch 8/10 [ 86.7%]  loss: 0.4954
  Epoch 8/10 [ 91.6%]  loss: 0.4487
  Epoch 8/10 [ 96.4%]  loss: 0.5249
  Epoch 8/10 [100.0%]  loss: 0.5298

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.11batch/s]

Epoch 8/10
Train Loss: 0.4928 | Train F1: 0.7618
Val Loss: 2.0474 | Val F1: 0.3402
Epoch Time: 38.50s

  Epoch 9/10 [  4.8%]  loss: 0.5444
  Epoch 9/10 [  9.6%]  loss: 0.6123
  Epoch 9/10 [ 14.5%]  loss: 0.5192
  Epoch 9/10 [ 19.3%]  loss: 0.5461
  Epoch 9/10 [ 24.1%]  loss: 0.4719
  Epoch 9/10 [ 28.9%]  loss: 0.5047
  Epoch 9/10 [ 33.7%]  loss: 0.5307
  Epoch 9/10 [ 38.6%]  loss: 0.5352
  Epoch 9/10 [ 43.4%]  loss: 0.5195
  Epoch 9/10 [ 48.2%]  loss: 0.5321
  Epoch 9/10 [ 53.0%]  loss: 0.4807
  Epoch 9/10 [ 57.8%]  loss: 0.5197
  Epoch 9/10 [ 62.7%]  loss: 0.5303
  Epoch 9/10 [ 67.5%]  loss: 0.5206
  Epoch 9/10 [ 72.3%]  loss: 0.4766
  Epoch 9/10 [ 77.1%]  loss: 0.4747
  Epoch 9/10 [ 81.9%]  loss: 0.4823
  Epoch 9/10 [ 86.7%]  loss: 0.5155
  Epoch 9/10 [ 91.6%]  loss: 0.4886
  Epoch 9/10 [ 96.4%]  loss: 0.5117
  Epoch 9/10 [100.0%]  loss: 0.5054

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.15batch/s]

Epoch 9/10
Train Loss: 0.5155 | Train F1: 0.7518
Val Loss: 2.0378 | Val F1: 0.3152
Epoch Time: 38.62s

  Epoch 10/10 [  4.8%]  loss: 0.5393
  Epoch 10/10 [  9.6%]  loss: 0.5014
  Epoch 10/10 [ 14.5%]  loss: 0.4679
  Epoch 10/10 [ 19.3%]  loss: 0.4615
  Epoch 10/10 [ 24.1%]  loss: 0.4759
  Epoch 10/10 [ 28.9%]  loss: 0.4782
  Epoch 10/10 [ 33.7%]  loss: 0.4954
  Epoch 10/10 [ 38.6%]  loss: 0.4617
  Epoch 10/10 [ 43.4%]  loss: 0.4561
  Epoch 10/10 [ 48.2%]  loss: 0.4436
  Epoch 10/10 [ 53.0%]  loss: 0.4617
  Epoch 10/10 [ 57.8%]  loss: 0.4325
  Epoch 10/10 [ 62.7%]  loss: 0.4596
  Epoch 10/10 [ 67.5%]  loss: 0.4461
  Epoch 10/10 [ 72.3%]  loss: 0.4472
  Epoch 10/10 [ 77.1%]  loss: 0.4724
  Epoch 10/10 [ 81.9%]  loss: 0.4509
  Epoch 10/10 [ 86.7%]  loss: 0.4563
  Epoch 10/10 [ 91.6%]  loss: 0.4604
  Epoch 10/10 [ 96.4%]  loss: 0.4636
  Epoch 10/10 [100.0%]  loss: 0.4054

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.12batch/s]

Epoch 10/10
Train Loss: 0.4644 | Train F1: 0.7717
Val Loss: 1.8397 | Val F1: 0.3468
Epoch Time: 38.64s

Finalised: 960/1920 conv1 channels zeroed (50.0%)
Saved → trained_models/pwkd_r18_r50/pwkd_r18_r50_full.pth

Warming up pwkd_r18_r50...
Running inference...
  ratio 50% | F1: 0.0009 | params: 5,715,069 | latency: 0.39ms

============================================================
  PWKD Option 1 (ResNet18) — pruning ratio 70%
============================================================
  Epoch 1/10 [  4.8%]  loss: 2.4714
  Epoch 1/10 [  9.6%]  loss: 2.8670
  Epoch 1/10 [ 14.5%]  loss: 2.3092
  Epoch 1/10 [ 19.3%]  loss: 2.1621
  Epoch 1/10 [ 24.1%]  loss: 2.2096
  Epoch 1/10 [ 28.9%]  loss: 2.0989
  Epoch 1/10 [ 33.7%]  loss: 1.8104
  Epoch 1/10 [ 38.6%]  loss: 1.7712
  Epoch 1/10 [ 43.4%]  loss: 1.6570
  Epoch 1/10 [ 48.2%]  loss: 1.5891
  Epoch 1/10 [ 53.0%]  loss: 1.5748
  Epoch 1/10 [ 57.8%]  loss: 1.4312
  Epoch 1/10 [ 62.7%]  loss: 1.3628
  Epoch 1/10 [ 67.5%]  loss: 1.3767
  Epoch 1/10 [ 72.3%]  loss: 1.2302
  Epoch 1/10 [ 77.1%]  loss: 1.3140
  Epoch 1/10 [ 81.9%]  loss: 1.1968
  Epoch 1/10 [ 86.7%]  loss: 1.2870
  Epoch 1/10 [ 91.6%]  loss: 1.0610
  Epoch 1/10 [ 96.4%]  loss: 1.2022
  Epoch 1/10 [100.0%]  loss: 1.1523

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.11batch/s]

Epoch 1/10
Train Loss: 1.6794 | Train F1: 0.4159
Val Loss: 2.2533 | Val F1: 0.2368
Epoch Time: 37.54s

  Epoch 2/10 [  4.8%]  loss: 1.0271
  Epoch 2/10 [  9.6%]  loss: 1.1115
  Epoch 2/10 [ 14.5%]  loss: 1.0831
  Epoch 2/10 [ 19.3%]  loss: 1.0268
  Epoch 2/10 [ 24.1%]  loss: 1.0138
  Epoch 2/10 [ 28.9%]  loss: 0.9823
  Epoch 2/10 [ 33.7%]  loss: 0.9979
  Epoch 2/10 [ 38.6%]  loss: 1.0305
  Epoch 2/10 [ 43.4%]  loss: 0.9496
  Epoch 2/10 [ 48.2%]  loss: 0.8855
  Epoch 2/10 [ 53.0%]  loss: 0.8489
  Epoch 2/10 [ 57.8%]  loss: 0.9787
  Epoch 2/10 [ 62.7%]  loss: 0.8942
  Epoch 2/10 [ 67.5%]  loss: 0.7793
  Epoch 2/10 [ 72.3%]  loss: 0.8352
  Epoch 2/10 [ 77.1%]  loss: 0.8132
  Epoch 2/10 [ 81.9%]  loss: 0.7714
  Epoch 2/10 [ 86.7%]  loss: 0.8180
  Epoch 2/10 [ 91.6%]  loss: 0.8091
  Epoch 2/10 [ 96.4%]  loss: 0.8009
  Epoch 2/10 [100.0%]  loss: 0.8266

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.19batch/s]

Epoch 2/10
Train Loss: 0.9194 | Train F1: 0.5718
Val Loss: 2.1149 | Val F1: 0.2858
Epoch Time: 38.63s

  Epoch 3/10 [  4.8%]  loss: 0.8147
  Epoch 3/10 [  9.6%]  loss: 0.7904
  Epoch 3/10 [ 14.5%]  loss: 0.7379
  Epoch 3/10 [ 19.3%]  loss: 0.7213
  Epoch 3/10 [ 24.1%]  loss: 0.8269
  Epoch 3/10 [ 28.9%]  loss: 0.7088
  Epoch 3/10 [ 33.7%]  loss: 0.7345
  Epoch 3/10 [ 38.6%]  loss: 0.8049
  Epoch 3/10 [ 43.4%]  loss: 0.7970
  Epoch 3/10 [ 48.2%]  loss: 0.7186
  Epoch 3/10 [ 53.0%]  loss: 0.7392
  Epoch 3/10 [ 57.8%]  loss: 0.6772
  Epoch 3/10 [ 62.7%]  loss: 0.7165
  Epoch 3/10 [ 67.5%]  loss: 0.6930
  Epoch 3/10 [ 72.3%]  loss: 0.7217
  Epoch 3/10 [ 77.1%]  loss: 0.7086
  Epoch 3/10 [ 81.9%]  loss: 0.6409
  Epoch 3/10 [ 86.7%]  loss: 0.6793
  Epoch 3/10 [ 91.6%]  loss: 0.6426
  Epoch 3/10 [ 96.4%]  loss: 0.6766
  Epoch 3/10 [100.0%]  loss: 0.7315

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.13batch/s]

Epoch 3/10
Train Loss: 0.7277 | Train F1: 0.6411
Val Loss: 1.9909 | Val F1: 0.3276
Epoch Time: 38.62s

  Epoch 4/10 [  4.8%]  loss: 0.7002
  Epoch 4/10 [  9.6%]  loss: 0.6354
  Epoch 4/10 [ 14.5%]  loss: 0.5964
  Epoch 4/10 [ 19.3%]  loss: 0.6566
  Epoch 4/10 [ 24.1%]  loss: 0.6758
  Epoch 4/10 [ 28.9%]  loss: 0.6323
  Epoch 4/10 [ 33.7%]  loss: 0.6401
  Epoch 4/10 [ 38.6%]  loss: 0.6265
  Epoch 4/10 [ 43.4%]  loss: 0.6028
  Epoch 4/10 [ 48.2%]  loss: 0.6403
  Epoch 4/10 [ 53.0%]  loss: 0.6450
  Epoch 4/10 [ 57.8%]  loss: 0.6471
  Epoch 4/10 [ 62.7%]  loss: 0.5811
  Epoch 4/10 [ 67.5%]  loss: 0.6070
  Epoch 4/10 [ 72.3%]  loss: 0.6230
  Epoch 4/10 [ 77.1%]  loss: 0.5949
  Epoch 4/10 [ 81.9%]  loss: 0.6228
  Epoch 4/10 [ 86.7%]  loss: 0.5664
  Epoch 4/10 [ 91.6%]  loss: 0.6632
  Epoch 4/10 [ 96.4%]  loss: 0.6202
  Epoch 4/10 [100.0%]  loss: 0.5999

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.24batch/s]

Epoch 4/10
Train Loss: 0.6278 | Train F1: 0.6881
Val Loss: 1.9532 | Val F1: 0.3311
Epoch Time: 38.55s

  Epoch 5/10 [  4.8%]  loss: 0.6270
  Epoch 5/10 [  9.6%]  loss: 0.6780
  Epoch 5/10 [ 14.5%]  loss: 0.6542
  Epoch 5/10 [ 19.3%]  loss: 0.7238
  Epoch 5/10 [ 24.1%]  loss: 0.6567
  Epoch 5/10 [ 28.9%]  loss: 0.6346
  Epoch 5/10 [ 33.7%]  loss: 0.6406
  Epoch 5/10 [ 38.6%]  loss: 0.6246
  Epoch 5/10 [ 43.4%]  loss: 0.6183
  Epoch 5/10 [ 48.2%]  loss: 0.6054
  Epoch 5/10 [ 53.0%]  loss: 0.6261
  Epoch 5/10 [ 57.8%]  loss: 0.5615
  Epoch 5/10 [ 62.7%]  loss: 0.6075
  Epoch 5/10 [ 67.5%]  loss: 0.5927
  Epoch 5/10 [ 72.3%]  loss: 0.5854
  Epoch 5/10 [ 77.1%]  loss: 0.5800
  Epoch 5/10 [ 81.9%]  loss: 0.5755
  Epoch 5/10 [ 86.7%]  loss: 0.6066
  Epoch 5/10 [ 91.6%]  loss: 0.5445
  Epoch 5/10 [ 96.4%]  loss: 0.5641
  Epoch 5/10 [100.0%]  loss: 0.5701

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.13batch/s]

Epoch 5/10
Train Loss: 0.6137 | Train F1: 0.6945
Val Loss: 1.9214 | Val F1: 0.3253
Epoch Time: 38.55s

  Epoch 6/10 [  4.8%]  loss: 0.5660
  Epoch 6/10 [  9.6%]  loss: 0.5805
  Epoch 6/10 [ 14.5%]  loss: 0.6108
  Epoch 6/10 [ 19.3%]  loss: 0.5936
  Epoch 6/10 [ 24.1%]  loss: 0.5309
  Epoch 6/10 [ 28.9%]  loss: 0.5638
  Epoch 6/10 [ 33.7%]  loss: 0.5070
  Epoch 6/10 [ 38.6%]  loss: 0.5247
  Epoch 6/10 [ 43.4%]  loss: 0.4837
  Epoch 6/10 [ 48.2%]  loss: 0.4927
  Epoch 6/10 [ 53.0%]  loss: 0.5079
  Epoch 6/10 [ 57.8%]  loss: 0.5348
  Epoch 6/10 [ 62.7%]  loss: 0.5131
  Epoch 6/10 [ 67.5%]  loss: 0.4757
  Epoch 6/10 [ 72.3%]  loss: 0.4891
  Epoch 6/10 [ 77.1%]  loss: 0.5141
  Epoch 6/10 [ 81.9%]  loss: 0.5341
  Epoch 6/10 [ 86.7%]  loss: 0.5314
  Epoch 6/10 [ 91.6%]  loss: 0.4918
  Epoch 6/10 [ 96.4%]  loss: 0.5225
  Epoch 6/10 [100.0%]  loss: 0.4797

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.14batch/s]

Epoch 6/10
Train Loss: 0.5266 | Train F1: 0.7342
Val Loss: 1.7994 | Val F1: 0.3414
Epoch Time: 38.70s

  Epoch 7/10 [  4.8%]  loss: 0.5379
  Epoch 7/10 [  9.6%]  loss: 0.5522
  Epoch 7/10 [ 14.5%]  loss: 0.5193
  Epoch 7/10 [ 19.3%]  loss: 0.5350
  Epoch 7/10 [ 24.1%]  loss: 0.5194
  Epoch 7/10 [ 28.9%]  loss: 0.5474
  Epoch 7/10 [ 33.7%]  loss: 0.5087
  Epoch 7/10 [ 38.6%]  loss: 0.5480
  Epoch 7/10 [ 43.4%]  loss: 0.5686
  Epoch 7/10 [ 48.2%]  loss: 0.5112
  Epoch 7/10 [ 53.0%]  loss: 0.5609
  Epoch 7/10 [ 57.8%]  loss: 0.5519
  Epoch 7/10 [ 62.7%]  loss: 0.5364
  Epoch 7/10 [ 67.5%]  loss: 0.4944
  Epoch 7/10 [ 72.3%]  loss: 0.5071
  Epoch 7/10 [ 77.1%]  loss: 0.4841
  Epoch 7/10 [ 81.9%]  loss: 0.5381
  Epoch 7/10 [ 86.7%]  loss: 0.5447
  Epoch 7/10 [ 91.6%]  loss: 0.5061
  Epoch 7/10 [ 96.4%]  loss: 0.5457
  Epoch 7/10 [100.0%]  loss: 0.5055

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.12batch/s]

Epoch 7/10
Train Loss: 0.5299 | Train F1: 0.7392
Val Loss: 1.9232 | Val F1: 0.3238
Epoch Time: 38.58s

  Epoch 8/10 [  4.8%]  loss: 0.5180
  Epoch 8/10 [  9.6%]  loss: 0.6298
  Epoch 8/10 [ 14.5%]  loss: 0.5223
  Epoch 8/10 [ 19.3%]  loss: 0.4847
  Epoch 8/10 [ 24.1%]  loss: 0.5171
  Epoch 8/10 [ 28.9%]  loss: 0.5110
  Epoch 8/10 [ 33.7%]  loss: 0.5053
  Epoch 8/10 [ 38.6%]  loss: 0.4976
  Epoch 8/10 [ 43.4%]  loss: 0.5071
  Epoch 8/10 [ 48.2%]  loss: 0.5048
  Epoch 8/10 [ 53.0%]  loss: 0.4693
  Epoch 8/10 [ 57.8%]  loss: 0.4615
  Epoch 8/10 [ 62.7%]  loss: 0.5096
  Epoch 8/10 [ 67.5%]  loss: 0.5133
  Epoch 8/10 [ 72.3%]  loss: 0.5161
  Epoch 8/10 [ 77.1%]  loss: 0.5368
  Epoch 8/10 [ 81.9%]  loss: 0.4806
  Epoch 8/10 [ 86.7%]  loss: 0.4728
  Epoch 8/10 [ 91.6%]  loss: 0.5015
  Epoch 8/10 [ 96.4%]  loss: 0.4901
  Epoch 8/10 [100.0%]  loss: 0.5608

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.17batch/s]

Epoch 8/10
Train Loss: 0.5094 | Train F1: 0.7557
Val Loss: 1.8769 | Val F1: 0.3356
Epoch Time: 38.62s

  Epoch 9/10 [  4.8%]  loss: 0.5410
  Epoch 9/10 [  9.6%]  loss: 0.5369
  Epoch 9/10 [ 14.5%]  loss: 0.5314
  Epoch 9/10 [ 19.3%]  loss: 0.5242
  Epoch 9/10 [ 24.1%]  loss: 0.5432
  Epoch 9/10 [ 28.9%]  loss: 0.5188
  Epoch 9/10 [ 33.7%]  loss: 0.5456
  Epoch 9/10 [ 38.6%]  loss: 0.5174
  Epoch 9/10 [ 43.4%]  loss: 0.5219
  Epoch 9/10 [ 48.2%]  loss: 0.5086
  Epoch 9/10 [ 53.0%]  loss: 0.4896
  Epoch 9/10 [ 57.8%]  loss: 0.5357
  Epoch 9/10 [ 62.7%]  loss: 0.4664
  Epoch 9/10 [ 67.5%]  loss: 0.4729
  Epoch 9/10 [ 72.3%]  loss: 0.4638
  Epoch 9/10 [ 77.1%]  loss: 0.4717
  Epoch 9/10 [ 81.9%]  loss: 0.4875
  Epoch 9/10 [ 86.7%]  loss: 0.5482
  Epoch 9/10 [ 91.6%]  loss: 0.5500
  Epoch 9/10 [ 96.4%]  loss: 0.5085
  Epoch 9/10 [100.0%]  loss: 0.4723

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.16batch/s]

Epoch 9/10
Train Loss: 0.5127 | Train F1: 0.7499
Val Loss: 1.9301 | Val F1: 0.3351
Epoch Time: 38.48s

  Epoch 10/10 [  4.8%]  loss: 0.4921
  Epoch 10/10 [  9.6%]  loss: 0.5261
  Epoch 10/10 [ 14.5%]  loss: 0.5284
  Epoch 10/10 [ 19.3%]  loss: 0.4505
  Epoch 10/10 [ 24.1%]  loss: 0.5095
  Epoch 10/10 [ 28.9%]  loss: 0.4957
  Epoch 10/10 [ 33.7%]  loss: 0.4780
  Epoch 10/10 [ 38.6%]  loss: 0.4924
  Epoch 10/10 [ 43.4%]  loss: 0.5297
  Epoch 10/10 [ 48.2%]  loss: 0.5772
  Epoch 10/10 [ 53.0%]  loss: 0.5800
  Epoch 10/10 [ 57.8%]  loss: 0.6001
  Epoch 10/10 [ 62.7%]  loss: 0.6076
  Epoch 10/10 [ 67.5%]  loss: 0.5576
  Epoch 10/10 [ 72.3%]  loss: 0.6031
  Epoch 10/10 [ 77.1%]  loss: 0.6514
  Epoch 10/10 [ 81.9%]  loss: 0.5905
  Epoch 10/10 [ 86.7%]  loss: 0.6299
  Epoch 10/10 [ 91.6%]  loss: 0.5999
  Epoch 10/10 [ 96.4%]  loss: 0.5628
  Epoch 10/10 [100.0%]  loss: 0.6778

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.11batch/s]

Epoch 10/10
Train Loss: 0.5576 | Train F1: 0.7397
Val Loss: 2.0740 | Val F1: 0.3107
Epoch Time: 38.71s

Finalised: 1340/1920 conv1 channels zeroed (69.8%)
Saved → trained_models/pwkd_r18_r70/pwkd_r18_r70_full.pth

Warming up pwkd_r18_r70...
Running inference...
  ratio 70% | F1: 0.0001 | params: 3,530,301 | latency: 0.38ms

============================================================
  PWKD Option 1 (ResNet18) — pruning ratio 90%
============================================================
  Epoch 1/10 [  4.8%]  loss: 2.5621
  Epoch 1/10 [  9.6%]  loss: 2.6466
  Epoch 1/10 [ 14.5%]  loss: 2.3540
  Epoch 1/10 [ 19.3%]  loss: 2.2669
  Epoch 1/10 [ 24.1%]  loss: 1.9522
  Epoch 1/10 [ 28.9%]  loss: 1.9746
  Epoch 1/10 [ 33.7%]  loss: 1.7854
  Epoch 1/10 [ 38.6%]  loss: 1.7958
  Epoch 1/10 [ 43.4%]  loss: 1.7207
  Epoch 1/10 [ 48.2%]  loss: 1.5238
  Epoch 1/10 [ 53.0%]  loss: 1.6833
  Epoch 1/10 [ 57.8%]  loss: 1.7255
  Epoch 1/10 [ 62.7%]  loss: 1.4476
  Epoch 1/10 [ 67.5%]  loss: 1.7176
  Epoch 1/10 [ 72.3%]  loss: 1.5115
  Epoch 1/10 [ 77.1%]  loss: 1.3689
  Epoch 1/10 [ 81.9%]  loss: 1.3526
  Epoch 1/10 [ 86.7%]  loss: 1.3621
  Epoch 1/10 [ 91.6%]  loss: 1.2987
  Epoch 1/10 [ 96.4%]  loss: 1.2145
  Epoch 1/10 [100.0%]  loss: 1.1361

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.11batch/s]

Epoch 1/10
Train Loss: 1.7406 | Train F1: 0.3962
Val Loss: 2.3689 | Val F1: 0.2221
Epoch Time: 38.32s

  Epoch 2/10 [  4.8%]  loss: 1.0994
  Epoch 2/10 [  9.6%]  loss: 1.0016
  Epoch 2/10 [ 14.5%]  loss: 1.0277
  Epoch 2/10 [ 19.3%]  loss: 0.9048
  Epoch 2/10 [ 24.1%]  loss: 1.0323
  Epoch 2/10 [ 28.9%]  loss: 0.9513
  Epoch 2/10 [ 33.7%]  loss: 0.9309
  Epoch 2/10 [ 38.6%]  loss: 0.8752
  Epoch 2/10 [ 43.4%]  loss: 0.9005
  Epoch 2/10 [ 48.2%]  loss: 0.8591
  Epoch 2/10 [ 53.0%]  loss: 0.8565
  Epoch 2/10 [ 57.8%]  loss: 0.9574
  Epoch 2/10 [ 62.7%]  loss: 0.9867
  Epoch 2/10 [ 67.5%]  loss: 0.8747
  Epoch 2/10 [ 72.3%]  loss: 0.9509
  Epoch 2/10 [ 77.1%]  loss: 0.8534
  Epoch 2/10 [ 81.9%]  loss: 0.8050
  Epoch 2/10 [ 86.7%]  loss: 0.8549
  Epoch 2/10 [ 91.6%]  loss: 0.7776
  Epoch 2/10 [ 96.4%]  loss: 0.8826
  Epoch 2/10 [100.0%]  loss: 0.7843

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.12batch/s]

Epoch 2/10
Train Loss: 0.9143 | Train F1: 0.5678
Val Loss: 2.1943 | Val F1: 0.2882
Epoch Time: 37.67s

  Epoch 3/10 [  4.8%]  loss: 0.8511
  Epoch 3/10 [  9.6%]  loss: 0.7201
  Epoch 3/10 [ 14.5%]  loss: 0.7116
  Epoch 3/10 [ 19.3%]  loss: 0.6652
  Epoch 3/10 [ 24.1%]  loss: 0.7313
  Epoch 3/10 [ 28.9%]  loss: 0.7661
  Epoch 3/10 [ 33.7%]  loss: 0.7270
  Epoch 3/10 [ 38.6%]  loss: 0.7029
  Epoch 3/10 [ 43.4%]  loss: 0.6953
  Epoch 3/10 [ 48.2%]  loss: 0.7281
  Epoch 3/10 [ 53.0%]  loss: 0.6945
  Epoch 3/10 [ 57.8%]  loss: 0.7179
  Epoch 3/10 [ 62.7%]  loss: 0.7345
  Epoch 3/10 [ 67.5%]  loss: 0.6814
  Epoch 3/10 [ 72.3%]  loss: 0.6382
  Epoch 3/10 [ 77.1%]  loss: 0.6947
  Epoch 3/10 [ 81.9%]  loss: 0.6537
  Epoch 3/10 [ 86.7%]  loss: 0.6309
  Epoch 3/10 [ 91.6%]  loss: 0.6500
  Epoch 3/10 [ 96.4%]  loss: 0.6819
  Epoch 3/10 [100.0%]  loss: 0.6619

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.15batch/s]

Epoch 3/10
Train Loss: 0.7023 | Train F1: 0.6558
Val Loss: 1.9900 | Val F1: 0.3014
Epoch Time: 38.28s

  Epoch 4/10 [  4.8%]  loss: 0.6906
  Epoch 4/10 [  9.6%]  loss: 0.7268
  Epoch 4/10 [ 14.5%]  loss: 0.7209
  Epoch 4/10 [ 19.3%]  loss: 0.7531
  Epoch 4/10 [ 24.1%]  loss: 0.6986
  Epoch 4/10 [ 28.9%]  loss: 0.6807
  Epoch 4/10 [ 33.7%]  loss: 0.7004
  Epoch 4/10 [ 38.6%]  loss: 0.6840
  Epoch 4/10 [ 43.4%]  loss: 0.7131
  Epoch 4/10 [ 48.2%]  loss: 0.6825
  Epoch 4/10 [ 53.0%]  loss: 0.6741
  Epoch 4/10 [ 57.8%]  loss: 0.6895
  Epoch 4/10 [ 62.7%]  loss: 0.6869
  Epoch 4/10 [ 67.5%]  loss: 0.7025
  Epoch 4/10 [ 72.3%]  loss: 0.7132
  Epoch 4/10 [ 77.1%]  loss: 0.7016
  Epoch 4/10 [ 81.9%]  loss: 0.6976
  Epoch 4/10 [ 86.7%]  loss: 0.7149
  Epoch 4/10 [ 91.6%]  loss: 0.7207
  Epoch 4/10 [ 96.4%]  loss: 0.7141
  Epoch 4/10 [100.0%]  loss: 0.7075

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.12batch/s]

Epoch 4/10
Train Loss: 0.7034 | Train F1: 0.6587
Val Loss: 1.9421 | Val F1: 0.3225
Epoch Time: 38.38s

  Epoch 5/10 [  4.8%]  loss: 0.6507
  Epoch 5/10 [  9.6%]  loss: 0.6635
  Epoch 5/10 [ 14.5%]  loss: 0.6038
  Epoch 5/10 [ 19.3%]  loss: 0.7606
  Epoch 5/10 [ 24.1%]  loss: 0.7507
  Epoch 5/10 [ 28.9%]  loss: 0.7042
  Epoch 5/10 [ 33.7%]  loss: 0.6323
  Epoch 5/10 [ 38.6%]  loss: 0.6565
  Epoch 5/10 [ 43.4%]  loss: 0.6627
  Epoch 5/10 [ 48.2%]  loss: 0.5949
  Epoch 5/10 [ 53.0%]  loss: 0.6178
  Epoch 5/10 [ 57.8%]  loss: 0.6577
  Epoch 5/10 [ 62.7%]  loss: 0.6250
  Epoch 5/10 [ 67.5%]  loss: 0.6547
  Epoch 5/10 [ 72.3%]  loss: 0.6134
  Epoch 5/10 [ 77.1%]  loss: 0.6078
  Epoch 5/10 [ 81.9%]  loss: 0.6085
  Epoch 5/10 [ 86.7%]  loss: 0.6011
  Epoch 5/10 [ 91.6%]  loss: 0.5611
  Epoch 5/10 [ 96.4%]  loss: 0.5929
  Epoch 5/10 [100.0%]  loss: 0.5886

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.15batch/s]

Epoch 5/10
Train Loss: 0.6391 | Train F1: 0.6864
Val Loss: 1.9790 | Val F1: 0.3257
Epoch Time: 37.54s

  Epoch 6/10 [  4.8%]  loss: 0.6303
  Epoch 6/10 [  9.6%]  loss: 0.5904
  Epoch 6/10 [ 14.5%]  loss: 0.5696
  Epoch 6/10 [ 19.3%]  loss: 0.5510
  Epoch 6/10 [ 24.1%]  loss: 0.5598
  Epoch 6/10 [ 28.9%]  loss: 0.5721
  Epoch 6/10 [ 33.7%]  loss: 0.5624
  Epoch 6/10 [ 38.6%]  loss: 0.5750
  Epoch 6/10 [ 43.4%]  loss: 0.5404
  Epoch 6/10 [ 48.2%]  loss: 0.5418
  Epoch 6/10 [ 53.0%]  loss: 0.5693
  Epoch 6/10 [ 57.8%]  loss: 0.5373
  Epoch 6/10 [ 62.7%]  loss: 0.5403
  Epoch 6/10 [ 67.5%]  loss: 0.5501
  Epoch 6/10 [ 72.3%]  loss: 0.5832
  Epoch 6/10 [ 77.1%]  loss: 0.5843
  Epoch 6/10 [ 81.9%]  loss: 0.5702
  Epoch 6/10 [ 86.7%]  loss: 0.5424
  Epoch 6/10 [ 91.6%]  loss: 0.5218
  Epoch 6/10 [ 96.4%]  loss: 0.5429
  Epoch 6/10 [100.0%]  loss: 0.5526

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.19batch/s]

Epoch 6/10
Train Loss: 0.5614 | Train F1: 0.7246
Val Loss: 1.9228 | Val F1: 0.3315
Epoch Time: 38.31s

  Epoch 7/10 [  4.8%]  loss: 0.5136
  Epoch 7/10 [  9.6%]  loss: 0.5367
  Epoch 7/10 [ 14.5%]  loss: 0.5333
  Epoch 7/10 [ 19.3%]  loss: 0.5257
  Epoch 7/10 [ 24.1%]  loss: 0.5314
  Epoch 7/10 [ 28.9%]  loss: 0.4693
  Epoch 7/10 [ 33.7%]  loss: 0.5244
  Epoch 7/10 [ 38.6%]  loss: 0.4786
  Epoch 7/10 [ 43.4%]  loss: 0.5020
  Epoch 7/10 [ 48.2%]  loss: 0.5032
  Epoch 7/10 [ 53.0%]  loss: 0.5356
  Epoch 7/10 [ 57.8%]  loss: 0.4744
  Epoch 7/10 [ 62.7%]  loss: 0.4998
  Epoch 7/10 [ 67.5%]  loss: 0.4784
  Epoch 7/10 [ 72.3%]  loss: 0.4966
  Epoch 7/10 [ 77.1%]  loss: 0.4929
  Epoch 7/10 [ 81.9%]  loss: 0.4563
  Epoch 7/10 [ 86.7%]  loss: 0.4787
  Epoch 7/10 [ 91.6%]  loss: 0.4828
  Epoch 7/10 [ 96.4%]  loss: 0.5713
  Epoch 7/10 [100.0%]  loss: 0.5449

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.02batch/s]

Epoch 7/10
Train Loss: 0.5057 | Train F1: 0.7563
Val Loss: 1.8483 | Val F1: 0.3474
Epoch Time: 38.67s

  Epoch 8/10 [  4.8%]  loss: 0.4891
  Epoch 8/10 [  9.6%]  loss: 0.5154
  Epoch 8/10 [ 14.5%]  loss: 0.5007
  Epoch 8/10 [ 19.3%]  loss: 0.5486
  Epoch 8/10 [ 24.1%]  loss: 0.5601
  Epoch 8/10 [ 28.9%]  loss: 0.5136
  Epoch 8/10 [ 33.7%]  loss: 0.4853
  Epoch 8/10 [ 38.6%]  loss: 0.5327
  Epoch 8/10 [ 43.4%]  loss: 0.4956
  Epoch 8/10 [ 48.2%]  loss: 0.6127
  Epoch 8/10 [ 53.0%]  loss: 0.5563
  Epoch 8/10 [ 57.8%]  loss: 0.5467
  Epoch 8/10 [ 62.7%]  loss: 0.5382
  Epoch 8/10 [ 67.5%]  loss: 0.5036
  Epoch 8/10 [ 72.3%]  loss: 0.5070
  Epoch 8/10 [ 77.1%]  loss: 0.5052
  Epoch 8/10 [ 81.9%]  loss: 0.5237
  Epoch 8/10 [ 86.7%]  loss: 0.5123
  Epoch 8/10 [ 91.6%]  loss: 0.4683
  Epoch 8/10 [ 96.4%]  loss: 0.5141
  Epoch 8/10 [100.0%]  loss: 0.4726

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.18batch/s]

Epoch 8/10
Train Loss: 0.5197 | Train F1: 0.7580
Val Loss: 1.7906 | Val F1: 0.3443
Epoch Time: 38.53s

  Epoch 9/10 [  4.8%]  loss: 0.4706
  Epoch 9/10 [  9.6%]  loss: 0.4963
  Epoch 9/10 [ 14.5%]  loss: 0.5430
  Epoch 9/10 [ 19.3%]  loss: 0.4898
  Epoch 9/10 [ 24.1%]  loss: 0.4559
  Epoch 9/10 [ 28.9%]  loss: 0.4814
  Epoch 9/10 [ 33.7%]  loss: 0.5015
  Epoch 9/10 [ 38.6%]  loss: 0.5040
  Epoch 9/10 [ 43.4%]  loss: 0.4879
  Epoch 9/10 [ 48.2%]  loss: 0.5091
  Epoch 9/10 [ 53.0%]  loss: 0.5046
  Epoch 9/10 [ 57.8%]  loss: 0.5234
  Epoch 9/10 [ 62.7%]  loss: 0.4865
  Epoch 9/10 [ 67.5%]  loss: 0.5476
  Epoch 9/10 [ 72.3%]  loss: 0.5114
  Epoch 9/10 [ 77.1%]  loss: 0.5644
  Epoch 9/10 [ 81.9%]  loss: 0.5133
  Epoch 9/10 [ 86.7%]  loss: 0.5263
  Epoch 9/10 [ 91.6%]  loss: 0.5073
  Epoch 9/10 [ 96.4%]  loss: 0.5083
  Epoch 9/10 [100.0%]  loss: 0.5452

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.14batch/s]

Epoch 9/10
Train Loss: 0.5080 | Train F1: 0.7567
Val Loss: 1.8483 | Val F1: 0.3575
Epoch Time: 38.46s

  Epoch 10/10 [  4.8%]  loss: 0.4955
  Epoch 10/10 [  9.6%]  loss: 0.5397
  Epoch 10/10 [ 14.5%]  loss: 0.4782
  Epoch 10/10 [ 19.3%]  loss: 0.5588
  Epoch 10/10 [ 24.1%]  loss: 0.5066
  Epoch 10/10 [ 28.9%]  loss: 0.5193
  Epoch 10/10 [ 33.7%]  loss: 0.6003
  Epoch 10/10 [ 38.6%]  loss: 0.5262
  Epoch 10/10 [ 43.4%]  loss: 0.5025
  Epoch 10/10 [ 48.2%]  loss: 0.5145
  Epoch 10/10 [ 53.0%]  loss: 0.4921
  Epoch 10/10 [ 57.8%]  loss: 0.4729
  Epoch 10/10 [ 62.7%]  loss: 0.4936
  Epoch 10/10 [ 67.5%]  loss: 0.4694
  Epoch 10/10 [ 72.3%]  loss: 0.4475
  Epoch 10/10 [ 77.1%]  loss: 0.4740
  Epoch 10/10 [ 81.9%]  loss: 0.4718
  Epoch 10/10 [ 86.7%]  loss: 0.4856
  Epoch 10/10 [ 91.6%]  loss: 0.4576
  Epoch 10/10 [ 96.4%]  loss: 0.4750
  Epoch 10/10 [100.0%]  loss: 0.4866

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.10batch/s]

Epoch 10/10
Train Loss: 0.4986 | Train F1: 0.7687
Val Loss: 1.8981 | Val F1: 0.3407
Epoch Time: 38.30s

Finalised: 1724/1920 conv1 channels zeroed (89.8%)
Saved → trained_models/pwkd_r18_r90/pwkd_r18_r90_full.pth

Warming up pwkd_r18_r90...
Running inference...
  ratio 90% | F1: 0.0001 | params: 1,339,197 | latency: 0.39ms

PWKD Option 1 (ResNet18) — Results

               Size Reduction (%)  F1 Score  Size (MB)  Latency (ms)
Pruning Ratio
10%                          9.69    0.3370       42.8          0.38
25%                         24.50    0.2729       42.8          0.40
50%                         49.01    0.0009       42.8          0.39
70%                         68.50    0.0001       42.8          0.38
90%                         88.05    0.0001       42.8          0.39

In [5]:
# only run this cell if not running the previous cell

import torch.nn as nn
import copy
from modules.model_trainer import modelTrainer
from modules.evaluate_model import ModelEvaluator
# from pwkd import PWKDLoss, make_aux_fn, finalise_student
import importlib, pwkd
importlib.reload(pwkd)
from pwkd import PWKDLoss, make_aux_fn, finalise_student

TEACHER_CHANNELS = {'layer2': 512,  'layer3': 1024, 'layer4': 2048}
STUDENT_CHANNELS = {'layer2': 128,  'layer3': 256,  'layer4': 512}

PRUNING_RATIOS = [0.10, 0.25, 0.50, 0.70, 0.90]
NUM_EPOCHS     = 10
LAM            = 0.2
KD_TEMP        = 4.0
SPARSE_WEIGHT  = 1e-4

evaluator = ModelEvaluator(
    data_loader=data_prep.val_loader,
    class_names=data_prep.class_names,
    device=str(device),
)




pwkd_metrics = []

In [6]:
# ── Extra ratios to better capture the Pareto curve descent ──────────────────
# Run this cell independently — existing trained models are not affected.

EXTRA_RATIOS = [0.2, 0.3, 0.35, 0.40, 0.45]   # between the good and collapsed points

for ratio in EXTRA_RATIOS:
    label = f'pwkd_r18_r{int(ratio * 100)}'
    print(f'\n{"="*60}')
    print(f'  PWKD Option 1 (ResNet18) — pruning ratio {ratio:.0%}')
    print(f'{"="*60}')

    student = copy.deepcopy(student_base).to(device)
    for p in student.parameters():
        p.requires_grad = True

    pwkd_loss = PWKDLoss(
        student          = student,
        teacher          = teacher,
        pruning_ratio    = ratio,
        teacher_channels = TEACHER_CHANNELS,
        student_channels = STUDENT_CHANNELS,
        class_weights    = data_prep.class_weights.to(device)
                           if data_prep.class_weights is not None else None,
        lam              = LAM,
        kd_temp          = KD_TEMP,
        sparse_weight    = SPARSE_WEIGHT,
    ).to(device)

    trainer = modelTrainer(
        model      = student,
        data_prep  = data_prep,
        device     = device,
        learn_rate = 5e-4,
        num_epochs = NUM_EPOCHS,
        model_name = label,
    )
    trainer.loss_fn   = pwkd_loss
    trainer.optimizer = torch.optim.AdamW(
        list(student.parameters()) + list(pwkd_loss.parameters()),
        lr=5e-4, weight_decay=1e-2,
    )
    trainer.create_classnum_to_label_map(data_prep.class_names)
    trainer.train_all(save_as_object=True, aux_forward_fn=make_aux_fn(teacher), pwkd=True)

    student = finalise_student(student, pwkd_loss, data_prep.train_loader, device)

    save_dir = os.path.join('trained_models', label)
    os.makedirs(save_dir, exist_ok=True)
    torch.save({'model': student, 'epoch': NUM_EPOCHS},
               os.path.join(save_dir, f'{label}_full.pth'))
    print(f'Saved → {save_dir}/{label}_full.pth')

    student.eval()
    metrics = evaluator.evaluate_single(student, label)

    pwkd_metrics.append({
        'Pruning Ratio':      f'{int(ratio*100)}%',
        'Size Reduction (%)': round((BASELINE_PARAMS - metrics['total_parameters'])
                                    / BASELINE_PARAMS * 100, 2),
        'F1 Score':           round(metrics['f1_macro'],     4),
        'Size (MB)':          round(metrics['model_size_mb'], 1),
        'Latency (ms)':       round(metrics['avg_latency_ms'], 2),
    })
    print(f'  ratio {ratio:.0%} | F1: {metrics["f1_macro"]:.4f} | '
          f'params: {metrics["total_parameters"]:,}')

summary_df = pd.DataFrame(pwkd_metrics).set_index('Pruning Ratio')
display(summary_df)

============================================================
  PWKD Option 1 (ResNet18) — pruning ratio 20%
============================================================
  Epoch 1/10 [  4.8%]  loss: 2.6207
  Epoch 1/10 [  9.6%]  loss: 2.8309
  Epoch 1/10 [ 14.5%]  loss: 2.4174
  Epoch 1/10 [ 19.3%]  loss: 1.9418
  Epoch 1/10 [ 24.1%]  loss: 1.9137
  Epoch 1/10 [ 28.9%]  loss: 1.9062
  Epoch 1/10 [ 33.7%]  loss: 1.8461
  Epoch 1/10 [ 38.6%]  loss: 1.6924
  Epoch 1/10 [ 43.4%]  loss: 1.6959
  Epoch 1/10 [ 48.2%]  loss: 1.6498
  Epoch 1/10 [ 53.0%]  loss: 1.5759
  Epoch 1/10 [ 57.8%]  loss: 1.4958
  Epoch 1/10 [ 62.7%]  loss: 1.4504
  Epoch 1/10 [ 67.5%]  loss: 1.3912
  Epoch 1/10 [ 72.3%]  loss: 1.2050
  Epoch 1/10 [ 77.1%]  loss: 1.2093
  Epoch 1/10 [ 81.9%]  loss: 1.2671
  Epoch 1/10 [ 86.7%]  loss: 1.1061
  Epoch 1/10 [ 91.6%]  loss: 1.1098
  Epoch 1/10 [ 96.4%]  loss: 1.1329
  Epoch 1/10 [100.0%]  loss: 0.9995

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.16batch/s]

Epoch 1/10
Train Loss: 1.6486 | Train F1: 0.4167
Val Loss: 2.0520 | Val F1: 0.2792
Epoch Time: 38.14s

  Epoch 2/10 [  4.8%]  loss: 1.1277
  Epoch 2/10 [  9.6%]  loss: 1.0431
  Epoch 2/10 [ 14.5%]  loss: 0.9882
  Epoch 2/10 [ 19.3%]  loss: 1.0144
  Epoch 2/10 [ 24.1%]  loss: 0.9416
  Epoch 2/10 [ 28.9%]  loss: 0.9811
  Epoch 2/10 [ 33.7%]  loss: 0.9259
  Epoch 2/10 [ 38.6%]  loss: 0.9126
  Epoch 2/10 [ 43.4%]  loss: 0.9139
  Epoch 2/10 [ 48.2%]  loss: 0.8244
  Epoch 2/10 [ 53.0%]  loss: 0.7961
  Epoch 2/10 [ 57.8%]  loss: 0.8396
  Epoch 2/10 [ 62.7%]  loss: 0.8440
  Epoch 2/10 [ 67.5%]  loss: 0.8826
  Epoch 2/10 [ 72.3%]  loss: 0.8007
  Epoch 2/10 [ 77.1%]  loss: 0.9049
  Epoch 2/10 [ 81.9%]  loss: 0.8109
  Epoch 2/10 [ 86.7%]  loss: 0.8543
  Epoch 2/10 [ 91.6%]  loss: 0.9753
  Epoch 2/10 [ 96.4%]  loss: 1.0217
  Epoch 2/10 [100.0%]  loss: 1.1500

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.23batch/s]

Epoch 2/10
Train Loss: 0.9285 | Train F1: 0.5664
Val Loss: 2.3396 | Val F1: 0.2377
Epoch Time: 38.24s

  Epoch 3/10 [  4.8%]  loss: 0.9227
  Epoch 3/10 [  9.6%]  loss: 1.0508
  Epoch 3/10 [ 14.5%]  loss: 0.9612
  Epoch 3/10 [ 19.3%]  loss: 0.9829
  Epoch 3/10 [ 24.1%]  loss: 0.9315
  Epoch 3/10 [ 28.9%]  loss: 0.8340
  Epoch 3/10 [ 33.7%]  loss: 0.8541
  Epoch 3/10 [ 38.6%]  loss: 0.9315
  Epoch 3/10 [ 43.4%]  loss: 0.7697
  Epoch 3/10 [ 48.2%]  loss: 0.7804
  Epoch 3/10 [ 53.0%]  loss: 0.7651
  Epoch 3/10 [ 57.8%]  loss: 0.7298
  Epoch 3/10 [ 62.7%]  loss: 0.7457
  Epoch 3/10 [ 67.5%]  loss: 0.6851
  Epoch 3/10 [ 72.3%]  loss: 0.6493
  Epoch 3/10 [ 77.1%]  loss: 0.7594
  Epoch 3/10 [ 81.9%]  loss: 0.6524
  Epoch 3/10 [ 86.7%]  loss: 0.6619
  Epoch 3/10 [ 91.6%]  loss: 0.6596
  Epoch 3/10 [ 96.4%]  loss: 0.6915
  Epoch 3/10 [100.0%]  loss: 0.6921

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.11batch/s]

Epoch 3/10
Train Loss: 0.7970 | Train F1: 0.6101
Val Loss: 2.0366 | Val F1: 0.2945
Epoch Time: 38.54s

  Epoch 4/10 [  4.8%]  loss: 0.6728
  Epoch 4/10 [  9.6%]  loss: 0.6289
  Epoch 4/10 [ 14.5%]  loss: 0.6006
  Epoch 4/10 [ 19.3%]  loss: 0.6215
  Epoch 4/10 [ 24.1%]  loss: 0.6284
  Epoch 4/10 [ 28.9%]  loss: 0.6021
  Epoch 4/10 [ 33.7%]  loss: 0.6036
  Epoch 4/10 [ 38.6%]  loss: 0.6026
  Epoch 4/10 [ 43.4%]  loss: 0.5779
  Epoch 4/10 [ 48.2%]  loss: 0.5660
  Epoch 4/10 [ 53.0%]  loss: 0.5155
  Epoch 4/10 [ 57.8%]  loss: 0.5728
  Epoch 4/10 [ 62.7%]  loss: 0.5821
  Epoch 4/10 [ 67.5%]  loss: 0.5985
  Epoch 4/10 [ 72.3%]  loss: 0.5921
  Epoch 4/10 [ 77.1%]  loss: 0.5612
  Epoch 4/10 [ 81.9%]  loss: 0.5855
  Epoch 4/10 [ 86.7%]  loss: 0.5822
  Epoch 4/10 [ 91.6%]  loss: 0.6286
  Epoch 4/10 [ 96.4%]  loss: 0.5675
  Epoch 4/10 [100.0%]  loss: 0.5997

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.28batch/s]

Epoch 4/10
Train Loss: 0.5947 | Train F1: 0.6777
Val Loss: 1.8488 | Val F1: 0.3452
Epoch Time: 38.24s

  Epoch 5/10 [  4.8%]  loss: 0.5800
  Epoch 5/10 [  9.6%]  loss: 0.5852
  Epoch 5/10 [ 14.5%]  loss: 0.5913
  Epoch 5/10 [ 19.3%]  loss: 0.5301
  Epoch 5/10 [ 24.1%]  loss: 0.5758
  Epoch 5/10 [ 28.9%]  loss: 0.5654
  Epoch 5/10 [ 33.7%]  loss: 0.6020
  Epoch 5/10 [ 38.6%]  loss: 0.6285
  Epoch 5/10 [ 43.4%]  loss: 0.6060
  Epoch 5/10 [ 48.2%]  loss: 0.5914
  Epoch 5/10 [ 53.0%]  loss: 0.5524
  Epoch 5/10 [ 57.8%]  loss: 0.5180
  Epoch 5/10 [ 62.7%]  loss: 0.5619
  Epoch 5/10 [ 67.5%]  loss: 0.5499
  Epoch 5/10 [ 72.3%]  loss: 0.5087
  Epoch 5/10 [ 77.1%]  loss: 0.5197
  Epoch 5/10 [ 81.9%]  loss: 0.5566
  Epoch 5/10 [ 86.7%]  loss: 0.4900
  Epoch 5/10 [ 91.6%]  loss: 0.4680
  Epoch 5/10 [ 96.4%]  loss: 0.5068
  Epoch 5/10 [100.0%]  loss: 0.5110

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.12batch/s]

Epoch 5/10
Train Loss: 0.5528 | Train F1: 0.7127
Val Loss: 1.8806 | Val F1: 0.3325
Epoch Time: 38.51s

  Epoch 6/10 [  4.8%]  loss: 0.5423
  Epoch 6/10 [  9.6%]  loss: 0.5403
  Epoch 6/10 [ 14.5%]  loss: 0.5390
  Epoch 6/10 [ 19.3%]  loss: 0.5595
  Epoch 6/10 [ 24.1%]  loss: 0.5637
  Epoch 6/10 [ 28.9%]  loss: 0.4786
  Epoch 6/10 [ 33.7%]  loss: 0.5607
  Epoch 6/10 [ 38.6%]  loss: 0.6143
  Epoch 6/10 [ 43.4%]  loss: 0.6072
  Epoch 6/10 [ 48.2%]  loss: 0.5331
  Epoch 6/10 [ 53.0%]  loss: 0.5406
  Epoch 6/10 [ 57.8%]  loss: 0.5331
  Epoch 6/10 [ 62.7%]  loss: 0.5195
  Epoch 6/10 [ 67.5%]  loss: 0.5159
  Epoch 6/10 [ 72.3%]  loss: 0.5205
  Epoch 6/10 [ 77.1%]  loss: 0.5364
  Epoch 6/10 [ 81.9%]  loss: 0.5442
  Epoch 6/10 [ 86.7%]  loss: 0.5504
  Epoch 6/10 [ 91.6%]  loss: 0.5372
  Epoch 6/10 [ 96.4%]  loss: 0.5060
  Epoch 6/10 [100.0%]  loss: 0.4870

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.21batch/s]

Epoch 6/10
Train Loss: 0.5401 | Train F1: 0.7235
Val Loss: 1.8890 | Val F1: 0.3428
Epoch Time: 38.33s

  Epoch 7/10 [  4.8%]  loss: 0.5338
  Epoch 7/10 [  9.6%]  loss: 0.4769
  Epoch 7/10 [ 14.5%]  loss: 0.4987
  Epoch 7/10 [ 19.3%]  loss: 0.5155
  Epoch 7/10 [ 24.1%]  loss: 0.5072
  Epoch 7/10 [ 28.9%]  loss: 0.4804
  Epoch 7/10 [ 33.7%]  loss: 0.4762
  Epoch 7/10 [ 38.6%]  loss: 0.4743
  Epoch 7/10 [ 43.4%]  loss: 0.4873
  Epoch 7/10 [ 48.2%]  loss: 0.5036
  Epoch 7/10 [ 53.0%]  loss: 0.5083
  Epoch 7/10 [ 57.8%]  loss: 0.5015
  Epoch 7/10 [ 62.7%]  loss: 0.5005
  Epoch 7/10 [ 67.5%]  loss: 0.5250
  Epoch 7/10 [ 72.3%]  loss: 0.4831
  Epoch 7/10 [ 77.1%]  loss: 0.4940
  Epoch 7/10 [ 81.9%]  loss: 0.4631
  Epoch 7/10 [ 86.7%]  loss: 0.5140
  Epoch 7/10 [ 91.6%]  loss: 0.5171
  Epoch 7/10 [ 96.4%]  loss: 0.4812
  Epoch 7/10 [100.0%]  loss: 0.5085

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.07batch/s]

Epoch 7/10
Train Loss: 0.4975 | Train F1: 0.7416
Val Loss: 1.8659 | Val F1: 0.3487
Epoch Time: 38.51s

  Epoch 8/10 [  4.8%]  loss: 0.5258
  Epoch 8/10 [  9.6%]  loss: 0.4966
  Epoch 8/10 [ 14.5%]  loss: 0.4883
  Epoch 8/10 [ 19.3%]  loss: 0.5207
  Epoch 8/10 [ 24.1%]  loss: 0.5380
  Epoch 8/10 [ 28.9%]  loss: 0.4760
  Epoch 8/10 [ 33.7%]  loss: 0.5444
  Epoch 8/10 [ 38.6%]  loss: 0.4654
  Epoch 8/10 [ 43.4%]  loss: 0.4742
  Epoch 8/10 [ 48.2%]  loss: 0.4866
  Epoch 8/10 [ 53.0%]  loss: 0.5008
  Epoch 8/10 [ 57.8%]  loss: 0.5388
  Epoch 8/10 [ 62.7%]  loss: 0.5107
  Epoch 8/10 [ 67.5%]  loss: 0.4612
  Epoch 8/10 [ 72.3%]  loss: 0.4664
  Epoch 8/10 [ 77.1%]  loss: 0.5055
  Epoch 8/10 [ 81.9%]  loss: 0.4968
  Epoch 8/10 [ 86.7%]  loss: 0.4727
  Epoch 8/10 [ 91.6%]  loss: 0.5379
  Epoch 8/10 [ 96.4%]  loss: 0.5213
  Epoch 8/10 [100.0%]  loss: 0.5252

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.23batch/s]

Epoch 8/10
Train Loss: 0.5023 | Train F1: 0.7458
Val Loss: 1.8795 | Val F1: 0.3316
Epoch Time: 38.43s

  Epoch 9/10 [  4.8%]  loss: 0.4956
  Epoch 9/10 [  9.6%]  loss: 0.5007
  Epoch 9/10 [ 14.5%]  loss: 0.4914
  Epoch 9/10 [ 19.3%]  loss: 0.4681
  Epoch 9/10 [ 24.1%]  loss: 0.4692
  Epoch 9/10 [ 28.9%]  loss: 0.4674
  Epoch 9/10 [ 33.7%]  loss: 0.4825
  Epoch 9/10 [ 38.6%]  loss: 0.5077
  Epoch 9/10 [ 43.4%]  loss: 0.4819
  Epoch 9/10 [ 48.2%]  loss: 0.4800
  Epoch 9/10 [ 53.0%]  loss: 0.4663
  Epoch 9/10 [ 57.8%]  loss: 0.4465
  Epoch 9/10 [ 62.7%]  loss: 0.4443
  Epoch 9/10 [ 67.5%]  loss: 0.4434
  Epoch 9/10 [ 72.3%]  loss: 0.4522
  Epoch 9/10 [ 77.1%]  loss: 0.4673
  Epoch 9/10 [ 81.9%]  loss: 0.4661
  Epoch 9/10 [ 86.7%]  loss: 0.4870
  Epoch 9/10 [ 91.6%]  loss: 0.4706
  Epoch 9/10 [ 96.4%]  loss: 0.4538
  Epoch 9/10 [100.0%]  loss: 0.5079

Validating: 100%|██████████| 50/50 [00:02<00:00, 19.32batch/s]

Epoch 9/10
Train Loss: 0.4734 | Train F1: 0.7614
Val Loss: 1.9290 | Val F1: 0.3604
Epoch Time: 38.38s

  Epoch 10/10 [  4.8%]  loss: 0.5180
  Epoch 10/10 [  9.6%]  loss: 0.4647
  Epoch 10/10 [ 14.5%]  loss: 0.4647
  Epoch 10/10 [ 19.3%]  loss: 0.4410
  Epoch 10/10 [ 24.1%]  loss: 0.4631
  Epoch 10/10 [ 28.9%]  loss: 0.4950
  Epoch 10/10 [ 33.7%]  loss: 0.4164
  Epoch 10/10 [ 38.6%]  loss: 0.4379
  Epoch 10/10 [ 43.4%]  loss: 0.4232
  Epoch 10/10 [ 48.2%]  loss: 0.4626
  Epoch 10/10 [ 53.0%]  loss: 0.4782
  Epoch 10/10 [ 57.8%]  loss: 0.4990
  Epoch 10/10 [ 62.7%]  loss: 0.4849
  Epoch 10/10 [ 67.5%]  loss: 0.5196
  Epoch 10/10 [ 72.3%]  loss: 0.4622
  Epoch 10/10 [ 77.1%]  loss: 0.5297
  Epoch 10/10 [ 81.9%]  loss: 0.4659
  Epoch 10/10 [ 86.7%]  loss: 0.4741
  Epoch 10/10 [ 91.6%]  loss: 0.4900
  Epoch 10/10 [ 96.4%]  loss: 0.4631
  Epoch 10/10 [100.0%]  loss: 0.5171

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.31batch/s]

Epoch 10/10
Train Loss: 0.4743 | Train F1: 0.7690
Val Loss: 1.9163 | Val F1: 0.3420
Epoch Time: 37.41s

Finalised: 380/1920 conv1 channels zeroed (19.8%)
Saved → trained_models/pwkd_r18_r20/pwkd_r18_r20_full.pth

Warming up pwkd_r18_r20...
Running inference...
  ratio 20% | F1: 0.2680 | params: 9,023,037

============================================================
  PWKD Option 1 (ResNet18) — pruning ratio 30%
============================================================
  Epoch 1/10 [  4.8%]  loss: 2.4296
  Epoch 1/10 [  9.6%]  loss: 2.9429
  Epoch 1/10 [ 14.5%]  loss: 2.8545
  Epoch 1/10 [ 19.3%]  loss: 2.3133
  Epoch 1/10 [ 24.1%]  loss: 1.7872
  Epoch 1/10 [ 28.9%]  loss: 1.7627
  Epoch 1/10 [ 33.7%]  loss: 1.6923
  Epoch 1/10 [ 38.6%]  loss: 1.8595
  Epoch 1/10 [ 43.4%]  loss: 1.5088
  Epoch 1/10 [ 48.2%]  loss: 1.4488
  Epoch 1/10 [ 53.0%]  loss: 1.3767
  Epoch 1/10 [ 57.8%]  loss: 1.3871
  Epoch 1/10 [ 62.7%]  loss: 1.2083
  Epoch 1/10 [ 67.5%]  loss: 1.3643
  Epoch 1/10 [ 72.3%]  loss: 1.2920
  Epoch 1/10 [ 77.1%]  loss: 1.3305
  Epoch 1/10 [ 81.9%]  loss: 1.1636
  Epoch 1/10 [ 86.7%]  loss: 1.1920
  Epoch 1/10 [ 91.6%]  loss: 1.0848
  Epoch 1/10 [ 96.4%]  loss: 1.1567
  Epoch 1/10 [100.0%]  loss: 1.0696

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.20batch/s]

Epoch 1/10
Train Loss: 1.6365 | Train F1: 0.4173
Val Loss: 2.2833 | Val F1: 0.2711
Epoch Time: 38.40s

  Epoch 2/10 [  4.8%]  loss: 1.0126
  Epoch 2/10 [  9.6%]  loss: 1.0458
  Epoch 2/10 [ 14.5%]  loss: 0.9142
  Epoch 2/10 [ 19.3%]  loss: 0.9531
  Epoch 2/10 [ 24.1%]  loss: 0.8848
  Epoch 2/10 [ 28.9%]  loss: 0.8936
  Epoch 2/10 [ 33.7%]  loss: 0.9050
  Epoch 2/10 [ 38.6%]  loss: 0.9092
  Epoch 2/10 [ 43.4%]  loss: 0.7695
  Epoch 2/10 [ 48.2%]  loss: 0.8713
  Epoch 2/10 [ 53.0%]  loss: 0.8531
  Epoch 2/10 [ 57.8%]  loss: 0.8430
  Epoch 2/10 [ 62.7%]  loss: 0.8068
  Epoch 2/10 [ 67.5%]  loss: 0.7640
  Epoch 2/10 [ 72.3%]  loss: 0.8459
  Epoch 2/10 [ 77.1%]  loss: 0.8059
  Epoch 2/10 [ 81.9%]  loss: 0.8169
  Epoch 2/10 [ 86.7%]  loss: 0.8838
  Epoch 2/10 [ 91.6%]  loss: 0.8834
  Epoch 2/10 [ 96.4%]  loss: 0.8074
  Epoch 2/10 [100.0%]  loss: 0.7862

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.30batch/s]

Epoch 2/10
Train Loss: 0.8703 | Train F1: 0.5875
Val Loss: 2.2370 | Val F1: 0.2726
Epoch Time: 38.55s

  Epoch 3/10 [  4.8%]  loss: 0.7917
  Epoch 3/10 [  9.6%]  loss: 0.7914
  Epoch 3/10 [ 14.5%]  loss: 0.8076
  Epoch 3/10 [ 19.3%]  loss: 0.8415
  Epoch 3/10 [ 24.1%]  loss: 0.8345
  Epoch 3/10 [ 28.9%]  loss: 0.9099
  Epoch 3/10 [ 33.7%]  loss: 0.7400
  Epoch 3/10 [ 38.6%]  loss: 0.8078
  Epoch 3/10 [ 43.4%]  loss: 0.7934
  Epoch 3/10 [ 48.2%]  loss: 0.7760
  Epoch 3/10 [ 53.0%]  loss: 0.7551
  Epoch 3/10 [ 57.8%]  loss: 0.8271
  Epoch 3/10 [ 62.7%]  loss: 0.7609
  Epoch 3/10 [ 67.5%]  loss: 0.7487
  Epoch 3/10 [ 72.3%]  loss: 0.7205
  Epoch 3/10 [ 77.1%]  loss: 0.6711
  Epoch 3/10 [ 81.9%]  loss: 0.7242
  Epoch 3/10 [ 86.7%]  loss: 0.6684
  Epoch 3/10 [ 91.6%]  loss: 0.7856
  Epoch 3/10 [ 96.4%]  loss: 0.6701
  Epoch 3/10 [100.0%]  loss: 0.8055

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.29batch/s]

Epoch 3/10
Train Loss: 0.7725 | Train F1: 0.6278
Val Loss: 1.9900 | Val F1: 0.3018
Epoch Time: 38.23s

  Epoch 4/10 [  4.8%]  loss: 0.7445
  Epoch 4/10 [  9.6%]  loss: 0.6890
  Epoch 4/10 [ 14.5%]  loss: 0.7135
  Epoch 4/10 [ 19.3%]  loss: 0.7666
  Epoch 4/10 [ 24.1%]  loss: 0.7274
  Epoch 4/10 [ 28.9%]  loss: 0.7259
  Epoch 4/10 [ 33.7%]  loss: 0.6775
  Epoch 4/10 [ 38.6%]  loss: 0.6322
  Epoch 4/10 [ 43.4%]  loss: 0.7035
  Epoch 4/10 [ 48.2%]  loss: 0.6406
  Epoch 4/10 [ 53.0%]  loss: 0.6539
  Epoch 4/10 [ 57.8%]  loss: 0.5900
  Epoch 4/10 [ 62.7%]  loss: 0.6546
  Epoch 4/10 [ 67.5%]  loss: 0.6531
  Epoch 4/10 [ 72.3%]  loss: 0.5905
  Epoch 4/10 [ 77.1%]  loss: 0.5656
  Epoch 4/10 [ 81.9%]  loss: 0.6391
  Epoch 4/10 [ 86.7%]  loss: 0.6068
  Epoch 4/10 [ 91.6%]  loss: 0.6181
  Epoch 4/10 [ 96.4%]  loss: 0.6222
  Epoch 4/10 [100.0%]  loss: 0.6527

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.26batch/s]

Epoch 4/10
Train Loss: 0.6604 | Train F1: 0.6738
Val Loss: 1.9155 | Val F1: 0.3055
Epoch Time: 38.44s

  Epoch 5/10 [  4.8%]  loss: 0.6457
  Epoch 5/10 [  9.6%]  loss: 0.7173
  Epoch 5/10 [ 14.5%]  loss: 0.6156
  Epoch 5/10 [ 19.3%]  loss: 0.6077
  Epoch 5/10 [ 24.1%]  loss: 0.6397
  Epoch 5/10 [ 28.9%]  loss: 0.6021
  Epoch 5/10 [ 33.7%]  loss: 0.6009
  Epoch 5/10 [ 38.6%]  loss: 0.5598
  Epoch 5/10 [ 43.4%]  loss: 0.5553
  Epoch 5/10 [ 48.2%]  loss: 0.5248
  Epoch 5/10 [ 53.0%]  loss: 0.5887
  Epoch 5/10 [ 57.8%]  loss: 0.5377
  Epoch 5/10 [ 62.7%]  loss: 0.5745
  Epoch 5/10 [ 67.5%]  loss: 0.6035
  Epoch 5/10 [ 72.3%]  loss: 0.5868
  Epoch 5/10 [ 77.1%]  loss: 0.5620
  Epoch 5/10 [ 81.9%]  loss: 0.5124
  Epoch 5/10 [ 86.7%]  loss: 0.5244
  Epoch 5/10 [ 91.6%]  loss: 0.5519
  Epoch 5/10 [ 96.4%]  loss: 0.5667
  Epoch 5/10 [100.0%]  loss: 0.4971

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.18batch/s]

Epoch 5/10
Train Loss: 0.5807 | Train F1: 0.7034
Val Loss: 1.9559 | Val F1: 0.3101
Epoch Time: 38.48s

  Epoch 6/10 [  4.8%]  loss: 0.5394
  Epoch 6/10 [  9.6%]  loss: 0.5195
  Epoch 6/10 [ 14.5%]  loss: 0.5363
  Epoch 6/10 [ 19.3%]  loss: 0.5365
  Epoch 6/10 [ 24.1%]  loss: 0.5739
  Epoch 6/10 [ 28.9%]  loss: 0.5490
  Epoch 6/10 [ 33.7%]  loss: 0.6077
  Epoch 6/10 [ 38.6%]  loss: 0.5714
  Epoch 6/10 [ 43.4%]  loss: 0.5394
  Epoch 6/10 [ 48.2%]  loss: 0.5646
  Epoch 6/10 [ 53.0%]  loss: 0.5070
  Epoch 6/10 [ 57.8%]  loss: 0.5649
  Epoch 6/10 [ 62.7%]  loss: 0.5041
  Epoch 6/10 [ 67.5%]  loss: 0.5270
  Epoch 6/10 [ 72.3%]  loss: 0.5193
  Epoch 6/10 [ 77.1%]  loss: 0.4806
  Epoch 6/10 [ 81.9%]  loss: 0.5090
  Epoch 6/10 [ 86.7%]  loss: 0.5000
  Epoch 6/10 [ 91.6%]  loss: 0.5109
  Epoch 6/10 [ 96.4%]  loss: 0.5190
  Epoch 6/10 [100.0%]  loss: 0.4947

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.22batch/s]

Epoch 6/10
Train Loss: 0.5326 | Train F1: 0.7258
Val Loss: 1.8734 | Val F1: 0.3331
Epoch Time: 38.22s

  Epoch 7/10 [  4.8%]  loss: 0.5076
  Epoch 7/10 [  9.6%]  loss: 0.4844
  Epoch 7/10 [ 14.5%]  loss: 0.4867
  Epoch 7/10 [ 19.3%]  loss: 0.5024
  Epoch 7/10 [ 24.1%]  loss: 0.5083
  Epoch 7/10 [ 28.9%]  loss: 0.4682
  Epoch 7/10 [ 33.7%]  loss: 0.4962
  Epoch 7/10 [ 38.6%]  loss: 0.4706
  Epoch 7/10 [ 43.4%]  loss: 0.5144
  Epoch 7/10 [ 48.2%]  loss: 0.4641
  Epoch 7/10 [ 53.0%]  loss: 0.4965
  Epoch 7/10 [ 57.8%]  loss: 0.4790
  Epoch 7/10 [ 62.7%]  loss: 0.4931
  Epoch 7/10 [ 67.5%]  loss: 0.4904
  Epoch 7/10 [ 72.3%]  loss: 0.4966
  Epoch 7/10 [ 77.1%]  loss: 0.4609
  Epoch 7/10 [ 81.9%]  loss: 0.4691
  Epoch 7/10 [ 86.7%]  loss: 0.4544
  Epoch 7/10 [ 91.6%]  loss: 0.4960
  Epoch 7/10 [ 96.4%]  loss: 0.4901
  Epoch 7/10 [100.0%]  loss: 0.4574

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.20batch/s]

Epoch 7/10
Train Loss: 0.4854 | Train F1: 0.7551
Val Loss: 1.8279 | Val F1: 0.3591
Epoch Time: 38.27s

  Epoch 8/10 [  4.8%]  loss: 0.4713
  Epoch 8/10 [  9.6%]  loss: 0.5282
  Epoch 8/10 [ 14.5%]  loss: 0.5262
  Epoch 8/10 [ 19.3%]  loss: 0.4786
  Epoch 8/10 [ 24.1%]  loss: 0.4858
  Epoch 8/10 [ 28.9%]  loss: 0.4676
  Epoch 8/10 [ 33.7%]  loss: 0.4672
  Epoch 8/10 [ 38.6%]  loss: 0.4874
  Epoch 8/10 [ 43.4%]  loss: 0.4506
  Epoch 8/10 [ 48.2%]  loss: 0.4483
  Epoch 8/10 [ 53.0%]  loss: 0.4414
  Epoch 8/10 [ 57.8%]  loss: 0.5190
  Epoch 8/10 [ 62.7%]  loss: 0.4761
  Epoch 8/10 [ 67.5%]  loss: 0.4726
  Epoch 8/10 [ 72.3%]  loss: 0.4489
  Epoch 8/10 [ 77.1%]  loss: 0.5004
  Epoch 8/10 [ 81.9%]  loss: 0.4723
  Epoch 8/10 [ 86.7%]  loss: 0.4488
  Epoch 8/10 [ 91.6%]  loss: 0.5603
  Epoch 8/10 [ 96.4%]  loss: 0.5360
  Epoch 8/10 [100.0%]  loss: 0.5227

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.31batch/s]

Epoch 8/10
Train Loss: 0.4857 | Train F1: 0.7526
Val Loss: 1.9466 | Val F1: 0.3209
Epoch Time: 38.29s

  Epoch 9/10 [  4.8%]  loss: 0.4926
  Epoch 9/10 [  9.6%]  loss: 0.5061
  Epoch 9/10 [ 14.5%]  loss: 0.5254
  Epoch 9/10 [ 19.3%]  loss: 0.4693
  Epoch 9/10 [ 24.1%]  loss: 0.4951
  Epoch 9/10 [ 28.9%]  loss: 0.4967
  Epoch 9/10 [ 33.7%]  loss: 0.5402
  Epoch 9/10 [ 38.6%]  loss: 0.5080
  Epoch 9/10 [ 43.4%]  loss: 0.4953
  Epoch 9/10 [ 48.2%]  loss: 0.4574
  Epoch 9/10 [ 53.0%]  loss: 0.4505
  Epoch 9/10 [ 57.8%]  loss: 0.4711
  Epoch 9/10 [ 62.7%]  loss: 0.4917
  Epoch 9/10 [ 67.5%]  loss: 0.4845
  Epoch 9/10 [ 72.3%]  loss: 0.4629
  Epoch 9/10 [ 77.1%]  loss: 0.4309
  Epoch 9/10 [ 81.9%]  loss: 0.4466
  Epoch 9/10 [ 86.7%]  loss: 0.4068
  Epoch 9/10 [ 91.6%]  loss: 0.4480
  Epoch 9/10 [ 96.4%]  loss: 0.4497
  Epoch 9/10 [100.0%]  loss: 0.4581

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.18batch/s]

Epoch 9/10
Train Loss: 0.4758 | Train F1: 0.7666
Val Loss: 1.8030 | Val F1: 0.3453
Epoch Time: 38.39s

  Epoch 10/10 [  4.8%]  loss: 0.4592
  Epoch 10/10 [  9.6%]  loss: 0.4309
  Epoch 10/10 [ 14.5%]  loss: 0.4281
  Epoch 10/10 [ 19.3%]  loss: 0.4196
  Epoch 10/10 [ 24.1%]  loss: 0.4319
  Epoch 10/10 [ 28.9%]  loss: 0.4646
  Epoch 10/10 [ 33.7%]  loss: 0.4428
  Epoch 10/10 [ 38.6%]  loss: 0.4371
  Epoch 10/10 [ 43.4%]  loss: 0.4365
  Epoch 10/10 [ 48.2%]  loss: 0.4244
  Epoch 10/10 [ 53.0%]  loss: 0.4325
  Epoch 10/10 [ 57.8%]  loss: 0.4372
  Epoch 10/10 [ 62.7%]  loss: 0.4413
  Epoch 10/10 [ 67.5%]  loss: 0.4490
  Epoch 10/10 [ 72.3%]  loss: 0.4499
  Epoch 10/10 [ 77.1%]  loss: 0.5011
  Epoch 10/10 [ 81.9%]  loss: 0.4715
  Epoch 10/10 [ 86.7%]  loss: 0.4648
  Epoch 10/10 [ 91.6%]  loss: 0.5090
  Epoch 10/10 [ 96.4%]  loss: 0.4889
  Epoch 10/10 [100.0%]  loss: 0.5030

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.18batch/s]

Epoch 10/10
Train Loss: 0.4529 | Train F1: 0.7739
Val Loss: 1.9226 | Val F1: 0.3128
Epoch Time: 38.45s

Finalised: 572/1920 conv1 channels zeroed (29.8%)
Saved → trained_models/pwkd_r18_r30/pwkd_r18_r30_full.pth

Warming up pwkd_r18_r30...
Running inference...
  ratio 30% | F1: 0.1004 | params: 7,930,365

============================================================
  PWKD Option 1 (ResNet18) — pruning ratio 35%
============================================================
  Epoch 1/10 [  4.8%]  loss: 2.6287
  Epoch 1/10 [  9.6%]  loss: 2.3757
  Epoch 1/10 [ 14.5%]  loss: 2.4243
  Epoch 1/10 [ 19.3%]  loss: 2.3557
  Epoch 1/10 [ 24.1%]  loss: 2.0898
  Epoch 1/10 [ 28.9%]  loss: 1.7405
  Epoch 1/10 [ 33.7%]  loss: 1.7056
  Epoch 1/10 [ 38.6%]  loss: 1.6173
  Epoch 1/10 [ 43.4%]  loss: 1.4094
  Epoch 1/10 [ 48.2%]  loss: 1.5281
  Epoch 1/10 [ 53.0%]  loss: 1.3777
  Epoch 1/10 [ 57.8%]  loss: 1.3176
  Epoch 1/10 [ 62.7%]  loss: 1.2301
  Epoch 1/10 [ 67.5%]  loss: 1.2482
  Epoch 1/10 [ 72.3%]  loss: 1.3145
  Epoch 1/10 [ 77.1%]  loss: 1.3658
  Epoch 1/10 [ 81.9%]  loss: 1.3387
  Epoch 1/10 [ 86.7%]  loss: 1.2896
  Epoch 1/10 [ 91.6%]  loss: 1.1294
  Epoch 1/10 [ 96.4%]  loss: 1.1366
  Epoch 1/10 [100.0%]  loss: 1.1814

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.19batch/s]

Epoch 1/10
Train Loss: 1.6149 | Train F1: 0.4284
Val Loss: 2.3580 | Val F1: 0.2284
Epoch Time: 37.56s

  Epoch 2/10 [  4.8%]  loss: 1.1335
  Epoch 2/10 [  9.6%]  loss: 1.1098
  Epoch 2/10 [ 14.5%]  loss: 0.9450
  Epoch 2/10 [ 19.3%]  loss: 1.1031
  Epoch 2/10 [ 24.1%]  loss: 0.9751
  Epoch 2/10 [ 28.9%]  loss: 0.9055
  Epoch 2/10 [ 33.7%]  loss: 0.9474
  Epoch 2/10 [ 38.6%]  loss: 0.9045
  Epoch 2/10 [ 43.4%]  loss: 1.0492
  Epoch 2/10 [ 48.2%]  loss: 0.9309
  Epoch 2/10 [ 53.0%]  loss: 0.8396
  Epoch 2/10 [ 57.8%]  loss: 0.8141
  Epoch 2/10 [ 62.7%]  loss: 0.8238
  Epoch 2/10 [ 67.5%]  loss: 0.7979
  Epoch 2/10 [ 72.3%]  loss: 0.8015
  Epoch 2/10 [ 77.1%]  loss: 0.8205
  Epoch 2/10 [ 81.9%]  loss: 0.7678
  Epoch 2/10 [ 86.7%]  loss: 0.7913
  Epoch 2/10 [ 91.6%]  loss: 0.8092
  Epoch 2/10 [ 96.4%]  loss: 0.7627
  Epoch 2/10 [100.0%]  loss: 0.7731

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.23batch/s]

Epoch 2/10
Train Loss: 0.8970 | Train F1: 0.5731
Val Loss: 2.0369 | Val F1: 0.2952
Epoch Time: 38.31s

  Epoch 3/10 [  4.8%]  loss: 0.7606
  Epoch 3/10 [  9.6%]  loss: 0.7117
  Epoch 3/10 [ 14.5%]  loss: 0.8192
  Epoch 3/10 [ 19.3%]  loss: 0.7192
  Epoch 3/10 [ 24.1%]  loss: 0.7240
  Epoch 3/10 [ 28.9%]  loss: 0.6933
  Epoch 3/10 [ 33.7%]  loss: 0.7245
  Epoch 3/10 [ 38.6%]  loss: 0.6568
  Epoch 3/10 [ 43.4%]  loss: 0.7029
  Epoch 3/10 [ 48.2%]  loss: 0.6593
  Epoch 3/10 [ 53.0%]  loss: 0.7067
  Epoch 3/10 [ 57.8%]  loss: 0.6347
  Epoch 3/10 [ 62.7%]  loss: 0.7054
  Epoch 3/10 [ 67.5%]  loss: 0.7504
  Epoch 3/10 [ 72.3%]  loss: 0.6864
  Epoch 3/10 [ 77.1%]  loss: 0.6672
  Epoch 3/10 [ 81.9%]  loss: 0.7070
  Epoch 3/10 [ 86.7%]  loss: 0.6840
  Epoch 3/10 [ 91.6%]  loss: 0.6341
  Epoch 3/10 [ 96.4%]  loss: 0.6540
  Epoch 3/10 [100.0%]  loss: 0.6017

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.27batch/s]

Epoch 3/10
Train Loss: 0.6965 | Train F1: 0.6456
Val Loss: 1.9161 | Val F1: 0.3169
Epoch Time: 38.18s

  Epoch 4/10 [  4.8%]  loss: 0.6100
  Epoch 4/10 [  9.6%]  loss: 0.6141
  Epoch 4/10 [ 14.5%]  loss: 0.6338
  Epoch 4/10 [ 19.3%]  loss: 0.6178
  Epoch 4/10 [ 24.1%]  loss: 0.6323
  Epoch 4/10 [ 28.9%]  loss: 0.5760
  Epoch 4/10 [ 33.7%]  loss: 0.5735
  Epoch 4/10 [ 38.6%]  loss: 0.5986
  Epoch 4/10 [ 43.4%]  loss: 0.6331
  Epoch 4/10 [ 48.2%]  loss: 0.5661
  Epoch 4/10 [ 53.0%]  loss: 0.6011
  Epoch 4/10 [ 57.8%]  loss: 0.6016
  Epoch 4/10 [ 62.7%]  loss: 0.5784
  Epoch 4/10 [ 67.5%]  loss: 0.5694
  Epoch 4/10 [ 72.3%]  loss: 0.6053
  Epoch 4/10 [ 77.1%]  loss: 0.6015
  Epoch 4/10 [ 81.9%]  loss: 0.5607
  Epoch 4/10 [ 86.7%]  loss: 0.5898
  Epoch 4/10 [ 91.6%]  loss: 0.5581
  Epoch 4/10 [ 96.4%]  loss: 0.5703
  Epoch 4/10 [100.0%]  loss: 0.5706

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.31batch/s]

Epoch 4/10
Train Loss: 0.5937 | Train F1: 0.6932
Val Loss: 2.0260 | Val F1: 0.3186
Epoch Time: 38.25s

  Epoch 5/10 [  4.8%]  loss: 0.5367
  Epoch 5/10 [  9.6%]  loss: 0.5528
  Epoch 5/10 [ 14.5%]  loss: 0.5729
  Epoch 5/10 [ 19.3%]  loss: 0.5581
  Epoch 5/10 [ 24.1%]  loss: 0.6086
  Epoch 5/10 [ 28.9%]  loss: 0.5577
  Epoch 5/10 [ 33.7%]  loss: 0.5418
  Epoch 5/10 [ 38.6%]  loss: 0.5559
  Epoch 5/10 [ 43.4%]  loss: 0.5553
  Epoch 5/10 [ 48.2%]  loss: 0.5469
  Epoch 5/10 [ 53.0%]  loss: 0.5759
  Epoch 5/10 [ 57.8%]  loss: 0.5232
  Epoch 5/10 [ 62.7%]  loss: 0.5149
  Epoch 5/10 [ 67.5%]  loss: 0.5657
  Epoch 5/10 [ 72.3%]  loss: 0.5036
  Epoch 5/10 [ 77.1%]  loss: 0.5633
  Epoch 5/10 [ 81.9%]  loss: 0.5458
  Epoch 5/10 [ 86.7%]  loss: 0.5619
  Epoch 5/10 [ 91.6%]  loss: 0.5532
  Epoch 5/10 [ 96.4%]  loss: 0.5676
  Epoch 5/10 [100.0%]  loss: 0.5896

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.22batch/s]

Epoch 5/10
Train Loss: 0.5544 | Train F1: 0.7143
Val Loss: 1.8673 | Val F1: 0.3353
Epoch Time: 38.16s

  Epoch 6/10 [  4.8%]  loss: 0.5804
  Epoch 6/10 [  9.6%]  loss: 0.5517
  Epoch 6/10 [ 14.5%]  loss: 0.5535
  Epoch 6/10 [ 19.3%]  loss: 0.5222
  Epoch 6/10 [ 24.1%]  loss: 0.5144
  Epoch 6/10 [ 28.9%]  loss: 0.5556
  Epoch 6/10 [ 33.7%]  loss: 0.5860
  Epoch 6/10 [ 38.6%]  loss: 0.6056
  Epoch 6/10 [ 43.4%]  loss: 0.6288
  Epoch 6/10 [ 48.2%]  loss: 0.5393
  Epoch 6/10 [ 53.0%]  loss: 0.5752
  Epoch 6/10 [ 57.8%]  loss: 0.5633
  Epoch 6/10 [ 62.7%]  loss: 0.5797
  Epoch 6/10 [ 67.5%]  loss: 0.5920
  Epoch 6/10 [ 72.3%]  loss: 0.5405
  Epoch 6/10 [ 77.1%]  loss: 0.5252
  Epoch 6/10 [ 81.9%]  loss: 0.5438
  Epoch 6/10 [ 86.7%]  loss: 0.5163
  Epoch 6/10 [ 91.6%]  loss: 0.4941
  Epoch 6/10 [ 96.4%]  loss: 0.5713
  Epoch 6/10 [100.0%]  loss: 0.5654

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.27batch/s]

Epoch 6/10
Train Loss: 0.5573 | Train F1: 0.7162
Val Loss: 1.8692 | Val F1: 0.3376
Epoch Time: 38.35s

  Epoch 7/10 [  4.8%]  loss: 0.4756
  Epoch 7/10 [  9.6%]  loss: 0.5286
  Epoch 7/10 [ 14.5%]  loss: 0.5610
  Epoch 7/10 [ 19.3%]  loss: 0.5220
  Epoch 7/10 [ 24.1%]  loss: 0.5605
  Epoch 7/10 [ 28.9%]  loss: 0.5247
  Epoch 7/10 [ 33.7%]  loss: 0.5698
  Epoch 7/10 [ 38.6%]  loss: 0.5864
  Epoch 7/10 [ 43.4%]  loss: 0.4748
  Epoch 7/10 [ 48.2%]  loss: 0.5515
  Epoch 7/10 [ 53.0%]  loss: 0.5157
  Epoch 7/10 [ 57.8%]  loss: 0.5597
  Epoch 7/10 [ 62.7%]  loss: 0.5446
  Epoch 7/10 [ 67.5%]  loss: 0.5454
  Epoch 7/10 [ 72.3%]  loss: 0.5668
  Epoch 7/10 [ 77.1%]  loss: 0.5540
  Epoch 7/10 [ 81.9%]  loss: 0.5120
  Epoch 7/10 [ 86.7%]  loss: 0.5203
  Epoch 7/10 [ 91.6%]  loss: 0.5088
  Epoch 7/10 [ 96.4%]  loss: 0.5359
  Epoch 7/10 [100.0%]  loss: 0.5869

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.23batch/s]

Epoch 7/10
Train Loss: 0.5378 | Train F1: 0.7380
Val Loss: 1.9639 | Val F1: 0.3363
Epoch Time: 38.15s

  Epoch 8/10 [  4.8%]  loss: 0.5912
  Epoch 8/10 [  9.6%]  loss: 0.5876
  Epoch 8/10 [ 14.5%]  loss: 0.5841
  Epoch 8/10 [ 19.3%]  loss: 0.5343
  Epoch 8/10 [ 24.1%]  loss: 0.5387
  Epoch 8/10 [ 28.9%]  loss: 0.4978
  Epoch 8/10 [ 33.7%]  loss: 0.5059
  Epoch 8/10 [ 38.6%]  loss: 0.4855
  Epoch 8/10 [ 43.4%]  loss: 0.4992
  Epoch 8/10 [ 48.2%]  loss: 0.4870
  Epoch 8/10 [ 53.0%]  loss: 0.4994
  Epoch 8/10 [ 57.8%]  loss: 0.4821
  Epoch 8/10 [ 62.7%]  loss: 0.4810
  Epoch 8/10 [ 67.5%]  loss: 0.4651
  Epoch 8/10 [ 72.3%]  loss: 0.4804
  Epoch 8/10 [ 77.1%]  loss: 0.4651
  Epoch 8/10 [ 81.9%]  loss: 0.4690
  Epoch 8/10 [ 86.7%]  loss: 0.4750
  Epoch 8/10 [ 91.6%]  loss: 0.4667
  Epoch 8/10 [ 96.4%]  loss: 0.4414
  Epoch 8/10 [100.0%]  loss: 0.5403

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.24batch/s]

Epoch 8/10
Train Loss: 0.5032 | Train F1: 0.7545
Val Loss: 1.9255 | Val F1: 0.3355
Epoch Time: 38.24s

  Epoch 9/10 [  4.8%]  loss: 0.5163
  Epoch 9/10 [  9.6%]  loss: 0.5305
  Epoch 9/10 [ 14.5%]  loss: 0.4879
  Epoch 9/10 [ 19.3%]  loss: 0.4804
  Epoch 9/10 [ 24.1%]  loss: 0.5407
  Epoch 9/10 [ 28.9%]  loss: 0.5058
  Epoch 9/10 [ 33.7%]  loss: 0.4842
  Epoch 9/10 [ 38.6%]  loss: 0.4701
  Epoch 9/10 [ 43.4%]  loss: 0.4692
  Epoch 9/10 [ 48.2%]  loss: 0.5040
  Epoch 9/10 [ 53.0%]  loss: 0.4866
  Epoch 9/10 [ 57.8%]  loss: 0.4890
  Epoch 9/10 [ 62.7%]  loss: 0.4964
  Epoch 9/10 [ 67.5%]  loss: 0.5054
  Epoch 9/10 [ 72.3%]  loss: 0.4999
  Epoch 9/10 [ 77.1%]  loss: 0.4966
  Epoch 9/10 [ 81.9%]  loss: 0.4625
  Epoch 9/10 [ 86.7%]  loss: 0.5024
  Epoch 9/10 [ 91.6%]  loss: 0.4952
  Epoch 9/10 [ 96.4%]  loss: 0.5360
  Epoch 9/10 [100.0%]  loss: 0.5542

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.28batch/s]

Epoch 9/10
Train Loss: 0.5000 | Train F1: 0.7552
Val Loss: 1.9067 | Val F1: 0.3396
Epoch Time: 37.50s

  Epoch 10/10 [  4.8%]  loss: 0.6119
  Epoch 10/10 [  9.6%]  loss: 0.5754
  Epoch 10/10 [ 14.5%]  loss: 0.5607
  Epoch 10/10 [ 19.3%]  loss: 0.5863
  Epoch 10/10 [ 24.1%]  loss: 0.5253
  Epoch 10/10 [ 28.9%]  loss: 0.5206
  Epoch 10/10 [ 33.7%]  loss: 0.5030
  Epoch 10/10 [ 38.6%]  loss: 0.5282
  Epoch 10/10 [ 43.4%]  loss: 0.5166
  Epoch 10/10 [ 48.2%]  loss: 0.4667
  Epoch 10/10 [ 53.0%]  loss: 0.4690
  Epoch 10/10 [ 57.8%]  loss: 0.4689
  Epoch 10/10 [ 62.7%]  loss: 0.4883
  Epoch 10/10 [ 67.5%]  loss: 0.4518
  Epoch 10/10 [ 72.3%]  loss: 0.4774
  Epoch 10/10 [ 77.1%]  loss: 0.4506
  Epoch 10/10 [ 81.9%]  loss: 0.4880
  Epoch 10/10 [ 86.7%]  loss: 0.4431
  Epoch 10/10 [ 91.6%]  loss: 0.4734
  Epoch 10/10 [ 96.4%]  loss: 0.4964
  Epoch 10/10 [100.0%]  loss: 0.4656

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.14batch/s]

Epoch 10/10
Train Loss: 0.5037 | Train F1: 0.7541
Val Loss: 1.9843 | Val F1: 0.3221
Epoch Time: 37.34s

Finalised: 668/1920 conv1 channels zeroed (34.8%)
Saved → trained_models/pwkd_r18_r35/pwkd_r18_r35_full.pth

Warming up pwkd_r18_r35...
Running inference...
  ratio 35% | F1: 0.0352 | params: 7,375,101

============================================================
  PWKD Option 1 (ResNet18) — pruning ratio 40%
============================================================
  Epoch 1/10 [  4.8%]  loss: 2.4466
  Epoch 1/10 [  9.6%]  loss: 2.3698
  Epoch 1/10 [ 14.5%]  loss: 2.4166
  Epoch 1/10 [ 19.3%]  loss: 2.2300
  Epoch 1/10 [ 24.1%]  loss: 1.8612
  Epoch 1/10 [ 28.9%]  loss: 2.0181
  Epoch 1/10 [ 33.7%]  loss: 1.9464
  Epoch 1/10 [ 38.6%]  loss: 1.8529
  Epoch 1/10 [ 43.4%]  loss: 1.5988
  Epoch 1/10 [ 48.2%]  loss: 1.6044
  Epoch 1/10 [ 53.0%]  loss: 1.2918
  Epoch 1/10 [ 57.8%]  loss: 1.2072
  Epoch 1/10 [ 62.7%]  loss: 1.4433
  Epoch 1/10 [ 67.5%]  loss: 1.5163
  Epoch 1/10 [ 72.3%]  loss: 1.3651
  Epoch 1/10 [ 77.1%]  loss: 1.2063
  Epoch 1/10 [ 81.9%]  loss: 1.2535
  Epoch 1/10 [ 86.7%]  loss: 1.2572
  Epoch 1/10 [ 91.6%]  loss: 1.1098
  Epoch 1/10 [ 96.4%]  loss: 1.1813
  Epoch 1/10 [100.0%]  loss: 1.1239

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.17batch/s]

Epoch 1/10
Train Loss: 1.6395 | Train F1: 0.4128
Val Loss: 2.3613 | Val F1: 0.2525
Epoch Time: 38.32s

  Epoch 2/10 [  4.8%]  loss: 0.9953
  Epoch 2/10 [  9.6%]  loss: 1.0121
  Epoch 2/10 [ 14.5%]  loss: 1.0677
  Epoch 2/10 [ 19.3%]  loss: 1.0526
  Epoch 2/10 [ 24.1%]  loss: 1.0227
  Epoch 2/10 [ 28.9%]  loss: 1.0577
  Epoch 2/10 [ 33.7%]  loss: 0.9504
  Epoch 2/10 [ 38.6%]  loss: 0.9564
  Epoch 2/10 [ 43.4%]  loss: 0.9564
  Epoch 2/10 [ 48.2%]  loss: 0.8625
  Epoch 2/10 [ 53.0%]  loss: 0.8706
  Epoch 2/10 [ 57.8%]  loss: 0.9642
  Epoch 2/10 [ 62.7%]  loss: 0.9748
  Epoch 2/10 [ 67.5%]  loss: 0.9194
  Epoch 2/10 [ 72.3%]  loss: 0.9001
  Epoch 2/10 [ 77.1%]  loss: 0.8587
  Epoch 2/10 [ 81.9%]  loss: 0.8915
  Epoch 2/10 [ 86.7%]  loss: 0.8609
  Epoch 2/10 [ 91.6%]  loss: 0.8011
  Epoch 2/10 [ 96.4%]  loss: 0.7417
  Epoch 2/10 [100.0%]  loss: 0.8038

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.23batch/s]

Epoch 2/10
Train Loss: 0.9311 | Train F1: 0.5742
Val Loss: 2.0928 | Val F1: 0.2785
Epoch Time: 37.41s

  Epoch 3/10 [  4.8%]  loss: 0.7611
  Epoch 3/10 [  9.6%]  loss: 0.8061
  Epoch 3/10 [ 14.5%]  loss: 0.7681
  Epoch 3/10 [ 19.3%]  loss: 0.8544
  Epoch 3/10 [ 24.1%]  loss: 0.7463
  Epoch 3/10 [ 28.9%]  loss: 0.7059
  Epoch 3/10 [ 33.7%]  loss: 0.6885
  Epoch 3/10 [ 38.6%]  loss: 0.6634
  Epoch 3/10 [ 43.4%]  loss: 0.7438
  Epoch 3/10 [ 48.2%]  loss: 0.7242
  Epoch 3/10 [ 53.0%]  loss: 0.6718
  Epoch 3/10 [ 57.8%]  loss: 0.6742
  Epoch 3/10 [ 62.7%]  loss: 0.7334
  Epoch 3/10 [ 67.5%]  loss: 0.7451
  Epoch 3/10 [ 72.3%]  loss: 0.6841
  Epoch 3/10 [ 77.1%]  loss: 0.6381
  Epoch 3/10 [ 81.9%]  loss: 0.6869
  Epoch 3/10 [ 86.7%]  loss: 0.7432
  Epoch 3/10 [ 91.6%]  loss: 0.6159
  Epoch 3/10 [ 96.4%]  loss: 0.6399
  Epoch 3/10 [100.0%]  loss: 0.6720

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.12batch/s]

Epoch 3/10
Train Loss: 0.7132 | Train F1: 0.6349
Val Loss: 1.9199 | Val F1: 0.3117
Epoch Time: 38.28s

  Epoch 4/10 [  4.8%]  loss: 0.6443
  Epoch 4/10 [  9.6%]  loss: 0.6602
  Epoch 4/10 [ 14.5%]  loss: 0.6202
  Epoch 4/10 [ 19.3%]  loss: 0.6735
  Epoch 4/10 [ 24.1%]  loss: 0.6126
  Epoch 4/10 [ 28.9%]  loss: 0.5973
  Epoch 4/10 [ 33.7%]  loss: 0.6063
  Epoch 4/10 [ 38.6%]  loss: 0.6304
  Epoch 4/10 [ 43.4%]  loss: 0.6308
  Epoch 4/10 [ 48.2%]  loss: 0.6069
  Epoch 4/10 [ 53.0%]  loss: 0.6260
  Epoch 4/10 [ 57.8%]  loss: 0.5548
  Epoch 4/10 [ 62.7%]  loss: 0.6004
  Epoch 4/10 [ 67.5%]  loss: 0.6058
  Epoch 4/10 [ 72.3%]  loss: 0.6172
  Epoch 4/10 [ 77.1%]  loss: 0.5716
  Epoch 4/10 [ 81.9%]  loss: 0.5496
  Epoch 4/10 [ 86.7%]  loss: 0.6288
  Epoch 4/10 [ 91.6%]  loss: 0.5479
  Epoch 4/10 [ 96.4%]  loss: 0.6063
  Epoch 4/10 [100.0%]  loss: 0.6027

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.24batch/s]

Epoch 4/10
Train Loss: 0.6093 | Train F1: 0.6866
Val Loss: 1.8993 | Val F1: 0.3278
Epoch Time: 38.26s

  Epoch 5/10 [  4.8%]  loss: 0.6139
  Epoch 5/10 [  9.6%]  loss: 0.6059
  Epoch 5/10 [ 14.5%]  loss: 0.5781
  Epoch 5/10 [ 19.3%]  loss: 0.5957
  Epoch 5/10 [ 24.1%]  loss: 0.5832
  Epoch 5/10 [ 28.9%]  loss: 0.6031
  Epoch 5/10 [ 33.7%]  loss: 0.5874
  Epoch 5/10 [ 38.6%]  loss: 0.6077
  Epoch 5/10 [ 43.4%]  loss: 0.6064
  Epoch 5/10 [ 48.2%]  loss: 0.6574
  Epoch 5/10 [ 53.0%]  loss: 0.7003
  Epoch 5/10 [ 57.8%]  loss: 0.6291
  Epoch 5/10 [ 62.7%]  loss: 0.5982
  Epoch 5/10 [ 67.5%]  loss: 0.5740
  Epoch 5/10 [ 72.3%]  loss: 0.5717
  Epoch 5/10 [ 77.1%]  loss: 0.5740
  Epoch 5/10 [ 81.9%]  loss: 0.5431
  Epoch 5/10 [ 86.7%]  loss: 0.6397
  Epoch 5/10 [ 91.6%]  loss: 0.5396
  Epoch 5/10 [ 96.4%]  loss: 0.5535
  Epoch 5/10 [100.0%]  loss: 0.5658

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.14batch/s]

Epoch 5/10
Train Loss: 0.5969 | Train F1: 0.7000
Val Loss: 2.0592 | Val F1: 0.3103
Epoch Time: 38.26s

  Epoch 6/10 [  4.8%]  loss: 0.5657
  Epoch 6/10 [  9.6%]  loss: 0.5829
  Epoch 6/10 [ 14.5%]  loss: 0.6155
  Epoch 6/10 [ 19.3%]  loss: 0.5139
  Epoch 6/10 [ 24.1%]  loss: 0.6438
  Epoch 6/10 [ 28.9%]  loss: 0.5334
  Epoch 6/10 [ 33.7%]  loss: 0.5531
  Epoch 6/10 [ 38.6%]  loss: 0.5378
  Epoch 6/10 [ 43.4%]  loss: 0.5687
  Epoch 6/10 [ 48.2%]  loss: 0.5213
  Epoch 6/10 [ 53.0%]  loss: 0.5175
  Epoch 6/10 [ 57.8%]  loss: 0.4964
  Epoch 6/10 [ 62.7%]  loss: 0.5306
  Epoch 6/10 [ 67.5%]  loss: 0.5033
  Epoch 6/10 [ 72.3%]  loss: 0.5633
  Epoch 6/10 [ 77.1%]  loss: 0.5539
  Epoch 6/10 [ 81.9%]  loss: 0.5241
  Epoch 6/10 [ 86.7%]  loss: 0.5060
  Epoch 6/10 [ 91.6%]  loss: 0.5082
  Epoch 6/10 [ 96.4%]  loss: 0.5230
  Epoch 6/10 [100.0%]  loss: 0.5144

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.22batch/s]

Epoch 6/10
Train Loss: 0.5421 | Train F1: 0.7284
Val Loss: 1.8929 | Val F1: 0.3294
Epoch Time: 38.46s

  Epoch 7/10 [  4.8%]  loss: 0.5003
  Epoch 7/10 [  9.6%]  loss: 0.5027
  Epoch 7/10 [ 14.5%]  loss: 0.5258
  Epoch 7/10 [ 19.3%]  loss: 0.5043
  Epoch 7/10 [ 24.1%]  loss: 0.5052
  Epoch 7/10 [ 28.9%]  loss: 0.4856
  Epoch 7/10 [ 33.7%]  loss: 0.4742
  Epoch 7/10 [ 38.6%]  loss: 0.4994
  Epoch 7/10 [ 43.4%]  loss: 0.4739
  Epoch 7/10 [ 48.2%]  loss: 0.4422
  Epoch 7/10 [ 53.0%]  loss: 0.4603
  Epoch 7/10 [ 57.8%]  loss: 0.4989
  Epoch 7/10 [ 62.7%]  loss: 0.4928
  Epoch 7/10 [ 67.5%]  loss: 0.5361
  Epoch 7/10 [ 72.3%]  loss: 0.4469
  Epoch 7/10 [ 77.1%]  loss: 0.4395
  Epoch 7/10 [ 81.9%]  loss: 0.4501
  Epoch 7/10 [ 86.7%]  loss: 0.4981
  Epoch 7/10 [ 91.6%]  loss: 0.4597
  Epoch 7/10 [ 96.4%]  loss: 0.5344
  Epoch 7/10 [100.0%]  loss: 0.4853

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.02batch/s]

Epoch 7/10
Train Loss: 0.4865 | Train F1: 0.7484
Val Loss: 1.8479 | Val F1: 0.3500
Epoch Time: 38.32s

  Epoch 8/10 [  4.8%]  loss: 0.5290
  Epoch 8/10 [  9.6%]  loss: 0.4794
  Epoch 8/10 [ 14.5%]  loss: 0.4480
  Epoch 8/10 [ 19.3%]  loss: 0.4733
  Epoch 8/10 [ 24.1%]  loss: 0.4475
  Epoch 8/10 [ 28.9%]  loss: 0.4583
  Epoch 8/10 [ 33.7%]  loss: 0.4778
  Epoch 8/10 [ 38.6%]  loss: 0.5009
  Epoch 8/10 [ 43.4%]  loss: 0.5139
  Epoch 8/10 [ 48.2%]  loss: 0.5087
  Epoch 8/10 [ 53.0%]  loss: 0.5371
  Epoch 8/10 [ 57.8%]  loss: 0.4746
  Epoch 8/10 [ 62.7%]  loss: 0.4686
  Epoch 8/10 [ 67.5%]  loss: 0.4800
  Epoch 8/10 [ 72.3%]  loss: 0.4547
  Epoch 8/10 [ 77.1%]  loss: 0.4873
  Epoch 8/10 [ 81.9%]  loss: 0.4686
  Epoch 8/10 [ 86.7%]  loss: 0.4256
  Epoch 8/10 [ 91.6%]  loss: 0.4508
  Epoch 8/10 [ 96.4%]  loss: 0.4196
  Epoch 8/10 [100.0%]  loss: 0.4301

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.32batch/s]

Epoch 8/10
Train Loss: 0.4736 | Train F1: 0.7617
Val Loss: 1.8354 | Val F1: 0.3683
Epoch Time: 38.34s

  Epoch 9/10 [  4.8%]  loss: 0.4854
  Epoch 9/10 [  9.6%]  loss: 0.4548
  Epoch 9/10 [ 14.5%]  loss: 0.4758
  Epoch 9/10 [ 19.3%]  loss: 0.4783
  Epoch 9/10 [ 24.1%]  loss: 0.4761
  Epoch 9/10 [ 28.9%]  loss: 0.4725
  Epoch 9/10 [ 33.7%]  loss: 0.4673
  Epoch 9/10 [ 38.6%]  loss: 0.5165
  Epoch 9/10 [ 43.4%]  loss: 0.5201
  Epoch 9/10 [ 48.2%]  loss: 0.5285
  Epoch 9/10 [ 53.0%]  loss: 0.5151
  Epoch 9/10 [ 57.8%]  loss: 0.4862
  Epoch 9/10 [ 62.7%]  loss: 0.4492
  Epoch 9/10 [ 67.5%]  loss: 0.4455
  Epoch 9/10 [ 72.3%]  loss: 0.4927
  Epoch 9/10 [ 77.1%]  loss: 0.4712
  Epoch 9/10 [ 81.9%]  loss: 0.4473
  Epoch 9/10 [ 86.7%]  loss: 0.4650
  Epoch 9/10 [ 91.6%]  loss: 0.4541
  Epoch 9/10 [ 96.4%]  loss: 0.4560
  Epoch 9/10 [100.0%]  loss: 0.4554

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.21batch/s]

Epoch 9/10
Train Loss: 0.4771 | Train F1: 0.7568
Val Loss: 1.9477 | Val F1: 0.3273
Epoch Time: 38.36s

  Epoch 10/10 [  4.8%]  loss: 0.4174
  Epoch 10/10 [  9.6%]  loss: 0.4486
  Epoch 10/10 [ 14.5%]  loss: 0.4543
  Epoch 10/10 [ 19.3%]  loss: 0.4628
  Epoch 10/10 [ 24.1%]  loss: 0.4123
  Epoch 10/10 [ 28.9%]  loss: 0.4251
  Epoch 10/10 [ 33.7%]  loss: 0.4445
  Epoch 10/10 [ 38.6%]  loss: 0.4433
  Epoch 10/10 [ 43.4%]  loss: 0.4216
  Epoch 10/10 [ 48.2%]  loss: 0.4622
  Epoch 10/10 [ 53.0%]  loss: 0.4098
  Epoch 10/10 [ 57.8%]  loss: 0.4288
  Epoch 10/10 [ 62.7%]  loss: 0.4436
  Epoch 10/10 [ 67.5%]  loss: 0.4574
  Epoch 10/10 [ 72.3%]  loss: 0.4602
  Epoch 10/10 [ 77.1%]  loss: 0.4599
  Epoch 10/10 [ 81.9%]  loss: 0.4256
  Epoch 10/10 [ 86.7%]  loss: 0.4288
  Epoch 10/10 [ 91.6%]  loss: 0.4304
  Epoch 10/10 [ 96.4%]  loss: 0.4900
  Epoch 10/10 [100.0%]  loss: 0.5136

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.20batch/s]

Epoch 10/10
Train Loss: 0.4439 | Train F1: 0.7848
Val Loss: 2.1469 | Val F1: 0.2926
Epoch Time: 38.29s

Finalised: 764/1920 conv1 channels zeroed (39.8%)
Saved → trained_models/pwkd_r18_r40/pwkd_r18_r40_full.pth

Warming up pwkd_r18_r40...
Running inference...
  ratio 40% | F1: 0.0124 | params: 6,831,933

============================================================
  PWKD Option 1 (ResNet18) — pruning ratio 45%
============================================================
  Epoch 1/10 [  4.8%]  loss: 2.3931
  Epoch 1/10 [  9.6%]  loss: 2.7508
  Epoch 1/10 [ 14.5%]  loss: 2.0741
  Epoch 1/10 [ 19.3%]  loss: 2.1114
  Epoch 1/10 [ 24.1%]  loss: 1.9206
  Epoch 1/10 [ 28.9%]  loss: 1.6413
  Epoch 1/10 [ 33.7%]  loss: 1.7314
  Epoch 1/10 [ 38.6%]  loss: 1.5695
  Epoch 1/10 [ 43.4%]  loss: 1.4591
  Epoch 1/10 [ 48.2%]  loss: 1.5513
  Epoch 1/10 [ 53.0%]  loss: 1.5731
  Epoch 1/10 [ 57.8%]  loss: 1.3912
  Epoch 1/10 [ 62.7%]  loss: 1.1693
  Epoch 1/10 [ 67.5%]  loss: 1.2951
  Epoch 1/10 [ 72.3%]  loss: 1.3202
  Epoch 1/10 [ 77.1%]  loss: 1.4159
  Epoch 1/10 [ 81.9%]  loss: 1.2483
  Epoch 1/10 [ 86.7%]  loss: 1.2895
  Epoch 1/10 [ 91.6%]  loss: 1.1665
  Epoch 1/10 [ 96.4%]  loss: 1.2006
  Epoch 1/10 [100.0%]  loss: 1.1204

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.26batch/s]

Epoch 1/10
Train Loss: 1.5958 | Train F1: 0.4254
Val Loss: 2.1459 | Val F1: 0.2474
Epoch Time: 37.45s

  Epoch 2/10 [  4.8%]  loss: 1.0890
  Epoch 2/10 [  9.6%]  loss: 1.0767
  Epoch 2/10 [ 14.5%]  loss: 0.9690
  Epoch 2/10 [ 19.3%]  loss: 0.9837
  Epoch 2/10 [ 24.1%]  loss: 0.9340
  Epoch 2/10 [ 28.9%]  loss: 0.9206
  Epoch 2/10 [ 33.7%]  loss: 0.8993
  Epoch 2/10 [ 38.6%]  loss: 0.9683
  Epoch 2/10 [ 43.4%]  loss: 0.9357
  Epoch 2/10 [ 48.2%]  loss: 0.9118
  Epoch 2/10 [ 53.0%]  loss: 0.8820
  Epoch 2/10 [ 57.8%]  loss: 0.9710
  Epoch 2/10 [ 62.7%]  loss: 0.8143
  Epoch 2/10 [ 67.5%]  loss: 0.8137
  Epoch 2/10 [ 72.3%]  loss: 0.8103
  Epoch 2/10 [ 77.1%]  loss: 0.8336
  Epoch 2/10 [ 81.9%]  loss: 0.7900
  Epoch 2/10 [ 86.7%]  loss: 0.7552
  Epoch 2/10 [ 91.6%]  loss: 0.8525
  Epoch 2/10 [ 96.4%]  loss: 0.7633
  Epoch 2/10 [100.0%]  loss: 0.8802

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.20batch/s]

Epoch 2/10
Train Loss: 0.8980 | Train F1: 0.5739
Val Loss: 2.1629 | Val F1: 0.2797
Epoch Time: 38.25s

  Epoch 3/10 [  4.8%]  loss: 0.8311
  Epoch 3/10 [  9.6%]  loss: 0.8270
  Epoch 3/10 [ 14.5%]  loss: 0.8117
  Epoch 3/10 [ 19.3%]  loss: 0.7991
  Epoch 3/10 [ 24.1%]  loss: 0.7755
  Epoch 3/10 [ 28.9%]  loss: 0.7554
  Epoch 3/10 [ 33.7%]  loss: 0.7247
  Epoch 3/10 [ 38.6%]  loss: 0.8013
  Epoch 3/10 [ 43.4%]  loss: 0.7097
  Epoch 3/10 [ 48.2%]  loss: 0.7362
  Epoch 3/10 [ 53.0%]  loss: 0.7503
  Epoch 3/10 [ 57.8%]  loss: 0.7821
  Epoch 3/10 [ 62.7%]  loss: 0.7529
  Epoch 3/10 [ 67.5%]  loss: 0.7277
  Epoch 3/10 [ 72.3%]  loss: 0.7169
  Epoch 3/10 [ 77.1%]  loss: 0.7416
  Epoch 3/10 [ 81.9%]  loss: 0.6695
  Epoch 3/10 [ 86.7%]  loss: 0.7062
  Epoch 3/10 [ 91.6%]  loss: 0.6983
  Epoch 3/10 [ 96.4%]  loss: 0.6741
  Epoch 3/10 [100.0%]  loss: 0.7377

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.15batch/s]

Epoch 3/10
Train Loss: 0.7491 | Train F1: 0.6298
Val Loss: 1.9966 | Val F1: 0.3059
Epoch Time: 38.48s

  Epoch 4/10 [  4.8%]  loss: 0.6292
  Epoch 4/10 [  9.6%]  loss: 0.6340
  Epoch 4/10 [ 14.5%]  loss: 0.6822
  Epoch 4/10 [ 19.3%]  loss: 0.6217
  Epoch 4/10 [ 24.1%]  loss: 0.6273
  Epoch 4/10 [ 28.9%]  loss: 0.5770
  Epoch 4/10 [ 33.7%]  loss: 0.6015
  Epoch 4/10 [ 38.6%]  loss: 0.5794
  Epoch 4/10 [ 43.4%]  loss: 0.6612
  Epoch 4/10 [ 48.2%]  loss: 0.5856
  Epoch 4/10 [ 53.0%]  loss: 0.6028
  Epoch 4/10 [ 57.8%]  loss: 0.6654
  Epoch 4/10 [ 62.7%]  loss: 0.5860
  Epoch 4/10 [ 67.5%]  loss: 0.5955
  Epoch 4/10 [ 72.3%]  loss: 0.5686
  Epoch 4/10 [ 77.1%]  loss: 0.6195
  Epoch 4/10 [ 81.9%]  loss: 0.6159
  Epoch 4/10 [ 86.7%]  loss: 0.6089
  Epoch 4/10 [ 91.6%]  loss: 0.6703
  Epoch 4/10 [ 96.4%]  loss: 0.5752
  Epoch 4/10 [100.0%]  loss: 0.6479

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.30batch/s]

Epoch 4/10
Train Loss: 0.6165 | Train F1: 0.6864
Val Loss: 2.0160 | Val F1: 0.2980
Epoch Time: 38.30s

  Epoch 5/10 [  4.8%]  loss: 0.6901
  Epoch 5/10 [  9.6%]  loss: 0.6228
  Epoch 5/10 [ 14.5%]  loss: 0.5666
  Epoch 5/10 [ 19.3%]  loss: 0.6886
  Epoch 5/10 [ 24.1%]  loss: 0.5716
  Epoch 5/10 [ 28.9%]  loss: 0.5783
  Epoch 5/10 [ 33.7%]  loss: 0.6038
  Epoch 5/10 [ 38.6%]  loss: 0.6667
  Epoch 5/10 [ 43.4%]  loss: 0.5466
  Epoch 5/10 [ 48.2%]  loss: 0.6048
  Epoch 5/10 [ 53.0%]  loss: 0.6114
  Epoch 5/10 [ 57.8%]  loss: 0.5923
  Epoch 5/10 [ 62.7%]  loss: 0.5786
  Epoch 5/10 [ 67.5%]  loss: 0.5617
  Epoch 5/10 [ 72.3%]  loss: 0.5776
  Epoch 5/10 [ 77.1%]  loss: 0.5814
  Epoch 5/10 [ 81.9%]  loss: 0.5851
  Epoch 5/10 [ 86.7%]  loss: 0.6036
  Epoch 5/10 [ 91.6%]  loss: 0.5286
  Epoch 5/10 [ 96.4%]  loss: 0.5761
  Epoch 5/10 [100.0%]  loss: 0.5377

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.14batch/s]

Epoch 5/10
Train Loss: 0.5947 | Train F1: 0.7039
Val Loss: 1.9972 | Val F1: 0.3284
Epoch Time: 38.52s

  Epoch 6/10 [  4.8%]  loss: 0.5634
  Epoch 6/10 [  9.6%]  loss: 0.5390
  Epoch 6/10 [ 14.5%]  loss: 0.4993
  Epoch 6/10 [ 19.3%]  loss: 0.5780
  Epoch 6/10 [ 24.1%]  loss: 0.5061
  Epoch 6/10 [ 28.9%]  loss: 0.5399
  Epoch 6/10 [ 33.7%]  loss: 0.4985
  Epoch 6/10 [ 38.6%]  loss: 0.5308
  Epoch 6/10 [ 43.4%]  loss: 0.4891
  Epoch 6/10 [ 48.2%]  loss: 0.5006
  Epoch 6/10 [ 53.0%]  loss: 0.4932
  Epoch 6/10 [ 57.8%]  loss: 0.5463
  Epoch 6/10 [ 62.7%]  loss: 0.5144
  Epoch 6/10 [ 67.5%]  loss: 0.5003
  Epoch 6/10 [ 72.3%]  loss: 0.5599
  Epoch 6/10 [ 77.1%]  loss: 0.5082
  Epoch 6/10 [ 81.9%]  loss: 0.5029
  Epoch 6/10 [ 86.7%]  loss: 0.4916
  Epoch 6/10 [ 91.6%]  loss: 0.4642
  Epoch 6/10 [ 96.4%]  loss: 0.4594
  Epoch 6/10 [100.0%]  loss: 0.5233

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.19batch/s]

Epoch 6/10
Train Loss: 0.5146 | Train F1: 0.7409
Val Loss: 1.8736 | Val F1: 0.3334
Epoch Time: 38.23s

  Epoch 7/10 [  4.8%]  loss: 0.4759
  Epoch 7/10 [  9.6%]  loss: 0.5195
  Epoch 7/10 [ 14.5%]  loss: 0.4819
  Epoch 7/10 [ 19.3%]  loss: 0.4846
  Epoch 7/10 [ 24.1%]  loss: 0.5050
  Epoch 7/10 [ 28.9%]  loss: 0.5156
  Epoch 7/10 [ 33.7%]  loss: 0.5133
  Epoch 7/10 [ 38.6%]  loss: 0.5093
  Epoch 7/10 [ 43.4%]  loss: 0.4664
  Epoch 7/10 [ 48.2%]  loss: 0.5240
  Epoch 7/10 [ 53.0%]  loss: 0.5147
  Epoch 7/10 [ 57.8%]  loss: 0.5478
  Epoch 7/10 [ 62.7%]  loss: 0.5224
  Epoch 7/10 [ 67.5%]  loss: 0.4936
  Epoch 7/10 [ 72.3%]  loss: 0.4750
  Epoch 7/10 [ 77.1%]  loss: 0.4725
  Epoch 7/10 [ 81.9%]  loss: 0.4915
  Epoch 7/10 [ 86.7%]  loss: 0.5115
  Epoch 7/10 [ 91.6%]  loss: 0.4878
  Epoch 7/10 [ 96.4%]  loss: 0.4836
  Epoch 7/10 [100.0%]  loss: 0.5026

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.11batch/s]

Epoch 7/10
Train Loss: 0.4999 | Train F1: 0.7573
Val Loss: 1.8442 | Val F1: 0.3401
Epoch Time: 38.26s

  Epoch 8/10 [  4.8%]  loss: 0.4626
  Epoch 8/10 [  9.6%]  loss: 0.4981
  Epoch 8/10 [ 14.5%]  loss: 0.5434
  Epoch 8/10 [ 19.3%]  loss: 0.5086
  Epoch 8/10 [ 24.1%]  loss: 0.5025
  Epoch 8/10 [ 28.9%]  loss: 0.4574
  Epoch 8/10 [ 33.7%]  loss: 0.4522
  Epoch 8/10 [ 38.6%]  loss: 0.4742
  Epoch 8/10 [ 43.4%]  loss: 0.4948
  Epoch 8/10 [ 48.2%]  loss: 0.4728
  Epoch 8/10 [ 53.0%]  loss: 0.4682
  Epoch 8/10 [ 57.8%]  loss: 0.4581
  Epoch 8/10 [ 62.7%]  loss: 0.4565
  Epoch 8/10 [ 67.5%]  loss: 0.4849
  Epoch 8/10 [ 72.3%]  loss: 0.4669
  Epoch 8/10 [ 77.1%]  loss: 0.4582
  Epoch 8/10 [ 81.9%]  loss: 0.4458
  Epoch 8/10 [ 86.7%]  loss: 0.4540
  Epoch 8/10 [ 91.6%]  loss: 0.4338
  Epoch 8/10 [ 96.4%]  loss: 0.4424
  Epoch 8/10 [100.0%]  loss: 0.5076

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.09batch/s]

Epoch 8/10
Train Loss: 0.4731 | Train F1: 0.7600
Val Loss: 1.8117 | Val F1: 0.3584
Epoch Time: 38.32s

  Epoch 9/10 [  4.8%]  loss: 0.4937
  Epoch 9/10 [  9.6%]  loss: 0.4624
  Epoch 9/10 [ 14.5%]  loss: 0.4529
  Epoch 9/10 [ 19.3%]  loss: 0.4400
  Epoch 9/10 [ 24.1%]  loss: 0.4346
  Epoch 9/10 [ 28.9%]  loss: 0.4380
  Epoch 9/10 [ 33.7%]  loss: 0.4843
  Epoch 9/10 [ 38.6%]  loss: 0.5001
  Epoch 9/10 [ 43.4%]  loss: 0.5416
  Epoch 9/10 [ 48.2%]  loss: 0.4661
  Epoch 9/10 [ 53.0%]  loss: 0.4800
  Epoch 9/10 [ 57.8%]  loss: 0.4766
  Epoch 9/10 [ 62.7%]  loss: 0.4739
  Epoch 9/10 [ 67.5%]  loss: 0.4888
  Epoch 9/10 [ 72.3%]  loss: 0.4614
  Epoch 9/10 [ 77.1%]  loss: 0.4715
  Epoch 9/10 [ 81.9%]  loss: 0.4776
  Epoch 9/10 [ 86.7%]  loss: 0.4416
  Epoch 9/10 [ 91.6%]  loss: 0.4379
  Epoch 9/10 [ 96.4%]  loss: 0.4476
  Epoch 9/10 [100.0%]  loss: 0.4160

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.24batch/s]

Epoch 9/10
Train Loss: 0.4666 | Train F1: 0.7728
Val Loss: 1.9143 | Val F1: 0.3343
Epoch Time: 38.39s

  Epoch 10/10 [  4.8%]  loss: 0.4532
  Epoch 10/10 [  9.6%]  loss: 0.4917
  Epoch 10/10 [ 14.5%]  loss: 0.4347
  Epoch 10/10 [ 19.3%]  loss: 0.4296
  Epoch 10/10 [ 24.1%]  loss: 0.4469
  Epoch 10/10 [ 28.9%]  loss: 0.4400
  Epoch 10/10 [ 33.7%]  loss: 0.4384
  Epoch 10/10 [ 38.6%]  loss: 0.4599
  Epoch 10/10 [ 43.4%]  loss: 0.4229
  Epoch 10/10 [ 48.2%]  loss: 0.4725
  Epoch 10/10 [ 53.0%]  loss: 0.4589
  Epoch 10/10 [ 57.8%]  loss: 0.4721
  Epoch 10/10 [ 62.7%]  loss: 0.4654
  Epoch 10/10 [ 67.5%]  loss: 0.4787
  Epoch 10/10 [ 72.3%]  loss: 0.4614
  Epoch 10/10 [ 77.1%]  loss: 0.4380
  Epoch 10/10 [ 81.9%]  loss: 0.5069
  Epoch 10/10 [ 86.7%]  loss: 0.4380
  Epoch 10/10 [ 91.6%]  loss: 0.4683
  Epoch 10/10 [ 96.4%]  loss: 0.4614
  Epoch 10/10 [100.0%]  loss: 0.4608

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.18batch/s]

Epoch 10/10
Train Loss: 0.4571 | Train F1: 0.7851
Val Loss: 1.9155 | Val F1: 0.3245
Epoch Time: 38.27s

Finalised: 860/1920 conv1 channels zeroed (44.8%)
Saved → trained_models/pwkd_r18_r45/pwkd_r18_r45_full.pth

Warming up pwkd_r18_r45...
Running inference...
  ratio 45% | F1: 0.0055 | params: 6,276,669

               Size Reduction (%)  F1 Score  Size (MB)  Latency (ms)
Pruning Ratio
20%                         19.49    0.2680       42.8          0.39
30%                         29.24    0.1004       42.8          0.39
35%                         34.20    0.0352       42.8          0.39
40%                         39.04    0.0124       42.8          0.39
45%                         44.00    0.0055       42.8          0.39