# PWKD Option 3 — Prune ResNet18 Directly

Implements **Pruning While Knowledge Distillation** (Wang et al., 2025) using:
- **Teacher**: frozen pretrained ResNet30 (RadImageNet weights)
- **Student**: a deep copy of the *same* pretrained ResNet30, fine-tuned
  with PWKD simultaneously pruning and distilling

This is a same-architecture setup, closely analogous to the paper's
EDSR-32-256 → EDSR-16-64 setup but keeping the architecture fixed and
instead driving channels to zero through the differentiable sparsity penalty.
The wavelet channel-projection step is skipped (teacher/student channels match).

Starting from pretrained weights means the student begins at the teacher's
F1 level (~0.4) and PWKD nudges it toward a smaller, slightly lower-F1 model —
a much more favourable trade-off than training from scratch.

Produces 5 compressed models at pruning ratios [10%, 25%, 50%, 70%, 90%],
saved to `trained_models/pwkd_self_r18_<ratio>/` and uploaded to HuggingFace.

**Run all cells top to bottom. Requires GPU.**

In [1]:
import os, copy, subprocess
import torch

target = 'CS6423_knowledge_distillation_project'
if not os.getcwd().endswith(target):
    import sys
    os.chdir(os.path.join(os.getcwd(), target))
    if os.getcwd() not in sys.path:
        sys.path.insert(0, os.getcwd())

print(f'Working dir: {os.getcwd()}')
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device: {device}')

subprocess.run(['pip', 'install', 'PyWavelets', '--quiet'], check=True)

Working dir: /home/cor10/CS6423_knowledge_distillation_project
Device: cuda

CompletedProcess(args=['pip', 'install', 'PyWavelets', '--quiet'], returncode=0)

In [2]:
import pandas as pd
from modules.dataset_prepper import datasetPrepper

data_prep = datasetPrepper(
    dataframe_path='data/labels.csv',
    image_dir='data/test_images',
).prepare(compute_class_weights=True)

NUM_CLASSES = len(data_prep.class_names)
print(f'Classes: {NUM_CLASSES}')
print(f'Train batches: {len(data_prep.train_loader)} | Val batches: {len(data_prep.val_loader)}')

Classes: 61
Train batches: 249 | Val batches: 50

In [3]:
from modules.imagenet_loader import ImagenetLoader
from modules.evaluate_model import ModelEvaluator

loader = ImagenetLoader()

# Load pretrained ResNet18 — this serves as both the frozen teacher
# and the starting point for each student deep copy
resnet18_pretrained = loader.load_radimagenet_resnet18(
    weights_path='trained_models/resnet18_baseline_gpu_new/resnet18_baseline_gpu_new.pth',
    load_type='load'
)
resnet18_pretrained = resnet18_pretrained.to(device)

evaluator = ModelEvaluator(
    data_loader=data_prep.val_loader,
    class_names=data_prep.class_names,
    device=str(device),
)

baseline_metrics = evaluator.evaluate_single(resnet18_pretrained, 'ResNet18_baseline')
BASELINE_PARAMS  = baseline_metrics['total_parameters']
print(f'ResNet18 baseline F1:    {baseline_metrics["f1_macro"]:.4f}')
print(f'ResNet18 baseline params: {BASELINE_PARAMS:,}')

Warming up ResNet18_baseline...
Running inference...
ResNet18 baseline F1:    0.4054
ResNet18 baseline params: 11,207,805

In [ ]:
import torch.nn as nn
import copy
from modules.model_trainer import modelTrainer
from modules.evaluate_model import ModelEvaluator
from pwkd.pwkd import PWKDLoss, make_aux_fn, finalise_student

RESNET18_CHANNELS = {'layer2': 128, 'layer3': 256, 'layer4': 512}

PRUNING_RATIOS = [0, 0.05, 0.10, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.50, 0.70, 0.90]
NUM_EPOCHS     = 10
KD_TEMP        = 4.0
LAM            = 0.2
SPARSE_WEIGHT  = 5e-4
learn_rate     = 1e-4

evaluator = ModelEvaluator(
    data_loader=data_prep.val_loader,
    class_names=data_prep.class_names,
    device=str(device),
)

teacher = copy.deepcopy(resnet18_pretrained).eval()
for p in teacher.parameters():
    p.requires_grad = False

pwkd_metrics = []

print(f'ResNet18 baseline F1:    {baseline_metrics["f1_macro"]:.4f}')
print(f'ResNet18 baseline params: {BASELINE_PARAMS:,}')


for ratio in PRUNING_RATIOS:
    label = f'pwkd_self_r18_r{int(ratio * 100)}'
    print(f'\n{"="*60}')
    print(f'  PWKD Option 3 (ResNet18) — pruning ratio {ratio:.0%}')
    print(f'{"="*60}')

    student = copy.deepcopy(resnet18_pretrained).to(device)
    for p in student.parameters():
        p.requires_grad = True
        
    # reset teacher each experiment
    teacher_copy = copy.deepcopy(teacher).to(device)
    teacher_copy.eval()

    pwkd_loss = PWKDLoss(
        student          = student,
        teacher          = teacher_copy,
        pruning_ratio    = ratio,
        teacher_channels = RESNET18_CHANNELS,
        student_channels = RESNET18_CHANNELS,
        class_weights    = data_prep.class_weights.to(device)
                           if data_prep.class_weights is not None else None,
        lam              = LAM,
        kd_temp          = KD_TEMP,
        sparse_weight    = 0 if ratio == 0 else SPARSE_WEIGHT,
    ).to(device)

    trainer = modelTrainer(
        model      = student,
        data_prep  = data_prep,
        device     = device,
        # learn_rate = 2e-4,
        learn_rate = learn_rate,
        num_epochs = NUM_EPOCHS,
        model_name = label,
    )
    trainer.loss_fn   = pwkd_loss
    trainer.optimizer = torch.optim.AdamW(
        list(student.parameters()) + list(pwkd_loss.parameters()),
        lr=5e-5 if ratio == 0 else learn_rate,
        weight_decay=1e-4,
    )
    trainer.create_classnum_to_label_map(data_prep.class_names)
    trainer.train_all(save_as_object=True, aux_forward_fn=make_aux_fn(teacher_copy), pwkd=True)
    
    # Reload best checkpoint before finalising
    best_ckpt = os.path.join('trained_models', label, f'{label}_full.pth')
    student = torch.load(best_ckpt, map_location=device, weights_only=False)['model']
    student = student.to(device)

    student = finalise_student(student, pwkd_loss, data_prep.train_loader, device)

    import os
    save_dir = os.path.join('trained_models', label)
    os.makedirs(save_dir, exist_ok=True)
    torch.save({'model': student, 'epoch': NUM_EPOCHS},
               os.path.join(save_dir, f'{label}_full.pth'))
    print(f'Saved → {save_dir}/{label}_full.pth')

    student.eval()
    metrics = evaluator.evaluate_single(student, label)

    pwkd_metrics.append({
        'Pruning Ratio':      f'{int(ratio*100)}%',
        'Size Reduction (%)': round((BASELINE_PARAMS - metrics['total_parameters'])
                                    / BASELINE_PARAMS * 100, 2),
        'F1 Score':           round(metrics['f1_macro'],     4),
        'Size (MB)':          round(metrics['model_size_mb'], 1),
        'Latency (ms)':       round(metrics['avg_latency_ms'], 2),
    })
    print(f'  ratio: {ratio:.0%} | F1: {metrics["f1_macro"]:.4f} | '
          f'params: {metrics["total_parameters"]:,} | '
          f'latency: {metrics["avg_latency_ms"]:.2f}ms')

summary_df = pd.DataFrame(pwkd_metrics).set_index('Pruning Ratio')
print('\nPWKD Option 3 (ResNet18) — Results')
display(summary_df)

ResNet18 baseline F1:    0.4054
ResNet18 baseline params: 11,207,805

============================================================
  PWKD Option 3 (ResNet18) — pruning ratio 0%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:27<00:00,  8.97batch/s, loss=0.837]
Validating: 100%|██████████| 50/50 [00:03<00:00, 16.49batch/s]

Epoch 1/10
Train Loss: 0.6860 | Train F1: 0.6585
Val Loss: 1.4045 | Val F1: 0.4166
Epoch Time: 30.81s

Epoch 2/10: 100%|██████████| 249/249 [00:28<00:00,  8.78batch/s, loss=0.603]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.04batch/s]

Epoch 2/10
Train Loss: 0.4782 | Train F1: 0.7310
Val Loss: 1.3502 | Val F1: 0.4260
Epoch Time: 31.14s

Epoch 3/10: 100%|██████████| 249/249 [00:28<00:00,  8.73batch/s, loss=0.664]
Validating: 100%|██████████| 50/50 [00:02<00:00, 19.31batch/s]

Epoch 3/10
Train Loss: 0.4158 | Train F1: 0.7627
Val Loss: 1.3578 | Val F1: 0.4430
Epoch Time: 31.12s

Epoch 4/10: 100%|██████████| 249/249 [00:27<00:00,  9.04batch/s, loss=0.404]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.99batch/s]

Epoch 4/10
Train Loss: 0.3699 | Train F1: 0.7839
Val Loss: 1.3526 | Val F1: 0.4412
Epoch Time: 30.33s

Epoch 5/10: 100%|██████████| 249/249 [00:27<00:00,  8.97batch/s, loss=0.461]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.70batch/s]

Epoch 5/10
Train Loss: 0.3381 | Train F1: 0.8024
Val Loss: 1.3702 | Val F1: 0.4335
Epoch Time: 30.61s

Epoch 6/10: 100%|██████████| 249/249 [00:27<00:00,  9.07batch/s, loss=0.235]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.19batch/s]

Epoch 6/10
Train Loss: 0.3193 | Train F1: 0.8096
Val Loss: 1.3461 | Val F1: 0.4511
Epoch Time: 30.21s

Epoch 7/10: 100%|██████████| 249/249 [00:28<00:00,  8.68batch/s, loss=0.31]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.09batch/s]

Epoch 7/10
Train Loss: 0.2989 | Train F1: 0.8247
Val Loss: 1.3221 | Val F1: 0.4446
Epoch Time: 31.47s

Epoch 8/10: 100%|██████████| 249/249 [00:27<00:00,  9.00batch/s, loss=0.418]
Validating: 100%|██████████| 50/50 [00:02<00:00, 19.21batch/s]

Epoch 8/10
Train Loss: 0.2848 | Train F1: 0.8304
Val Loss: 1.2936 | Val F1: 0.4644
Epoch Time: 30.28s

Epoch 9/10: 100%|██████████| 249/249 [00:28<00:00,  8.76batch/s, loss=0.283]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.08batch/s]

Epoch 9/10
Train Loss: 0.2794 | Train F1: 0.8315
Val Loss: 1.3279 | Val F1: 0.4561
Epoch Time: 31.20s

Epoch 10/10: 100%|██████████| 249/249 [00:28<00:00,  8.73batch/s, loss=0.473]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.97batch/s]

Epoch 10/10
Train Loss: 0.2713 | Train F1: 0.8437
Val Loss: 1.3152 | Val F1: 0.4576
Epoch Time: 31.32s

Finalised: 0/1920 conv1 channels zeroed (0.0%)
Saved → trained_models/pwkd_self_r18_r0/pwkd_self_r18_r0_full.pth

Warming up pwkd_self_r18_r0...
Running inference...
  ratio: 0% | F1: 0.4644 | params: 11,207,805 | latency: 0.39ms

============================================================
  PWKD Option 3 (ResNet18) — pruning ratio 5%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:32<00:00,  7.75batch/s, loss=0.528]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.09batch/s]

Epoch 1/10
Train Loss: 0.7305 | Train F1: 0.6447
Val Loss: 1.4407 | Val F1: 0.3859
Epoch Time: 34.90s

Epoch 2/10: 100%|██████████| 249/249 [00:31<00:00,  7.84batch/s, loss=0.696]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.11batch/s]

Epoch 2/10
Train Loss: 0.4781 | Train F1: 0.7362
Val Loss: 1.4737 | Val F1: 0.4216
Epoch Time: 34.52s

Epoch 3/10: 100%|██████████| 249/249 [00:32<00:00,  7.65batch/s, loss=0.314]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.82batch/s]

Epoch 3/10
Train Loss: 0.4004 | Train F1: 0.7669
Val Loss: 1.4034 | Val F1: 0.4219
Epoch Time: 35.38s

Epoch 4/10: 100%|██████████| 249/249 [00:32<00:00,  7.61batch/s, loss=0.429]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.07batch/s]

Epoch 4/10
Train Loss: 0.3450 | Train F1: 0.7937
Val Loss: 1.3736 | Val F1: 0.4221
Epoch Time: 35.51s

Epoch 5/10: 100%|██████████| 249/249 [00:32<00:00,  7.65batch/s, loss=0.3]
Validating: 100%|██████████| 50/50 [00:02<00:00, 19.19batch/s]

Epoch 5/10
Train Loss: 0.3273 | Train F1: 0.8103
Val Loss: 1.3974 | Val F1: 0.4405
Epoch Time: 35.17s

Epoch 6/10: 100%|██████████| 249/249 [00:32<00:00,  7.64batch/s, loss=0.277]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.20batch/s]

Epoch 6/10
Train Loss: 0.3151 | Train F1: 0.8203
Val Loss: 1.4165 | Val F1: 0.4310
Epoch Time: 35.35s

Epoch 7/10: 100%|██████████| 249/249 [00:32<00:00,  7.65batch/s, loss=0.334]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.04batch/s]

Epoch 7/10
Train Loss: 0.3087 | Train F1: 0.8262
Val Loss: 1.3599 | Val F1: 0.4417
Epoch Time: 35.34s

Epoch 8/10: 100%|██████████| 249/249 [00:31<00:00,  7.89batch/s, loss=0.409]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.16batch/s]

Epoch 8/10
Train Loss: 0.3015 | Train F1: 0.8309
Val Loss: 1.3810 | Val F1: 0.4344
Epoch Time: 34.32s

Epoch 9/10: 100%|██████████| 249/249 [00:31<00:00,  7.86batch/s, loss=0.274]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.11batch/s]

Epoch 9/10
Train Loss: 0.2939 | Train F1: 0.8395
Val Loss: 1.4324 | Val F1: 0.4275
Epoch Time: 34.45s

Epoch 10/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.394]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.04batch/s]

Epoch 10/10
Train Loss: 0.2851 | Train F1: 0.8502
Val Loss: 1.4071 | Val F1: 0.4493
Epoch Time: 35.42s

Finalised: 92/1920 conv1 channels zeroed (4.8%)
Saved → trained_models/pwkd_self_r18_r5/pwkd_self_r18_r5_full.pth

Warming up pwkd_self_r18_r5...
Running inference...
  ratio: 5% | F1: 0.3996 | params: 10,676,733 | latency: 0.39ms

============================================================
  PWKD Option 3 (ResNet18) — pruning ratio 10%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:31<00:00,  7.82batch/s, loss=0.962]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.99batch/s]

Epoch 1/10
Train Loss: 0.7344 | Train F1: 0.6468
Val Loss: 1.4382 | Val F1: 0.4096
Epoch Time: 34.63s

Epoch 2/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.789]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.06batch/s]

Epoch 2/10
Train Loss: 0.5072 | Train F1: 0.7264
Val Loss: 1.5147 | Val F1: 0.4123
Epoch Time: 35.41s

Epoch 3/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.488]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.00batch/s]

Epoch 3/10
Train Loss: 0.4056 | Train F1: 0.7741
Val Loss: 1.3674 | Val F1: 0.4271
Epoch Time: 35.41s

Epoch 4/10: 100%|██████████| 249/249 [00:32<00:00,  7.64batch/s, loss=0.871]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.04batch/s]

Epoch 4/10
Train Loss: 0.3648 | Train F1: 0.7920
Val Loss: 1.4268 | Val F1: 0.4179
Epoch Time: 35.37s

Epoch 5/10: 100%|██████████| 249/249 [00:32<00:00,  7.64batch/s, loss=0.378]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.05batch/s]

Epoch 5/10
Train Loss: 0.3437 | Train F1: 0.8031
Val Loss: 1.3693 | Val F1: 0.4243
Epoch Time: 35.39s

Epoch 6/10: 100%|██████████| 249/249 [00:32<00:00,  7.62batch/s, loss=0.356]
Validating: 100%|██████████| 50/50 [00:02<00:00, 19.10batch/s]

Epoch 6/10
Train Loss: 0.3241 | Train F1: 0.8158
Val Loss: 1.3950 | Val F1: 0.4175
Epoch Time: 35.32s

Epoch 7/10: 100%|██████████| 249/249 [00:32<00:00,  7.60batch/s, loss=0.399]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.77batch/s]

Epoch 7/10
Train Loss: 0.3072 | Train F1: 0.8237
Val Loss: 1.4180 | Val F1: 0.4142
Epoch Time: 35.60s

Epoch 8/10: 100%|██████████| 249/249 [00:32<00:00,  7.61batch/s, loss=0.427]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.08batch/s]

Epoch 8/10
Train Loss: 0.3018 | Train F1: 0.8396
Val Loss: 1.3706 | Val F1: 0.4321
Epoch Time: 35.50s

Epoch 9/10: 100%|██████████| 249/249 [00:32<00:00,  7.62batch/s, loss=0.599]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.14batch/s]

Epoch 9/10
Train Loss: 0.3039 | Train F1: 0.8296
Val Loss: 1.4010 | Val F1: 0.4273
Epoch Time: 35.46s

Epoch 10/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.49]
Validating: 100%|██████████| 50/50 [00:02<00:00, 19.14batch/s]

Epoch 10/10
Train Loss: 0.2941 | Train F1: 0.8431
Val Loss: 1.3862 | Val F1: 0.4305
Epoch Time: 35.26s

Finalised: 188/1920 conv1 channels zeroed (9.8%)
Saved → trained_models/pwkd_self_r18_r10/pwkd_self_r18_r10_full.pth

Warming up pwkd_self_r18_r10...
Running inference...
  ratio: 10% | F1: 0.3776 | params: 10,121,469 | latency: 0.38ms

============================================================
  PWKD Option 3 (ResNet18) — pruning ratio 15%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:31<00:00,  7.83batch/s, loss=0.834]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.02batch/s]

Epoch 1/10
Train Loss: 0.7575 | Train F1: 0.6409
Val Loss: 1.4968 | Val F1: 0.3855
Epoch Time: 34.58s

Epoch 2/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.579]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.08batch/s]

Epoch 2/10
Train Loss: 0.4972 | Train F1: 0.7249
Val Loss: 1.4391 | Val F1: 0.4022
Epoch Time: 35.40s

Epoch 3/10: 100%|██████████| 249/249 [00:31<00:00,  7.83batch/s, loss=0.527]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.02batch/s]

Epoch 3/10
Train Loss: 0.4134 | Train F1: 0.7685
Val Loss: 1.5060 | Val F1: 0.4081
Epoch Time: 34.57s

Epoch 4/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.431]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.94batch/s]

Epoch 4/10
Train Loss: 0.3674 | Train F1: 0.7937
Val Loss: 1.3998 | Val F1: 0.4299
Epoch Time: 35.45s

Epoch 5/10: 100%|██████████| 249/249 [00:32<00:00,  7.66batch/s, loss=0.404]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.09batch/s]

Epoch 5/10
Train Loss: 0.3527 | Train F1: 0.7982
Val Loss: 1.4085 | Val F1: 0.4043
Epoch Time: 35.30s

Epoch 6/10: 100%|██████████| 249/249 [00:32<00:00,  7.62batch/s, loss=0.422]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.10batch/s]

Epoch 6/10
Train Loss: 0.3290 | Train F1: 0.8208
Val Loss: 1.4101 | Val F1: 0.4258
Epoch Time: 35.44s

Epoch 7/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.45]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.05batch/s]

Epoch 7/10
Train Loss: 0.3269 | Train F1: 0.8273
Val Loss: 1.3781 | Val F1: 0.4252
Epoch Time: 35.40s

Epoch 8/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.374]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.75batch/s]

Epoch 8/10
Train Loss: 0.3195 | Train F1: 0.8327
Val Loss: 1.3759 | Val F1: 0.4460
Epoch Time: 35.45s

Epoch 9/10: 100%|██████████| 249/249 [00:32<00:00,  7.69batch/s, loss=0.416]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.02batch/s]

Epoch 9/10
Train Loss: 0.3015 | Train F1: 0.8356
Val Loss: 1.3905 | Val F1: 0.4297
Epoch Time: 35.14s

Epoch 10/10: 100%|██████████| 249/249 [00:32<00:00,  7.62batch/s, loss=0.326]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.07batch/s]

Epoch 10/10
Train Loss: 0.3044 | Train F1: 0.8404
Val Loss: 1.3835 | Val F1: 0.4357
Epoch Time: 35.45s

Finalised: 284/1920 conv1 channels zeroed (14.8%)
Saved → trained_models/pwkd_self_r18_r15/pwkd_self_r18_r15_full.pth

Warming up pwkd_self_r18_r15...
Running inference...
  ratio: 15% | F1: 0.3465 | params: 9,578,301 | latency: 0.38ms

============================================================
  PWKD Option 3 (ResNet18) — pruning ratio 20%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:32<00:00,  7.64batch/s, loss=0.693]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.62batch/s]

Epoch 1/10
Train Loss: 0.7632 | Train F1: 0.6547
Val Loss: 1.4522 | Val F1: 0.4024
Epoch Time: 35.42s

Epoch 2/10: 100%|██████████| 249/249 [00:32<00:00,  7.62batch/s, loss=0.49]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.96batch/s]

Epoch 2/10
Train Loss: 0.4972 | Train F1: 0.7419
Val Loss: 1.5014 | Val F1: 0.4011
Epoch Time: 35.46s

Epoch 3/10: 100%|██████████| 249/249 [00:32<00:00,  7.64batch/s, loss=0.501]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.10batch/s]

Epoch 3/10
Train Loss: 0.4241 | Train F1: 0.7705
Val Loss: 1.4300 | Val F1: 0.4279
Epoch Time: 35.37s

Epoch 4/10: 100%|██████████| 249/249 [00:32<00:00,  7.64batch/s, loss=0.517]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.76batch/s]

Epoch 4/10
Train Loss: 0.3833 | Train F1: 0.7898
Val Loss: 1.3910 | Val F1: 0.4312
Epoch Time: 35.41s

Epoch 5/10: 100%|██████████| 249/249 [00:32<00:00,  7.64batch/s, loss=0.396]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.04batch/s]

Epoch 5/10
Train Loss: 0.3534 | Train F1: 0.8109
Val Loss: 1.4246 | Val F1: 0.4369
Epoch Time: 35.37s

Epoch 6/10: 100%|██████████| 249/249 [00:32<00:00,  7.65batch/s, loss=0.424]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.76batch/s]

Epoch 6/10
Train Loss: 0.3343 | Train F1: 0.8160
Val Loss: 1.4221 | Val F1: 0.4304
Epoch Time: 35.37s

Epoch 7/10: 100%|██████████| 249/249 [00:32<00:00,  7.61batch/s, loss=0.34]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.04batch/s]

Epoch 7/10
Train Loss: 0.3272 | Train F1: 0.8265
Val Loss: 1.4028 | Val F1: 0.4337
Epoch Time: 35.52s

Epoch 8/10: 100%|██████████| 249/249 [00:32<00:00,  7.62batch/s, loss=0.406]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.14batch/s]

Epoch 8/10
Train Loss: 0.3238 | Train F1: 0.8357
Val Loss: 1.3905 | Val F1: 0.4403
Epoch Time: 35.43s

Epoch 9/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.412]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.92batch/s]

Epoch 9/10
Train Loss: 0.3172 | Train F1: 0.8438
Val Loss: 1.3963 | Val F1: 0.4411
Epoch Time: 35.43s

Epoch 10/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.415]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.87batch/s]

Epoch 10/10
Train Loss: 0.3112 | Train F1: 0.8351
Val Loss: 1.3790 | Val F1: 0.4367
Epoch Time: 35.46s

Finalised: 380/1920 conv1 channels zeroed (19.8%)
Saved → trained_models/pwkd_self_r18_r20/pwkd_self_r18_r20_full.pth

Warming up pwkd_self_r18_r20...
Running inference...
  ratio: 20% | F1: 0.2960 | params: 9,023,037 | latency: 0.39ms

============================================================
  PWKD Option 3 (ResNet18) — pruning ratio 25%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:32<00:00,  7.65batch/s, loss=0.63]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.13batch/s]

Epoch 1/10
Train Loss: 0.7851 | Train F1: 0.6445
Val Loss: 1.4776 | Val F1: 0.4023
Epoch Time: 35.31s

Epoch 2/10: 100%|██████████| 249/249 [00:32<00:00,  7.64batch/s, loss=0.478]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.79batch/s]

Epoch 2/10
Train Loss: 0.5012 | Train F1: 0.7348
Val Loss: 1.4487 | Val F1: 0.4105
Epoch Time: 35.39s

Epoch 3/10: 100%|██████████| 249/249 [00:32<00:00,  7.62batch/s, loss=0.555]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.09batch/s]

Epoch 3/10
Train Loss: 0.4386 | Train F1: 0.7680
Val Loss: 1.4509 | Val F1: 0.4228
Epoch Time: 35.45s

Epoch 4/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.479]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.11batch/s]

Epoch 4/10
Train Loss: 0.3819 | Train F1: 0.7877
Val Loss: 1.4439 | Val F1: 0.3998
Epoch Time: 35.39s

Epoch 5/10: 100%|██████████| 249/249 [00:32<00:00,  7.62batch/s, loss=0.394]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.14batch/s]

Epoch 5/10
Train Loss: 0.3637 | Train F1: 0.8062
Val Loss: 1.3965 | Val F1: 0.4337
Epoch Time: 35.46s

Epoch 6/10: 100%|██████████| 249/249 [00:32<00:00,  7.62batch/s, loss=0.374]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.76batch/s]

Epoch 6/10
Train Loss: 0.3446 | Train F1: 0.8253
Val Loss: 1.3693 | Val F1: 0.4317
Epoch Time: 35.50s

Epoch 7/10: 100%|██████████| 249/249 [00:31<00:00,  7.85batch/s, loss=0.319]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.95batch/s]

Epoch 7/10
Train Loss: 0.3398 | Train F1: 0.8289
Val Loss: 1.3628 | Val F1: 0.4286
Epoch Time: 34.53s

Epoch 8/10: 100%|██████████| 249/249 [00:31<00:00,  7.84batch/s, loss=0.59]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.06batch/s]

Epoch 8/10
Train Loss: 0.3322 | Train F1: 0.8385
Val Loss: 1.3794 | Val F1: 0.4399
Epoch Time: 34.54s

Epoch 9/10: 100%|██████████| 249/249 [00:31<00:00,  7.86batch/s, loss=0.655]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.19batch/s]

Epoch 9/10
Train Loss: 0.3254 | Train F1: 0.8445
Val Loss: 1.3801 | Val F1: 0.4425
Epoch Time: 34.45s

Epoch 10/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.425]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.00batch/s]

Epoch 10/10
Train Loss: 0.3173 | Train F1: 0.8466
Val Loss: 1.4284 | Val F1: 0.4300
Epoch Time: 35.41s

Finalised: 480/1920 conv1 channels zeroed (25.0%)
Saved → trained_models/pwkd_self_r18_r25/pwkd_self_r18_r25_full.pth

Warming up pwkd_self_r18_r25...
Running inference...
  ratio: 25% | F1: 0.2204 | params: 8,461,437 | latency: 0.39ms

============================================================
  PWKD Option 3 (ResNet18) — pruning ratio 30%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:32<00:00,  7.62batch/s, loss=0.645]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.72batch/s]

Epoch 1/10
Train Loss: 0.7811 | Train F1: 0.6361
Val Loss: 1.5016 | Val F1: 0.3843
Epoch Time: 35.51s

Epoch 2/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.668]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.13batch/s]

Epoch 2/10
Train Loss: 0.5222 | Train F1: 0.7337
Val Loss: 1.4198 | Val F1: 0.4216
Epoch Time: 35.40s

Epoch 3/10: 100%|██████████| 249/249 [00:32<00:00,  7.64batch/s, loss=0.531]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.10batch/s]

Epoch 3/10
Train Loss: 0.4416 | Train F1: 0.7707
Val Loss: 1.4413 | Val F1: 0.4061
Epoch Time: 35.35s

Epoch 4/10: 100%|██████████| 249/249 [00:32<00:00,  7.62batch/s, loss=0.479]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.06batch/s]

Epoch 4/10
Train Loss: 0.3980 | Train F1: 0.7896
Val Loss: 1.4132 | Val F1: 0.4301
Epoch Time: 35.44s

Epoch 5/10: 100%|██████████| 249/249 [00:32<00:00,  7.65batch/s, loss=0.41]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.08batch/s]

Epoch 5/10
Train Loss: 0.3860 | Train F1: 0.8047
Val Loss: 1.3918 | Val F1: 0.4407
Epoch Time: 35.34s

Epoch 6/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.39]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.17batch/s]

Epoch 6/10
Train Loss: 0.3603 | Train F1: 0.8170
Val Loss: 1.3811 | Val F1: 0.4352
Epoch Time: 35.42s

Epoch 7/10: 100%|██████████| 249/249 [00:32<00:00,  7.62batch/s, loss=0.427]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.01batch/s]

Epoch 7/10
Train Loss: 0.3464 | Train F1: 0.8334
Val Loss: 1.4251 | Val F1: 0.4372
Epoch Time: 35.48s

Epoch 8/10: 100%|██████████| 249/249 [00:31<00:00,  7.87batch/s, loss=0.559]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.02batch/s]

Epoch 8/10
Train Loss: 0.3366 | Train F1: 0.8352
Val Loss: 1.3832 | Val F1: 0.4403
Epoch Time: 34.41s

Epoch 9/10: 100%|██████████| 249/249 [00:31<00:00,  7.83batch/s, loss=0.331]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.09batch/s]

Epoch 9/10
Train Loss: 0.3342 | Train F1: 0.8433
Val Loss: 1.3755 | Val F1: 0.4513
Epoch Time: 34.57s

Epoch 10/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.512]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.01batch/s]

Epoch 10/10
Train Loss: 0.3251 | Train F1: 0.8463
Val Loss: 1.4036 | Val F1: 0.4372
Epoch Time: 35.40s

Finalised: 572/1920 conv1 channels zeroed (29.8%)
Saved → trained_models/pwkd_self_r18_r30/pwkd_self_r18_r30_full.pth

Warming up pwkd_self_r18_r30...
Running inference...
  ratio: 30% | F1: 0.0838 | params: 7,930,365 | latency: 0.39ms

============================================================
  PWKD Option 3 (ResNet18) — pruning ratio 35%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:31<00:00,  7.83batch/s, loss=1.15]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.15batch/s]

Epoch 1/10
Train Loss: 0.8042 | Train F1: 0.6371
Val Loss: 1.5200 | Val F1: 0.3819
Epoch Time: 34.58s

Epoch 2/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.765]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.18batch/s]

Epoch 2/10
Train Loss: 0.5330 | Train F1: 0.7345
Val Loss: 1.4608 | Val F1: 0.4035
Epoch Time: 35.40s

Epoch 3/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.508]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.94batch/s]

Epoch 3/10
Train Loss: 0.4643 | Train F1: 0.7597
Val Loss: 1.4189 | Val F1: 0.4248
Epoch Time: 35.42s

Epoch 4/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.617]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.99batch/s]

Epoch 4/10
Train Loss: 0.4089 | Train F1: 0.7913
Val Loss: 1.4096 | Val F1: 0.4268
Epoch Time: 35.41s

Epoch 5/10: 100%|██████████| 249/249 [00:32<00:00,  7.62batch/s, loss=0.659]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.01batch/s]

Epoch 5/10
Train Loss: 0.3754 | Train F1: 0.8098
Val Loss: 1.4058 | Val F1: 0.4291
Epoch Time: 35.47s

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.03batch/s], loss=0.337]

Epoch 7/10
Train Loss: 0.3545 | Train F1: 0.8237
Val Loss: 1.3885 | Val F1: 0.4267
Epoch Time: 34.63s

Epoch 8/10: 100%|██████████| 249/249 [00:32<00:00,  7.60batch/s, loss=0.385]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.10batch/s]

Epoch 8/10
Train Loss: 0.3372 | Train F1: 0.8377
Val Loss: 1.3602 | Val F1: 0.4343
Epoch Time: 35.55s

Epoch 9/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.405]
Validating: 100%|██████████| 50/50 [00:03<00:00, 16.45batch/s]

Epoch 9/10
Train Loss: 0.3374 | Train F1: 0.8428
Val Loss: 1.3897 | Val F1: 0.4373
Epoch Time: 35.70s

Epoch 10/10: 100%|██████████| 249/249 [00:32<00:00,  7.62batch/s, loss=0.343]
Validating: 100%|██████████| 50/50 [00:03<00:00, 16.42batch/s]

Epoch 10/10
Train Loss: 0.3336 | Train F1: 0.8471
Val Loss: 1.4279 | Val F1: 0.4283
Epoch Time: 35.75s

Finalised: 668/1920 conv1 channels zeroed (34.8%)
Saved → trained_models/pwkd_self_r18_r35/pwkd_self_r18_r35_full.pth

Warming up pwkd_self_r18_r35...
Running inference...
  ratio: 35% | F1: 0.0423 | params: 7,375,101 | latency: 0.39ms

============================================================
  PWKD Option 3 (ResNet18) — pruning ratio 40%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:31<00:00,  7.81batch/s, loss=0.97]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.74batch/s]

Epoch 1/10
Train Loss: 0.7995 | Train F1: 0.6376
Val Loss: 1.5535 | Val F1: 0.3815
Epoch Time: 34.72s

Epoch 2/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.611]
Validating: 100%|██████████| 50/50 [00:03<00:00, 16.49batch/s]

Epoch 2/10
Train Loss: 0.5410 | Train F1: 0.7260
Val Loss: 1.4255 | Val F1: 0.4084
Epoch Time: 35.68s

Epoch 3/10: 100%|██████████| 249/249 [00:32<00:00,  7.62batch/s, loss=0.556]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.16batch/s]

Epoch 3/10
Train Loss: 0.4513 | Train F1: 0.7735
Val Loss: 1.3960 | Val F1: 0.4376
Epoch Time: 35.42s

Epoch 4/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.69]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.13batch/s]

Epoch 4/10
Train Loss: 0.4185 | Train F1: 0.7895
Val Loss: 1.4169 | Val F1: 0.4286
Epoch Time: 35.42s

Epoch 5/10: 100%|██████████| 249/249 [00:32<00:00,  7.61batch/s, loss=0.491]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.14batch/s]

Epoch 5/10
Train Loss: 0.3916 | Train F1: 0.8084
Val Loss: 1.3878 | Val F1: 0.4426
Epoch Time: 35.49s

Epoch 6/10: 100%|██████████| 249/249 [00:31<00:00,  7.84batch/s, loss=0.295]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.16batch/s]

Epoch 6/10
Train Loss: 0.3709 | Train F1: 0.8146
Val Loss: 1.3790 | Val F1: 0.4291
Epoch Time: 34.51s

Epoch 7/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.419]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.09batch/s]

Epoch 7/10
Train Loss: 0.3570 | Train F1: 0.8308
Val Loss: 1.4242 | Val F1: 0.4334
Epoch Time: 35.43s

Epoch 8/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.424]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.17batch/s]

Epoch 8/10
Train Loss: 0.3456 | Train F1: 0.8317
Val Loss: 1.4115 | Val F1: 0.4443
Epoch Time: 35.41s

Epoch 9/10: 100%|██████████| 249/249 [00:32<00:00,  7.62batch/s, loss=0.585]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.17batch/s]

Epoch 9/10
Train Loss: 0.3456 | Train F1: 0.8352
Val Loss: 1.4276 | Val F1: 0.4308
Epoch Time: 35.43s

Epoch 10/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.343]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.80batch/s]

Epoch 10/10
Train Loss: 0.3430 | Train F1: 0.8428
Val Loss: 1.4610 | Val F1: 0.4384
Epoch Time: 35.47s

Finalised: 764/1920 conv1 channels zeroed (39.8%)
Saved → trained_models/pwkd_self_r18_r40/pwkd_self_r18_r40_full.pth

Warming up pwkd_self_r18_r40...
Running inference...
  ratio: 40% | F1: 0.0296 | params: 6,831,933 | latency: 0.39ms

============================================================
  PWKD Option 3 (ResNet18) — pruning ratio 45%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:31<00:00,  7.82batch/s, loss=0.69]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.72batch/s]

Epoch 1/10
Train Loss: 0.8002 | Train F1: 0.6444
Val Loss: 1.4864 | Val F1: 0.4044
Epoch Time: 34.66s

Epoch 2/10: 100%|██████████| 249/249 [00:32<00:00,  7.66batch/s, loss=0.647]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.10batch/s]

Epoch 2/10
Train Loss: 0.5395 | Train F1: 0.7332
Val Loss: 1.4177 | Val F1: 0.4189
Epoch Time: 35.29s

Epoch 3/10: 100%|██████████| 249/249 [00:32<00:00,  7.67batch/s, loss=0.383]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.11batch/s]

Epoch 3/10
Train Loss: 0.4650 | Train F1: 0.7663
Val Loss: 1.4486 | Val F1: 0.4279
Epoch Time: 35.24s

Epoch 4/10: 100%|██████████| 249/249 [00:32<00:00,  7.64batch/s, loss=0.415]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.05batch/s]

Epoch 4/10
Train Loss: 0.4270 | Train F1: 0.7849
Val Loss: 1.4237 | Val F1: 0.4094
Epoch Time: 35.39s

Epoch 5/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.647]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.73batch/s]

Epoch 5/10
Train Loss: 0.3884 | Train F1: 0.8049
Val Loss: 1.4027 | Val F1: 0.4322
Epoch Time: 35.48s

Epoch 6/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.376]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.78batch/s]

Epoch 6/10
Train Loss: 0.3809 | Train F1: 0.8150
Val Loss: 1.4102 | Val F1: 0.4204
Epoch Time: 35.45s

Epoch 7/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.439]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.86batch/s]

Epoch 7/10
Train Loss: 0.3758 | Train F1: 0.8267
Val Loss: 1.4353 | Val F1: 0.4162
Epoch Time: 35.44s

Epoch 8/10: 100%|██████████| 249/249 [00:32<00:00,  7.61batch/s, loss=0.409]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.13batch/s]

Epoch 8/10
Train Loss: 0.3657 | Train F1: 0.8270
Val Loss: 1.4359 | Val F1: 0.4251
Epoch Time: 35.47s

Epoch 9/10: 100%|██████████| 249/249 [00:32<00:00,  7.61batch/s, loss=0.314]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.10batch/s]

Epoch 9/10
Train Loss: 0.3537 | Train F1: 0.8378
Val Loss: 1.3938 | Val F1: 0.4372
Epoch Time: 35.49s

Epoch 10/10: 100%|██████████| 249/249 [00:31<00:00,  7.83batch/s, loss=0.535]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.11batch/s]

Epoch 10/10
Train Loss: 0.3505 | Train F1: 0.8468
Val Loss: 1.3910 | Val F1: 0.4436
Epoch Time: 34.58s

Finalised: 860/1920 conv1 channels zeroed (44.8%)
Saved → trained_models/pwkd_self_r18_r45/pwkd_self_r18_r45_full.pth

Warming up pwkd_self_r18_r45...
Running inference...
  ratio: 45% | F1: 0.0153 | params: 6,276,669 | latency: 0.38ms

============================================================
  PWKD Option 3 (ResNet18) — pruning ratio 50%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:31<00:00,  7.84batch/s, loss=0.729]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.11batch/s]

Epoch 1/10
Train Loss: 0.8209 | Train F1: 0.6430
Val Loss: 1.4273 | Val F1: 0.3971
Epoch Time: 34.55s

Epoch 2/10: 100%|██████████| 249/249 [00:32<00:00,  7.64batch/s, loss=0.636]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.03batch/s]

Epoch 2/10
Train Loss: 0.5514 | Train F1: 0.7349
Val Loss: 1.4645 | Val F1: 0.4222
Epoch Time: 35.36s

Epoch 3/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.753]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.06batch/s]

Epoch 3/10
Train Loss: 0.4726 | Train F1: 0.7680
Val Loss: 1.4357 | Val F1: 0.4304
Epoch Time: 35.43s

Epoch 4/10: 100%|██████████| 249/249 [00:32<00:00,  7.64batch/s, loss=0.421]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.14batch/s]

Epoch 4/10
Train Loss: 0.4426 | Train F1: 0.7862
Val Loss: 1.5195 | Val F1: 0.4250
Epoch Time: 35.38s

Epoch 5/10: 100%|██████████| 249/249 [00:32<00:00,  7.62batch/s, loss=0.365]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.99batch/s]

Epoch 5/10
Train Loss: 0.4077 | Train F1: 0.8053
Val Loss: 1.4927 | Val F1: 0.4156
Epoch Time: 35.45s

Epoch 6/10: 100%|██████████| 249/249 [00:32<00:00,  7.66batch/s, loss=0.501]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.96batch/s]

Epoch 6/10
Train Loss: 0.3862 | Train F1: 0.8194
Val Loss: 1.4611 | Val F1: 0.4197
Epoch Time: 35.31s

Epoch 7/10: 100%|██████████| 249/249 [00:31<00:00,  7.85batch/s, loss=0.497]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.08batch/s]

Epoch 7/10
Train Loss: 0.3768 | Train F1: 0.8281
Val Loss: 1.4353 | Val F1: 0.4240
Epoch Time: 34.49s

Epoch 8/10: 100%|██████████| 249/249 [00:31<00:00,  7.83batch/s, loss=0.781]
Validating: 100%|██████████| 50/50 [00:02<00:00, 19.20batch/s]

Epoch 8/10
Train Loss: 0.3673 | Train F1: 0.8343
Val Loss: 1.4485 | Val F1: 0.4270
Epoch Time: 34.41s

Epoch 9/10: 100%|██████████| 249/249 [00:32<00:00,  7.62batch/s, loss=0.459]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.03batch/s]

Epoch 9/10
Train Loss: 0.3596 | Train F1: 0.8391
Val Loss: 1.3852 | Val F1: 0.4449
Epoch Time: 35.45s

Epoch 10/10: 100%|██████████| 249/249 [00:31<00:00,  7.80batch/s, loss=0.407]
Validating: 100%|██████████| 50/50 [00:02<00:00, 19.27batch/s]

Epoch 10/10
Train Loss: 0.3621 | Train F1: 0.8526
Val Loss: 1.3899 | Val F1: 0.4499
Epoch Time: 34.52s

Finalised: 960/1920 conv1 channels zeroed (50.0%)
Saved → trained_models/pwkd_self_r18_r50/pwkd_self_r18_r50_full.pth

Warming up pwkd_self_r18_r50...
Running inference...
  ratio: 50% | F1: 0.0026 | params: 5,715,069 | latency: 0.39ms

============================================================
  PWKD Option 3 (ResNet18) — pruning ratio 70%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:31<00:00,  7.83batch/s, loss=0.556]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.16batch/s]

Epoch 1/10
Train Loss: 0.8410 | Train F1: 0.6446
Val Loss: 1.4714 | Val F1: 0.4018
Epoch Time: 34.56s

Epoch 2/10: 100%|██████████| 249/249 [00:32<00:00,  7.65batch/s, loss=0.702]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.77batch/s]

Epoch 2/10
Train Loss: 0.5876 | Train F1: 0.7350
Val Loss: 1.4324 | Val F1: 0.4068
Epoch Time: 35.36s

Epoch 3/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.515]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.12batch/s]

Epoch 3/10
Train Loss: 0.4952 | Train F1: 0.7805
Val Loss: 1.3525 | Val F1: 0.4391
Epoch Time: 35.43s

Epoch 4/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.402]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.12batch/s]

Epoch 4/10
Train Loss: 0.4605 | Train F1: 0.7935
Val Loss: 1.3353 | Val F1: 0.4304
Epoch Time: 35.42s

Epoch 5/10: 100%|██████████| 249/249 [00:32<00:00,  7.60batch/s, loss=0.449]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.15batch/s]

Epoch 5/10
Train Loss: 0.4490 | Train F1: 0.8003
Val Loss: 1.3866 | Val F1: 0.4327
Epoch Time: 35.51s

Epoch 6/10: 100%|██████████| 249/249 [00:32<00:00,  7.64batch/s, loss=0.519]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.01batch/s]

Epoch 6/10
Train Loss: 0.4277 | Train F1: 0.8169
Val Loss: 1.4031 | Val F1: 0.4377
Epoch Time: 35.39s

Epoch 7/10: 100%|██████████| 249/249 [00:32<00:00,  7.62batch/s, loss=0.433]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.99batch/s]

Epoch 7/10
Train Loss: 0.4163 | Train F1: 0.8279
Val Loss: 1.3941 | Val F1: 0.4356
Epoch Time: 35.48s

Epoch 8/10: 100%|██████████| 249/249 [00:31<00:00,  7.84batch/s, loss=0.735]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.11batch/s]

Epoch 8/10
Train Loss: 0.4126 | Train F1: 0.8324
Val Loss: 1.4072 | Val F1: 0.4257
Epoch Time: 34.55s

Epoch 9/10: 100%|██████████| 249/249 [00:32<00:00,  7.62batch/s, loss=0.405]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.71batch/s]

Epoch 9/10
Train Loss: 0.4051 | Train F1: 0.8393
Val Loss: 1.3960 | Val F1: 0.4409
Epoch Time: 35.52s

Epoch 10/10: 100%|██████████| 249/249 [00:32<00:00,  7.61batch/s, loss=0.512]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.06batch/s]

Epoch 10/10
Train Loss: 0.4019 | Train F1: 0.8393
Val Loss: 1.3907 | Val F1: 0.4310
Epoch Time: 35.49s

Finalised: 1340/1920 conv1 channels zeroed (69.8%)
Saved → trained_models/pwkd_self_r18_r70/pwkd_self_r18_r70_full.pth

Warming up pwkd_self_r18_r70...
Running inference...
  ratio: 70% | F1: 0.0001 | params: 3,530,301 | latency: 0.39ms

============================================================
  PWKD Option 3 (ResNet18) — pruning ratio 90%
============================================================

Epoch 1/10: 100%|██████████| 249/249 [00:31<00:00,  7.81batch/s, loss=0.608]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.82batch/s]

Epoch 1/10
Train Loss: 0.8629 | Train F1: 0.6495
Val Loss: 1.4529 | Val F1: 0.4033
Epoch Time: 34.68s

Epoch 2/10: 100%|██████████| 249/249 [00:32<00:00,  7.62batch/s, loss=0.485]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.06batch/s]

Epoch 2/10
Train Loss: 0.6198 | Train F1: 0.7290
Val Loss: 1.4047 | Val F1: 0.4163
Epoch Time: 35.47s

Epoch 3/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=1.02]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.12batch/s]

Epoch 3/10
Train Loss: 0.5431 | Train F1: 0.7723
Val Loss: 1.3990 | Val F1: 0.4232
Epoch Time: 35.40s

Epoch 4/10: 100%|██████████| 249/249 [00:32<00:00,  7.63batch/s, loss=0.649]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.09batch/s]

Epoch 4/10
Train Loss: 0.4923 | Train F1: 0.7894
Val Loss: 1.3862 | Val F1: 0.4231
Epoch Time: 35.40s

Epoch 5/10: 100%|██████████| 249/249 [00:32<00:00,  7.62batch/s, loss=0.569]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.03batch/s]

Epoch 5/10
Train Loss: 0.4724 | Train F1: 0.8010
Val Loss: 1.3943 | Val F1: 0.4301
Epoch Time: 35.48s

Epoch 6/10: 100%|██████████| 249/249 [00:32<00:00,  7.64batch/s, loss=0.649]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.22batch/s]

Epoch 6/10
Train Loss: 0.4549 | Train F1: 0.8209
Val Loss: 1.3843 | Val F1: 0.4433
Epoch Time: 35.34s

Epoch 7/10: 100%|██████████| 249/249 [00:32<00:00,  7.61batch/s, loss=0.463]
Validating: 100%|██████████| 50/50 [00:02<00:00, 17.98batch/s]

Epoch 7/10
Train Loss: 0.4533 | Train F1: 0.8182
Val Loss: 1.3662 | Val F1: 0.4390
Epoch Time: 35.53s

Epoch 8/10: 100%|██████████| 249/249 [00:32<00:00,  7.60batch/s, loss=0.526]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.08batch/s]

Epoch 8/10
Train Loss: 0.4359 | Train F1: 0.8342
Val Loss: 1.3535 | Val F1: 0.4370
Epoch Time: 35.52s

Epoch 9/10: 100%|██████████| 249/249 [00:32<00:00,  7.62batch/s, loss=0.497]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.16batch/s]

Epoch 9/10
Train Loss: 0.4326 | Train F1: 0.8337
Val Loss: 1.3494 | Val F1: 0.4361
Epoch Time: 35.43s

Epoch 10/10: 100%|██████████| 249/249 [00:32<00:00,  7.61batch/s, loss=0.552]
Validating: 100%|██████████| 50/50 [00:02<00:00, 18.13batch/s]

Epoch 10/10
Train Loss: 0.4355 | Train F1: 0.8430
Val Loss: 1.3865 | Val F1: 0.4389
Epoch Time: 35.48s

Finalised: 1724/1920 conv1 channels zeroed (89.8%)
Saved → trained_models/pwkd_self_r18_r90/pwkd_self_r18_r90_full.pth

Warming up pwkd_self_r18_r90...
Running inference...
  ratio: 90% | F1: 0.0001 | params: 1,339,197 | latency: 0.39ms

PWKD Option 3 (ResNet18) — Results

               Size Reduction (%)  F1 Score  Size (MB)  Latency (ms)
Pruning Ratio
0%                           0.00    0.4644       42.8          0.39
5%                           4.74    0.3996       42.8          0.39
10%                          9.69    0.3776       42.8          0.38
15%                         14.54    0.3465       42.8          0.38
20%                         19.49    0.2960       42.8          0.39
25%                         24.50    0.2204       42.8          0.39
30%                         29.24    0.0838       42.8          0.39
35%                         34.20    0.0423       42.8          0.39
40%                         39.04    0.0296       42.8          0.39
45%                         44.00    0.0153       42.8          0.38
50%                         49.01    0.0026       42.8          0.39
70%                         68.50    0.0001       42.8          0.39
90%                         88.05    0.0001       42.8          0.39

In [ ]:
print('\nPWKD Option 3 (ResNet18) — Results')
display(summary_df)

# this is learn_rate = 1e-4

PWKD Option 3 (ResNet18) — Results

               Size Reduction (%)  F1 Score  Size (MB)  Latency (ms)
Pruning Ratio
0%                           0.00    0.4644       42.8          0.39
5%                           4.74    0.3996       42.8          0.39
10%                          9.69    0.3776       42.8          0.38
15%                         14.54    0.3465       42.8          0.38
20%                         19.49    0.2960       42.8          0.39
25%                         24.50    0.2204       42.8          0.39
30%                         29.24    0.0838       42.8          0.39
35%                         34.20    0.0423       42.8          0.39
40%                         39.04    0.0296       42.8          0.39
45%                         44.00    0.0153       42.8          0.38
50%                         49.01    0.0026       42.8          0.39
70%                         68.50    0.0001       42.8          0.39
90%                         88.05    0.0001       42.8          0.39