# PWKD Option 3 — Prune ResNet18 Directly

Implements **Pruning While Knowledge Distillation** (Wang et al., 2025) using:
- **Teacher**: frozen pretrained ResNet30 (RadImageNet weights)
- **Student**: a deep copy of the *same* pretrained ResNet30, fine-tuned
  with PWKD simultaneously pruning and distilling

This is a same-architecture setup, closely analogous to the paper's
EDSR-32-256 → EDSR-16-64 setup but keeping the architecture fixed and
instead driving channels to zero through the differentiable sparsity penalty.
The wavelet channel-projection step is skipped (teacher/student channels match).

Starting from pretrained weights means the student begins at the teacher's
F1 level (~0.4) and PWKD nudges it toward a smaller, slightly lower-F1 model —
a much more favourable trade-off than training from scratch.

Produces 5 compressed models at pruning ratios [10%, 25%, 50%, 70%, 90%],
saved to `trained_models/pwkd_self_r18_<ratio>/` and uploaded to HuggingFace.

**Run all cells top to bottom. Requires GPU.**

In [1]:
import os, copy, subprocess
import torch

target = 'CS6423_knowledge_distillation_project'
if not os.getcwd().endswith(target):
    import sys
    os.chdir(os.path.join(os.getcwd(), target))
    if os.getcwd() not in sys.path:
        sys.path.insert(0, os.getcwd())

print(f'Working dir: {os.getcwd()}')
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device: {device}')

subprocess.run(['pip', 'install', 'PyWavelets', '--quiet'], check=True)

Working dir: /home/cor10/CS6423_knowledge_distillation_project
Device: cuda

CompletedProcess(args=['pip', 'install', 'PyWavelets', '--quiet'], returncode=0)

In [2]:
import pandas as pd
from modules.dataset_prepper import datasetPrepper

data_prep = datasetPrepper(
    dataframe_path='data/labels.csv',
    image_dir='data/test_images',
).prepare(compute_class_weights=True)

NUM_CLASSES = len(data_prep.class_names)
print(f'Classes: {NUM_CLASSES}')
print(f'Train batches: {len(data_prep.train_loader)} | Val batches: {len(data_prep.val_loader)}')

Classes: 61
Train batches: 249 | Val batches: 50

In [3]:
from modules.imagenet_loader import ImagenetLoader
from modules.evaluate_model import ModelEvaluator

loader = ImagenetLoader()

# Load pretrained ResNet18 — this serves as both the frozen teacher
# and the starting point for each student deep copy
resnet18_pretrained = loader.load_radimagenet_resnet18(
    weights_path='trained_models/resnet18_baseline_gpu_new/resnet18_baseline_gpu_new.pth',
    load_type='load'
)
resnet18_pretrained = resnet18_pretrained.to(device)

evaluator = ModelEvaluator(
    data_loader=data_prep.val_loader,
    class_names=data_prep.class_names,
    device=str(device),
)

baseline_metrics = evaluator.evaluate_single(resnet18_pretrained, 'ResNet18_baseline')
BASELINE_PARAMS  = baseline_metrics['total_parameters']
print(f'ResNet18 baseline F1:    {baseline_metrics["f1_macro"]:.4f}')
print(f'ResNet18 baseline params: {BASELINE_PARAMS:,}')

Warming up ResNet18_baseline...
Running inference...
ResNet18 baseline F1:    0.4054
ResNet18 baseline params: 11,207,805

In [4]:
import torch.nn as nn
import copy
from modules.model_trainer import modelTrainer
from modules.evaluate_model import ModelEvaluator
from pwkd import PWKDLoss, make_aux_fn, finalise_student

RESNET18_CHANNELS = {'layer2': 128, 'layer3': 256, 'layer4': 512}

PRUNING_RATIOS = [0.10, 0.25, 0.50, 0.70, 0.90]
NUM_EPOCHS     = 10
LAM            = 0.2
KD_TEMP        = 4.0
SPARSE_WEIGHT  = 1e-4

evaluator = ModelEvaluator(
    data_loader=data_prep.val_loader,
    class_names=data_prep.class_names,
    device=str(device),
)

teacher = copy.deepcopy(resnet18_pretrained).eval()
for p in teacher.parameters():
    p.requires_grad = False

pwkd_metrics = []

print(f'ResNet18 baseline F1:    {baseline_metrics["f1_macro"]:.4f}')
print(f'ResNet18 baseline params: {BASELINE_PARAMS:,}')


for ratio in PRUNING_RATIOS:
    label = f'pwkd_self_r18_r{int(ratio * 100)}'
    print(f'\n{"="*60}')
    print(f'  PWKD Option 3 (ResNet18) — pruning ratio {ratio:.0%}')
    print(f'{"="*60}')

    student = copy.deepcopy(resnet18_pretrained).to(device)
    for p in student.parameters():
        p.requires_grad = True

    pwkd_loss = PWKDLoss(
        student          = student,
        teacher          = teacher,
        pruning_ratio    = ratio,
        teacher_channels = RESNET18_CHANNELS,
        student_channels = RESNET18_CHANNELS,
        class_weights    = data_prep.class_weights.to(device)
                           if data_prep.class_weights is not None else None,
        lam              = LAM,
        kd_temp          = KD_TEMP,
        sparse_weight    = SPARSE_WEIGHT,
    ).to(device)

    trainer = modelTrainer(
        model      = student,
        data_prep  = data_prep,
        device     = device,
        learn_rate = 2e-4,
        num_epochs = NUM_EPOCHS,
        model_name = label,
    )
    trainer.loss_fn   = pwkd_loss
    trainer.optimizer = torch.optim.AdamW(
        list(student.parameters()) + list(pwkd_loss.parameters()),
        lr=2e-4, weight_decay=1e-2,
    )
    trainer.create_classnum_to_label_map(data_prep.class_names)
    trainer.train_all(save_as_object=True, aux_forward_fn=make_aux_fn(teacher), pwkd=True)

    student = finalise_student(student, pwkd_loss, data_prep.train_loader, device)

    import os
    save_dir = os.path.join('trained_models', label)
    os.makedirs(save_dir, exist_ok=True)
    torch.save({'model': student, 'epoch': NUM_EPOCHS},
               os.path.join(save_dir, f'{label}_full.pth'))
    print(f'Saved → {save_dir}/{label}_full.pth')

    student.eval()
    metrics = evaluator.evaluate_single(student, label)

    pwkd_metrics.append({
        'Pruning Ratio':      f'{int(ratio*100)}%',
        'Size Reduction (%)': round((BASELINE_PARAMS - metrics['total_parameters'])
                                    / BASELINE_PARAMS * 100, 2),
        'F1 Score':           round(metrics['f1_macro'],     4),
        'Size (MB)':          round(metrics['model_size_mb'], 1),
        'Latency (ms)':       round(metrics['avg_latency_ms'], 2),
    })
    print(f'  ratio: {ratio:.0%} | F1: {metrics["f1_macro"]:.4f} | '
          f'params: {metrics["total_parameters"]:,} | '
          f'latency: {metrics["avg_latency_ms"]:.2f}ms')

summary_df = pd.DataFrame(pwkd_metrics).set_index('Pruning Ratio')
print('\nPWKD Option 3 (ResNet18) — Results')
display(summary_df)

ResNet18 baseline F1:    0.4054
ResNet18 baseline params: 11,207,805

============================================================
  PWKD Option 3 (ResNet18) — pruning ratio 10%
============================================================
  Epoch 1/10 [  4.8%]  loss: 1.2029
  Epoch 1/10 [  9.6%]  loss: 1.2126
  Epoch 1/10 [ 14.5%]  loss: 1.3565
  Epoch 1/10 [ 19.3%]  loss: 1.3716
  Epoch 1/10 [ 24.1%]  loss: 1.0862
  Epoch 1/10 [ 28.9%]  loss: 1.1640
  Epoch 1/10 [ 33.7%]  loss: 0.9825
  Epoch 1/10 [ 38.6%]  loss: 0.8092
  Epoch 1/10 [ 43.4%]  loss: 0.9097
  Epoch 1/10 [ 48.2%]  loss: 0.8727
  Epoch 1/10 [ 53.0%]  loss: 0.8067
  Epoch 1/10 [ 57.8%]  loss: 0.7593
  Epoch 1/10 [ 62.7%]  loss: 0.7108
  Epoch 1/10 [ 67.5%]  loss: 0.7688
  Epoch 1/10 [ 72.3%]  loss: 0.6361
  Epoch 1/10 [ 77.1%]  loss: 0.6338
  Epoch 1/10 [ 81.9%]  loss: 0.6448
  Epoch 1/10 [ 86.7%]  loss: 0.6609
  Epoch 1/10 [ 91.6%]  loss: 0.6519
  Epoch 1/10 [ 96.4%]  loss: 0.5818
  Epoch 1/10 [100.0%]  loss: 0.6252

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.20batch/s]

Epoch 1/10
Train Loss: 0.8815 | Train F1: 0.5909
Val Loss: 1.6380 | Val F1: 0.3563
Epoch Time: 34.66s

  Epoch 2/10 [  4.8%]  loss: 0.6096
  Epoch 2/10 [  9.6%]  loss: 0.6121
  Epoch 2/10 [ 14.5%]  loss: 0.5500
  Epoch 2/10 [ 19.3%]  loss: 0.5767
  Epoch 2/10 [ 24.1%]  loss: 0.5175
  Epoch 2/10 [ 28.9%]  loss: 0.5362
  Epoch 2/10 [ 33.7%]  loss: 0.5298
  Epoch 2/10 [ 38.6%]  loss: 0.5356
  Epoch 2/10 [ 43.4%]  loss: 0.5539
  Epoch 2/10 [ 48.2%]  loss: 0.5138
  Epoch 2/10 [ 53.0%]  loss: 0.4959
  Epoch 2/10 [ 57.8%]  loss: 0.5325
  Epoch 2/10 [ 62.7%]  loss: 0.4847
  Epoch 2/10 [ 67.5%]  loss: 0.4380
  Epoch 2/10 [ 72.3%]  loss: 0.4894
  Epoch 2/10 [ 77.1%]  loss: 0.4471
  Epoch 2/10 [ 81.9%]  loss: 0.4803
  Epoch 2/10 [ 86.7%]  loss: 0.4789
  Epoch 2/10 [ 91.6%]  loss: 0.4255
  Epoch 2/10 [ 96.4%]  loss: 0.4202
  Epoch 2/10 [100.0%]  loss: 0.4859

Validating: 100%|██████████| 50/50 [00:03<00:00, 16.38batch/s]

Epoch 2/10
Train Loss: 0.5105 | Train F1: 0.6993
Val Loss: 1.5472 | Val F1: 0.4010
Epoch Time: 35.66s

  Epoch 3/10 [  4.8%]  loss: 0.4434
  Epoch 3/10 [  9.6%]  loss: 0.4300
  Epoch 3/10 [ 14.5%]  loss: 0.4438
  Epoch 3/10 [ 19.3%]  loss: 0.4271
  Epoch 3/10 [ 24.1%]  loss: 0.4253
  Epoch 3/10 [ 28.9%]  loss: 0.4132
  Epoch 3/10 [ 33.7%]  loss: 0.4154
  Epoch 3/10 [ 38.6%]  loss: 0.4284
  Epoch 3/10 [ 43.4%]  loss: 0.4073
  Epoch 3/10 [ 48.2%]  loss: 0.4255
  Epoch 3/10 [ 53.0%]  loss: 0.4248
  Epoch 3/10 [ 57.8%]  loss: 0.3982
  Epoch 3/10 [ 62.7%]  loss: 0.3832
  Epoch 3/10 [ 67.5%]  loss: 0.4032
  Epoch 3/10 [ 72.3%]  loss: 0.4111
  Epoch 3/10 [ 77.1%]  loss: 0.4111
  Epoch 3/10 [ 81.9%]  loss: 0.4221
  Epoch 3/10 [ 86.7%]  loss: 0.4194
  Epoch 3/10 [ 91.6%]  loss: 0.4490
  Epoch 3/10 [ 96.4%]  loss: 0.4449
  Epoch 3/10 [100.0%]  loss: 0.4438

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.91batch/s]

Epoch 3/10
Train Loss: 0.4221 | Train F1: 0.7462
Val Loss: 1.5383 | Val F1: 0.3778
Epoch Time: 35.34s

  Epoch 4/10 [  4.8%]  loss: 0.3931
  Epoch 4/10 [  9.6%]  loss: 0.4185
  Epoch 4/10 [ 14.5%]  loss: 0.4246
  Epoch 4/10 [ 19.3%]  loss: 0.4200
  Epoch 4/10 [ 24.1%]  loss: 0.3597
  Epoch 4/10 [ 28.9%]  loss: 0.3840
  Epoch 4/10 [ 33.7%]  loss: 0.3709
  Epoch 4/10 [ 38.6%]  loss: 0.3624
  Epoch 4/10 [ 43.4%]  loss: 0.3729
  Epoch 4/10 [ 48.2%]  loss: 0.3766
  Epoch 4/10 [ 53.0%]  loss: 0.3717
  Epoch 4/10 [ 57.8%]  loss: 0.3715
  Epoch 4/10 [ 62.7%]  loss: 0.3805
  Epoch 4/10 [ 67.5%]  loss: 0.4036
  Epoch 4/10 [ 72.3%]  loss: 0.3473
  Epoch 4/10 [ 77.1%]  loss: 0.4026
  Epoch 4/10 [ 81.9%]  loss: 0.3598
  Epoch 4/10 [ 86.7%]  loss: 0.3469
  Epoch 4/10 [ 91.6%]  loss: 0.3539
  Epoch 4/10 [ 96.4%]  loss: 0.3744
  Epoch 4/10 [100.0%]  loss: 0.3901

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.06batch/s]

Epoch 4/10
Train Loss: 0.3801 | Train F1: 0.7637
Val Loss: 1.5040 | Val F1: 0.4071
Epoch Time: 35.20s

  Epoch 5/10 [  4.8%]  loss: 0.4024
  Epoch 5/10 [  9.6%]  loss: 0.3641
  Epoch 5/10 [ 14.5%]  loss: 0.3645
  Epoch 5/10 [ 19.3%]  loss: 0.3837
  Epoch 5/10 [ 24.1%]  loss: 0.3791
  Epoch 5/10 [ 28.9%]  loss: 0.3968
  Epoch 5/10 [ 33.7%]  loss: 0.3731
  Epoch 5/10 [ 38.6%]  loss: 0.3741
  Epoch 5/10 [ 43.4%]  loss: 0.3682
  Epoch 5/10 [ 48.2%]  loss: 0.3733
  Epoch 5/10 [ 53.0%]  loss: 0.3611
  Epoch 5/10 [ 57.8%]  loss: 0.3521
  Epoch 5/10 [ 62.7%]  loss: 0.3661
  Epoch 5/10 [ 67.5%]  loss: 0.3638
  Epoch 5/10 [ 72.3%]  loss: 0.3306
  Epoch 5/10 [ 77.1%]  loss: 0.3619
  Epoch 5/10 [ 81.9%]  loss: 0.3836
  Epoch 5/10 [ 86.7%]  loss: 0.3754
  Epoch 5/10 [ 91.6%]  loss: 0.3389
  Epoch 5/10 [ 96.4%]  loss: 0.3663
  Epoch 5/10 [100.0%]  loss: 0.3381

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.14batch/s]

Epoch 5/10
Train Loss: 0.3678 | Train F1: 0.7892
Val Loss: 1.5155 | Val F1: 0.4077
Epoch Time: 35.07s

  Epoch 6/10 [  4.8%]  loss: 0.3590
  Epoch 6/10 [  9.6%]  loss: 0.3568
  Epoch 6/10 [ 14.5%]  loss: 0.3467
  Epoch 6/10 [ 19.3%]  loss: 0.3489
  Epoch 6/10 [ 24.1%]  loss: 0.3362
  Epoch 6/10 [ 28.9%]  loss: 0.3415
  Epoch 6/10 [ 33.7%]  loss: 0.3298
  Epoch 6/10 [ 38.6%]  loss: 0.3419
  Epoch 6/10 [ 43.4%]  loss: 0.3186
  Epoch 6/10 [ 48.2%]  loss: 0.3239
  Epoch 6/10 [ 53.0%]  loss: 0.3259
  Epoch 6/10 [ 57.8%]  loss: 0.3105
  Epoch 6/10 [ 62.7%]  loss: 0.3212
  Epoch 6/10 [ 67.5%]  loss: 0.3334
  Epoch 6/10 [ 72.3%]  loss: 0.3494
  Epoch 6/10 [ 77.1%]  loss: 0.3333
  Epoch 6/10 [ 81.9%]  loss: 0.3411
  Epoch 6/10 [ 86.7%]  loss: 0.3398
  Epoch 6/10 [ 91.6%]  loss: 0.3302
  Epoch 6/10 [ 96.4%]  loss: 0.3517
  Epoch 6/10 [100.0%]  loss: 0.3159

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.03batch/s]

Epoch 6/10
Train Loss: 0.3362 | Train F1: 0.8072
Val Loss: 1.4639 | Val F1: 0.3935
Epoch Time: 35.23s

  Epoch 7/10 [  4.8%]  loss: 0.3357
  Epoch 7/10 [  9.6%]  loss: 0.3636
  Epoch 7/10 [ 14.5%]  loss: 0.3486
  Epoch 7/10 [ 19.3%]  loss: 0.3258
  Epoch 7/10 [ 24.1%]  loss: 0.3518
  Epoch 7/10 [ 28.9%]  loss: 0.3328
  Epoch 7/10 [ 33.7%]  loss: 0.3200
  Epoch 7/10 [ 38.6%]  loss: 0.3132
  Epoch 7/10 [ 43.4%]  loss: 0.3294
  Epoch 7/10 [ 48.2%]  loss: 0.3292
  Epoch 7/10 [ 53.0%]  loss: 0.3467
  Epoch 7/10 [ 57.8%]  loss: 0.3165
  Epoch 7/10 [ 62.7%]  loss: 0.3355
  Epoch 7/10 [ 67.5%]  loss: 0.3351
  Epoch 7/10 [ 72.3%]  loss: 0.3781
  Epoch 7/10 [ 77.1%]  loss: 0.3265
  Epoch 7/10 [ 81.9%]  loss: 0.3619
  Epoch 7/10 [ 86.7%]  loss: 0.3424
  Epoch 7/10 [ 91.6%]  loss: 0.3206
  Epoch 7/10 [ 96.4%]  loss: 0.3277
  Epoch 7/10 [100.0%]  loss: 0.3228

Validating: 100%|██████████| 50/50 [00:02<00:00, 19.26batch/s]

Epoch 7/10
Train Loss: 0.3365 | Train F1: 0.8068
Val Loss: 1.4928 | Val F1: 0.3989
Epoch Time: 35.19s

  Epoch 8/10 [  4.8%]  loss: 0.3263
  Epoch 8/10 [  9.6%]  loss: 0.3207
  Epoch 8/10 [ 14.5%]  loss: 0.3422
  Epoch 8/10 [ 19.3%]  loss: 0.3417
  Epoch 8/10 [ 24.1%]  loss: 0.3369
  Epoch 8/10 [ 28.9%]  loss: 0.3163
  Epoch 8/10 [ 33.7%]  loss: 0.3257
  Epoch 8/10 [ 38.6%]  loss: 0.3273
  Epoch 8/10 [ 43.4%]  loss: 0.3150
  Epoch 8/10 [ 48.2%]  loss: 0.3140
  Epoch 8/10 [ 53.0%]  loss: 0.3171
  Epoch 8/10 [ 57.8%]  loss: 0.3234
  Epoch 8/10 [ 62.7%]  loss: 0.3131
  Epoch 8/10 [ 67.5%]  loss: 0.3251
  Epoch 8/10 [ 72.3%]  loss: 0.3257
  Epoch 8/10 [ 77.1%]  loss: 0.2995
  Epoch 8/10 [ 81.9%]  loss: 0.3120
  Epoch 8/10 [ 86.7%]  loss: 0.3066
  Epoch 8/10 [ 91.6%]  loss: 0.3013
  Epoch 8/10 [ 96.4%]  loss: 0.2999
  Epoch 8/10 [100.0%]  loss: 0.2984

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.69batch/s]

Epoch 8/10
Train Loss: 0.3187 | Train F1: 0.8214
Val Loss: 1.4989 | Val F1: 0.4019
Epoch Time: 35.33s

  Epoch 9/10 [  4.8%]  loss: 0.3105
  Epoch 9/10 [  9.6%]  loss: 0.3062
  Epoch 9/10 [ 14.5%]  loss: 0.2957
  Epoch 9/10 [ 19.3%]  loss: 0.2956
  Epoch 9/10 [ 24.1%]  loss: 0.3077
  Epoch 9/10 [ 28.9%]  loss: 0.3204
  Epoch 9/10 [ 33.7%]  loss: 0.2855
  Epoch 9/10 [ 38.6%]  loss: 0.3123
  Epoch 9/10 [ 43.4%]  loss: 0.3303
  Epoch 9/10 [ 48.2%]  loss: 0.2992
  Epoch 9/10 [ 53.0%]  loss: 0.2974
  Epoch 9/10 [ 57.8%]  loss: 0.2971
  Epoch 9/10 [ 62.7%]  loss: 0.3011
  Epoch 9/10 [ 67.5%]  loss: 0.3006
  Epoch 9/10 [ 72.3%]  loss: 0.3104
  Epoch 9/10 [ 77.1%]  loss: 0.3009
  Epoch 9/10 [ 81.9%]  loss: 0.3053
  Epoch 9/10 [ 86.7%]  loss: 0.2842
  Epoch 9/10 [ 91.6%]  loss: 0.2897
  Epoch 9/10 [ 96.4%]  loss: 0.2910
  Epoch 9/10 [100.0%]  loss: 0.3148

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.01batch/s]

Epoch 9/10
Train Loss: 0.3025 | Train F1: 0.8284
Val Loss: 1.4565 | Val F1: 0.4118
Epoch Time: 34.13s

  Epoch 10/10 [  4.8%]  loss: 0.2997
  Epoch 10/10 [  9.6%]  loss: 0.2831
  Epoch 10/10 [ 14.5%]  loss: 0.3033
  Epoch 10/10 [ 19.3%]  loss: 0.2923
  Epoch 10/10 [ 24.1%]  loss: 0.2916
  Epoch 10/10 [ 28.9%]  loss: 0.2826
  Epoch 10/10 [ 33.7%]  loss: 0.2886
  Epoch 10/10 [ 38.6%]  loss: 0.3155
  Epoch 10/10 [ 43.4%]  loss: 0.2900
  Epoch 10/10 [ 48.2%]  loss: 0.2904
  Epoch 10/10 [ 53.0%]  loss: 0.3197
  Epoch 10/10 [ 57.8%]  loss: 0.3064
  Epoch 10/10 [ 62.7%]  loss: 0.3068
  Epoch 10/10 [ 67.5%]  loss: 0.3190
  Epoch 10/10 [ 72.3%]  loss: 0.3011
  Epoch 10/10 [ 77.1%]  loss: 0.2766
  Epoch 10/10 [ 81.9%]  loss: 0.2948
  Epoch 10/10 [ 86.7%]  loss: 0.2896
  Epoch 10/10 [ 91.6%]  loss: 0.2992
  Epoch 10/10 [ 96.4%]  loss: 0.3082
  Epoch 10/10 [100.0%]  loss: 0.3064

Validating: 100%|██████████| 50/50 [00:02<00:00, 19.32batch/s]

Epoch 10/10
Train Loss: 0.2982 | Train F1: 0.8360
Val Loss: 1.5179 | Val F1: 0.4104
Epoch Time: 34.04s

Finalised: 188/1920 conv1 channels zeroed (9.8%)
Saved → trained_models/pwkd_self_r18_r10/pwkd_self_r18_r10_full.pth

Warming up pwkd_self_r18_r10...
Running inference...
  ratio: 10% | F1: 0.3858 | params: 10,121,469 | latency: 0.39ms

============================================================
  PWKD Option 3 (ResNet18) — pruning ratio 25%
============================================================
  Epoch 1/10 [  4.8%]  loss: 1.1698
  Epoch 1/10 [  9.6%]  loss: 1.3262
  Epoch 1/10 [ 14.5%]  loss: 1.2860
  Epoch 1/10 [ 19.3%]  loss: 1.2094
  Epoch 1/10 [ 24.1%]  loss: 1.1242
  Epoch 1/10 [ 28.9%]  loss: 0.9662
  Epoch 1/10 [ 33.7%]  loss: 0.9369
  Epoch 1/10 [ 38.6%]  loss: 0.9016
  Epoch 1/10 [ 43.4%]  loss: 0.7993
  Epoch 1/10 [ 48.2%]  loss: 0.9014
  Epoch 1/10 [ 53.0%]  loss: 0.7488
  Epoch 1/10 [ 57.8%]  loss: 0.7660
  Epoch 1/10 [ 62.7%]  loss: 0.7491
  Epoch 1/10 [ 67.5%]  loss: 0.7478
  Epoch 1/10 [ 72.3%]  loss: 0.7054
  Epoch 1/10 [ 77.1%]  loss: 0.6870
  Epoch 1/10 [ 81.9%]  loss: 0.6180
  Epoch 1/10 [ 86.7%]  loss: 0.6290
  Epoch 1/10 [ 91.6%]  loss: 0.5730
  Epoch 1/10 [ 96.4%]  loss: 0.5991
  Epoch 1/10 [100.0%]  loss: 0.6320

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.02batch/s]

Epoch 1/10
Train Loss: 0.8635 | Train F1: 0.5919
Val Loss: 1.5958 | Val F1: 0.3463
Epoch Time: 34.88s

  Epoch 2/10 [  4.8%]  loss: 0.5853
  Epoch 2/10 [  9.6%]  loss: 0.6297
  Epoch 2/10 [ 14.5%]  loss: 0.5988
  Epoch 2/10 [ 19.3%]  loss: 0.5721
  Epoch 2/10 [ 24.1%]  loss: 0.5656
  Epoch 2/10 [ 28.9%]  loss: 0.5390
  Epoch 2/10 [ 33.7%]  loss: 0.6057
  Epoch 2/10 [ 38.6%]  loss: 0.5328
  Epoch 2/10 [ 43.4%]  loss: 0.5078
  Epoch 2/10 [ 48.2%]  loss: 0.5118
  Epoch 2/10 [ 53.0%]  loss: 0.5082
  Epoch 2/10 [ 57.8%]  loss: 0.4839
  Epoch 2/10 [ 62.7%]  loss: 0.4625
  Epoch 2/10 [ 67.5%]  loss: 0.4571
  Epoch 2/10 [ 72.3%]  loss: 0.4330
  Epoch 2/10 [ 77.1%]  loss: 0.4800
  Epoch 2/10 [ 81.9%]  loss: 0.5030
  Epoch 2/10 [ 86.7%]  loss: 0.4594
  Epoch 2/10 [ 91.6%]  loss: 0.4127
  Epoch 2/10 [ 96.4%]  loss: 0.4616
  Epoch 2/10 [100.0%]  loss: 0.4719

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.73batch/s]

Epoch 2/10
Train Loss: 0.5139 | Train F1: 0.7030
Val Loss: 1.5039 | Val F1: 0.4091
Epoch Time: 34.97s

  Epoch 3/10 [  4.8%]  loss: 0.4259
  Epoch 3/10 [  9.6%]  loss: 0.4486
  Epoch 3/10 [ 14.5%]  loss: 0.4273
  Epoch 3/10 [ 19.3%]  loss: 0.4326
  Epoch 3/10 [ 24.1%]  loss: 0.4395
  Epoch 3/10 [ 28.9%]  loss: 0.4560
  Epoch 3/10 [ 33.7%]  loss: 0.4598
  Epoch 3/10 [ 38.6%]  loss: 0.4397
  Epoch 3/10 [ 43.4%]  loss: 0.4121
  Epoch 3/10 [ 48.2%]  loss: 0.4089
  Epoch 3/10 [ 53.0%]  loss: 0.4133
  Epoch 3/10 [ 57.8%]  loss: 0.4351
  Epoch 3/10 [ 62.7%]  loss: 0.4351
  Epoch 3/10 [ 67.5%]  loss: 0.3964
  Epoch 3/10 [ 72.3%]  loss: 0.4000
  Epoch 3/10 [ 77.1%]  loss: 0.4237
  Epoch 3/10 [ 81.9%]  loss: 0.4142
  Epoch 3/10 [ 86.7%]  loss: 0.3871
  Epoch 3/10 [ 91.6%]  loss: 0.4087
  Epoch 3/10 [ 96.4%]  loss: 0.4053
  Epoch 3/10 [100.0%]  loss: 0.4185

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.68batch/s]

Epoch 3/10
Train Loss: 0.4233 | Train F1: 0.7543
Val Loss: 1.5255 | Val F1: 0.4003
Epoch Time: 34.38s

  Epoch 4/10 [  4.8%]  loss: 0.3911
  Epoch 4/10 [  9.6%]  loss: 0.4143
  Epoch 4/10 [ 14.5%]  loss: 0.3674
  Epoch 4/10 [ 19.3%]  loss: 0.4196
  Epoch 4/10 [ 24.1%]  loss: 0.3744
  Epoch 4/10 [ 28.9%]  loss: 0.4328
  Epoch 4/10 [ 33.7%]  loss: 0.3716
  Epoch 4/10 [ 38.6%]  loss: 0.4034
  Epoch 4/10 [ 43.4%]  loss: 0.3913
  Epoch 4/10 [ 48.2%]  loss: 0.3670
  Epoch 4/10 [ 53.0%]  loss: 0.3864
  Epoch 4/10 [ 57.8%]  loss: 0.3736
  Epoch 4/10 [ 62.7%]  loss: 0.3608
  Epoch 4/10 [ 67.5%]  loss: 0.3832
  Epoch 4/10 [ 72.3%]  loss: 0.3874
  Epoch 4/10 [ 77.1%]  loss: 0.3878
  Epoch 4/10 [ 81.9%]  loss: 0.3608
  Epoch 4/10 [ 86.7%]  loss: 0.3802
  Epoch 4/10 [ 91.6%]  loss: 0.3736
  Epoch 4/10 [ 96.4%]  loss: 0.3586
  Epoch 4/10 [100.0%]  loss: 0.3475

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.12batch/s]

Epoch 4/10
Train Loss: 0.3829 | Train F1: 0.7792
Val Loss: 1.4952 | Val F1: 0.4236
Epoch Time: 34.03s

  Epoch 5/10 [  4.8%]  loss: 0.3768
  Epoch 5/10 [  9.6%]  loss: 0.3609
  Epoch 5/10 [ 14.5%]  loss: 0.3849
  Epoch 5/10 [ 19.3%]  loss: 0.3756
  Epoch 5/10 [ 24.1%]  loss: 0.3600
  Epoch 5/10 [ 28.9%]  loss: 0.3761
  Epoch 5/10 [ 33.7%]  loss: 0.3868
  Epoch 5/10 [ 38.6%]  loss: 0.4046
  Epoch 5/10 [ 43.4%]  loss: 0.3671
  Epoch 5/10 [ 48.2%]  loss: 0.3845
  Epoch 5/10 [ 53.0%]  loss: 0.3885
  Epoch 5/10 [ 57.8%]  loss: 0.3516
  Epoch 5/10 [ 62.7%]  loss: 0.3402
  Epoch 5/10 [ 67.5%]  loss: 0.3573
  Epoch 5/10 [ 72.3%]  loss: 0.3780
  Epoch 5/10 [ 77.1%]  loss: 0.3557
  Epoch 5/10 [ 81.9%]  loss: 0.3757
  Epoch 5/10 [ 86.7%]  loss: 0.3497
  Epoch 5/10 [ 91.6%]  loss: 0.3547
  Epoch 5/10 [ 96.4%]  loss: 0.3433
  Epoch 5/10 [100.0%]  loss: 0.3590

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.04batch/s]

Epoch 5/10
Train Loss: 0.3682 | Train F1: 0.7867
Val Loss: 1.5157 | Val F1: 0.4043
Epoch Time: 35.29s

  Epoch 6/10 [  4.8%]  loss: 0.3562
  Epoch 6/10 [  9.6%]  loss: 0.3443
  Epoch 6/10 [ 14.5%]  loss: 0.3372
  Epoch 6/10 [ 19.3%]  loss: 0.3599
  Epoch 6/10 [ 24.1%]  loss: 0.3254
  Epoch 6/10 [ 28.9%]  loss: 0.3593
  Epoch 6/10 [ 33.7%]  loss: 0.3500
  Epoch 6/10 [ 38.6%]  loss: 0.3303
  Epoch 6/10 [ 43.4%]  loss: 0.3406
  Epoch 6/10 [ 48.2%]  loss: 0.3272
  Epoch 6/10 [ 53.0%]  loss: 0.3374
  Epoch 6/10 [ 57.8%]  loss: 0.3371
  Epoch 6/10 [ 62.7%]  loss: 0.3633
  Epoch 6/10 [ 67.5%]  loss: 0.3890
  Epoch 6/10 [ 72.3%]  loss: 0.3573
  Epoch 6/10 [ 77.1%]  loss: 0.3586
  Epoch 6/10 [ 81.9%]  loss: 0.3691
  Epoch 6/10 [ 86.7%]  loss: 0.3406
  Epoch 6/10 [ 91.6%]  loss: 0.3467
  Epoch 6/10 [ 96.4%]  loss: 0.3327
  Epoch 6/10 [100.0%]  loss: 0.3616

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.57batch/s]

Epoch 6/10
Train Loss: 0.3486 | Train F1: 0.8010
Val Loss: 1.5564 | Val F1: 0.3886
Epoch Time: 35.37s

  Epoch 7/10 [  4.8%]  loss: 0.3331
  Epoch 7/10 [  9.6%]  loss: 0.3508
  Epoch 7/10 [ 14.5%]  loss: 0.3612
  Epoch 7/10 [ 19.3%]  loss: 0.3446
  Epoch 7/10 [ 24.1%]  loss: 0.3445
  Epoch 7/10 [ 28.9%]  loss: 0.3421
  Epoch 7/10 [ 33.7%]  loss: 0.3455
  Epoch 7/10 [ 38.6%]  loss: 0.3267
  Epoch 7/10 [ 43.4%]  loss: 0.3435
  Epoch 7/10 [ 48.2%]  loss: 0.3163
  Epoch 7/10 [ 53.0%]  loss: 0.3047
  Epoch 7/10 [ 57.8%]  loss: 0.3294
  Epoch 7/10 [ 62.7%]  loss: 0.3415
  Epoch 7/10 [ 67.5%]  loss: 0.3390
  Epoch 7/10 [ 72.3%]  loss: 0.3525
  Epoch 7/10 [ 77.1%]  loss: 0.3583
  Epoch 7/10 [ 81.9%]  loss: 0.3610
  Epoch 7/10 [ 86.7%]  loss: 0.3444
  Epoch 7/10 [ 91.6%]  loss: 0.3326
  Epoch 7/10 [ 96.4%]  loss: 0.3402
  Epoch 7/10 [100.0%]  loss: 0.3456

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.10batch/s]

Epoch 7/10
Train Loss: 0.3408 | Train F1: 0.8139
Val Loss: 1.5383 | Val F1: 0.4108
Epoch Time: 35.22s

  Epoch 8/10 [  4.8%]  loss: 0.3578
  Epoch 8/10 [  9.6%]  loss: 0.3530
  Epoch 8/10 [ 14.5%]  loss: 0.3845
  Epoch 8/10 [ 19.3%]  loss: 0.3529
  Epoch 8/10 [ 24.1%]  loss: 0.3508
  Epoch 8/10 [ 28.9%]  loss: 0.3862
  Epoch 8/10 [ 33.7%]  loss: 0.4201
  Epoch 8/10 [ 38.6%]  loss: 0.3961
  Epoch 8/10 [ 43.4%]  loss: 0.4404
  Epoch 8/10 [ 48.2%]  loss: 0.4260
  Epoch 8/10 [ 53.0%]  loss: 0.4489
  Epoch 8/10 [ 57.8%]  loss: 0.4450
  Epoch 8/10 [ 62.7%]  loss: 0.4022
  Epoch 8/10 [ 67.5%]  loss: 0.4076
  Epoch 8/10 [ 72.3%]  loss: 0.3848
  Epoch 8/10 [ 77.1%]  loss: 0.4283
  Epoch 8/10 [ 81.9%]  loss: 0.3730
  Epoch 8/10 [ 86.7%]  loss: 0.3627
  Epoch 8/10 [ 91.6%]  loss: 0.3450
  Epoch 8/10 [ 96.4%]  loss: 0.3608
  Epoch 8/10 [100.0%]  loss: 0.4273

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.13batch/s]

Epoch 8/10
Train Loss: 0.3926 | Train F1: 0.7915
Val Loss: 1.5933 | Val F1: 0.4125
Epoch Time: 34.91s

  Epoch 9/10 [  4.8%]  loss: 0.3795
  Epoch 9/10 [  9.6%]  loss: 0.4278
  Epoch 9/10 [ 14.5%]  loss: 0.4006
  Epoch 9/10 [ 19.3%]  loss: 0.3798
  Epoch 9/10 [ 24.1%]  loss: 0.3844
  Epoch 9/10 [ 28.9%]  loss: 0.3525
  Epoch 9/10 [ 33.7%]  loss: 0.3605
  Epoch 9/10 [ 38.6%]  loss: 0.3603
  Epoch 9/10 [ 43.4%]  loss: 0.3376
  Epoch 9/10 [ 48.2%]  loss: 0.3384
  Epoch 9/10 [ 53.0%]  loss: 0.3276
  Epoch 9/10 [ 57.8%]  loss: 0.3398
  Epoch 9/10 [ 62.7%]  loss: 0.3391
  Epoch 9/10 [ 67.5%]  loss: 0.3378
  Epoch 9/10 [ 72.3%]  loss: 0.3554
  Epoch 9/10 [ 77.1%]  loss: 0.3683
  Epoch 9/10 [ 81.9%]  loss: 0.3335
  Epoch 9/10 [ 86.7%]  loss: 0.3256
  Epoch 9/10 [ 91.6%]  loss: 0.3427
  Epoch 9/10 [ 96.4%]  loss: 0.3478
  Epoch 9/10 [100.0%]  loss: 0.4035

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.85batch/s]

Epoch 9/10
Train Loss: 0.3586 | Train F1: 0.8085
Val Loss: 1.5781 | Val F1: 0.3840
Epoch Time: 35.05s

  Epoch 10/10 [  4.8%]  loss: 0.3614
  Epoch 10/10 [  9.6%]  loss: 0.3371
  Epoch 10/10 [ 14.5%]  loss: 0.3449
  Epoch 10/10 [ 19.3%]  loss: 0.3361
  Epoch 10/10 [ 24.1%]  loss: 0.3312
  Epoch 10/10 [ 28.9%]  loss: 0.3338
  Epoch 10/10 [ 33.7%]  loss: 0.3351
  Epoch 10/10 [ 38.6%]  loss: 0.3092
  Epoch 10/10 [ 43.4%]  loss: 0.3267
  Epoch 10/10 [ 48.2%]  loss: 0.2932
  Epoch 10/10 [ 53.0%]  loss: 0.3251
  Epoch 10/10 [ 57.8%]  loss: 0.3010
  Epoch 10/10 [ 62.7%]  loss: 0.2949
  Epoch 10/10 [ 67.5%]  loss: 0.3050
  Epoch 10/10 [ 72.3%]  loss: 0.3035
  Epoch 10/10 [ 77.1%]  loss: 0.3255
  Epoch 10/10 [ 81.9%]  loss: 0.3077
  Epoch 10/10 [ 86.7%]  loss: 0.3048
  Epoch 10/10 [ 91.6%]  loss: 0.3050
  Epoch 10/10 [ 96.4%]  loss: 0.2964
  Epoch 10/10 [100.0%]  loss: 0.3250

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.10batch/s]

Epoch 10/10
Train Loss: 0.3191 | Train F1: 0.8272
Val Loss: 1.5000 | Val F1: 0.4261
Epoch Time: 35.22s

Finalised: 480/1920 conv1 channels zeroed (25.0%)
Saved → trained_models/pwkd_self_r18_r25/pwkd_self_r18_r25_full.pth

Warming up pwkd_self_r18_r25...
Running inference...
  ratio: 25% | F1: 0.2268 | params: 8,461,437 | latency: 0.38ms

============================================================
  PWKD Option 3 (ResNet18) — pruning ratio 50%
============================================================
  Epoch 1/10 [  4.8%]  loss: 1.2858
  Epoch 1/10 [  9.6%]  loss: 1.4004
  Epoch 1/10 [ 14.5%]  loss: 1.3513
  Epoch 1/10 [ 19.3%]  loss: 1.2222
  Epoch 1/10 [ 24.1%]  loss: 1.1181
  Epoch 1/10 [ 28.9%]  loss: 0.9521
  Epoch 1/10 [ 33.7%]  loss: 0.9912
  Epoch 1/10 [ 38.6%]  loss: 0.8370
  Epoch 1/10 [ 43.4%]  loss: 0.7813
  Epoch 1/10 [ 48.2%]  loss: 0.7593
  Epoch 1/10 [ 53.0%]  loss: 0.7509
  Epoch 1/10 [ 57.8%]  loss: 0.7178
  Epoch 1/10 [ 62.7%]  loss: 0.6781
  Epoch 1/10 [ 67.5%]  loss: 0.6266
  Epoch 1/10 [ 72.3%]  loss: 0.6790
  Epoch 1/10 [ 77.1%]  loss: 0.6653
  Epoch 1/10 [ 81.9%]  loss: 0.6012
  Epoch 1/10 [ 86.7%]  loss: 0.6400
  Epoch 1/10 [ 91.6%]  loss: 0.5827
  Epoch 1/10 [ 96.4%]  loss: 0.6035
  Epoch 1/10 [100.0%]  loss: 0.5807

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.12batch/s]

Epoch 1/10
Train Loss: 0.8520 | Train F1: 0.6072
Val Loss: 1.5186 | Val F1: 0.3834
Epoch Time: 35.13s

  Epoch 2/10 [  4.8%]  loss: 0.5594
  Epoch 2/10 [  9.6%]  loss: 0.5668
  Epoch 2/10 [ 14.5%]  loss: 0.5446
  Epoch 2/10 [ 19.3%]  loss: 0.5602
  Epoch 2/10 [ 24.1%]  loss: 0.5474
  Epoch 2/10 [ 28.9%]  loss: 0.6078
  Epoch 2/10 [ 33.7%]  loss: 0.5555
  Epoch 2/10 [ 38.6%]  loss: 0.5627
  Epoch 2/10 [ 43.4%]  loss: 0.5282
  Epoch 2/10 [ 48.2%]  loss: 0.5529
  Epoch 2/10 [ 53.0%]  loss: 0.5267
  Epoch 2/10 [ 57.8%]  loss: 0.5388
  Epoch 2/10 [ 62.7%]  loss: 0.5453
  Epoch 2/10 [ 67.5%]  loss: 0.5670
  Epoch 2/10 [ 72.3%]  loss: 0.5291
  Epoch 2/10 [ 77.1%]  loss: 0.5352
  Epoch 2/10 [ 81.9%]  loss: 0.4992
  Epoch 2/10 [ 86.7%]  loss: 0.4665
  Epoch 2/10 [ 91.6%]  loss: 0.4936
  Epoch 2/10 [ 96.4%]  loss: 0.5056
  Epoch 2/10 [100.0%]  loss: 0.4958

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.17batch/s]

Epoch 2/10
Train Loss: 0.5380 | Train F1: 0.7023
Val Loss: 1.5923 | Val F1: 0.3661
Epoch Time: 35.28s

  Epoch 3/10 [  4.8%]  loss: 0.4907
  Epoch 3/10 [  9.6%]  loss: 0.4910
  Epoch 3/10 [ 14.5%]  loss: 0.4319
  Epoch 3/10 [ 19.3%]  loss: 0.5037
  Epoch 3/10 [ 24.1%]  loss: 0.4473
  Epoch 3/10 [ 28.9%]  loss: 0.4669
  Epoch 3/10 [ 33.7%]  loss: 0.4583
  Epoch 3/10 [ 38.6%]  loss: 0.4458
  Epoch 3/10 [ 43.4%]  loss: 0.4020
  Epoch 3/10 [ 48.2%]  loss: 0.4252
  Epoch 3/10 [ 53.0%]  loss: 0.4274
  Epoch 3/10 [ 57.8%]  loss: 0.4229
  Epoch 3/10 [ 62.7%]  loss: 0.3948
  Epoch 3/10 [ 67.5%]  loss: 0.3830
  Epoch 3/10 [ 72.3%]  loss: 0.3754
  Epoch 3/10 [ 77.1%]  loss: 0.3820
  Epoch 3/10 [ 81.9%]  loss: 0.4204
  Epoch 3/10 [ 86.7%]  loss: 0.3548
  Epoch 3/10 [ 91.6%]  loss: 0.3815
  Epoch 3/10 [ 96.4%]  loss: 0.3681
  Epoch 3/10 [100.0%]  loss: 0.3873

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.79batch/s]

Epoch 3/10
Train Loss: 0.4223 | Train F1: 0.7496
Val Loss: 1.5412 | Val F1: 0.3833
Epoch Time: 34.11s

  Epoch 4/10 [  4.8%]  loss: 0.4091
  Epoch 4/10 [  9.6%]  loss: 0.4165
  Epoch 4/10 [ 14.5%]  loss: 0.3930
  Epoch 4/10 [ 19.3%]  loss: 0.3704
  Epoch 4/10 [ 24.1%]  loss: 0.3827
  Epoch 4/10 [ 28.9%]  loss: 0.3698
  Epoch 4/10 [ 33.7%]  loss: 0.4296
  Epoch 4/10 [ 38.6%]  loss: 0.3917
  Epoch 4/10 [ 43.4%]  loss: 0.3769
  Epoch 4/10 [ 48.2%]  loss: 0.4029
  Epoch 4/10 [ 53.0%]  loss: 0.3828
  Epoch 4/10 [ 57.8%]  loss: 0.3745
  Epoch 4/10 [ 62.7%]  loss: 0.3644
  Epoch 4/10 [ 67.5%]  loss: 0.3582
  Epoch 4/10 [ 72.3%]  loss: 0.3633
  Epoch 4/10 [ 77.1%]  loss: 0.3896
  Epoch 4/10 [ 81.9%]  loss: 0.3862
  Epoch 4/10 [ 86.7%]  loss: 0.3583
  Epoch 4/10 [ 91.6%]  loss: 0.3763
  Epoch 4/10 [ 96.4%]  loss: 0.4079
  Epoch 4/10 [100.0%]  loss: 0.3964

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.14batch/s]

Epoch 4/10
Train Loss: 0.3856 | Train F1: 0.7743
Val Loss: 1.6196 | Val F1: 0.3912
Epoch Time: 34.81s

  Epoch 5/10 [  4.8%]  loss: 0.4177
  Epoch 5/10 [  9.6%]  loss: 0.3996
  Epoch 5/10 [ 14.5%]  loss: 0.4019
  Epoch 5/10 [ 19.3%]  loss: 0.4225
  Epoch 5/10 [ 24.1%]  loss: 0.3802
  Epoch 5/10 [ 28.9%]  loss: 0.4256
  Epoch 5/10 [ 33.7%]  loss: 0.4046
  Epoch 5/10 [ 38.6%]  loss: 0.3732
  Epoch 5/10 [ 43.4%]  loss: 0.3778
  Epoch 5/10 [ 48.2%]  loss: 0.3489
  Epoch 5/10 [ 53.0%]  loss: 0.3629
  Epoch 5/10 [ 57.8%]  loss: 0.3899
  Epoch 5/10 [ 62.7%]  loss: 0.3767
  Epoch 5/10 [ 67.5%]  loss: 0.3471
  Epoch 5/10 [ 72.3%]  loss: 0.3580
  Epoch 5/10 [ 77.1%]  loss: 0.3533
  Epoch 5/10 [ 81.9%]  loss: 0.3613
  Epoch 5/10 [ 86.7%]  loss: 0.3818
  Epoch 5/10 [ 91.6%]  loss: 0.3661
  Epoch 5/10 [ 96.4%]  loss: 0.3575
  Epoch 5/10 [100.0%]  loss: 0.3778

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.19batch/s]

Epoch 5/10
Train Loss: 0.3802 | Train F1: 0.7842
Val Loss: 1.4817 | Val F1: 0.4157
Epoch Time: 35.19s

  Epoch 6/10 [  4.8%]  loss: 0.3552
  Epoch 6/10 [  9.6%]  loss: 0.3743
  Epoch 6/10 [ 14.5%]  loss: 0.3641
  Epoch 6/10 [ 19.3%]  loss: 0.3648
  Epoch 6/10 [ 24.1%]  loss: 0.3540
  Epoch 6/10 [ 28.9%]  loss: 0.3356
  Epoch 6/10 [ 33.7%]  loss: 0.3422
  Epoch 6/10 [ 38.6%]  loss: 0.3683
  Epoch 6/10 [ 43.4%]  loss: 0.3641
  Epoch 6/10 [ 48.2%]  loss: 0.3453
  Epoch 6/10 [ 53.0%]  loss: 0.3529
  Epoch 6/10 [ 57.8%]  loss: 0.3708
  Epoch 6/10 [ 62.7%]  loss: 0.3368
  Epoch 6/10 [ 67.5%]  loss: 0.3519
  Epoch 6/10 [ 72.3%]  loss: 0.3549
  Epoch 6/10 [ 77.1%]  loss: 0.3549
  Epoch 6/10 [ 81.9%]  loss: 0.3438
  Epoch 6/10 [ 86.7%]  loss: 0.3378
  Epoch 6/10 [ 91.6%]  loss: 0.3554
  Epoch 6/10 [ 96.4%]  loss: 0.3616
  Epoch 6/10 [100.0%]  loss: 0.3681

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.96batch/s]

Epoch 6/10
Train Loss: 0.3549 | Train F1: 0.7963
Val Loss: 1.5296 | Val F1: 0.4215
Epoch Time: 35.25s

  Epoch 7/10 [  4.8%]  loss: 0.3326
  Epoch 7/10 [  9.6%]  loss: 0.3596
  Epoch 7/10 [ 14.5%]  loss: 0.3706
  Epoch 7/10 [ 19.3%]  loss: 0.3820
  Epoch 7/10 [ 24.1%]  loss: 0.4142
  Epoch 7/10 [ 28.9%]  loss: 0.3699
  Epoch 7/10 [ 33.7%]  loss: 0.3930
  Epoch 7/10 [ 38.6%]  loss: 0.4095
  Epoch 7/10 [ 43.4%]  loss: 0.4317
  Epoch 7/10 [ 48.2%]  loss: 0.5397
  Epoch 7/10 [ 53.0%]  loss: 0.4895
  Epoch 7/10 [ 57.8%]  loss: 0.4675
  Epoch 7/10 [ 62.7%]  loss: 0.4521
  Epoch 7/10 [ 67.5%]  loss: 0.4781
  Epoch 7/10 [ 72.3%]  loss: 0.4407
  Epoch 7/10 [ 77.1%]  loss: 0.4071
  Epoch 7/10 [ 81.9%]  loss: 0.4013
  Epoch 7/10 [ 86.7%]  loss: 0.4027
  Epoch 7/10 [ 91.6%]  loss: 0.3917
  Epoch 7/10 [ 96.4%]  loss: 0.3890
  Epoch 7/10 [100.0%]  loss: 0.3958

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.10batch/s]

Epoch 7/10
Train Loss: 0.4154 | Train F1: 0.7789
Val Loss: 1.5932 | Val F1: 0.3847
Epoch Time: 35.05s

  Epoch 8/10 [  4.8%]  loss: 0.3838
  Epoch 8/10 [  9.6%]  loss: 0.3700
  Epoch 8/10 [ 14.5%]  loss: 0.3660
  Epoch 8/10 [ 19.3%]  loss: 0.3713
  Epoch 8/10 [ 24.1%]  loss: 0.3825
  Epoch 8/10 [ 28.9%]  loss: 0.3680
  Epoch 8/10 [ 33.7%]  loss: 0.3629
  Epoch 8/10 [ 38.6%]  loss: 0.3701
  Epoch 8/10 [ 43.4%]  loss: 0.3790
  Epoch 8/10 [ 48.2%]  loss: 0.3573
  Epoch 8/10 [ 53.0%]  loss: 0.3379
  Epoch 8/10 [ 57.8%]  loss: 0.3650
  Epoch 8/10 [ 62.7%]  loss: 0.3577
  Epoch 8/10 [ 67.5%]  loss: 0.3574
  Epoch 8/10 [ 72.3%]  loss: 0.3514
  Epoch 8/10 [ 77.1%]  loss: 0.3476
  Epoch 8/10 [ 81.9%]  loss: 0.3490
  Epoch 8/10 [ 86.7%]  loss: 0.3326
  Epoch 8/10 [ 91.6%]  loss: 0.3261
  Epoch 8/10 [ 96.4%]  loss: 0.3424
  Epoch 8/10 [100.0%]  loss: 0.3584

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.20batch/s]

Epoch 8/10
Train Loss: 0.3589 | Train F1: 0.8026
Val Loss: 1.5262 | Val F1: 0.4083
Epoch Time: 34.04s

  Epoch 9/10 [  4.8%]  loss: 0.3440
  Epoch 9/10 [  9.6%]  loss: 0.3338
  Epoch 9/10 [ 14.5%]  loss: 0.3614
  Epoch 9/10 [ 19.3%]  loss: 0.3283
  Epoch 9/10 [ 24.1%]  loss: 0.3326
  Epoch 9/10 [ 28.9%]  loss: 0.3111
  Epoch 9/10 [ 33.7%]  loss: 0.3442
  Epoch 9/10 [ 38.6%]  loss: 0.3467
  Epoch 9/10 [ 43.4%]  loss: 0.3291
  Epoch 9/10 [ 48.2%]  loss: 0.3219
  Epoch 9/10 [ 53.0%]  loss: 0.3321
  Epoch 9/10 [ 57.8%]  loss: 0.3188
  Epoch 9/10 [ 62.7%]  loss: 0.3355
  Epoch 9/10 [ 67.5%]  loss: 0.3557
  Epoch 9/10 [ 72.3%]  loss: 0.3268
  Epoch 9/10 [ 77.1%]  loss: 0.3216
  Epoch 9/10 [ 81.9%]  loss: 0.3209
  Epoch 9/10 [ 86.7%]  loss: 0.3035
  Epoch 9/10 [ 91.6%]  loss: 0.3296
  Epoch 9/10 [ 96.4%]  loss: 0.3274
  Epoch 9/10 [100.0%]  loss: 0.3381

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.20batch/s]

Epoch 9/10
Train Loss: 0.3315 | Train F1: 0.8224
Val Loss: 1.4786 | Val F1: 0.4145
Epoch Time: 35.20s

  Epoch 10/10 [  4.8%]  loss: 0.3156
  Epoch 10/10 [  9.6%]  loss: 0.3216
  Epoch 10/10 [ 14.5%]  loss: 0.3296
  Epoch 10/10 [ 19.3%]  loss: 0.3115
  Epoch 10/10 [ 24.1%]  loss: 0.3180
  Epoch 10/10 [ 28.9%]  loss: 0.3157
  Epoch 10/10 [ 33.7%]  loss: 0.3347
  Epoch 10/10 [ 38.6%]  loss: 0.3408
  Epoch 10/10 [ 43.4%]  loss: 0.3372
  Epoch 10/10 [ 48.2%]  loss: 0.3266
  Epoch 10/10 [ 53.0%]  loss: 0.3150
  Epoch 10/10 [ 57.8%]  loss: 0.3092
  Epoch 10/10 [ 62.7%]  loss: 0.3223
  Epoch 10/10 [ 67.5%]  loss: 0.3127
  Epoch 10/10 [ 72.3%]  loss: 0.3190
  Epoch 10/10 [ 77.1%]  loss: 0.3102
  Epoch 10/10 [ 81.9%]  loss: 0.3256
  Epoch 10/10 [ 86.7%]  loss: 0.3134
  Epoch 10/10 [ 91.6%]  loss: 0.3293
  Epoch 10/10 [ 96.4%]  loss: 0.2898
  Epoch 10/10 [100.0%]  loss: 0.3741

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.17batch/s]

Epoch 10/10
Train Loss: 0.3218 | Train F1: 0.8288
Val Loss: 1.4644 | Val F1: 0.4074
Epoch Time: 35.02s

Finalised: 960/1920 conv1 channels zeroed (50.0%)
Saved → trained_models/pwkd_self_r18_r50/pwkd_self_r18_r50_full.pth

Warming up pwkd_self_r18_r50...
Running inference...
  ratio: 50% | F1: 0.0008 | params: 5,715,069 | latency: 0.39ms

============================================================
  PWKD Option 3 (ResNet18) — pruning ratio 70%
============================================================
  Epoch 1/10 [  4.8%]  loss: 1.2834
  Epoch 1/10 [  9.6%]  loss: 1.4561
  Epoch 1/10 [ 14.5%]  loss: 1.3809
  Epoch 1/10 [ 19.3%]  loss: 1.2819
  Epoch 1/10 [ 24.1%]  loss: 1.1713
  Epoch 1/10 [ 28.9%]  loss: 1.0697
  Epoch 1/10 [ 33.7%]  loss: 0.9840
  Epoch 1/10 [ 38.6%]  loss: 0.8854
  Epoch 1/10 [ 43.4%]  loss: 0.9309
  Epoch 1/10 [ 48.2%]  loss: 0.8472
  Epoch 1/10 [ 53.0%]  loss: 0.8231
  Epoch 1/10 [ 57.8%]  loss: 0.8168
  Epoch 1/10 [ 62.7%]  loss: 0.7644
  Epoch 1/10 [ 67.5%]  loss: 0.6981
  Epoch 1/10 [ 72.3%]  loss: 0.6986
  Epoch 1/10 [ 77.1%]  loss: 0.6722
  Epoch 1/10 [ 81.9%]  loss: 0.6405
  Epoch 1/10 [ 86.7%]  loss: 0.6344
  Epoch 1/10 [ 91.6%]  loss: 0.7034
  Epoch 1/10 [ 96.4%]  loss: 0.6159
  Epoch 1/10 [100.0%]  loss: 0.6648

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.19batch/s]

Epoch 1/10
Train Loss: 0.9088 | Train F1: 0.5909
Val Loss: 1.6041 | Val F1: 0.3744
Epoch Time: 34.92s

  Epoch 2/10 [  4.8%]  loss: 0.6013
  Epoch 2/10 [  9.6%]  loss: 0.5519
  Epoch 2/10 [ 14.5%]  loss: 0.5874
  Epoch 2/10 [ 19.3%]  loss: 0.5659
  Epoch 2/10 [ 24.1%]  loss: 0.5361
  Epoch 2/10 [ 28.9%]  loss: 0.5535
  Epoch 2/10 [ 33.7%]  loss: 0.4724
  Epoch 2/10 [ 38.6%]  loss: 0.4974
  Epoch 2/10 [ 43.4%]  loss: 0.5065
  Epoch 2/10 [ 48.2%]  loss: 0.5635
  Epoch 2/10 [ 53.0%]  loss: 0.5178
  Epoch 2/10 [ 57.8%]  loss: 0.5258
  Epoch 2/10 [ 62.7%]  loss: 0.4463
  Epoch 2/10 [ 67.5%]  loss: 0.5158
  Epoch 2/10 [ 72.3%]  loss: 0.4872
  Epoch 2/10 [ 77.1%]  loss: 0.4870
  Epoch 2/10 [ 81.9%]  loss: 0.4952
  Epoch 2/10 [ 86.7%]  loss: 0.4605
  Epoch 2/10 [ 91.6%]  loss: 0.4286
  Epoch 2/10 [ 96.4%]  loss: 0.4185
  Epoch 2/10 [100.0%]  loss: 0.4598

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.22batch/s]

Epoch 2/10
Train Loss: 0.5091 | Train F1: 0.7041
Val Loss: 1.5694 | Val F1: 0.3726
Epoch Time: 34.15s

  Epoch 3/10 [  4.8%]  loss: 0.4456
  Epoch 3/10 [  9.6%]  loss: 0.4891
  Epoch 3/10 [ 14.5%]  loss: 0.4146
  Epoch 3/10 [ 19.3%]  loss: 0.4574
  Epoch 3/10 [ 24.1%]  loss: 0.4106
  Epoch 3/10 [ 28.9%]  loss: 0.4520
  Epoch 3/10 [ 33.7%]  loss: 0.4456
  Epoch 3/10 [ 38.6%]  loss: 0.4001
  Epoch 3/10 [ 43.4%]  loss: 0.4374
  Epoch 3/10 [ 48.2%]  loss: 0.4130
  Epoch 3/10 [ 53.0%]  loss: 0.4411
  Epoch 3/10 [ 57.8%]  loss: 0.4356
  Epoch 3/10 [ 62.7%]  loss: 0.4457
  Epoch 3/10 [ 67.5%]  loss: 0.4081
  Epoch 3/10 [ 72.3%]  loss: 0.4232
  Epoch 3/10 [ 77.1%]  loss: 0.4665
  Epoch 3/10 [ 81.9%]  loss: 0.3971
  Epoch 3/10 [ 86.7%]  loss: 0.4444
  Epoch 3/10 [ 91.6%]  loss: 0.4121
  Epoch 3/10 [ 96.4%]  loss: 0.4340
  Epoch 3/10 [100.0%]  loss: 0.4317

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.82batch/s]

Epoch 3/10
Train Loss: 0.4336 | Train F1: 0.7458
Val Loss: 1.5585 | Val F1: 0.3847
Epoch Time: 35.22s

  Epoch 4/10 [  4.8%]  loss: 0.4084
  Epoch 4/10 [  9.6%]  loss: 0.4364
  Epoch 4/10 [ 14.5%]  loss: 0.4164
  Epoch 4/10 [ 19.3%]  loss: 0.4391
  Epoch 4/10 [ 24.1%]  loss: 0.4415
  Epoch 4/10 [ 28.9%]  loss: 0.4047
  Epoch 4/10 [ 33.7%]  loss: 0.3884
  Epoch 4/10 [ 38.6%]  loss: 0.3973
  Epoch 4/10 [ 43.4%]  loss: 0.4110
  Epoch 4/10 [ 48.2%]  loss: 0.3866
  Epoch 4/10 [ 53.0%]  loss: 0.3965
  Epoch 4/10 [ 57.8%]  loss: 0.3874
  Epoch 4/10 [ 62.7%]  loss: 0.4179
  Epoch 4/10 [ 67.5%]  loss: 0.4061
  Epoch 4/10 [ 72.3%]  loss: 0.4228
  Epoch 4/10 [ 77.1%]  loss: 0.4108
  Epoch 4/10 [ 81.9%]  loss: 0.4183
  Epoch 4/10 [ 86.7%]  loss: 0.4048
  Epoch 4/10 [ 91.6%]  loss: 0.4163
  Epoch 4/10 [ 96.4%]  loss: 0.3658
  Epoch 4/10 [100.0%]  loss: 0.4345

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.03batch/s]

Epoch 4/10
Train Loss: 0.4097 | Train F1: 0.7690
Val Loss: 1.5207 | Val F1: 0.3901
Epoch Time: 35.24s

  Epoch 5/10 [  4.8%]  loss: 0.4038
  Epoch 5/10 [  9.6%]  loss: 0.4492
  Epoch 5/10 [ 14.5%]  loss: 0.4069
  Epoch 5/10 [ 19.3%]  loss: 0.4331
  Epoch 5/10 [ 24.1%]  loss: 0.4056
  Epoch 5/10 [ 28.9%]  loss: 0.3949
  Epoch 5/10 [ 33.7%]  loss: 0.3856
  Epoch 5/10 [ 38.6%]  loss: 0.3769
  Epoch 5/10 [ 43.4%]  loss: 0.3765
  Epoch 5/10 [ 48.2%]  loss: 0.3817
  Epoch 5/10 [ 53.0%]  loss: 0.3755
  Epoch 5/10 [ 57.8%]  loss: 0.3698
  Epoch 5/10 [ 62.7%]  loss: 0.3873
  Epoch 5/10 [ 67.5%]  loss: 0.3415
  Epoch 5/10 [ 72.3%]  loss: 0.3593
  Epoch 5/10 [ 77.1%]  loss: 0.3737
  Epoch 5/10 [ 81.9%]  loss: 0.3764
  Epoch 5/10 [ 86.7%]  loss: 0.3677
  Epoch 5/10 [ 91.6%]  loss: 0.3898
  Epoch 5/10 [ 96.4%]  loss: 0.3642
  Epoch 5/10 [100.0%]  loss: 0.3588

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.87batch/s]

Epoch 5/10
Train Loss: 0.3850 | Train F1: 0.7901
Val Loss: 1.5355 | Val F1: 0.3686
Epoch Time: 34.94s

  Epoch 6/10 [  4.8%]  loss: 0.3610
  Epoch 6/10 [  9.6%]  loss: 0.4032
  Epoch 6/10 [ 14.5%]  loss: 0.3651
  Epoch 6/10 [ 19.3%]  loss: 0.3872
  Epoch 6/10 [ 24.1%]  loss: 0.3684
  Epoch 6/10 [ 28.9%]  loss: 0.3663
  Epoch 6/10 [ 33.7%]  loss: 0.3821
  Epoch 6/10 [ 38.6%]  loss: 0.3474
  Epoch 6/10 [ 43.4%]  loss: 0.3736
  Epoch 6/10 [ 48.2%]  loss: 0.3607
  Epoch 6/10 [ 53.0%]  loss: 0.3811
  Epoch 6/10 [ 57.8%]  loss: 0.3589
  Epoch 6/10 [ 62.7%]  loss: 0.3727
  Epoch 6/10 [ 67.5%]  loss: 0.3594
  Epoch 6/10 [ 72.3%]  loss: 0.3580
  Epoch 6/10 [ 77.1%]  loss: 0.3622
  Epoch 6/10 [ 81.9%]  loss: 0.3881
  Epoch 6/10 [ 86.7%]  loss: 0.3674
  Epoch 6/10 [ 91.6%]  loss: 0.3986
  Epoch 6/10 [ 96.4%]  loss: 0.3657
  Epoch 6/10 [100.0%]  loss: 0.3646

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.13batch/s]

Epoch 6/10
Train Loss: 0.3711 | Train F1: 0.7967
Val Loss: 1.5781 | Val F1: 0.4027
Epoch Time: 35.19s

  Epoch 7/10 [  4.8%]  loss: 0.3869
  Epoch 7/10 [  9.6%]  loss: 0.3742
  Epoch 7/10 [ 14.5%]  loss: 0.3829
  Epoch 7/10 [ 19.3%]  loss: 0.3720
  Epoch 7/10 [ 24.1%]  loss: 0.3683
  Epoch 7/10 [ 28.9%]  loss: 0.3664
  Epoch 7/10 [ 33.7%]  loss: 0.3804
  Epoch 7/10 [ 38.6%]  loss: 0.3608
  Epoch 7/10 [ 43.4%]  loss: 0.3760
  Epoch 7/10 [ 48.2%]  loss: 0.3711
  Epoch 7/10 [ 53.0%]  loss: 0.3604
  Epoch 7/10 [ 57.8%]  loss: 0.3619
  Epoch 7/10 [ 62.7%]  loss: 0.3573
  Epoch 7/10 [ 67.5%]  loss: 0.3708
  Epoch 7/10 [ 72.3%]  loss: 0.3783
  Epoch 7/10 [ 77.1%]  loss: 0.3739
  Epoch 7/10 [ 81.9%]  loss: 0.3904
  Epoch 7/10 [ 86.7%]  loss: 0.3713
  Epoch 7/10 [ 91.6%]  loss: 0.3707
  Epoch 7/10 [ 96.4%]  loss: 0.3507
  Epoch 7/10 [100.0%]  loss: 0.4151

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.14batch/s]

Epoch 7/10
Train Loss: 0.3728 | Train F1: 0.8029
Val Loss: 1.6621 | Val F1: 0.3714
Epoch Time: 35.16s

  Epoch 8/10 [  4.8%]  loss: 0.3604
  Epoch 8/10 [  9.6%]  loss: 0.3801
  Epoch 8/10 [ 14.5%]  loss: 0.3855
  Epoch 8/10 [ 19.3%]  loss: 0.3920
  Epoch 8/10 [ 24.1%]  loss: 0.3609
  Epoch 8/10 [ 28.9%]  loss: 0.3693
  Epoch 8/10 [ 33.7%]  loss: 0.3904
  Epoch 8/10 [ 38.6%]  loss: 0.3487
  Epoch 8/10 [ 43.4%]  loss: 0.3785
  Epoch 8/10 [ 48.2%]  loss: 0.3567
  Epoch 8/10 [ 53.0%]  loss: 0.3659
  Epoch 8/10 [ 57.8%]  loss: 0.3391
  Epoch 8/10 [ 62.7%]  loss: 0.3507
  Epoch 8/10 [ 67.5%]  loss: 0.3489
  Epoch 8/10 [ 72.3%]  loss: 0.3439
  Epoch 8/10 [ 77.1%]  loss: 0.3435
  Epoch 8/10 [ 81.9%]  loss: 0.3259
  Epoch 8/10 [ 86.7%]  loss: 0.3497
  Epoch 8/10 [ 91.6%]  loss: 0.3371
  Epoch 8/10 [ 96.4%]  loss: 0.3365
  Epoch 8/10 [100.0%]  loss: 0.3715

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.11batch/s]

Epoch 8/10
Train Loss: 0.3587 | Train F1: 0.8094
Val Loss: 1.5222 | Val F1: 0.4052
Epoch Time: 34.26s

  Epoch 9/10 [  4.8%]  loss: 0.3478
  Epoch 9/10 [  9.6%]  loss: 0.3660
  Epoch 9/10 [ 14.5%]  loss: 0.3423
  Epoch 9/10 [ 19.3%]  loss: 0.3555
  Epoch 9/10 [ 24.1%]  loss: 0.3433
  Epoch 9/10 [ 28.9%]  loss: 0.3288
  Epoch 9/10 [ 33.7%]  loss: 0.3345
  Epoch 9/10 [ 38.6%]  loss: 0.3417
  Epoch 9/10 [ 43.4%]  loss: 0.3360
  Epoch 9/10 [ 48.2%]  loss: 0.3527
  Epoch 9/10 [ 53.0%]  loss: 0.3759
  Epoch 9/10 [ 57.8%]  loss: 0.3351
  Epoch 9/10 [ 62.7%]  loss: 0.3463
  Epoch 9/10 [ 67.5%]  loss: 0.3282
  Epoch 9/10 [ 72.3%]  loss: 0.3179
  Epoch 9/10 [ 77.1%]  loss: 0.3617
  Epoch 9/10 [ 81.9%]  loss: 0.3234
  Epoch 9/10 [ 86.7%]  loss: 0.3350
  Epoch 9/10 [ 91.6%]  loss: 0.3040
  Epoch 9/10 [ 96.4%]  loss: 0.3531
  Epoch 9/10 [100.0%]  loss: 0.3561

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.13batch/s]

Epoch 9/10
Train Loss: 0.3420 | Train F1: 0.8216
Val Loss: 1.4566 | Val F1: 0.4248
Epoch Time: 35.14s

  Epoch 10/10 [  4.8%]  loss: 0.3309
  Epoch 10/10 [  9.6%]  loss: 0.3197
  Epoch 10/10 [ 14.5%]  loss: 0.3367
  Epoch 10/10 [ 19.3%]  loss: 0.3322
  Epoch 10/10 [ 24.1%]  loss: 0.3621
  Epoch 10/10 [ 28.9%]  loss: 0.3261
  Epoch 10/10 [ 33.7%]  loss: 0.3215
  Epoch 10/10 [ 38.6%]  loss: 0.3231
  Epoch 10/10 [ 43.4%]  loss: 0.3169
  Epoch 10/10 [ 48.2%]  loss: 0.3329
  Epoch 10/10 [ 53.0%]  loss: 0.2952
  Epoch 10/10 [ 57.8%]  loss: 0.3197
  Epoch 10/10 [ 62.7%]  loss: 0.3042
  Epoch 10/10 [ 67.5%]  loss: 0.3246
  Epoch 10/10 [ 72.3%]  loss: 0.3258
  Epoch 10/10 [ 77.1%]  loss: 0.3298
  Epoch 10/10 [ 81.9%]  loss: 0.3156
  Epoch 10/10 [ 86.7%]  loss: 0.3087
  Epoch 10/10 [ 91.6%]  loss: 0.3082
  Epoch 10/10 [ 96.4%]  loss: 0.3445
  Epoch 10/10 [100.0%]  loss: 0.3108

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.16batch/s]

Epoch 10/10
Train Loss: 0.3234 | Train F1: 0.8374
Val Loss: 1.5234 | Val F1: 0.4177
Epoch Time: 34.20s

Finalised: 1340/1920 conv1 channels zeroed (69.8%)
Saved → trained_models/pwkd_self_r18_r70/pwkd_self_r18_r70_full.pth

Warming up pwkd_self_r18_r70...
Running inference...
  ratio: 70% | F1: 0.0002 | params: 3,530,301 | latency: 0.38ms

============================================================
  PWKD Option 3 (ResNet18) — pruning ratio 90%
============================================================
  Epoch 1/10 [  4.8%]  loss: 1.3469
  Epoch 1/10 [  9.6%]  loss: 1.3540
  Epoch 1/10 [ 14.5%]  loss: 1.3926
  Epoch 1/10 [ 19.3%]  loss: 1.3972
  Epoch 1/10 [ 24.1%]  loss: 1.1821
  Epoch 1/10 [ 28.9%]  loss: 1.0607
  Epoch 1/10 [ 33.7%]  loss: 0.9653
  Epoch 1/10 [ 38.6%]  loss: 0.9709
  Epoch 1/10 [ 43.4%]  loss: 0.8713
  Epoch 1/10 [ 48.2%]  loss: 0.9129
  Epoch 1/10 [ 53.0%]  loss: 0.7753
  Epoch 1/10 [ 57.8%]  loss: 0.7797
  Epoch 1/10 [ 62.7%]  loss: 0.6970
  Epoch 1/10 [ 67.5%]  loss: 0.7468
  Epoch 1/10 [ 72.3%]  loss: 0.7019
  Epoch 1/10 [ 77.1%]  loss: 0.6767
  Epoch 1/10 [ 81.9%]  loss: 0.7089
  Epoch 1/10 [ 86.7%]  loss: 0.6124
  Epoch 1/10 [ 91.6%]  loss: 0.6374
  Epoch 1/10 [ 96.4%]  loss: 0.6452
  Epoch 1/10 [100.0%]  loss: 0.6260

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.09batch/s]

Epoch 1/10
Train Loss: 0.9111 | Train F1: 0.6008
Val Loss: 1.6113 | Val F1: 0.3660
Epoch Time: 34.16s

  Epoch 2/10 [  4.8%]  loss: 0.6473
  Epoch 2/10 [  9.6%]  loss: 0.6056
  Epoch 2/10 [ 14.5%]  loss: 0.6333
  Epoch 2/10 [ 19.3%]  loss: 0.6069
  Epoch 2/10 [ 24.1%]  loss: 0.5508
  Epoch 2/10 [ 28.9%]  loss: 0.5484
  Epoch 2/10 [ 33.7%]  loss: 0.5387
  Epoch 2/10 [ 38.6%]  loss: 0.5253
  Epoch 2/10 [ 43.4%]  loss: 0.5733
  Epoch 2/10 [ 48.2%]  loss: 0.5388
  Epoch 2/10 [ 53.0%]  loss: 0.5422
  Epoch 2/10 [ 57.8%]  loss: 0.4953
  Epoch 2/10 [ 62.7%]  loss: 0.4681
  Epoch 2/10 [ 67.5%]  loss: 0.4662
  Epoch 2/10 [ 72.3%]  loss: 0.4517
  Epoch 2/10 [ 77.1%]  loss: 0.4789
  Epoch 2/10 [ 81.9%]  loss: 0.4395
  Epoch 2/10 [ 86.7%]  loss: 0.4602
  Epoch 2/10 [ 91.6%]  loss: 0.4789
  Epoch 2/10 [ 96.4%]  loss: 0.4765
  Epoch 2/10 [100.0%]  loss: 0.4966

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.18batch/s]

Epoch 2/10
Train Loss: 0.5252 | Train F1: 0.7117
Val Loss: 1.6344 | Val F1: 0.3855
Epoch Time: 34.95s

  Epoch 3/10 [  4.8%]  loss: 0.4809
  Epoch 3/10 [  9.6%]  loss: 0.4836
  Epoch 3/10 [ 14.5%]  loss: 0.4546
  Epoch 3/10 [ 19.3%]  loss: 0.4287
  Epoch 3/10 [ 24.1%]  loss: 0.4263
  Epoch 3/10 [ 28.9%]  loss: 0.4376
  Epoch 3/10 [ 33.7%]  loss: 0.4218
  Epoch 3/10 [ 38.6%]  loss: 0.4634
  Epoch 3/10 [ 43.4%]  loss: 0.4334
  Epoch 3/10 [ 48.2%]  loss: 0.4070
  Epoch 3/10 [ 53.0%]  loss: 0.4751
  Epoch 3/10 [ 57.8%]  loss: 0.4447
  Epoch 3/10 [ 62.7%]  loss: 0.4718
  Epoch 3/10 [ 67.5%]  loss: 0.4969
  Epoch 3/10 [ 72.3%]  loss: 0.4358
  Epoch 3/10 [ 77.1%]  loss: 0.4547
  Epoch 3/10 [ 81.9%]  loss: 0.4483
  Epoch 3/10 [ 86.7%]  loss: 0.4323
  Epoch 3/10 [ 91.6%]  loss: 0.4404
  Epoch 3/10 [ 96.4%]  loss: 0.4614
  Epoch 3/10 [100.0%]  loss: 0.4195

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.66batch/s]

Epoch 3/10
Train Loss: 0.4488 | Train F1: 0.7449
Val Loss: 1.5604 | Val F1: 0.4101
Epoch Time: 35.27s

  Epoch 4/10 [  4.8%]  loss: 0.4426
  Epoch 4/10 [  9.6%]  loss: 0.3971
  Epoch 4/10 [ 14.5%]  loss: 0.4181
  Epoch 4/10 [ 19.3%]  loss: 0.4181
  Epoch 4/10 [ 24.1%]  loss: 0.3876
  Epoch 4/10 [ 28.9%]  loss: 0.4093
  Epoch 4/10 [ 33.7%]  loss: 0.4260
  Epoch 4/10 [ 38.6%]  loss: 0.4275
  Epoch 4/10 [ 43.4%]  loss: 0.4040
  Epoch 4/10 [ 48.2%]  loss: 0.4214
  Epoch 4/10 [ 53.0%]  loss: 0.4171
  Epoch 4/10 [ 57.8%]  loss: 0.4037
  Epoch 4/10 [ 62.7%]  loss: 0.4200
  Epoch 4/10 [ 67.5%]  loss: 0.4011
  Epoch 4/10 [ 72.3%]  loss: 0.4318
  Epoch 4/10 [ 77.1%]  loss: 0.4339
  Epoch 4/10 [ 81.9%]  loss: 0.3791
  Epoch 4/10 [ 86.7%]  loss: 0.3658
  Epoch 4/10 [ 91.6%]  loss: 0.3841
  Epoch 4/10 [ 96.4%]  loss: 0.4135
  Epoch 4/10 [100.0%]  loss: 0.4089

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.08batch/s]

Epoch 4/10
Train Loss: 0.4100 | Train F1: 0.7712
Val Loss: 1.5174 | Val F1: 0.4009
Epoch Time: 35.10s

  Epoch 5/10 [  4.8%]  loss: 0.4160
  Epoch 5/10 [  9.6%]  loss: 0.4113
  Epoch 5/10 [ 14.5%]  loss: 0.4312
  Epoch 5/10 [ 19.3%]  loss: 0.4653
  Epoch 5/10 [ 24.1%]  loss: 0.4271
  Epoch 5/10 [ 28.9%]  loss: 0.4025
  Epoch 5/10 [ 33.7%]  loss: 0.4261
  Epoch 5/10 [ 38.6%]  loss: 0.4002
  Epoch 5/10 [ 43.4%]  loss: 0.3855
  Epoch 5/10 [ 48.2%]  loss: 0.3970
  Epoch 5/10 [ 53.0%]  loss: 0.3934
  Epoch 5/10 [ 57.8%]  loss: 0.3707
  Epoch 5/10 [ 62.7%]  loss: 0.3849
  Epoch 5/10 [ 67.5%]  loss: 0.3822
  Epoch 5/10 [ 72.3%]  loss: 0.3842
  Epoch 5/10 [ 77.1%]  loss: 0.3688
  Epoch 5/10 [ 81.9%]  loss: 0.3929
  Epoch 5/10 [ 86.7%]  loss: 0.3903
  Epoch 5/10 [ 91.6%]  loss: 0.3967
  Epoch 5/10 [ 96.4%]  loss: 0.3695
  Epoch 5/10 [100.0%]  loss: 0.3604

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.06batch/s]

Epoch 5/10
Train Loss: 0.3984 | Train F1: 0.7883
Val Loss: 1.5028 | Val F1: 0.4115
Epoch Time: 35.08s

  Epoch 6/10 [  4.8%]  loss: 0.3950
  Epoch 6/10 [  9.6%]  loss: 0.3454
  Epoch 6/10 [ 14.5%]  loss: 0.3490
  Epoch 6/10 [ 19.3%]  loss: 0.3532
  Epoch 6/10 [ 24.1%]  loss: 0.3432
  Epoch 6/10 [ 28.9%]  loss: 0.3632
  Epoch 6/10 [ 33.7%]  loss: 0.4059
  Epoch 6/10 [ 38.6%]  loss: 0.3699
  Epoch 6/10 [ 43.4%]  loss: 0.3835
  Epoch 6/10 [ 48.2%]  loss: 0.3967
  Epoch 6/10 [ 53.0%]  loss: 0.3935
  Epoch 6/10 [ 57.8%]  loss: 0.3821
  Epoch 6/10 [ 62.7%]  loss: 0.3697
  Epoch 6/10 [ 67.5%]  loss: 0.3768
  Epoch 6/10 [ 72.3%]  loss: 0.3500
  Epoch 6/10 [ 77.1%]  loss: 0.3646
  Epoch 6/10 [ 81.9%]  loss: 0.3598
  Epoch 6/10 [ 86.7%]  loss: 0.3691
  Epoch 6/10 [ 91.6%]  loss: 0.3486
  Epoch 6/10 [ 96.4%]  loss: 0.3472
  Epoch 6/10 [100.0%]  loss: 0.3617

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.70batch/s]

Epoch 6/10
Train Loss: 0.3681 | Train F1: 0.8043
Val Loss: 1.5009 | Val F1: 0.4130
Epoch Time: 35.26s

  Epoch 7/10 [  4.8%]  loss: 0.3634
  Epoch 7/10 [  9.6%]  loss: 0.3358
  Epoch 7/10 [ 14.5%]  loss: 0.3554
  Epoch 7/10 [ 19.3%]  loss: 0.3785
  Epoch 7/10 [ 24.1%]  loss: 0.3408
  Epoch 7/10 [ 28.9%]  loss: 0.3480
  Epoch 7/10 [ 33.7%]  loss: 0.3454
  Epoch 7/10 [ 38.6%]  loss: 0.3448
  Epoch 7/10 [ 43.4%]  loss: 0.3434
  Epoch 7/10 [ 48.2%]  loss: 0.3431
  Epoch 7/10 [ 53.0%]  loss: 0.3349
  Epoch 7/10 [ 57.8%]  loss: 0.3992
  Epoch 7/10 [ 62.7%]  loss: 0.3479
  Epoch 7/10 [ 67.5%]  loss: 0.3805
  Epoch 7/10 [ 72.3%]  loss: 0.3899
  Epoch 7/10 [ 77.1%]  loss: 0.3530
  Epoch 7/10 [ 81.9%]  loss: 0.3899
  Epoch 7/10 [ 86.7%]  loss: 0.3870
  Epoch 7/10 [ 91.6%]  loss: 0.3392
  Epoch 7/10 [ 96.4%]  loss: 0.3596
  Epoch 7/10 [100.0%]  loss: 0.3895

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.87batch/s]

Epoch 7/10
Train Loss: 0.3601 | Train F1: 0.8129
Val Loss: 1.5946 | Val F1: 0.3874
Epoch Time: 35.29s

  Epoch 8/10 [  4.8%]  loss: 0.3764
  Epoch 8/10 [  9.6%]  loss: 0.3420
  Epoch 8/10 [ 14.5%]  loss: 0.3463
  Epoch 8/10 [ 19.3%]  loss: 0.3459
  Epoch 8/10 [ 24.1%]  loss: 0.3735
  Epoch 8/10 [ 28.9%]  loss: 0.3719
  Epoch 8/10 [ 33.7%]  loss: 0.3639
  Epoch 8/10 [ 38.6%]  loss: 0.3680
  Epoch 8/10 [ 43.4%]  loss: 0.3459
  Epoch 8/10 [ 48.2%]  loss: 0.3612
  Epoch 8/10 [ 53.0%]  loss: 0.3605
  Epoch 8/10 [ 57.8%]  loss: 0.3343
  Epoch 8/10 [ 62.7%]  loss: 0.3357
  Epoch 8/10 [ 67.5%]  loss: 0.3625
  Epoch 8/10 [ 72.3%]  loss: 0.3512
  Epoch 8/10 [ 77.1%]  loss: 0.3361
  Epoch 8/10 [ 81.9%]  loss: 0.3467
  Epoch 8/10 [ 86.7%]  loss: 0.3498
  Epoch 8/10 [ 91.6%]  loss: 0.3467
  Epoch 8/10 [ 96.4%]  loss: 0.3265
  Epoch 8/10 [100.0%]  loss: 0.3317

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.14batch/s]

Epoch 8/10
Train Loss: 0.3515 | Train F1: 0.8133
Val Loss: 1.5001 | Val F1: 0.3985
Epoch Time: 34.90s

  Epoch 9/10 [  4.8%]  loss: 0.3398
  Epoch 9/10 [  9.6%]  loss: 0.3807
  Epoch 9/10 [ 14.5%]  loss: 0.3414
  Epoch 9/10 [ 19.3%]  loss: 0.3424
  Epoch 9/10 [ 24.1%]  loss: 0.3570
  Epoch 9/10 [ 28.9%]  loss: 0.3599
  Epoch 9/10 [ 33.7%]  loss: 0.3452
  Epoch 9/10 [ 38.6%]  loss: 0.3314
  Epoch 9/10 [ 43.4%]  loss: 0.3505
  Epoch 9/10 [ 48.2%]  loss: 0.3546
  Epoch 9/10 [ 53.0%]  loss: 0.3798
  Epoch 9/10 [ 57.8%]  loss: 0.3696
  Epoch 9/10 [ 62.7%]  loss: 0.3551
  Epoch 9/10 [ 67.5%]  loss: 0.3555
  Epoch 9/10 [ 72.3%]  loss: 0.3535
  Epoch 9/10 [ 77.1%]  loss: 0.3257
  Epoch 9/10 [ 81.9%]  loss: 0.3278
  Epoch 9/10 [ 86.7%]  loss: 0.3376
  Epoch 9/10 [ 91.6%]  loss: 0.3341
  Epoch 9/10 [ 96.4%]  loss: 0.3388
  Epoch 9/10 [100.0%]  loss: 0.3358

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.08batch/s]

Epoch 9/10
Train Loss: 0.3485 | Train F1: 0.8156
Val Loss: 1.5116 | Val F1: 0.4044
Epoch Time: 35.20s

  Epoch 10/10 [  4.8%]  loss: 0.3235
  Epoch 10/10 [  9.6%]  loss: 0.3150
  Epoch 10/10 [ 14.5%]  loss: 0.3582
  Epoch 10/10 [ 19.3%]  loss: 0.3457
  Epoch 10/10 [ 24.1%]  loss: 0.3146
  Epoch 10/10 [ 28.9%]  loss: 0.3454
  Epoch 10/10 [ 33.7%]  loss: 0.3270
  Epoch 10/10 [ 38.6%]  loss: 0.3254
  Epoch 10/10 [ 43.4%]  loss: 0.3252
  Epoch 10/10 [ 48.2%]  loss: 0.3492
  Epoch 10/10 [ 53.0%]  loss: 0.3455
  Epoch 10/10 [ 57.8%]  loss: 0.3350
  Epoch 10/10 [ 62.7%]  loss: 0.3477
  Epoch 10/10 [ 67.5%]  loss: 0.3276
  Epoch 10/10 [ 72.3%]  loss: 0.3269
  Epoch 10/10 [ 77.1%]  loss: 0.3412
  Epoch 10/10 [ 81.9%]  loss: 0.3366
  Epoch 10/10 [ 86.7%]  loss: 0.3241
  Epoch 10/10 [ 91.6%]  loss: 0.3297
  Epoch 10/10 [ 96.4%]  loss: 0.3266
  Epoch 10/10 [100.0%]  loss: 0.3527

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.95batch/s]

Epoch 10/10
Train Loss: 0.3342 | Train F1: 0.8363
Val Loss: 1.4871 | Val F1: 0.4209
Epoch Time: 35.16s

Finalised: 1724/1920 conv1 channels zeroed (89.8%)
Saved → trained_models/pwkd_self_r18_r90/pwkd_self_r18_r90_full.pth

Warming up pwkd_self_r18_r90...
Running inference...
  ratio: 90% | F1: 0.0002 | params: 1,339,197 | latency: 0.39ms

PWKD Option 3 (ResNet18) — Results

               Size Reduction (%)  F1 Score  Size (MB)  Latency (ms)
Pruning Ratio
10%                          9.69    0.3858       42.8          0.39
25%                         24.50    0.2268       42.8          0.38
50%                         49.01    0.0008       42.8          0.39
70%                         68.50    0.0002       42.8          0.38
90%                         88.05    0.0002       42.8          0.39

In [6]:
# ── Extra ratios to better capture the Pareto curve descent ──────────────────
# Run this cell independently — existing trained models are not affected.

EXTRA_RATIOS = [0.2, 0.3, 0.35, 0.40, 0.45]   # between the good and collapsed points

for ratio in EXTRA_RATIOS:
    label = f'pwkd_self_r18_r{int(ratio * 100)}'
    print(f'\n{"="*60}')
    print(f'  PWKD Option 3 (ResNet18) — pruning ratio {ratio:.0%}')
    print(f'{"="*60}')

    student = copy.deepcopy(resnet18_pretrained).to(device)
    for p in student.parameters():
        p.requires_grad = True

    pwkd_loss = PWKDLoss(
        student          = student,
        teacher          = teacher,
        pruning_ratio    = ratio,
        teacher_channels = RESNET18_CHANNELS,
        student_channels = RESNET18_CHANNELS,
        class_weights    = data_prep.class_weights.to(device)
                           if data_prep.class_weights is not None else None,
        lam              = LAM,
        kd_temp          = KD_TEMP,
        sparse_weight    = SPARSE_WEIGHT,
    ).to(device)

    trainer = modelTrainer(
        model      = student,
        data_prep  = data_prep,
        device     = device,
        learn_rate = 5e-4,
        num_epochs = NUM_EPOCHS,
        model_name = label,
    )
    trainer.loss_fn   = pwkd_loss
    trainer.optimizer = torch.optim.AdamW(
        list(student.parameters()) + list(pwkd_loss.parameters()),
        lr=5e-4, weight_decay=1e-2,
    )
    trainer.create_classnum_to_label_map(data_prep.class_names)
    trainer.train_all(save_as_object=True, aux_forward_fn=make_aux_fn(teacher), pwkd=True)

    student = finalise_student(student, pwkd_loss, data_prep.train_loader, device)

    save_dir = os.path.join('trained_models', label)
    os.makedirs(save_dir, exist_ok=True)
    torch.save({'model': student, 'epoch': NUM_EPOCHS},
               os.path.join(save_dir, f'{label}_full.pth'))
    print(f'Saved → {save_dir}/{label}_full.pth')

    student.eval()
    metrics = evaluator.evaluate_single(student, label)

    pwkd_metrics.append({
        'Pruning Ratio':      f'{int(ratio*100)}%',
        'Size Reduction (%)': round((BASELINE_PARAMS - metrics['total_parameters'])
                                    / BASELINE_PARAMS * 100, 2),
        'F1 Score':           round(metrics['f1_macro'],     4),
        'Size (MB)':          round(metrics['model_size_mb'], 1),
        'Latency (ms)':       round(metrics['avg_latency_ms'], 2),
    })
    print(f'  ratio: {ratio:.0%} | F1: {metrics["f1_macro"]:.4f} | '
          f'params: {metrics["total_parameters"]:,}')

summary_df = pd.DataFrame(pwkd_metrics).set_index('Pruning Ratio')
display(summary_df)

============================================================
  PWKD Option 3 (ResNet18) — pruning ratio 20%
============================================================
  Epoch 1/10 [  4.8%]  loss: 1.9581
  Epoch 1/10 [  9.6%]  loss: 2.3039
  Epoch 1/10 [ 14.5%]  loss: 2.3477
  Epoch 1/10 [ 19.3%]  loss: 2.0448
  Epoch 1/10 [ 24.1%]  loss: 1.7762
  Epoch 1/10 [ 28.9%]  loss: 1.7435
  Epoch 1/10 [ 33.7%]  loss: 1.5967
  Epoch 1/10 [ 38.6%]  loss: 1.5793
  Epoch 1/10 [ 43.4%]  loss: 1.4946
  Epoch 1/10 [ 48.2%]  loss: 1.5867
  Epoch 1/10 [ 53.0%]  loss: 1.2651
  Epoch 1/10 [ 57.8%]  loss: 1.2774
  Epoch 1/10 [ 62.7%]  loss: 1.1060
  Epoch 1/10 [ 67.5%]  loss: 1.2242
  Epoch 1/10 [ 72.3%]  loss: 1.0655
  Epoch 1/10 [ 77.1%]  loss: 1.0708
  Epoch 1/10 [ 81.9%]  loss: 1.0910
  Epoch 1/10 [ 86.7%]  loss: 1.0435
  Epoch 1/10 [ 91.6%]  loss: 1.0059
  Epoch 1/10 [ 96.4%]  loss: 1.0149
  Epoch 1/10 [100.0%]  loss: 0.9300

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.14batch/s]

Epoch 1/10
Train Loss: 1.4599 | Train F1: 0.4103
Val Loss: 2.1841 | Val F1: 0.2409
Epoch Time: 34.05s

  Epoch 2/10 [  4.8%]  loss: 1.0035
  Epoch 2/10 [  9.6%]  loss: 0.9506
  Epoch 2/10 [ 14.5%]  loss: 0.8132
  Epoch 2/10 [ 19.3%]  loss: 0.9065
  Epoch 2/10 [ 24.1%]  loss: 0.9335
  Epoch 2/10 [ 28.9%]  loss: 0.7876
  Epoch 2/10 [ 33.7%]  loss: 0.8188
  Epoch 2/10 [ 38.6%]  loss: 0.8541
  Epoch 2/10 [ 43.4%]  loss: 0.7839
  Epoch 2/10 [ 48.2%]  loss: 0.7512
  Epoch 2/10 [ 53.0%]  loss: 0.7734
  Epoch 2/10 [ 57.8%]  loss: 0.7353
  Epoch 2/10 [ 62.7%]  loss: 0.6897
  Epoch 2/10 [ 67.5%]  loss: 0.6670
  Epoch 2/10 [ 72.3%]  loss: 0.7133
  Epoch 2/10 [ 77.1%]  loss: 0.6318
  Epoch 2/10 [ 81.9%]  loss: 0.6125
  Epoch 2/10 [ 86.7%]  loss: 0.6754
  Epoch 2/10 [ 91.6%]  loss: 0.6592
  Epoch 2/10 [ 96.4%]  loss: 0.6445
  Epoch 2/10 [100.0%]  loss: 0.6382

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.82batch/s]

Epoch 2/10
Train Loss: 0.7655 | Train F1: 0.5742
Val Loss: 1.8259 | Val F1: 0.3157
Epoch Time: 35.22s

  Epoch 3/10 [  4.8%]  loss: 0.6385
  Epoch 3/10 [  9.6%]  loss: 0.6470
  Epoch 3/10 [ 14.5%]  loss: 0.6644
  Epoch 3/10 [ 19.3%]  loss: 0.5668
  Epoch 3/10 [ 24.1%]  loss: 0.6084
  Epoch 3/10 [ 28.9%]  loss: 0.6227
  Epoch 3/10 [ 33.7%]  loss: 0.6112
  Epoch 3/10 [ 38.6%]  loss: 0.5897
  Epoch 3/10 [ 43.4%]  loss: 0.5706
  Epoch 3/10 [ 48.2%]  loss: 0.5858
  Epoch 3/10 [ 53.0%]  loss: 0.5488
  Epoch 3/10 [ 57.8%]  loss: 0.6090
  Epoch 3/10 [ 62.7%]  loss: 0.6009
  Epoch 3/10 [ 67.5%]  loss: 0.5701
  Epoch 3/10 [ 72.3%]  loss: 0.5722
  Epoch 3/10 [ 77.1%]  loss: 0.6086
  Epoch 3/10 [ 81.9%]  loss: 0.6011
  Epoch 3/10 [ 86.7%]  loss: 0.5886
  Epoch 3/10 [ 91.6%]  loss: 0.7133
  Epoch 3/10 [ 96.4%]  loss: 0.6441
  Epoch 3/10 [100.0%]  loss: 0.7128

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.20batch/s]

Epoch 3/10
Train Loss: 0.6119 | Train F1: 0.6516
Val Loss: 2.0295 | Val F1: 0.2818
Epoch Time: 35.08s

  Epoch 4/10 [  4.8%]  loss: 0.6095
  Epoch 4/10 [  9.6%]  loss: 0.7231
  Epoch 4/10 [ 14.5%]  loss: 0.7248
  Epoch 4/10 [ 19.3%]  loss: 0.6423
  Epoch 4/10 [ 24.1%]  loss: 0.5807
  Epoch 4/10 [ 28.9%]  loss: 0.5864
  Epoch 4/10 [ 33.7%]  loss: 0.5581
  Epoch 4/10 [ 38.6%]  loss: 0.5925
  Epoch 4/10 [ 43.4%]  loss: 0.5647
  Epoch 4/10 [ 48.2%]  loss: 0.5086
  Epoch 4/10 [ 53.0%]  loss: 0.5356
  Epoch 4/10 [ 57.8%]  loss: 0.5740
  Epoch 4/10 [ 62.7%]  loss: 0.5349
  Epoch 4/10 [ 67.5%]  loss: 0.5749
  Epoch 4/10 [ 72.3%]  loss: 0.5558
  Epoch 4/10 [ 77.1%]  loss: 0.5430
  Epoch 4/10 [ 81.9%]  loss: 0.5212
  Epoch 4/10 [ 86.7%]  loss: 0.5621
  Epoch 4/10 [ 91.6%]  loss: 0.5520
  Epoch 4/10 [ 96.4%]  loss: 0.5281
  Epoch 4/10 [100.0%]  loss: 0.5064

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.07batch/s]

Epoch 4/10
Train Loss: 0.5760 | Train F1: 0.6596
Val Loss: 1.8685 | Val F1: 0.3098
Epoch Time: 35.18s

  Epoch 5/10 [  4.8%]  loss: 0.5244
  Epoch 5/10 [  9.6%]  loss: 0.5077
  Epoch 5/10 [ 14.5%]  loss: 0.5232
  Epoch 5/10 [ 19.3%]  loss: 0.5485
  Epoch 5/10 [ 24.1%]  loss: 0.4905
  Epoch 5/10 [ 28.9%]  loss: 0.4551
  Epoch 5/10 [ 33.7%]  loss: 0.4592
  Epoch 5/10 [ 38.6%]  loss: 0.5328
  Epoch 5/10 [ 43.4%]  loss: 0.5047
  Epoch 5/10 [ 48.2%]  loss: 0.5020
  Epoch 5/10 [ 53.0%]  loss: 0.5584
  Epoch 5/10 [ 57.8%]  loss: 0.4654
  Epoch 5/10 [ 62.7%]  loss: 0.5054
  Epoch 5/10 [ 67.5%]  loss: 0.4938
  Epoch 5/10 [ 72.3%]  loss: 0.4510
  Epoch 5/10 [ 77.1%]  loss: 0.4779
  Epoch 5/10 [ 81.9%]  loss: 0.4646
  Epoch 5/10 [ 86.7%]  loss: 0.4817
  Epoch 5/10 [ 91.6%]  loss: 0.4402
  Epoch 5/10 [ 96.4%]  loss: 0.4509
  Epoch 5/10 [100.0%]  loss: 0.4717

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.97batch/s]

Epoch 5/10
Train Loss: 0.4911 | Train F1: 0.6967
Val Loss: 1.7264 | Val F1: 0.3523
Epoch Time: 35.28s

  Epoch 6/10 [  4.8%]  loss: 0.4799
  Epoch 6/10 [  9.6%]  loss: 0.4431
  Epoch 6/10 [ 14.5%]  loss: 0.4452
  Epoch 6/10 [ 19.3%]  loss: 0.4137
  Epoch 6/10 [ 24.1%]  loss: 0.4269
  Epoch 6/10 [ 28.9%]  loss: 0.4872
  Epoch 6/10 [ 33.7%]  loss: 0.4369
  Epoch 6/10 [ 38.6%]  loss: 0.4336
  Epoch 6/10 [ 43.4%]  loss: 0.4104
  Epoch 6/10 [ 48.2%]  loss: 0.3960
  Epoch 6/10 [ 53.0%]  loss: 0.3973
  Epoch 6/10 [ 57.8%]  loss: 0.4288
  Epoch 6/10 [ 62.7%]  loss: 0.4158
  Epoch 6/10 [ 67.5%]  loss: 0.4269
  Epoch 6/10 [ 72.3%]  loss: 0.4410
  Epoch 6/10 [ 77.1%]  loss: 0.3999
  Epoch 6/10 [ 81.9%]  loss: 0.4151
  Epoch 6/10 [ 86.7%]  loss: 0.3950
  Epoch 6/10 [ 91.6%]  loss: 0.4493
  Epoch 6/10 [ 96.4%]  loss: 0.4319
  Epoch 6/10 [100.0%]  loss: 0.4359

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.16batch/s]

Epoch 6/10
Train Loss: 0.4290 | Train F1: 0.7408
Val Loss: 1.7706 | Val F1: 0.3423
Epoch Time: 34.92s

  Epoch 7/10 [  4.8%]  loss: 0.4164
  Epoch 7/10 [  9.6%]  loss: 0.4350
  Epoch 7/10 [ 14.5%]  loss: 0.4140
  Epoch 7/10 [ 19.3%]  loss: 0.4572
  Epoch 7/10 [ 24.1%]  loss: 0.4233
  Epoch 7/10 [ 28.9%]  loss: 0.4035
  Epoch 7/10 [ 33.7%]  loss: 0.4042
  Epoch 7/10 [ 38.6%]  loss: 0.4064
  Epoch 7/10 [ 43.4%]  loss: 0.4280
  Epoch 7/10 [ 48.2%]  loss: 0.4060
  Epoch 7/10 [ 53.0%]  loss: 0.3976
  Epoch 7/10 [ 57.8%]  loss: 0.4199
  Epoch 7/10 [ 62.7%]  loss: 0.4203
  Epoch 7/10 [ 67.5%]  loss: 0.4189
  Epoch 7/10 [ 72.3%]  loss: 0.4296
  Epoch 7/10 [ 77.1%]  loss: 0.5089
  Epoch 7/10 [ 81.9%]  loss: 0.4526
  Epoch 7/10 [ 86.7%]  loss: 0.4297
  Epoch 7/10 [ 91.6%]  loss: 0.4866
  Epoch 7/10 [ 96.4%]  loss: 0.4316
  Epoch 7/10 [100.0%]  loss: 0.4733

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.68batch/s]

Epoch 7/10
Train Loss: 0.4311 | Train F1: 0.7518
Val Loss: 1.8492 | Val F1: 0.3280
Epoch Time: 34.93s

  Epoch 8/10 [  4.8%]  loss: 0.4290
  Epoch 8/10 [  9.6%]  loss: 0.3918
  Epoch 8/10 [ 14.5%]  loss: 0.4250
  Epoch 8/10 [ 19.3%]  loss: 0.4049
  Epoch 8/10 [ 24.1%]  loss: 0.4148
  Epoch 8/10 [ 28.9%]  loss: 0.4212
  Epoch 8/10 [ 33.7%]  loss: 0.3976
  Epoch 8/10 [ 38.6%]  loss: 0.4376
  Epoch 8/10 [ 43.4%]  loss: 0.3740
  Epoch 8/10 [ 48.2%]  loss: 0.4045
  Epoch 8/10 [ 53.0%]  loss: 0.4303
  Epoch 8/10 [ 57.8%]  loss: 0.3871
  Epoch 8/10 [ 62.7%]  loss: 0.4225
  Epoch 8/10 [ 67.5%]  loss: 0.3803
  Epoch 8/10 [ 72.3%]  loss: 0.3847
  Epoch 8/10 [ 77.1%]  loss: 0.4001
  Epoch 8/10 [ 81.9%]  loss: 0.3901
  Epoch 8/10 [ 86.7%]  loss: 0.3783
  Epoch 8/10 [ 91.6%]  loss: 0.3779
  Epoch 8/10 [ 96.4%]  loss: 0.3971
  Epoch 8/10 [100.0%]  loss: 0.4196

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.14batch/s]

Epoch 8/10
Train Loss: 0.4031 | Train F1: 0.7648
Val Loss: 1.7068 | Val F1: 0.3442
Epoch Time: 35.08s

  Epoch 9/10 [  4.8%]  loss: 0.4057
  Epoch 9/10 [  9.6%]  loss: 0.3689
  Epoch 9/10 [ 14.5%]  loss: 0.3875
  Epoch 9/10 [ 19.3%]  loss: 0.3640
  Epoch 9/10 [ 24.1%]  loss: 0.3700
  Epoch 9/10 [ 28.9%]  loss: 0.3770
  Epoch 9/10 [ 33.7%]  loss: 0.3604
  Epoch 9/10 [ 38.6%]  loss: 0.3711
  Epoch 9/10 [ 43.4%]  loss: 0.3522
  Epoch 9/10 [ 48.2%]  loss: 0.3468
  Epoch 9/10 [ 53.0%]  loss: 0.4101
  Epoch 9/10 [ 57.8%]  loss: 0.3844
  Epoch 9/10 [ 62.7%]  loss: 0.3749
  Epoch 9/10 [ 67.5%]  loss: 0.4263
  Epoch 9/10 [ 72.3%]  loss: 0.4677
  Epoch 9/10 [ 77.1%]  loss: 0.3809
  Epoch 9/10 [ 81.9%]  loss: 0.4039
  Epoch 9/10 [ 86.7%]  loss: 0.4368
  Epoch 9/10 [ 91.6%]  loss: 0.4393
  Epoch 9/10 [ 96.4%]  loss: 0.4529
  Epoch 9/10 [100.0%]  loss: 0.4562

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.19batch/s]

Epoch 9/10
Train Loss: 0.3963 | Train F1: 0.7713
Val Loss: 1.8569 | Val F1: 0.3324
Epoch Time: 34.30s

  Epoch 10/10 [  4.8%]  loss: 0.5006
  Epoch 10/10 [  9.6%]  loss: 0.4976
  Epoch 10/10 [ 14.5%]  loss: 0.4207
  Epoch 10/10 [ 19.3%]  loss: 0.4310
  Epoch 10/10 [ 24.1%]  loss: 0.3920
  Epoch 10/10 [ 28.9%]  loss: 0.4206
  Epoch 10/10 [ 33.7%]  loss: 0.4046
  Epoch 10/10 [ 38.6%]  loss: 0.4400
  Epoch 10/10 [ 43.4%]  loss: 0.4169
  Epoch 10/10 [ 48.2%]  loss: 0.4210
  Epoch 10/10 [ 53.0%]  loss: 0.4415
  Epoch 10/10 [ 57.8%]  loss: 0.4554
  Epoch 10/10 [ 62.7%]  loss: 0.4169
  Epoch 10/10 [ 67.5%]  loss: 0.3881
  Epoch 10/10 [ 72.3%]  loss: 0.3473
  Epoch 10/10 [ 77.1%]  loss: 0.3853
  Epoch 10/10 [ 81.9%]  loss: 0.4057
  Epoch 10/10 [ 86.7%]  loss: 0.3899
  Epoch 10/10 [ 91.6%]  loss: 0.4169
  Epoch 10/10 [ 96.4%]  loss: 0.3831
  Epoch 10/10 [100.0%]  loss: 0.4439

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.72batch/s]

Epoch 10/10
Train Loss: 0.4197 | Train F1: 0.7581
Val Loss: 1.7431 | Val F1: 0.3624
Epoch Time: 34.94s

Finalised: 380/1920 conv1 channels zeroed (19.8%)
Saved → trained_models/pwkd_self_r18_r20/pwkd_self_r18_r20_full.pth

Warming up pwkd_self_r18_r20...
Running inference...
  ratio: 20% | F1: 0.3177 | params: 9,023,037

============================================================
  PWKD Option 3 (ResNet18) — pruning ratio 30%
============================================================
  Epoch 1/10 [  4.8%]  loss: 2.2379
  Epoch 1/10 [  9.6%]  loss: 2.2452
  Epoch 1/10 [ 14.5%]  loss: 1.9446
  Epoch 1/10 [ 19.3%]  loss: 1.7618
  Epoch 1/10 [ 24.1%]  loss: 1.9107
  Epoch 1/10 [ 28.9%]  loss: 1.7821
  Epoch 1/10 [ 33.7%]  loss: 1.5628
  Epoch 1/10 [ 38.6%]  loss: 1.4105
  Epoch 1/10 [ 43.4%]  loss: 1.3278
  Epoch 1/10 [ 48.2%]  loss: 1.3637
  Epoch 1/10 [ 53.0%]  loss: 1.2402
  Epoch 1/10 [ 57.8%]  loss: 1.1527
  Epoch 1/10 [ 62.7%]  loss: 1.2347
  Epoch 1/10 [ 67.5%]  loss: 1.1651
  Epoch 1/10 [ 72.3%]  loss: 1.0291
  Epoch 1/10 [ 77.1%]  loss: 0.9940
  Epoch 1/10 [ 81.9%]  loss: 0.8596
  Epoch 1/10 [ 86.7%]  loss: 0.9150
  Epoch 1/10 [ 91.6%]  loss: 0.9344
  Epoch 1/10 [ 96.4%]  loss: 0.8960
  Epoch 1/10 [100.0%]  loss: 0.8970

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.26batch/s]

Epoch 1/10
Train Loss: 1.3803 | Train F1: 0.4264
Val Loss: 2.0999 | Val F1: 0.2742
Epoch Time: 35.03s

  Epoch 2/10 [  4.8%]  loss: 0.9453
  Epoch 2/10 [  9.6%]  loss: 0.9461
  Epoch 2/10 [ 14.5%]  loss: 0.8686
  Epoch 2/10 [ 19.3%]  loss: 0.7781
  Epoch 2/10 [ 24.1%]  loss: 0.8234
  Epoch 2/10 [ 28.9%]  loss: 0.8138
  Epoch 2/10 [ 33.7%]  loss: 0.7351
  Epoch 2/10 [ 38.6%]  loss: 0.7432
  Epoch 2/10 [ 43.4%]  loss: 0.7305
  Epoch 2/10 [ 48.2%]  loss: 0.7827
  Epoch 2/10 [ 53.0%]  loss: 0.7753
  Epoch 2/10 [ 57.8%]  loss: 0.6655
  Epoch 2/10 [ 62.7%]  loss: 0.6848
  Epoch 2/10 [ 67.5%]  loss: 0.7136
  Epoch 2/10 [ 72.3%]  loss: 0.6254
  Epoch 2/10 [ 77.1%]  loss: 0.7141
  Epoch 2/10 [ 81.9%]  loss: 0.7436
  Epoch 2/10 [ 86.7%]  loss: 0.7273
  Epoch 2/10 [ 91.6%]  loss: 0.6657
  Epoch 2/10 [ 96.4%]  loss: 0.6621
  Epoch 2/10 [100.0%]  loss: 0.6059

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.93batch/s]

Epoch 2/10
Train Loss: 0.7517 | Train F1: 0.5840
Val Loss: 1.9172 | Val F1: 0.2989
Epoch Time: 35.15s

  Epoch 3/10 [  4.8%]  loss: 0.6448
  Epoch 3/10 [  9.6%]  loss: 0.5436
  Epoch 3/10 [ 14.5%]  loss: 0.6511
  Epoch 3/10 [ 19.3%]  loss: 0.5651
  Epoch 3/10 [ 24.1%]  loss: 0.6432
  Epoch 3/10 [ 28.9%]  loss: 0.5899
  Epoch 3/10 [ 33.7%]  loss: 0.5928
  Epoch 3/10 [ 38.6%]  loss: 0.6389
  Epoch 3/10 [ 43.4%]  loss: 0.6704
  Epoch 3/10 [ 48.2%]  loss: 0.6204
  Epoch 3/10 [ 53.0%]  loss: 0.6293
  Epoch 3/10 [ 57.8%]  loss: 0.6579
  Epoch 3/10 [ 62.7%]  loss: 0.6000
  Epoch 3/10 [ 67.5%]  loss: 0.6262
  Epoch 3/10 [ 72.3%]  loss: 0.5930
  Epoch 3/10 [ 77.1%]  loss: 0.5809
  Epoch 3/10 [ 81.9%]  loss: 0.5367
  Epoch 3/10 [ 86.7%]  loss: 0.5705
  Epoch 3/10 [ 91.6%]  loss: 0.5547
  Epoch 3/10 [ 96.4%]  loss: 0.5078
  Epoch 3/10 [100.0%]  loss: 0.4869

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.13batch/s]

Epoch 3/10
Train Loss: 0.5967 | Train F1: 0.6511
Val Loss: 1.8509 | Val F1: 0.3098
Epoch Time: 35.15s

  Epoch 4/10 [  4.8%]  loss: 0.5396
  Epoch 4/10 [  9.6%]  loss: 0.5265
  Epoch 4/10 [ 14.5%]  loss: 0.5037
  Epoch 4/10 [ 19.3%]  loss: 0.5279
  Epoch 4/10 [ 24.1%]  loss: 0.4844
  Epoch 4/10 [ 28.9%]  loss: 0.5256
  Epoch 4/10 [ 33.7%]  loss: 0.5290
  Epoch 4/10 [ 38.6%]  loss: 0.5184
  Epoch 4/10 [ 43.4%]  loss: 0.5189
  Epoch 4/10 [ 48.2%]  loss: 0.5336
  Epoch 4/10 [ 53.0%]  loss: 0.4839
  Epoch 4/10 [ 57.8%]  loss: 0.4866
  Epoch 4/10 [ 62.7%]  loss: 0.5014
  Epoch 4/10 [ 67.5%]  loss: 0.5006
  Epoch 4/10 [ 72.3%]  loss: 0.4864
  Epoch 4/10 [ 77.1%]  loss: 0.5200
  Epoch 4/10 [ 81.9%]  loss: 0.4980
  Epoch 4/10 [ 86.7%]  loss: 0.4856
  Epoch 4/10 [ 91.6%]  loss: 0.5004
  Epoch 4/10 [ 96.4%]  loss: 0.5051
  Epoch 4/10 [100.0%]  loss: 0.4886

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.12batch/s]

Epoch 4/10
Train Loss: 0.5081 | Train F1: 0.6949
Val Loss: 1.7601 | Val F1: 0.3360
Epoch Time: 34.87s

  Epoch 5/10 [  4.8%]  loss: 0.5284
  Epoch 5/10 [  9.6%]  loss: 0.4831
  Epoch 5/10 [ 14.5%]  loss: 0.4811
  Epoch 5/10 [ 19.3%]  loss: 0.5234
  Epoch 5/10 [ 24.1%]  loss: 0.5362
  Epoch 5/10 [ 28.9%]  loss: 0.5364
  Epoch 5/10 [ 33.7%]  loss: 0.5491
  Epoch 5/10 [ 38.6%]  loss: 0.5128
  Epoch 5/10 [ 43.4%]  loss: 0.5631
  Epoch 5/10 [ 48.2%]  loss: 0.5448
  Epoch 5/10 [ 53.0%]  loss: 0.5187
  Epoch 5/10 [ 57.8%]  loss: 0.5421
  Epoch 5/10 [ 62.7%]  loss: 0.5132
  Epoch 5/10 [ 67.5%]  loss: 0.5068
  Epoch 5/10 [ 72.3%]  loss: 0.5132
  Epoch 5/10 [ 77.1%]  loss: 0.5495
  Epoch 5/10 [ 81.9%]  loss: 0.5222
  Epoch 5/10 [ 86.7%]  loss: 0.5488
  Epoch 5/10 [ 91.6%]  loss: 0.5457
  Epoch 5/10 [ 96.4%]  loss: 0.5396
  Epoch 5/10 [100.0%]  loss: 0.5231

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.87batch/s]

Epoch 5/10
Train Loss: 0.5277 | Train F1: 0.6972
Val Loss: 1.9479 | Val F1: 0.3229
Epoch Time: 35.17s

  Epoch 6/10 [  4.8%]  loss: 0.4913
  Epoch 6/10 [  9.6%]  loss: 0.5500
  Epoch 6/10 [ 14.5%]  loss: 0.4883
  Epoch 6/10 [ 19.3%]  loss: 0.4608
  Epoch 6/10 [ 24.1%]  loss: 0.4984
  Epoch 6/10 [ 28.9%]  loss: 0.4958
  Epoch 6/10 [ 33.7%]  loss: 0.5124
  Epoch 6/10 [ 38.6%]  loss: 0.4688
  Epoch 6/10 [ 43.4%]  loss: 0.4458
  Epoch 6/10 [ 48.2%]  loss: 0.4531
  Epoch 6/10 [ 53.0%]  loss: 0.4491
  Epoch 6/10 [ 57.8%]  loss: 0.4120
  Epoch 6/10 [ 62.7%]  loss: 0.4123
  Epoch 6/10 [ 67.5%]  loss: 0.4406
  Epoch 6/10 [ 72.3%]  loss: 0.4706
  Epoch 6/10 [ 77.1%]  loss: 0.4809
  Epoch 6/10 [ 81.9%]  loss: 0.4400
  Epoch 6/10 [ 86.7%]  loss: 0.4258
  Epoch 6/10 [ 91.6%]  loss: 0.4621
  Epoch 6/10 [ 96.4%]  loss: 0.4216
  Epoch 6/10 [100.0%]  loss: 0.4341

Validating: 100%|██████████| 50/50 [00:02<00:00, 19.19batch/s]

Epoch 6/10
Train Loss: 0.4629 | Train F1: 0.7282
Val Loss: 1.7713 | Val F1: 0.3249
Epoch Time: 35.11s

  Epoch 7/10 [  4.8%]  loss: 0.4278
  Epoch 7/10 [  9.6%]  loss: 0.4152
  Epoch 7/10 [ 14.5%]  loss: 0.4151
  Epoch 7/10 [ 19.3%]  loss: 0.4289
  Epoch 7/10 [ 24.1%]  loss: 0.4144
  Epoch 7/10 [ 28.9%]  loss: 0.4304
  Epoch 7/10 [ 33.7%]  loss: 0.4599
  Epoch 7/10 [ 38.6%]  loss: 0.4275
  Epoch 7/10 [ 43.4%]  loss: 0.4008
  Epoch 7/10 [ 48.2%]  loss: 0.4388
  Epoch 7/10 [ 53.0%]  loss: 0.4320
  Epoch 7/10 [ 57.8%]  loss: 0.4114
  Epoch 7/10 [ 62.7%]  loss: 0.4152
  Epoch 7/10 [ 67.5%]  loss: 0.3920
  Epoch 7/10 [ 72.3%]  loss: 0.4145
  Epoch 7/10 [ 77.1%]  loss: 0.4157
  Epoch 7/10 [ 81.9%]  loss: 0.3936
  Epoch 7/10 [ 86.7%]  loss: 0.3873
  Epoch 7/10 [ 91.6%]  loss: 0.4086
  Epoch 7/10 [ 96.4%]  loss: 0.3823
  Epoch 7/10 [100.0%]  loss: 0.4119

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.18batch/s]

Epoch 7/10
Train Loss: 0.4154 | Train F1: 0.7604
Val Loss: 1.6879 | Val F1: 0.3622
Epoch Time: 35.16s

  Epoch 8/10 [  4.8%]  loss: 0.3809
  Epoch 8/10 [  9.6%]  loss: 0.4374
  Epoch 8/10 [ 14.5%]  loss: 0.4014
  Epoch 8/10 [ 19.3%]  loss: 0.4273
  Epoch 8/10 [ 24.1%]  loss: 0.3815
  Epoch 8/10 [ 28.9%]  loss: 0.3922
  Epoch 8/10 [ 33.7%]  loss: 0.3789
  Epoch 8/10 [ 38.6%]  loss: 0.3887
  Epoch 8/10 [ 43.4%]  loss: 0.3610
  Epoch 8/10 [ 48.2%]  loss: 0.3508
  Epoch 8/10 [ 53.0%]  loss: 0.3984
  Epoch 8/10 [ 57.8%]  loss: 0.4266
  Epoch 8/10 [ 62.7%]  loss: 0.3822
  Epoch 8/10 [ 67.5%]  loss: 0.3981
  Epoch 8/10 [ 72.3%]  loss: 0.3948
  Epoch 8/10 [ 77.1%]  loss: 0.3685
  Epoch 8/10 [ 81.9%]  loss: 0.3564
  Epoch 8/10 [ 86.7%]  loss: 0.3596
  Epoch 8/10 [ 91.6%]  loss: 0.3621
  Epoch 8/10 [ 96.4%]  loss: 0.3671
  Epoch 8/10 [100.0%]  loss: 0.3834

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.81batch/s]

Epoch 8/10
Train Loss: 0.3856 | Train F1: 0.7741
Val Loss: 1.7635 | Val F1: 0.3508
Epoch Time: 34.96s

  Epoch 9/10 [  4.8%]  loss: 0.4015
  Epoch 9/10 [  9.6%]  loss: 0.3571
  Epoch 9/10 [ 14.5%]  loss: 0.3755
  Epoch 9/10 [ 19.3%]  loss: 0.3763
  Epoch 9/10 [ 24.1%]  loss: 0.3880
  Epoch 9/10 [ 28.9%]  loss: 0.3841
  Epoch 9/10 [ 33.7%]  loss: 0.4035
  Epoch 9/10 [ 38.6%]  loss: 0.3763
  Epoch 9/10 [ 43.4%]  loss: 0.4112
  Epoch 9/10 [ 48.2%]  loss: 0.3544
  Epoch 9/10 [ 53.0%]  loss: 0.3389
  Epoch 9/10 [ 57.8%]  loss: 0.3621
  Epoch 9/10 [ 62.7%]  loss: 0.3795
  Epoch 9/10 [ 67.5%]  loss: 0.3819
  Epoch 9/10 [ 72.3%]  loss: 0.3976
  Epoch 9/10 [ 77.1%]  loss: 0.3754
  Epoch 9/10 [ 81.9%]  loss: 0.4115
  Epoch 9/10 [ 86.7%]  loss: 0.3681
  Epoch 9/10 [ 91.6%]  loss: 0.3979
  Epoch 9/10 [ 96.4%]  loss: 0.3847
  Epoch 9/10 [100.0%]  loss: 0.3854

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.95batch/s]

Epoch 9/10
Train Loss: 0.3814 | Train F1: 0.7893
Val Loss: 1.8165 | Val F1: 0.3427
Epoch Time: 35.13s

  Epoch 10/10 [  4.8%]  loss: 0.4072
  Epoch 10/10 [  9.6%]  loss: 0.3948
  Epoch 10/10 [ 14.5%]  loss: 0.4020
  Epoch 10/10 [ 19.3%]  loss: 0.4152
  Epoch 10/10 [ 24.1%]  loss: 0.4174
  Epoch 10/10 [ 28.9%]  loss: 0.4151
  Epoch 10/10 [ 33.7%]  loss: 0.3695
  Epoch 10/10 [ 38.6%]  loss: 0.4192
  Epoch 10/10 [ 43.4%]  loss: 0.4463
  Epoch 10/10 [ 48.2%]  loss: 0.4221
  Epoch 10/10 [ 53.0%]  loss: 0.4217
  Epoch 10/10 [ 57.8%]  loss: 0.4222
  Epoch 10/10 [ 62.7%]  loss: 0.3931
  Epoch 10/10 [ 67.5%]  loss: 0.3982
  Epoch 10/10 [ 72.3%]  loss: 0.4537
  Epoch 10/10 [ 77.1%]  loss: 0.3914
  Epoch 10/10 [ 81.9%]  loss: 0.4041
  Epoch 10/10 [ 86.7%]  loss: 0.3910
  Epoch 10/10 [ 91.6%]  loss: 0.3888
  Epoch 10/10 [ 96.4%]  loss: 0.3596
  Epoch 10/10 [100.0%]  loss: 0.3883

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.14batch/s]

Epoch 10/10
Train Loss: 0.4060 | Train F1: 0.7722
Val Loss: 1.7538 | Val F1: 0.3471
Epoch Time: 34.94s

Finalised: 572/1920 conv1 channels zeroed (29.8%)
Saved → trained_models/pwkd_self_r18_r30/pwkd_self_r18_r30_full.pth

Warming up pwkd_self_r18_r30...
Running inference...
  ratio: 30% | F1: 0.1643 | params: 7,930,365

============================================================
  PWKD Option 3 (ResNet18) — pruning ratio 35%
============================================================
  Epoch 1/10 [  4.8%]  loss: 2.1866
  Epoch 1/10 [  9.6%]  loss: 2.3442
  Epoch 1/10 [ 14.5%]  loss: 2.2538
  Epoch 1/10 [ 19.3%]  loss: 1.7765
  Epoch 1/10 [ 24.1%]  loss: 1.7468
  Epoch 1/10 [ 28.9%]  loss: 1.6134
  Epoch 1/10 [ 33.7%]  loss: 1.5404
  Epoch 1/10 [ 38.6%]  loss: 1.5113
  Epoch 1/10 [ 43.4%]  loss: 1.4685
  Epoch 1/10 [ 48.2%]  loss: 1.3508
  Epoch 1/10 [ 53.0%]  loss: 1.2989
  Epoch 1/10 [ 57.8%]  loss: 1.2135
  Epoch 1/10 [ 62.7%]  loss: 1.1971
  Epoch 1/10 [ 67.5%]  loss: 1.1441
  Epoch 1/10 [ 72.3%]  loss: 1.0817
  Epoch 1/10 [ 77.1%]  loss: 1.2059
  Epoch 1/10 [ 81.9%]  loss: 1.0258
  Epoch 1/10 [ 86.7%]  loss: 0.9904
  Epoch 1/10 [ 91.6%]  loss: 0.9123
  Epoch 1/10 [ 96.4%]  loss: 1.0198
  Epoch 1/10 [100.0%]  loss: 0.9809

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.18batch/s]

Epoch 1/10
Train Loss: 1.4273 | Train F1: 0.4131
Val Loss: 2.2843 | Val F1: 0.2569
Epoch Time: 34.85s

  Epoch 2/10 [  4.8%]  loss: 0.9932
  Epoch 2/10 [  9.6%]  loss: 0.9054
  Epoch 2/10 [ 14.5%]  loss: 0.8049
  Epoch 2/10 [ 19.3%]  loss: 0.7854
  Epoch 2/10 [ 24.1%]  loss: 0.8026
  Epoch 2/10 [ 28.9%]  loss: 0.8003
  Epoch 2/10 [ 33.7%]  loss: 0.7817
  Epoch 2/10 [ 38.6%]  loss: 0.7347
  Epoch 2/10 [ 43.4%]  loss: 0.7269
  Epoch 2/10 [ 48.2%]  loss: 0.8009
  Epoch 2/10 [ 53.0%]  loss: 0.7496
  Epoch 2/10 [ 57.8%]  loss: 0.7825
  Epoch 2/10 [ 62.7%]  loss: 0.7802
  Epoch 2/10 [ 67.5%]  loss: 0.8634
  Epoch 2/10 [ 72.3%]  loss: 0.7625
  Epoch 2/10 [ 77.1%]  loss: 0.7115
  Epoch 2/10 [ 81.9%]  loss: 0.6951
  Epoch 2/10 [ 86.7%]  loss: 0.6532
  Epoch 2/10 [ 91.6%]  loss: 0.8165
  Epoch 2/10 [ 96.4%]  loss: 0.7482
  Epoch 2/10 [100.0%]  loss: 0.7322

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.26batch/s]

Epoch 2/10
Train Loss: 0.7830 | Train F1: 0.5563
Val Loss: 2.0759 | Val F1: 0.2830
Epoch Time: 35.02s

  Epoch 3/10 [  4.8%]  loss: 0.7810
  Epoch 3/10 [  9.6%]  loss: 0.7472
  Epoch 3/10 [ 14.5%]  loss: 0.7074
  Epoch 3/10 [ 19.3%]  loss: 0.6835
  Epoch 3/10 [ 24.1%]  loss: 0.6158
  Epoch 3/10 [ 28.9%]  loss: 0.6708
  Epoch 3/10 [ 33.7%]  loss: 0.6188
  Epoch 3/10 [ 38.6%]  loss: 0.6192
  Epoch 3/10 [ 43.4%]  loss: 0.6781
  Epoch 3/10 [ 48.2%]  loss: 0.5343
  Epoch 3/10 [ 53.0%]  loss: 0.6205
  Epoch 3/10 [ 57.8%]  loss: 0.5798
  Epoch 3/10 [ 62.7%]  loss: 0.6131
  Epoch 3/10 [ 67.5%]  loss: 0.6099
  Epoch 3/10 [ 72.3%]  loss: 0.6028
  Epoch 3/10 [ 77.1%]  loss: 0.5899
  Epoch 3/10 [ 81.9%]  loss: 0.5881
  Epoch 3/10 [ 86.7%]  loss: 0.5957
  Epoch 3/10 [ 91.6%]  loss: 0.5965
  Epoch 3/10 [ 96.4%]  loss: 0.5510
  Epoch 3/10 [100.0%]  loss: 0.6396

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.76batch/s]

Epoch 3/10
Train Loss: 0.6305 | Train F1: 0.6364
Val Loss: 1.8834 | Val F1: 0.3132
Epoch Time: 35.30s

  Epoch 4/10 [  4.8%]  loss: 0.5829
  Epoch 4/10 [  9.6%]  loss: 0.5801
  Epoch 4/10 [ 14.5%]  loss: 0.5712
  Epoch 4/10 [ 19.3%]  loss: 0.5390
  Epoch 4/10 [ 24.1%]  loss: 0.5364
  Epoch 4/10 [ 28.9%]  loss: 0.5342
  Epoch 4/10 [ 33.7%]  loss: 0.5344
  Epoch 4/10 [ 38.6%]  loss: 0.5547
  Epoch 4/10 [ 43.4%]  loss: 0.5362
  Epoch 4/10 [ 48.2%]  loss: 0.5335
  Epoch 4/10 [ 53.0%]  loss: 0.5121
  Epoch 4/10 [ 57.8%]  loss: 0.4626
  Epoch 4/10 [ 62.7%]  loss: 0.5473
  Epoch 4/10 [ 67.5%]  loss: 0.5018
  Epoch 4/10 [ 72.3%]  loss: 0.5045
  Epoch 4/10 [ 77.1%]  loss: 0.4908
  Epoch 4/10 [ 81.9%]  loss: 0.5036
  Epoch 4/10 [ 86.7%]  loss: 0.5012
  Epoch 4/10 [ 91.6%]  loss: 0.4853
  Epoch 4/10 [ 96.4%]  loss: 0.5089
  Epoch 4/10 [100.0%]  loss: 0.4811

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.82batch/s]

Epoch 4/10
Train Loss: 0.5244 | Train F1: 0.6878
Val Loss: 1.9596 | Val F1: 0.3032
Epoch Time: 35.22s

  Epoch 5/10 [  4.8%]  loss: 0.4862
  Epoch 5/10 [  9.6%]  loss: 0.4864
  Epoch 5/10 [ 14.5%]  loss: 0.4639
  Epoch 5/10 [ 19.3%]  loss: 0.4550
  Epoch 5/10 [ 24.1%]  loss: 0.4665
  Epoch 5/10 [ 28.9%]  loss: 0.4853
  Epoch 5/10 [ 33.7%]  loss: 0.4670
  Epoch 5/10 [ 38.6%]  loss: 0.4377
  Epoch 5/10 [ 43.4%]  loss: 0.4474
  Epoch 5/10 [ 48.2%]  loss: 0.4639
  Epoch 5/10 [ 53.0%]  loss: 0.4722
  Epoch 5/10 [ 57.8%]  loss: 0.4589
  Epoch 5/10 [ 62.7%]  loss: 0.5455
  Epoch 5/10 [ 67.5%]  loss: 0.4599
  Epoch 5/10 [ 72.3%]  loss: 0.5176
  Epoch 5/10 [ 77.1%]  loss: 0.5292
  Epoch 5/10 [ 81.9%]  loss: 0.4659
  Epoch 5/10 [ 86.7%]  loss: 0.4902
  Epoch 5/10 [ 91.6%]  loss: 0.4674
  Epoch 5/10 [ 96.4%]  loss: 0.4671
  Epoch 5/10 [100.0%]  loss: 0.4979

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.25batch/s]

Epoch 5/10
Train Loss: 0.4774 | Train F1: 0.7210
Val Loss: 1.8358 | Val F1: 0.3245
Epoch Time: 34.01s

  Epoch 6/10 [  4.8%]  loss: 0.4786
  Epoch 6/10 [  9.6%]  loss: 0.4927
  Epoch 6/10 [ 14.5%]  loss: 0.4857
  Epoch 6/10 [ 19.3%]  loss: 0.4567
  Epoch 6/10 [ 24.1%]  loss: 0.5031
  Epoch 6/10 [ 28.9%]  loss: 0.4624
  Epoch 6/10 [ 33.7%]  loss: 0.4972
  Epoch 6/10 [ 38.6%]  loss: 0.4528
  Epoch 6/10 [ 43.4%]  loss: 0.4957
  Epoch 6/10 [ 48.2%]  loss: 0.5206
  Epoch 6/10 [ 53.0%]  loss: 0.4968
  Epoch 6/10 [ 57.8%]  loss: 0.4524
  Epoch 6/10 [ 62.7%]  loss: 0.4708
  Epoch 6/10 [ 67.5%]  loss: 0.4601
  Epoch 6/10 [ 72.3%]  loss: 0.4631
  Epoch 6/10 [ 77.1%]  loss: 0.4523
  Epoch 6/10 [ 81.9%]  loss: 0.4758
  Epoch 6/10 [ 86.7%]  loss: 0.4378
  Epoch 6/10 [ 91.6%]  loss: 0.4550
  Epoch 6/10 [ 96.4%]  loss: 0.4160
  Epoch 6/10 [100.0%]  loss: 0.4347

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.18batch/s]

Epoch 6/10
Train Loss: 0.4700 | Train F1: 0.7202
Val Loss: 1.8461 | Val F1: 0.3334
Epoch Time: 35.02s

  Epoch 7/10 [  4.8%]  loss: 0.4770
  Epoch 7/10 [  9.6%]  loss: 0.4322
  Epoch 7/10 [ 14.5%]  loss: 0.4769
  Epoch 7/10 [ 19.3%]  loss: 0.4358
  Epoch 7/10 [ 24.1%]  loss: 0.4501
  Epoch 7/10 [ 28.9%]  loss: 0.4187
  Epoch 7/10 [ 33.7%]  loss: 0.4418
  Epoch 7/10 [ 38.6%]  loss: 0.4476
  Epoch 7/10 [ 43.4%]  loss: 0.4273
  Epoch 7/10 [ 48.2%]  loss: 0.4062
  Epoch 7/10 [ 53.0%]  loss: 0.4357
  Epoch 7/10 [ 57.8%]  loss: 0.4620
  Epoch 7/10 [ 62.7%]  loss: 0.4432
  Epoch 7/10 [ 67.5%]  loss: 0.4290
  Epoch 7/10 [ 72.3%]  loss: 0.4385
  Epoch 7/10 [ 77.1%]  loss: 0.4380
  Epoch 7/10 [ 81.9%]  loss: 0.4505
  Epoch 7/10 [ 86.7%]  loss: 0.4427
  Epoch 7/10 [ 91.6%]  loss: 0.4742
  Epoch 7/10 [ 96.4%]  loss: 0.4200
  Epoch 7/10 [100.0%]  loss: 0.4400

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.13batch/s]

Epoch 7/10
Train Loss: 0.4423 | Train F1: 0.7446
Val Loss: 1.8679 | Val F1: 0.3152
Epoch Time: 35.19s

  Epoch 8/10 [  4.8%]  loss: 0.4034
  Epoch 8/10 [  9.6%]  loss: 0.4223
  Epoch 8/10 [ 14.5%]  loss: 0.4242
  Epoch 8/10 [ 19.3%]  loss: 0.4139
  Epoch 8/10 [ 24.1%]  loss: 0.4280
  Epoch 8/10 [ 28.9%]  loss: 0.4541
  Epoch 8/10 [ 33.7%]  loss: 0.4352
  Epoch 8/10 [ 38.6%]  loss: 0.4446
  Epoch 8/10 [ 43.4%]  loss: 0.5172
  Epoch 8/10 [ 48.2%]  loss: 0.4459
  Epoch 8/10 [ 53.0%]  loss: 0.4076
  Epoch 8/10 [ 57.8%]  loss: 0.4426
  Epoch 8/10 [ 62.7%]  loss: 0.4725
  Epoch 8/10 [ 67.5%]  loss: 0.4853
  Epoch 8/10 [ 72.3%]  loss: 0.4740
  Epoch 8/10 [ 77.1%]  loss: 0.4799
  Epoch 8/10 [ 81.9%]  loss: 0.4120
  Epoch 8/10 [ 86.7%]  loss: 0.4182
  Epoch 8/10 [ 91.6%]  loss: 0.4184
  Epoch 8/10 [ 96.4%]  loss: 0.4182
  Epoch 8/10 [100.0%]  loss: 0.4078

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.84batch/s]

Epoch 8/10
Train Loss: 0.4397 | Train F1: 0.7488
Val Loss: 1.7782 | Val F1: 0.3436
Epoch Time: 35.25s

  Epoch 9/10 [  4.8%]  loss: 0.3998
  Epoch 9/10 [  9.6%]  loss: 0.4270
  Epoch 9/10 [ 14.5%]  loss: 0.4520
  Epoch 9/10 [ 19.3%]  loss: 0.4372
  Epoch 9/10 [ 24.1%]  loss: 0.4209
  Epoch 9/10 [ 28.9%]  loss: 0.4012
  Epoch 9/10 [ 33.7%]  loss: 0.4159
  Epoch 9/10 [ 38.6%]  loss: 0.4165
  Epoch 9/10 [ 43.4%]  loss: 0.4301
  Epoch 9/10 [ 48.2%]  loss: 0.4440
  Epoch 9/10 [ 53.0%]  loss: 0.4190
  Epoch 9/10 [ 57.8%]  loss: 0.4285
  Epoch 9/10 [ 62.7%]  loss: 0.4293
  Epoch 9/10 [ 67.5%]  loss: 0.4397
  Epoch 9/10 [ 72.3%]  loss: 0.4156
  Epoch 9/10 [ 77.1%]  loss: 0.4381
  Epoch 9/10 [ 81.9%]  loss: 0.4086
  Epoch 9/10 [ 86.7%]  loss: 0.4175
  Epoch 9/10 [ 91.6%]  loss: 0.4028
  Epoch 9/10 [ 96.4%]  loss: 0.3987
  Epoch 9/10 [100.0%]  loss: 0.4200

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.18batch/s]

Epoch 9/10
Train Loss: 0.4220 | Train F1: 0.7591
Val Loss: 1.7601 | Val F1: 0.3507
Epoch Time: 35.16s

  Epoch 10/10 [  4.8%]  loss: 0.4116
  Epoch 10/10 [  9.6%]  loss: 0.3911
  Epoch 10/10 [ 14.5%]  loss: 0.4006
  Epoch 10/10 [ 19.3%]  loss: 0.4010
  Epoch 10/10 [ 24.1%]  loss: 0.3956
  Epoch 10/10 [ 28.9%]  loss: 0.3953
  Epoch 10/10 [ 33.7%]  loss: 0.3981
  Epoch 10/10 [ 38.6%]  loss: 0.3793
  Epoch 10/10 [ 43.4%]  loss: 0.4195
  Epoch 10/10 [ 48.2%]  loss: 0.3795
  Epoch 10/10 [ 53.0%]  loss: 0.3620
  Epoch 10/10 [ 57.8%]  loss: 0.3603
  Epoch 10/10 [ 62.7%]  loss: 0.3642
  Epoch 10/10 [ 67.5%]  loss: 0.3701
  Epoch 10/10 [ 72.3%]  loss: 0.3364
  Epoch 10/10 [ 77.1%]  loss: 0.3727
  Epoch 10/10 [ 81.9%]  loss: 0.3800
  Epoch 10/10 [ 86.7%]  loss: 0.3653
  Epoch 10/10 [ 91.6%]  loss: 0.3678
  Epoch 10/10 [ 96.4%]  loss: 0.3551
  Epoch 10/10 [100.0%]  loss: 0.3643

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.14batch/s]

Epoch 10/10
Train Loss: 0.3797 | Train F1: 0.7800
Val Loss: 1.7679 | Val F1: 0.3460
Epoch Time: 35.02s

Finalised: 668/1920 conv1 channels zeroed (34.8%)
Saved → trained_models/pwkd_self_r18_r35/pwkd_self_r18_r35_full.pth

Warming up pwkd_self_r18_r35...
Running inference...
  ratio: 35% | F1: 0.0786 | params: 7,375,101

============================================================
  PWKD Option 3 (ResNet18) — pruning ratio 40%
============================================================
  Epoch 1/10 [  4.8%]  loss: 2.1569
  Epoch 1/10 [  9.6%]  loss: 2.4636
  Epoch 1/10 [ 14.5%]  loss: 2.1366
  Epoch 1/10 [ 19.3%]  loss: 1.8196
  Epoch 1/10 [ 24.1%]  loss: 1.8207
  Epoch 1/10 [ 28.9%]  loss: 1.7902
  Epoch 1/10 [ 33.7%]  loss: 1.6206
  Epoch 1/10 [ 38.6%]  loss: 1.4222
  Epoch 1/10 [ 43.4%]  loss: 1.3942
  Epoch 1/10 [ 48.2%]  loss: 1.2575
  Epoch 1/10 [ 53.0%]  loss: 1.2781
  Epoch 1/10 [ 57.8%]  loss: 1.1308
  Epoch 1/10 [ 62.7%]  loss: 1.1467
  Epoch 1/10 [ 67.5%]  loss: 1.0698
  Epoch 1/10 [ 72.3%]  loss: 0.9900
  Epoch 1/10 [ 77.1%]  loss: 1.0331
  Epoch 1/10 [ 81.9%]  loss: 1.2405
  Epoch 1/10 [ 86.7%]  loss: 1.0026
  Epoch 1/10 [ 91.6%]  loss: 0.9793
  Epoch 1/10 [ 96.4%]  loss: 0.9489
  Epoch 1/10 [100.0%]  loss: 1.1341

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.19batch/s]

Epoch 1/10
Train Loss: 1.4242 | Train F1: 0.4207
Val Loss: 2.2555 | Val F1: 0.2349
Epoch Time: 35.15s

  Epoch 2/10 [  4.8%]  loss: 0.9574
  Epoch 2/10 [  9.6%]  loss: 0.9132
  Epoch 2/10 [ 14.5%]  loss: 0.8912
  Epoch 2/10 [ 19.3%]  loss: 0.9221
  Epoch 2/10 [ 24.1%]  loss: 0.8788
  Epoch 2/10 [ 28.9%]  loss: 0.9183
  Epoch 2/10 [ 33.7%]  loss: 0.9052
  Epoch 2/10 [ 38.6%]  loss: 0.8198
  Epoch 2/10 [ 43.4%]  loss: 0.8203
  Epoch 2/10 [ 48.2%]  loss: 0.8584
  Epoch 2/10 [ 53.0%]  loss: 0.7528
  Epoch 2/10 [ 57.8%]  loss: 0.7920
  Epoch 2/10 [ 62.7%]  loss: 0.9068
  Epoch 2/10 [ 67.5%]  loss: 0.7916
  Epoch 2/10 [ 72.3%]  loss: 0.7460
  Epoch 2/10 [ 77.1%]  loss: 0.6902
  Epoch 2/10 [ 81.9%]  loss: 0.6942
  Epoch 2/10 [ 86.7%]  loss: 0.8195
  Epoch 2/10 [ 91.6%]  loss: 0.7142
  Epoch 2/10 [ 96.4%]  loss: 0.6955
  Epoch 2/10 [100.0%]  loss: 0.7734

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.84batch/s]

Epoch 2/10
Train Loss: 0.8225 | Train F1: 0.5570
Val Loss: 1.9875 | Val F1: 0.2934
Epoch Time: 34.01s

  Epoch 3/10 [  4.8%]  loss: 0.7601
  Epoch 3/10 [  9.6%]  loss: 0.7208
  Epoch 3/10 [ 14.5%]  loss: 0.6675
  Epoch 3/10 [ 19.3%]  loss: 0.6377
  Epoch 3/10 [ 24.1%]  loss: 0.6701
  Epoch 3/10 [ 28.9%]  loss: 0.6228
  Epoch 3/10 [ 33.7%]  loss: 0.6745
  Epoch 3/10 [ 38.6%]  loss: 0.6327
  Epoch 3/10 [ 43.4%]  loss: 0.6217
  Epoch 3/10 [ 48.2%]  loss: 0.5672
  Epoch 3/10 [ 53.0%]  loss: 0.6142
  Epoch 3/10 [ 57.8%]  loss: 0.5860
  Epoch 3/10 [ 62.7%]  loss: 0.6134
  Epoch 3/10 [ 67.5%]  loss: 0.6470
  Epoch 3/10 [ 72.3%]  loss: 0.5504
  Epoch 3/10 [ 77.1%]  loss: 0.5312
  Epoch 3/10 [ 81.9%]  loss: 0.5228
  Epoch 3/10 [ 86.7%]  loss: 0.5459
  Epoch 3/10 [ 91.6%]  loss: 0.6481
  Epoch 3/10 [ 96.4%]  loss: 0.5858
  Epoch 3/10 [100.0%]  loss: 0.5182

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.77batch/s]

Epoch 3/10
Train Loss: 0.6173 | Train F1: 0.6478
Val Loss: 1.9473 | Val F1: 0.2911
Epoch Time: 35.03s

  Epoch 4/10 [  4.8%]  loss: 0.5529
  Epoch 4/10 [  9.6%]  loss: 0.4960
  Epoch 4/10 [ 14.5%]  loss: 0.5919
  Epoch 4/10 [ 19.3%]  loss: 0.5254
  Epoch 4/10 [ 24.1%]  loss: 0.5305
  Epoch 4/10 [ 28.9%]  loss: 0.5274
  Epoch 4/10 [ 33.7%]  loss: 0.4489
  Epoch 4/10 [ 38.6%]  loss: 0.5026
  Epoch 4/10 [ 43.4%]  loss: 0.5368
  Epoch 4/10 [ 48.2%]  loss: 0.4862
  Epoch 4/10 [ 53.0%]  loss: 0.5116
  Epoch 4/10 [ 57.8%]  loss: 0.5335
  Epoch 4/10 [ 62.7%]  loss: 0.5415
  Epoch 4/10 [ 67.5%]  loss: 0.4930
  Epoch 4/10 [ 72.3%]  loss: 0.5360
  Epoch 4/10 [ 77.1%]  loss: 0.5096
  Epoch 4/10 [ 81.9%]  loss: 0.5059
  Epoch 4/10 [ 86.7%]  loss: 0.4901
  Epoch 4/10 [ 91.6%]  loss: 0.4827
  Epoch 4/10 [ 96.4%]  loss: 0.4614
  Epoch 4/10 [100.0%]  loss: 0.4694

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.68batch/s]

Epoch 4/10
Train Loss: 0.5116 | Train F1: 0.6961
Val Loss: 1.8141 | Val F1: 0.3233
Epoch Time: 34.98s

  Epoch 5/10 [  4.8%]  loss: 0.4922
  Epoch 5/10 [  9.6%]  loss: 0.4717
  Epoch 5/10 [ 14.5%]  loss: 0.4890
  Epoch 5/10 [ 19.3%]  loss: 0.4721
  Epoch 5/10 [ 24.1%]  loss: 0.4582
  Epoch 5/10 [ 28.9%]  loss: 0.4564
  Epoch 5/10 [ 33.7%]  loss: 0.4760
  Epoch 5/10 [ 38.6%]  loss: 0.4521
  Epoch 5/10 [ 43.4%]  loss: 0.4753
  Epoch 5/10 [ 48.2%]  loss: 0.4402
  Epoch 5/10 [ 53.0%]  loss: 0.4996
  Epoch 5/10 [ 57.8%]  loss: 0.4738
  Epoch 5/10 [ 62.7%]  loss: 0.4678
  Epoch 5/10 [ 67.5%]  loss: 0.4796
  Epoch 5/10 [ 72.3%]  loss: 0.4313
  Epoch 5/10 [ 77.1%]  loss: 0.4396
  Epoch 5/10 [ 81.9%]  loss: 0.4498
  Epoch 5/10 [ 86.7%]  loss: 0.4565
  Epoch 5/10 [ 91.6%]  loss: 0.4633
  Epoch 5/10 [ 96.4%]  loss: 0.4575
  Epoch 5/10 [100.0%]  loss: 0.4723

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.07batch/s]

Epoch 5/10
Train Loss: 0.4654 | Train F1: 0.7158
Val Loss: 1.7127 | Val F1: 0.3528
Epoch Time: 35.04s

  Epoch 6/10 [  4.8%]  loss: 0.4703
  Epoch 6/10 [  9.6%]  loss: 0.4483
  Epoch 6/10 [ 14.5%]  loss: 0.4269
  Epoch 6/10 [ 19.3%]  loss: 0.4839
  Epoch 6/10 [ 24.1%]  loss: 0.4351
  Epoch 6/10 [ 28.9%]  loss: 0.4164
  Epoch 6/10 [ 33.7%]  loss: 0.4515
  Epoch 6/10 [ 38.6%]  loss: 0.4427
  Epoch 6/10 [ 43.4%]  loss: 0.4705
  Epoch 6/10 [ 48.2%]  loss: 0.4306
  Epoch 6/10 [ 53.0%]  loss: 0.4533
  Epoch 6/10 [ 57.8%]  loss: 0.4398
  Epoch 6/10 [ 62.7%]  loss: 0.4457
  Epoch 6/10 [ 67.5%]  loss: 0.4375
  Epoch 6/10 [ 72.3%]  loss: 0.4496
  Epoch 6/10 [ 77.1%]  loss: 0.4331
  Epoch 6/10 [ 81.9%]  loss: 0.4665
  Epoch 6/10 [ 86.7%]  loss: 0.4374
  Epoch 6/10 [ 91.6%]  loss: 0.4641
  Epoch 6/10 [ 96.4%]  loss: 0.4226
  Epoch 6/10 [100.0%]  loss: 0.4207

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.11batch/s]

Epoch 6/10
Train Loss: 0.4454 | Train F1: 0.7379
Val Loss: 1.8373 | Val F1: 0.3338
Epoch Time: 35.02s

  Epoch 7/10 [  4.8%]  loss: 0.4471
  Epoch 7/10 [  9.6%]  loss: 0.4785
  Epoch 7/10 [ 14.5%]  loss: 0.4810
  Epoch 7/10 [ 19.3%]  loss: 0.4221
  Epoch 7/10 [ 24.1%]  loss: 0.4314
  Epoch 7/10 [ 28.9%]  loss: 0.4226
  Epoch 7/10 [ 33.7%]  loss: 0.4455
  Epoch 7/10 [ 38.6%]  loss: 0.4258
  Epoch 7/10 [ 43.4%]  loss: 0.4376
  Epoch 7/10 [ 48.2%]  loss: 0.4340
  Epoch 7/10 [ 53.0%]  loss: 0.4015
  Epoch 7/10 [ 57.8%]  loss: 0.4125
  Epoch 7/10 [ 62.7%]  loss: 0.4551
  Epoch 7/10 [ 67.5%]  loss: 0.4355
  Epoch 7/10 [ 72.3%]  loss: 0.4716
  Epoch 7/10 [ 77.1%]  loss: 0.5349
  Epoch 7/10 [ 81.9%]  loss: 0.5250
  Epoch 7/10 [ 86.7%]  loss: 0.5188
  Epoch 7/10 [ 91.6%]  loss: 0.4699
  Epoch 7/10 [ 96.4%]  loss: 0.5015
  Epoch 7/10 [100.0%]  loss: 0.5243

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.74batch/s]

Epoch 7/10
Train Loss: 0.4600 | Train F1: 0.7394
Val Loss: 1.8940 | Val F1: 0.3339
Epoch Time: 35.28s

  Epoch 8/10 [  4.8%]  loss: 0.4779
  Epoch 8/10 [  9.6%]  loss: 0.5181
  Epoch 8/10 [ 14.5%]  loss: 0.5000
  Epoch 8/10 [ 19.3%]  loss: 0.4837
  Epoch 8/10 [ 24.1%]  loss: 0.4868
  Epoch 8/10 [ 28.9%]  loss: 0.4984
  Epoch 8/10 [ 33.7%]  loss: 0.4829
  Epoch 8/10 [ 38.6%]  loss: 0.4426
  Epoch 8/10 [ 43.4%]  loss: 0.4534
  Epoch 8/10 [ 48.2%]  loss: 0.4498
  Epoch 8/10 [ 53.0%]  loss: 0.4380
  Epoch 8/10 [ 57.8%]  loss: 0.4646
  Epoch 8/10 [ 62.7%]  loss: 0.4672
  Epoch 8/10 [ 67.5%]  loss: 0.4557
  Epoch 8/10 [ 72.3%]  loss: 0.4274
  Epoch 8/10 [ 77.1%]  loss: 0.4376
  Epoch 8/10 [ 81.9%]  loss: 0.4412
  Epoch 8/10 [ 86.7%]  loss: 0.4150
  Epoch 8/10 [ 91.6%]  loss: 0.4215
  Epoch 8/10 [ 96.4%]  loss: 0.4888
  Epoch 8/10 [100.0%]  loss: 0.4243

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.73batch/s]

Epoch 8/10
Train Loss: 0.4611 | Train F1: 0.7373
Val Loss: 1.7889 | Val F1: 0.3489
Epoch Time: 34.34s

  Epoch 9/10 [  4.8%]  loss: 0.3998
  Epoch 9/10 [  9.6%]  loss: 0.4030
  Epoch 9/10 [ 14.5%]  loss: 0.4017
  Epoch 9/10 [ 19.3%]  loss: 0.4202
  Epoch 9/10 [ 24.1%]  loss: 0.4426
  Epoch 9/10 [ 28.9%]  loss: 0.4194
  Epoch 9/10 [ 33.7%]  loss: 0.4094
  Epoch 9/10 [ 38.6%]  loss: 0.4030
  Epoch 9/10 [ 43.4%]  loss: 0.4283
  Epoch 9/10 [ 48.2%]  loss: 0.4126
  Epoch 9/10 [ 53.0%]  loss: 0.4254
  Epoch 9/10 [ 57.8%]  loss: 0.3944
  Epoch 9/10 [ 62.7%]  loss: 0.4061
  Epoch 9/10 [ 67.5%]  loss: 0.4054
  Epoch 9/10 [ 72.3%]  loss: 0.4004
  Epoch 9/10 [ 77.1%]  loss: 0.3653
  Epoch 9/10 [ 81.9%]  loss: 0.4089
  Epoch 9/10 [ 86.7%]  loss: 0.3930
  Epoch 9/10 [ 91.6%]  loss: 0.3847
  Epoch 9/10 [ 96.4%]  loss: 0.3860
  Epoch 9/10 [100.0%]  loss: 0.4224

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.75batch/s]

Epoch 9/10
Train Loss: 0.4061 | Train F1: 0.7694
Val Loss: 1.7291 | Val F1: 0.3457
Epoch Time: 35.27s

  Epoch 10/10 [  4.8%]  loss: 0.3680
  Epoch 10/10 [  9.6%]  loss: 0.4053
  Epoch 10/10 [ 14.5%]  loss: 0.3994
  Epoch 10/10 [ 19.3%]  loss: 0.3920
  Epoch 10/10 [ 24.1%]  loss: 0.3778
  Epoch 10/10 [ 28.9%]  loss: 0.4022
  Epoch 10/10 [ 33.7%]  loss: 0.3869
  Epoch 10/10 [ 38.6%]  loss: 0.3858
  Epoch 10/10 [ 43.4%]  loss: 0.3979
  Epoch 10/10 [ 48.2%]  loss: 0.3760
  Epoch 10/10 [ 53.0%]  loss: 0.3728
  Epoch 10/10 [ 57.8%]  loss: 0.3818
  Epoch 10/10 [ 62.7%]  loss: 0.3685
  Epoch 10/10 [ 67.5%]  loss: 0.4141
  Epoch 10/10 [ 72.3%]  loss: 0.3843
  Epoch 10/10 [ 77.1%]  loss: 0.4008
  Epoch 10/10 [ 81.9%]  loss: 0.3925
  Epoch 10/10 [ 86.7%]  loss: 0.3774
  Epoch 10/10 [ 91.6%]  loss: 0.3929
  Epoch 10/10 [ 96.4%]  loss: 0.3707
  Epoch 10/10 [100.0%]  loss: 0.3760

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.76batch/s]

Epoch 10/10
Train Loss: 0.3870 | Train F1: 0.7825
Val Loss: 1.7569 | Val F1: 0.3562
Epoch Time: 34.96s

Finalised: 764/1920 conv1 channels zeroed (39.8%)
Saved → trained_models/pwkd_self_r18_r40/pwkd_self_r18_r40_full.pth

Warming up pwkd_self_r18_r40...
Running inference...
  ratio: 40% | F1: 0.0138 | params: 6,831,933

============================================================
  PWKD Option 3 (ResNet18) — pruning ratio 45%
============================================================
  Epoch 1/10 [  4.8%]  loss: 2.4400
  Epoch 1/10 [  9.6%]  loss: 2.3119
  Epoch 1/10 [ 14.5%]  loss: 2.1438
  Epoch 1/10 [ 19.3%]  loss: 1.9332
  Epoch 1/10 [ 24.1%]  loss: 1.6313
  Epoch 1/10 [ 28.9%]  loss: 1.5233
  Epoch 1/10 [ 33.7%]  loss: 1.7267
  Epoch 1/10 [ 38.6%]  loss: 1.5589
  Epoch 1/10 [ 43.4%]  loss: 1.5036
  Epoch 1/10 [ 48.2%]  loss: 1.5811
  Epoch 1/10 [ 53.0%]  loss: 1.4142
  Epoch 1/10 [ 57.8%]  loss: 1.2944
  Epoch 1/10 [ 62.7%]  loss: 1.3140
  Epoch 1/10 [ 67.5%]  loss: 1.3996
  Epoch 1/10 [ 72.3%]  loss: 1.1898
  Epoch 1/10 [ 77.1%]  loss: 1.0567
  Epoch 1/10 [ 81.9%]  loss: 0.9900
  Epoch 1/10 [ 86.7%]  loss: 0.9148
  Epoch 1/10 [ 91.6%]  loss: 1.0188
  Epoch 1/10 [ 96.4%]  loss: 0.8862
  Epoch 1/10 [100.0%]  loss: 0.8602

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.87batch/s]

Epoch 1/10
Train Loss: 1.4688 | Train F1: 0.4126
Val Loss: 2.1647 | Val F1: 0.2276
Epoch Time: 34.28s

  Epoch 2/10 [  4.8%]  loss: 0.8483
  Epoch 2/10 [  9.6%]  loss: 0.8350
  Epoch 2/10 [ 14.5%]  loss: 0.8274
  Epoch 2/10 [ 19.3%]  loss: 0.8273
  Epoch 2/10 [ 24.1%]  loss: 0.8543
  Epoch 2/10 [ 28.9%]  loss: 0.8446
  Epoch 2/10 [ 33.7%]  loss: 0.8047
  Epoch 2/10 [ 38.6%]  loss: 0.8145
  Epoch 2/10 [ 43.4%]  loss: 0.7301
  Epoch 2/10 [ 48.2%]  loss: 0.7128
  Epoch 2/10 [ 53.0%]  loss: 0.7246
  Epoch 2/10 [ 57.8%]  loss: 0.8385
  Epoch 2/10 [ 62.7%]  loss: 0.6906
  Epoch 2/10 [ 67.5%]  loss: 0.7308
  Epoch 2/10 [ 72.3%]  loss: 0.7063
  Epoch 2/10 [ 77.1%]  loss: 0.6875
  Epoch 2/10 [ 81.9%]  loss: 0.6707
  Epoch 2/10 [ 86.7%]  loss: 0.6709
  Epoch 2/10 [ 91.6%]  loss: 0.6663
  Epoch 2/10 [ 96.4%]  loss: 0.7571
  Epoch 2/10 [100.0%]  loss: 0.8504

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.71batch/s]

Epoch 2/10
Train Loss: 0.7653 | Train F1: 0.5837
Val Loss: 2.0993 | Val F1: 0.2877
Epoch Time: 35.28s

  Epoch 3/10 [  4.8%]  loss: 0.9154
  Epoch 3/10 [  9.6%]  loss: 0.8667
  Epoch 3/10 [ 14.5%]  loss: 0.8620
  Epoch 3/10 [ 19.3%]  loss: 0.7658
  Epoch 3/10 [ 24.1%]  loss: 0.7208
  Epoch 3/10 [ 28.9%]  loss: 0.7008
  Epoch 3/10 [ 33.7%]  loss: 0.7218
  Epoch 3/10 [ 38.6%]  loss: 0.6583
  Epoch 3/10 [ 43.4%]  loss: 0.7468
  Epoch 3/10 [ 48.2%]  loss: 0.6662
  Epoch 3/10 [ 53.0%]  loss: 0.6502
  Epoch 3/10 [ 57.8%]  loss: 0.6082
  Epoch 3/10 [ 62.7%]  loss: 0.6694
  Epoch 3/10 [ 67.5%]  loss: 0.5808
  Epoch 3/10 [ 72.3%]  loss: 0.6168
  Epoch 3/10 [ 77.1%]  loss: 0.6350
  Epoch 3/10 [ 81.9%]  loss: 0.5474
  Epoch 3/10 [ 86.7%]  loss: 0.5822
  Epoch 3/10 [ 91.6%]  loss: 0.4946
  Epoch 3/10 [ 96.4%]  loss: 0.5695
  Epoch 3/10 [100.0%]  loss: 0.5668

Validating: 100%|██████████| 50/50 [00:02<00:00, 17.80batch/s]

Epoch 3/10
Train Loss: 0.6749 | Train F1: 0.6246
Val Loss: 1.9578 | Val F1: 0.2931
Epoch Time: 35.27s

  Epoch 4/10 [  4.8%]  loss: 0.5468
  Epoch 4/10 [  9.6%]  loss: 0.5983
  Epoch 4/10 [ 14.5%]  loss: 0.5751
  Epoch 4/10 [ 19.3%]  loss: 0.5782
  Epoch 4/10 [ 24.1%]  loss: 0.5975
  Epoch 4/10 [ 28.9%]  loss: 0.6089
  Epoch 4/10 [ 33.7%]  loss: 0.5116
  Epoch 4/10 [ 38.6%]  loss: 0.5540
  Epoch 4/10 [ 43.4%]  loss: 0.4891
  Epoch 4/10 [ 48.2%]  loss: 0.5181
  Epoch 4/10 [ 53.0%]  loss: 0.5593
  Epoch 4/10 [ 57.8%]  loss: 0.4774
  Epoch 4/10 [ 62.7%]  loss: 0.5018
  Epoch 4/10 [ 67.5%]  loss: 0.4715
  Epoch 4/10 [ 72.3%]  loss: 0.6533
  Epoch 4/10 [ 77.1%]  loss: 0.5885
  Epoch 4/10 [ 81.9%]  loss: 0.5495
  Epoch 4/10 [ 86.7%]  loss: 0.5352
  Epoch 4/10 [ 91.6%]  loss: 0.5514
  Epoch 4/10 [ 96.4%]  loss: 0.5033
  Epoch 4/10 [100.0%]  loss: 0.5511

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.05batch/s]

Epoch 4/10
Train Loss: 0.5485 | Train F1: 0.6777
Val Loss: 1.8656 | Val F1: 0.3155
Epoch Time: 35.17s

  Epoch 5/10 [  4.8%]  loss: 0.5198
  Epoch 5/10 [  9.6%]  loss: 0.5563
  Epoch 5/10 [ 14.5%]  loss: 0.4642
  Epoch 5/10 [ 19.3%]  loss: 0.4987
  Epoch 5/10 [ 24.1%]  loss: 0.5140
  Epoch 5/10 [ 28.9%]  loss: 0.4688
  Epoch 5/10 [ 33.7%]  loss: 0.5085
  Epoch 5/10 [ 38.6%]  loss: 0.4805
  Epoch 5/10 [ 43.4%]  loss: 0.4536
  Epoch 5/10 [ 48.2%]  loss: 0.4562
  Epoch 5/10 [ 53.0%]  loss: 0.5203
  Epoch 5/10 [ 57.8%]  loss: 0.4797
  Epoch 5/10 [ 62.7%]  loss: 0.4696
  Epoch 5/10 [ 67.5%]  loss: 0.4618
  Epoch 5/10 [ 72.3%]  loss: 0.4585
  Epoch 5/10 [ 77.1%]  loss: 0.4153
  Epoch 5/10 [ 81.9%]  loss: 0.4907
  Epoch 5/10 [ 86.7%]  loss: 0.4817
  Epoch 5/10 [ 91.6%]  loss: 0.4576
  Epoch 5/10 [ 96.4%]  loss: 0.4385
  Epoch 5/10 [100.0%]  loss: 0.4498

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.17batch/s]

Epoch 5/10
Train Loss: 0.4786 | Train F1: 0.7089
Val Loss: 1.8029 | Val F1: 0.3096
Epoch Time: 35.21s

  Epoch 6/10 [  4.8%]  loss: 0.4604
  Epoch 6/10 [  9.6%]  loss: 0.4786
  Epoch 6/10 [ 14.5%]  loss: 0.4603
  Epoch 6/10 [ 19.3%]  loss: 0.4313
  Epoch 6/10 [ 24.1%]  loss: 0.4350
  Epoch 6/10 [ 28.9%]  loss: 0.4553
  Epoch 6/10 [ 33.7%]  loss: 0.4337
  Epoch 6/10 [ 38.6%]  loss: 0.4648
  Epoch 6/10 [ 43.4%]  loss: 0.4803
  Epoch 6/10 [ 48.2%]  loss: 0.4666
  Epoch 6/10 [ 53.0%]  loss: 0.4247
  Epoch 6/10 [ 57.8%]  loss: 0.4525
  Epoch 6/10 [ 62.7%]  loss: 0.4655
  Epoch 6/10 [ 67.5%]  loss: 0.4402
  Epoch 6/10 [ 72.3%]  loss: 0.4746
  Epoch 6/10 [ 77.1%]  loss: 0.3966
  Epoch 6/10 [ 81.9%]  loss: 0.4317
  Epoch 6/10 [ 86.7%]  loss: 0.4214
  Epoch 6/10 [ 91.6%]  loss: 0.4470
  Epoch 6/10 [ 96.4%]  loss: 0.4494
  Epoch 6/10 [100.0%]  loss: 0.4511

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.07batch/s]

Epoch 6/10
Train Loss: 0.4486 | Train F1: 0.7339
Val Loss: 1.7160 | Val F1: 0.3409
Epoch Time: 35.08s

  Epoch 7/10 [  4.8%]  loss: 0.4411
  Epoch 7/10 [  9.6%]  loss: 0.4287
  Epoch 7/10 [ 14.5%]  loss: 0.4318
  Epoch 7/10 [ 19.3%]  loss: 0.4235
  Epoch 7/10 [ 24.1%]  loss: 0.4193
  Epoch 7/10 [ 28.9%]  loss: 0.4167
  Epoch 7/10 [ 33.7%]  loss: 0.4537
  Epoch 7/10 [ 38.6%]  loss: 0.4454
  Epoch 7/10 [ 43.4%]  loss: 0.4589
  Epoch 7/10 [ 48.2%]  loss: 0.4494
  Epoch 7/10 [ 53.0%]  loss: 0.4330
  Epoch 7/10 [ 57.8%]  loss: 0.4253
  Epoch 7/10 [ 62.7%]  loss: 0.3954
  Epoch 7/10 [ 67.5%]  loss: 0.3899
  Epoch 7/10 [ 72.3%]  loss: 0.4094
  Epoch 7/10 [ 77.1%]  loss: 0.4036
  Epoch 7/10 [ 81.9%]  loss: 0.3839
  Epoch 7/10 [ 86.7%]  loss: 0.3970
  Epoch 7/10 [ 91.6%]  loss: 0.4102
  Epoch 7/10 [ 96.4%]  loss: 0.3571
  Epoch 7/10 [100.0%]  loss: 0.4026

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.07batch/s]

Epoch 7/10
Train Loss: 0.4181 | Train F1: 0.7583
Val Loss: 1.7150 | Val F1: 0.3691
Epoch Time: 35.16s

  Epoch 8/10 [  4.8%]  loss: 0.4139
  Epoch 8/10 [  9.6%]  loss: 0.4048
  Epoch 8/10 [ 14.5%]  loss: 0.4147
  Epoch 8/10 [ 19.3%]  loss: 0.3885
  Epoch 8/10 [ 24.1%]  loss: 0.4043
  Epoch 8/10 [ 28.9%]  loss: 0.3979
  Epoch 8/10 [ 33.7%]  loss: 0.4343
  Epoch 8/10 [ 38.6%]  loss: 0.4177
  Epoch 8/10 [ 43.4%]  loss: 0.4149
  Epoch 8/10 [ 48.2%]  loss: 0.3967
  Epoch 8/10 [ 53.0%]  loss: 0.4211
  Epoch 8/10 [ 57.8%]  loss: 0.3970
  Epoch 8/10 [ 62.7%]  loss: 0.4460
  Epoch 8/10 [ 67.5%]  loss: 0.4714
  Epoch 8/10 [ 72.3%]  loss: 0.4395
  Epoch 8/10 [ 77.1%]  loss: 0.4450
  Epoch 8/10 [ 81.9%]  loss: 0.4189
  Epoch 8/10 [ 86.7%]  loss: 0.4090
  Epoch 8/10 [ 91.6%]  loss: 0.4013
  Epoch 8/10 [ 96.4%]  loss: 0.4190
  Epoch 8/10 [100.0%]  loss: 0.4050

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.18batch/s]

Epoch 8/10
Train Loss: 0.4173 | Train F1: 0.7632
Val Loss: 1.7588 | Val F1: 0.3485
Epoch Time: 35.19s

  Epoch 9/10 [  4.8%]  loss: 0.4198
  Epoch 9/10 [  9.6%]  loss: 0.4181
  Epoch 9/10 [ 14.5%]  loss: 0.4412
  Epoch 9/10 [ 19.3%]  loss: 0.4424
  Epoch 9/10 [ 24.1%]  loss: 0.4487
  Epoch 9/10 [ 28.9%]  loss: 0.4498
  Epoch 9/10 [ 33.7%]  loss: 0.4261
  Epoch 9/10 [ 38.6%]  loss: 0.4103
  Epoch 9/10 [ 43.4%]  loss: 0.4442
  Epoch 9/10 [ 48.2%]  loss: 0.4253
  Epoch 9/10 [ 53.0%]  loss: 0.3883
  Epoch 9/10 [ 57.8%]  loss: 0.4056
  Epoch 9/10 [ 62.7%]  loss: 0.4165
  Epoch 9/10 [ 67.5%]  loss: 0.4032
  Epoch 9/10 [ 72.3%]  loss: 0.3984
  Epoch 9/10 [ 77.1%]  loss: 0.4019
  Epoch 9/10 [ 81.9%]  loss: 0.4133
  Epoch 9/10 [ 86.7%]  loss: 0.3948
  Epoch 9/10 [ 91.6%]  loss: 0.3904
  Epoch 9/10 [ 96.4%]  loss: 0.3636
  Epoch 9/10 [100.0%]  loss: 0.3732

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.15batch/s]

Epoch 9/10
Train Loss: 0.4136 | Train F1: 0.7658
Val Loss: 1.6998 | Val F1: 0.3561
Epoch Time: 35.19s

  Epoch 10/10 [  4.8%]  loss: 0.3807
  Epoch 10/10 [  9.6%]  loss: 0.4024
  Epoch 10/10 [ 14.5%]  loss: 0.4455
  Epoch 10/10 [ 19.3%]  loss: 0.3980
  Epoch 10/10 [ 24.1%]  loss: 0.3986
  Epoch 10/10 [ 28.9%]  loss: 0.4186
  Epoch 10/10 [ 33.7%]  loss: 0.5213
  Epoch 10/10 [ 38.6%]  loss: 0.5893
  Epoch 10/10 [ 43.4%]  loss: 0.5527
  Epoch 10/10 [ 48.2%]  loss: 0.5453
  Epoch 10/10 [ 53.0%]  loss: 0.6273
  Epoch 10/10 [ 57.8%]  loss: 0.6222
  Epoch 10/10 [ 62.7%]  loss: 0.5714
  Epoch 10/10 [ 67.5%]  loss: 0.5427
  Epoch 10/10 [ 72.3%]  loss: 0.5240
  Epoch 10/10 [ 77.1%]  loss: 0.5296
  Epoch 10/10 [ 81.9%]  loss: 0.5124
  Epoch 10/10 [ 86.7%]  loss: 0.5082
  Epoch 10/10 [ 91.6%]  loss: 0.5015
  Epoch 10/10 [ 96.4%]  loss: 0.4950
  Epoch 10/10 [100.0%]  loss: 0.4944

Validating: 100%|██████████| 50/50 [00:02<00:00, 18.16batch/s]

Epoch 10/10
Train Loss: 0.5040 | Train F1: 0.7342
Val Loss: 1.9486 | Val F1: 0.2968
Epoch Time: 35.19s

Finalised: 860/1920 conv1 channels zeroed (44.8%)
Saved → trained_models/pwkd_self_r18_r45/pwkd_self_r18_r45_full.pth

Warming up pwkd_self_r18_r45...
Running inference...
  ratio: 45% | F1: 0.0056 | params: 6,276,669

               Size Reduction (%)  F1 Score  Size (MB)  Latency (ms)
Pruning Ratio
10%                          9.69    0.3858       42.8          0.39
25%                         24.50    0.2268       42.8          0.38
50%                         49.01    0.0008       42.8          0.39
70%                         68.50    0.0002       42.8          0.38
90%                         88.05    0.0002       42.8          0.39
20%                         19.49    0.3177       42.8          0.38
30%                         29.24    0.1643       42.8          0.39
35%                         34.20    0.0786       42.8          0.39
40%                         39.04    0.0138       42.8          0.38
45%                         44.00    0.0056       42.8          0.39